### ISSUE TITLE
support the set blob metadata operation with storage SDK

### ISSUE THREAD

**Issue by gregman-msft** [Azure/azure-sdk-for-c#101]
Multiple C SDK users have requested support for the [Set Blob Metadata ](https://docs.microsoft.com/en-us/rest/api/storageservices/set-blob-metadata) operation with this SDK.

Original GitHub issue: https://github.com/Azure/azure-iot-sdk-c/issues/375

**Comment by vhvb1989** [comment]
Closed as the original
