### ISSUE TITLE
Add Pipeline Witness categorization for failed cache steps

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-c#1014]
There are at least two failures on MacOS DevOps agents coming from the `Vcpkg Cache` step. We should track these failures in our system to understand how widespread it is. 

Failure message: 

```
##[error]The HTTP request timed out after 00:00:30.
```

Known failures: 

* https://dev.azure.com/azure-sdk/public/_build/results?buildId=486522&view=logs&j=458eebdd-b8c0-53fa-652f-fe4233aa7246&t=a49668b7-66ea-5f36-4791-f26a292d6dcc&s=ff05ad62-bb9a-53b6-ce9f-72f329a63e7c
* https://dev.azure.com/azure-sdk/internal/_build/results?buildId=482895&view=logs&j=4bef5d43-441c-5b11-9e73-e199bb3c37eb&t=d12f0e06-61f0-5a39-48b7-764a4fee902c

Example classifier: https://github.com/Azure/azure-sdk-tools/blob/master/tools/pipeline-witness/Azure.Sdk.Tools.PipelineWitness/Services/FailureAnalysis/PythonPipelineTestFailureClassifier.cs

**Comment by RickWinter** [comment]
This is showing up a few times a month.  It affects our CI metrics and may create a false impression on code quality.
@mitchdenny is this appearing in your reports?

**Comment by mitchdenny** [comment]
Looking at the failures, it looks like it is a 30 second timeout, and successful runs are coming up close to that. So it might be just a case of increasing the timeout to 1 minute to cover slower than average cache fetch times that are likely to occur from time to time?

**Comment by mitchdenny** [comment]
Take a look at the PR I just linked. It is still failing after I increase the timeout to 1 minute. But look at the cache size it is restoring - that seems pretty large for such a tight library.

**Comment by mitchdenny** [comment]
I'm not seeing any issues anymore.
