### ISSUE TITLE
Remove azure-sdk-for-c_ from package release version tag

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-c#1016]
Changes from: https://github.com/Azure/azure-sdk/pull/1615

**Comment by ahsonkhan** [comment]
@danieljurek is this done?

**Comment by danieljurek** [comment]
It's done in the C repo but this PR needs to be checked in to make the changes permanent -- https://github.com/Azure/azure-sdk-tools/pull/857
