### ISSUE TITLE
Investigate and fix issue with paho_iot_hub_twin_sample related to JSON writer

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-c#1030]
For a repro:
> Use the updated sample documentation
README: https://github.com/Azure/azure-sdk-for-c/blob/master/sdk/samples/iot/README.md
The executable will be `paho_iot_hub_twin_sample`

Investigate the changes in this commit.

dc533e1 : Add support for non-contiguous buffers within JSON build using a ca…
https://github.com/Azure/azure-sdk-for-c/commit/dc533e1db8f030dd94161e78a155ad66134a0d8a#diff-73d7c292a70e269a4e1660e924301ec4
 
@momuno tracked the issue to this commit, in which the `sdk/samples/iot/paho_iot_hub_twin_sample` gives the following error when run:
```text
ERROR:          /mnt/c/Repos/momuno_azure-sdk-for-c/sdk/samples/iot/hub/src/paho_iot_hub_twin_example.c:send_reported_property():398: Unable to build reported property payload to send, az_result return code 80010002
(80010002 = AZ_ERROR_INSUFFICIENT_SPAN_SIZE)
```

The code in the twin sample being called is the following:
https://github.com/Azure/azure-sdk-for-c/blob/14ca09fca5bd7785044dcbd41070baf049a09ac9/sdk/samples/iot/paho_iot_hub_twin_sample.c#L424-L438
 
And the error is occurring on this line:
```C
 AZ_RETURN_IF_FAILED(az_json_writer_append_property_name(&json_writer, reported_property_name));
 ```

When I looked into the `az_json_writer.c` file, it looks like `append_property_name()` is calling a new function called `append_property_name_chunked()`.  And somewhere in this chunked function the `AZ_ERROR_INSUFFICIENT_SPAN_SIZE` is occurring. 
 
FYI, the size for the buffer is the same as before:
```C
static char reported_property_buffer[64];
```

**Comment by ahsonkhan** [comment]
This is by-design because the JSON writer pessimistically requires at least 64-bytes of space when writing any string larger than 10 characters because it tries to write in 64 byte chunks (10 character * 6 if all need to be escaped into the unicode form \uXXXX). The expected fix is to add 64 bytes of slack in the output JSON buffer.

Removing `blocking-release`. If necessary, we can re-evaluate that design, to see whether it needs to change, but for now, it doesn't seem like a blocker to me.

```C
// Workaround: Add 64 bytes of slack. If expected payload is 18, use size: 18+ 64 = 82. Using 128 as
// next power of two, just because.
static char reported_property_buffer[128];
static az_span reported_property_name = AZ_SPAN_LITERAL_FROM_STR("device_count");
static int32_t reported_property_value = 0;

static void test_json_writer_iot(void** state)
{
  (void)state;

  az_json_writer json_writer;

  TEST_EXPECT_SUCCESS(
      az_json_writer_init(&json_writer, AZ_SPAN_FROM_BUFFER(reported_property_buffer), NULL));
  TEST_EXPECT_SUCCESS(az_json_writer_append_begin_object(&json_writer));
  TEST_EXPECT_SUCCESS(az_json_writer_append_property_name(&json_writer, reported_property_name));
  TEST_EXPECT_SUCCESS(az_json_writer_append_int32(&json_writer, reported_property_value));
  TEST_EXPECT_SUCCESS(az_json_writer_append_end_object(&json_writer));

  az_span reported_property_payload = az_json_writer_get_bytes_used_in_destination(&json_writer);

  assert_int_equal(az_span_size(reported_property_payload), 18);
}

```

**Comment by momuno** [comment]
PR #1034 fixes this issue.
