### ISSUE TITLE
Address storage API, readme and concept doc review comments

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-c#1040]
I left some docs and API feedback for these PRs that are worth taking another look at and fixing:
https://github.com/Azure/azure-sdk-for-c/pull/993
https://github.com/Azure/azure-sdk-for-c/pull/1005

- [x] Use linter to remove extra whitespace: https://github.com/Azure/azure-sdk-for-c/pull/1005#discussion_r467269583
- [x] Change `#az_context` to `#az_context_application` in doc comments: https://github.com/Azure/azure-sdk-for-c/pull/1005#discussion_r467270320
- [x] Add docs to `context` which is a public field: https://github.com/Azure/azure-sdk-for-c/pull/1005#discussion_r467270404
- [x] Remove `(void)`: https://github.com/Azure/azure-sdk-for-c/pull/1005#discussion_r467271645
- [x] Update upload sample to pass in options explicitly (rather than `NULL`): https://github.com/Azure/azure-sdk-for-c/pull/1005#discussion_r466613950
- [x] Update brief to contain non-redundant/non-obvious info: https://github.com/Azure/azure-sdk-for-c/pull/993#discussion_r466055461
  - See other examples like:
https://github.com/Azure/azure-sdk-for-c/blob/846f0d56b718016513a9983341a0d038a3a17df1/sdk/inc/azure/core/az_json.h#L221-L251
- [x] Update brief of storage client to be more descriptive: https://github.com/Azure/azure-sdk-for-c/pull/993#discussion_r466057718
- [x] Allow passing in `NULL` for storage client to mean default and document: https://github.com/Azure/azure-sdk-for-c/pull/993#discussion_r466058362, https://github.com/Azure/azure-sdk-for-c/pull/1005#discussion_r466613950
- [x] Remove remark for empty options struct: https://github.com/Azure/azure-sdk-for-c/pull/993#discussion_r466058568
- [x] Change the type and name of the unused option field to be `bool unused`: https://github.com/Azure/azure-sdk-for-c/pull/993#discussion_r466059010

**Comment by antkmsft** [comment]
I touched Storage docs a bit in https://github.com/Azure/azure-sdk-for-c/pull/1057
