### ISSUE TITLE
Add documentation for how to generate docs locally

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-c#1063]
I noticed that running `doxygen DoxyFile` works locally but produces a different docs website than what we get from CI pipeline:

This is how it looks the CI pipeline generated:
![image](https://user-images.githubusercontent.com/24213737/90435823-75824d00-e084-11ea-8bca-91947ec3da91.png)

And this is how it looks the locally generated:
![image](https://user-images.githubusercontent.com/24213737/90436469-97300400-e085-11ea-9c60-ddbe2e62c53f.png)

**Comment by vhvb1989** [comment]
@danieljurek   Maybe there is just something I might be missing.
But, look at the top menu on locally generated, It doesn't show the Data Struct and File Menu

**Comment by danieljurek** [comment]
Was able to reproduce this locally on WSL using doxygen 1.8.13 which came directly from the default apt configuration. We generate docs in CI using doxygen 1.8.18. Using that version should result in correct documentation output. 

https://github.com/Azure/azure-sdk-for-c/blob/50990da1a61293c043dbfc9a74f1b1ebfcee3fb4/eng/pipelines/templates/jobs/archetype-sdk-client.yml#L328

**Comment by vhvb1989** [comment]
yeah, using version 1.8.18 works as expected :)

We might want to add a note in docs about that.
