### ISSUE TITLE
Fix all doc generation warnings in the SDK and fail the CI on such warnings going forward

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-c#1064]
Here are the example of the various warnings we have as part of the `Generate docs` step in the `GenerateReleaseArtifacts` CI pipeline.

**Those warnings should not be silently ignored, but instead cause the CI to fail.**

And, we should fix all those warnings.

- [ ] Fix all doc generation warnings.
- [ ] Enable CI pipeline failures on future warnings, to stay green.

https://dev.azure.com/azure-sdk/public/_build/results?buildId=498352&view=logs&j=a129effc-2dd1-54d1-fb5a-ad7bdc0e851d&t=7114ab44-c708-5f6f-2727-058ed05787c5

> Preprocessing D:/a/1/s/sdk/inc/azure/iot/az_iot_hub_client.h...
D:/a/1/s/sdk/inc/azure/core/az_http_transport.h:195: warning: explicit link request to 'AZ_ERROR_HTTP_RESPONSE_OVERFLOW' could not be resolved
D:/a/1/s/sdk/inc/azure/core/az_http_transport.h:198: warning: explicit link request to 'AZ_ERROR_HTTP_RESPONSE_COULDNT_RESOLVE_HOST' could not be resolved
D:/a/1/s/sdk/inc/azure/core/az_http_transport.h:200: warning: explicit link request to 'AZ_ERROR_HTTP_PLATFORM' could not be resolved
D:/a/1/s/sdk/inc/azure/core/az_json.h:412: warning: explicit link request to 'AZ_ERROR_NOT_SUPPORTED' could not be resolved
D:/a/1/s/sdk/inc/azure/core/az_result.h:44: warning: Member AZ_RETURN_IF_FAILED(exp) (macro definition) of file az_result.h is not documented.
D:/a/1/s/sdk/inc/azure/core/az_result.h:54: warning: Member AZ_RETURN_IF_NOT_ENOUGH_SIZE(span, required_size) (macro definition) of file az_result.h is not documented.
D:/a/1/s/sdk/inc/azure/core/az_span.h:435: warning: explicit link request to 'AZ_ERROR_NOT_SUPPORTED' could not be resolved
D:/a/1/s/sdk/inc/azure/core/az_version.h:21: warning: Member AZ_SDK_VERSION_STRING (macro definition) of file az_version.h is not documented.
D:/a/1/s/sdk/inc/azure/core/az_version.h:24: warning: Member AZ_SDK_VERSION_MAJOR (macro definition) of file az_version.h is not documented.
D:/a/1/s/sdk/inc/azure/core/az_version.h:27: warning: Member AZ_SDK_VERSION_MINOR (macro definition) of file az_version.h is not documented.
D:/a/1/s/sdk/inc/azure/core/az_version.h:30: warning: Member AZ_SDK_VERSION_PATCH (macro definition) of file az_version.h is not documented.
D:/a/1/s/sdk/inc/azure/core/az_version.h:34: warning: Member AZ_SDK_VERSION_PRERELEASE (macro definition) of file az_version.h is not documented.
D:/a/1/s/sdk/inc/azure/iot/az_iot_provisioning_client.h:29: warning: Member AZ_IOT_PROVISIONING_SERVICE_VERSION (macro definition) of file az_iot_provisioning_client.h is not documented.
Parsing file D:/a/1/s/sdk/inc/azure/iot/az_iot_hub_client.h...

...

> D:/a/1/s/sdk/inc/azure/core/az_http.h:121: warning: Member retry_delay_msec (variable) of class az_http_policy_retry_options is not documented.
D:/a/1/s/sdk/inc/azure/core/az_http.h:122: warning: Member max_retry_delay_msec (variable) of class az_http_policy_retry_options is not documented.
D:/a/1/s/sdk/inc/azure/core/az_http.h:123: warning: Member max_retries (variable) of class az_http_policy_retry_options is not documented.
D:/a/1/s/sdk/inc/azure/core/az_http.h:191: warning: Member reason_phrase (variable) of class az_http_response_status_line is not documented.
D:/a/1/s/sdk/inc/azure/core/az_http.h:192: warning: Member status_code (variable) of class az_http_response_status_line is not documented.
D:/a/1/s/sdk/inc/azure/core/az_http.h:193: warning: Member major_version (variable) of class az_http_response_status_line is not documented.
D:/a/1/s/sdk/inc/azure/core/az_http.h:194: warning: Member minor_version (variable) of class az_http_response_status_line is not documented.
D:/a/1/s/sdk/inc/azure/core/az_json.h:542: warning: Member json_buffer (variable) of class az_json_reader is not documented.
D:/a/1/s/sdk/inc/azure/core/az_json.h:543: warning: Member json_buffers (variable) of class az_json_reader is not documented.
D:/a/1/s/sdk/inc/azure/core/az_json.h:544: warning: Member number_of_buffers (variable) of class az_json_reader is not documented.
D:/a/1/s/sdk/inc/azure/core/az_json.h:545: warning: Member buffer_index (variable) of class az_json_reader is not documented.
D:/a/1/s/sdk/inc/azure/core/az_json.h:546: warning: Member bytes_consumed (variable) of class az_json_reader is not documented.
D:/a/1/s/sdk/inc/azure/core/az_json.h:547: warning: Member total_bytes_consumed (variable) of class az_json_reader is not documented.
D:/a/1/s/sdk/inc/azure/core/az_json.h:548: warning: Member is_complex_json (variable) of class az_json_reader is not documented.
D:/a/1/s/sdk/inc/azure/core/az_json.h:549: warning: Member bit_stack (variable) of class az_json_reader is not documented.
D:/a/1/s/sdk/inc/azure/core/az_json.h:550: warning: Member options (variable) of class az_json_reader is not documented.
D:/a/1/s/sdk/inc/azure/core/az_json.h:85: warning: Member string_has_escaped_chars (variable) of class az_json_token is not documented.
D:/a/1/s/sdk/inc/azure/core/az_json.h:86: warning: Member pointer_to_first_buffer (variable) of class az_json_token is not documented.
D:/a/1/s/sdk/inc/azure/core/az_json.h:87: warning: Member start_buffer_index (variable) of class az_json_token is not documented.
D:/a/1/s/sdk/inc/azure/core/az_json.h:88: warning: Member start_buffer_offset (variable) of class az_json_token is not documented.
D:/a/1/s/sdk/inc/azure/core/az_json.h:89: warning: Member end_buffer_index (variable) of class az_json_token is not documented.
D:/a/1/s/sdk/inc/azure/core/az_json.h:90: warning: Member end_buffer_offset (variable) of class az_json_token is not documented.
D:/a/1/s/sdk/inc/azure/core/az_span.h:503: warning: Member key (variable) of class az_pair is not documented.
D:/a/1/s/sdk/inc/azure/core/az_span.h:504: warning: Member value (variable) of class az_pair is not documented.
D:/a/1/s/sdk/inc/azure/storage/az_storage_blobs.h:45: warning: Member api_version (variable) of class az_storage_blobs_blob_client_options is not documented.
D:/a/1/s/sdk/inc/azure/storage/az_storage_blobs.h:46: warning: Member telemetry_options (variable) of class az_storage_blobs_blob_client_options is not documented.
D:/a/1/s/sdk/inc/azure/storage/az_storage_blobs.h:93: warning: Member context (variable) of class az_storage_blobs_blob_upload_options is not documented.
D:/a/1/s/sdk/inc/azure/storage/az_storage_blobs.h:96: warning: Member unused (variable) of class az_storage_blobs_blob_upload_options is not documented.

cc @danieljurek, @RickWinter, @JeffreyRichter

**Comment by ahsonkhan** [comment]
To fix some of the warnings, add the missing docs. For example, `az_http_policy_retry_options` has public member fields that don't have documentation, like `status_codes`.

https://azuresdkdocs.blob.core.windows.net/$web/c/docs/1.0.0-preview.4/structaz__http__policy__retry__options.html
https://github.com/Azure/azure-sdk-for-c/blob/7a3d63d2255fb3a5f28ba0729db9e346016a1e98/sdk/inc/azure/core/az_http.h#L118-L124

On the other hand, we may want to suppress (but still consider documenting) warnings related to internal fields that aren't documented, like these:
> D:/a/1/s/sdk/inc/azure/core/az_json.h:86: warning: Member pointer_to_first_buffer (variable) of class az_json_token is not documented.
https://github.com/Azure/azure-sdk-for-c/blob/f33ac998fce23c83408730c6685f37eb923da986/sdk/inc/azure/core/az_json.h#L83-L91

cc @vhvb1989

**Comment by ahsonkhan** [comment]
Here's the WARN_AS_ERROR flag for doxygen:
https://www.doxygen.nl/manual/config.html#cfg_warn_as_error

**Comment by danieljurek** [comment]
@ahsonkhan This looks pretty reasonable. If we set `WARN_LOGFILE` the warnings only go to the log file. We'll have to output the warnings in a later step in the pipeline. Counting file lines is easy enough and we can use a parameter to set the maximum number of warnings. 

* Do we care if running `doxygen Doxyfile` outputs warnings to the console when running locally? (I assume so) 
* What's the upper bound for warnings before we fail the build? (This number would be static because it's difficult to look up output from previous builds)

**Comment by ahsonkhan** [comment]
> * Do we care if running `doxygen Doxyfile` outputs warnings to the console when running locally? (I assume so) 

Yes.

> * What's the upper bound for warnings before we fail the build? (This number would be static because it's difficult to look up output from previous builds) 

Let's start with the most strict, at 0, and see if we find hard exceptions to account for, that we can't workaround.

**Comment by kurtzeborn** [comment]
Removing "EngSys" lable since the "Client" and "EngSys" labels are used to track _who_ is doing the work for the issue (and not necessarily the area the issue falls into).  They should be mutually exclusive.  In this case the client libraries team is following up on this and not someone on the EngSys team, so it should be labeled "Client"
