### ISSUE TITLE
IoT Hub Client needs content type and content encoding

### ISSUE THREAD

**Issue by danewalton** [Azure/azure-sdk-for-c#1065]
Content type and content encoding should be added as options for the IoT Hub client. They are currently in the `iot/pnp_wip` branch here:
https://github.com/Azure/azure-sdk-for-c/blob/e1153f8ee9318478eef456f65c0adbac894f053b/sdk/iot/pnp/inc/az_iot_pnp_client.h#L32-L33
This is not only a pnp feature.

**Comment by RickWinter** [comment]
@danewalton @ericwol-msft Is this something you'll be adding before the September release?

**Comment by ericwol-msft** [comment]
yes
