### ISSUE TITLE
Compiler warning due to Unicode characters

### ISSUE THREAD

**Issue by TiejunMS** [Azure/azure-sdk-for-c#1087]
**Describe the bug**
In file sdk\src\azure\core\az_http_header_validation_private.h, there are Unicode characters. In non English environment, the compiler will give warnings.
```
warning C4819: The file contains a character that cannot
be represented in the current code page (936). Save the file in Unicode format to prevent data loss (compiling source file C:\azure-sdk-for-c\sdk\src\azure\core\az_http_request.c) [C:\build\sdk_core\sdk\src\azure\core\az_core.vcxproj]
```

Check the file format in Linux, it shows,
```
file az_http_header_validation_private.h
az_http_header_validation_private.h: C source, UTF-8 Unicode text
```

**To Reproduce**
Compile the project in non English environment.

**Screenshots**
Reopen file with GBK encoding.
![image](https://user-images.githubusercontent.com/50469179/90720093-7d422b80-e2e8-11ea-8825-18c8d0ac57f1.png)

**Setup (please complete the following information):**

- OS: Win10
- IDE: VS2019
- Version of the Library used: 1.0.0-preview 4

**Comment by ahsonkhan** [comment]
cc @vhvb1989

**Comment by ahsonkhan** [comment]
@vhvb1989  Look at the hex  dump. Instead of seeing hex 20 for space after device, we see `c2 a0`, which is a non-break space.

Updating the comments to use regular ASCII space should fix the issue.

Use: https://www.fileformat.info/tool/hexdump.htm

```text
0000-04e0:  2f 20 31 39-20 2d 3e 20-20 64 65 76-69 63 65 c2  /.19.->. .device.
0000-04f0:  a0 63 6f 6e-74 72 6f 6c-c2 a0 33 0d-0a 20 20 30  .control ..3....0
0000-0500:  2c 20 2f 2f-20 32 30 20-2d 3e 20 20-64 65 76 69  ,.//.20. ->..devi
```
