### ISSUE TITLE
Code size reporting from map files

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-c#1096]
Map files have different formats between toolchains. We should output the code size of functions from the map files in a normalized format so we can compare results between toolchains and over time.

**Comment by kurtzeborn** [comment]
Bumping this back to use the "Client" label instead of "EngSys" because these labels are used to track _who_ is doing the work and not the area the issue occurs in.  In this case, this is work that members of the c libraries team should probably own since it will require their language expertise.
