### ISSUE TITLE
Link to "Microsoft Azure Projects Contribution Guidelines" results in 404 redirect.

### ISSUE THREAD

**Issue by jbobotek** [Azure/azure-sdk-for-c#1101]
**Describe the bug**
https://github.com/Azure/azure-sdk-for-c/blob/master/CONTRIBUTING.md, Line 38. Link is broken.

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**
Steps to reproduce the behavior: Click on the link.

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**
Link directs to an actual guidelines page.

**Screenshots**

**Setup (please complete the following information):**

- IDE: [e.g. IntelliJ]
- Version of the Library used

**Additional context**

**Information Checklist**
Please make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report

- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by weshaggard** [comment]
@ahsonkhan this is an interesting broken link scenario. I'm not sure we can easily detect it with our link verification script unless we start following all different types of redirects, however I've filed an issue https://github.com/Azure/azure-sdk-tools/issues/910 to investigate.

**Comment by p-bojkowski** [comment]
Same here: https://github.com/Azure/azure-libraries-for-net/issues/1201
