### ISSUE TITLE
Rename the az_failed helper method for az_result to az_result_failed and remove az_succeeded.

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-c#1104]
Semantically, one is just a negation of the other.

https://github.com/Azure/azure-sdk-for-c/blob/9ce11465d167e512e1abdaa912bc0e5c5dec3346/sdk/inc/azure/core/az_result.h#L139-L156

Most of the coding patterns I have seen is:
```C
if (az_failed(...))
{
   // log, early return, etc.
}
// Continue with expected success path and logic.
```
OR
```C
AZ_RETURN_IF_FAILED(...);
// Continue with expected success path and logic.
```

From @JeffreyRichter 
> If we decide to keep one, I'd keep az_failed. az_suceess should return true if the code is >=0.  The idea is that the function is returning a reason for success. But the caller may only care that the function was successful and not care WHY it was successful.

**Comment by RickWinter** [comment]
We should leave both.  Developers often times prefer to NOT use the `if(!(AZ_FAILED(...)){}` pattern.  Code readability its cleaner and clearer to read `if(AZ_SUCEEDED(...)){}

**Comment by ahsonkhan** [comment]
I have seen folks use `!az_succeeded` in a few places. I don't necessarily buy the argument that developers prefer one over the other.

For example:
https://github.com/azure-rtos/azure-iot-preview/blob/d0343b59943d096da40feafec80ea7958e7dd8cf/samples/sample_pnp_temperature_controller/sample_pnp_thermostat_component.c#L62-L64

If we didn't have `az_succeeded`, the developer would have more cleanly written `az_failed(...)` instead. This goes back to the point that giving the user an extra choice/decision to make can be counter-productive here.

Since one is a negation of the other, users can always flip the condition not use the `!` if they really wanted to. Also, there is nothing stopping them from creating their own `az_succeeded(...)` method that is `!az_failed(...)`, but like I said, it introduces two ways to do the same thing which introduces brittleness in the customers code, making it harder to maintain and update, and to review for correctness.

```C
if (!az_failed(...))
{
  // success path
}
else
{
  // fail path
}
```

Versus flipped:
```C
if (az_failed(...))
{
  // fail path
}
else
{
  // success path
}
```

The overwhelmingly common pattern I have seen, at least in our code base and sample, is using the fail to do an early break and return or exit either via the `az_failed` method directly or the `AZ_RETURN_IF_FAILED` macro.

**Use of `az_failed`:**
src - 7
samples - 119
docs - 3
inc - 3

**Ue of `az_succeeded`:**
src - 11
samples - 14
docs - 3
inc - 2

**Use of `AZ_RETURN_IF_FAILED`:**
src - 14
samples - 156
docs - 0
inc - 1

I found no usages of `!az_failed(...)` and one use of `!az_succeeded(...)`:
https://github.com/Azure/azure-sdk-for-c/blob/bc577de6d8a601f845e3b695dca26e5f88ee1f8c/sdk/src/azure/core/az_json_writer.c#L82-L85

Let me see what some of the coding patterns and samples look like without using `az_succeeded` and get back to you. I would be surprised if it looks less clean/readable or becomes too cumbersome, but if that's the case, I will leave them as is.

**Comment by ahsonkhan** [comment]
This issue has a rename of a public method and hence can't be in the backlog. Moving back to september.
