### ISSUE TITLE
Guidelines: put a page with best practices on doxygen commenting.

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-c#1105]
Topics to cover: 
* `@retval` What to do when bool. az_results. -1, 0, and >=0. When not to use retval.
* Starting with capital letter, ending with periods.
* backticking (`NULL`, `true`, `false`, `uint32_t` and so on)
* `#` references (+ ending functions with `()`)
* short `@brief`s, when to use `@remarks` or `@notes`, or `@details`
* `@param[in]`, `[out]`, `[in,out]`, or just `@param`.
* Use `@file`. Use `@file` with no name after it.
* Few examples of non-ideal wording, and better ones (search https://github.com/Azure/azure-sdk-for-c/pull/1057 for examples)
* Do not use "see below" in doxygen comments.
* Documenting struct members, enum members. `///<` vs '///'. Separating groups with regular comment (`// === Section ===`). Separate with empty line before, stick from the top with with no newline.
* What not to include in doxygen, but put as a simple comment
* Documenting internal and local functions, tests? Samples? in .c files?

- Prefer illustrative do/don't format.

**Comment by RickWinter** [comment]
Moved to the SDK repo, 
https://github.com/Azure/azure-sdk/issues/1721

**Comment by ahsonkhan** [comment]
FYI, you can use the GitHub "Transfer issue" feature to move issues between repos. That makes it quite easy.

![image](https://user-images.githubusercontent.com/6527137/91092707-46805400-e60d-11ea-96a4-30bffe548d40.png)

![image](https://user-images.githubusercontent.com/6527137/91092795-66177c80-e60d-11ea-9050-80d82ac82b43.png)
