### ISSUE TITLE
Remove 'az_pair' and all its usages from internal and public surface area, and samples

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-c#1116]
The az_pair struct has limited usages within the SDK and we should consider removing it.
https://github.com/Azure/azure-sdk-for-c/search?p=1&q=az_pair&unscoped_q=az_pair

https://github.com/Azure/azure-sdk-for-c/blob/4d2f0902b91ac2cb54929f24b9c04f51fa4d4324/sdk/inc/azure/core/az_span.h#L528-L561

**It is currently being exposed as part of these public API that need to change:**
https://github.com/Azure/azure-sdk-for-c/blob/4d2f0902b91ac2cb54929f24b9c04f51fa4d4324/sdk/inc/azure/core/az_http.h#L250-L251
https://github.com/Azure/azure-sdk-for-c/blob/70106be3d91c0945f30735f67e7eee832d05267b/sdk/inc/azure/iot/az_iot_hub_client.h#L306

**It is also used as implementation detail here, which need to be re-written:**
https://github.com/Azure/azure-sdk-for-c/blob/d24a8908e1b14240ab9c5148f667f69c47404d1f/sdk/src/azure/core/az_http_private.h#L27-L42
https://github.com/Azure/azure-sdk-for-c/blob/9ce11465d167e512e1abdaa912bc0e5c5dec3346/sdk/src/azure/core/az_http_request.c#L192-L200
https://github.com/Azure/azure-sdk-for-c/blob/4d2f0902b91ac2cb54929f24b9c04f51fa4d4324/sdk/src/azure/platform/az_curl.c#L88-L89

**Comment by vhvb1989** [comment]
headers are az_pair.
See `az_http_request_append_header`.  It takes az_span for key and value but init an az_pair from them
`az_pair header_to_append = az_pair_init(key, value);`

Removing az_pair will let the headers buffer as a `az_span[]` where pair index is key and non pair index is value.
Headers size is calculated as bufferSize/sizeof(az_pair) .. it would need to be calculated as bufferSize/sizeof(az_span)*2 ? (I am not sure if this might give us alignment issues or not.

Also for getting a header, would we need to have az_span_key_out and az_span_value_out?

**Comment by danewalton** [comment]
Is this still looking to get removed?

**Comment by ahsonkhan** [comment]
> Is this still looking to get removed?

Yes, at the very least removing it from the public headers. If there is too much implementation detail relying on it, we might keep it internal.

We should certainly not expose this type as part of public API surface though (like in the case of `az_iot_hub_client_properties_next`).

**Comment by danewalton** [comment]
@ahsonkhan 
PR to remove on IoT side: https://github.com/Azure/azure-sdk-for-c/pull/1136
