### ISSUE TITLE
Consider renaming AZ_ERROR_INSUFFICIENT_SPAN_SIZE to be more generic: AZ_ERROR_NOT_ENOUGH_SPACE

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-c#1121]
Quite a few places return `AZ_ERROR_INSUFFICIENT_SPAN_SIZE` today but in many cases the span being referred to here is not passed in to the local method that returns this `az_result` but rather the type/struct that contains the destination buffer.

https://github.com/Azure/azure-sdk-for-c/blob/4d2f0902b91ac2cb54929f24b9c04f51fa4d4324/sdk/inc/azure/core/az_result.h#L84-L85

This could cause confusion when users see that the span size is too small, when the only span provided is an input.

For example, looking at this function locally, it returning `AZ_ERROR_INSUFFICIENT_SPAN_SIZE` makes it seem like `json_text` is too small, and not that the destination provided to `az_json_writer` is too small.
```C
AZ_NODISCARD az_result az_json_writer_append_json_text(az_json_writer* ref_json_writer, az_span json_text);
```

This is even more problematic if the input doesn't have any span parameters (or accepts more than one). This API returning `AZ_ERROR_INSUFFICIENT_SPAN_SIZE` is confusing since the destination is a `char*`. 
```C
AZ_NODISCARD az_result az_iot_hub_client_get_user_name(
    az_iot_hub_client const* client,
    char* mqtt_user_name,
    size_t mqtt_user_name_size,
    size_t* out_mqtt_user_name_length);

AZ_NODISCARD az_result az_json_token_get_string(
    az_json_token const* json_token,
    char* destination,
    int32_t destination_max_size,
    int32_t* out_string_length);
```

In this case, which span is the `az_result` referring to? It can't be (and isn't) the two input parameters.
```C
AZ_NODISCARD az_result az_http_request_set_query_parameter(
    az_http_request* ref_request,
    az_span name,
    az_span value,
    bool is_value_url_encoded);
```

Renaming it to something that is more generic, not using the term `span` would be more clear:
`AZ_ERROR_NOT_ENOUGH_SPACE`

@JeffreyRichter - what do you think?

**Comment by JeffreyRichter** [comment]
The focus is on how can a customer diagnose and fix whatever is wrong. So, by putting SPAN in the name, that tells the customer to look for some span. Why do you think making it more generic makes it more clear?

**Comment by ahsonkhan** [comment]
> So, by putting SPAN in the name, that tells the customer to look for some span. Why do you think making it more generic makes it more clear?

Because we are using it in cases where there is no span or where the span in question that needs to change is not part of that particular callsite.

Let's take an example where we use an API that doesn't have `az_span` in it's signature. The issue here has nothing to do with some `span` being too small.

```C
typedef struct
{
  char* name_string;
  int32_t name_length;
} model;

static az_result _az_get_json_string(az_span json_input, model* output)
{
  az_json_reader jr = { 0 };
  AZ_RETURN_IF_FAILED(az_json_reader_init(&jr, json_input, NULL));
  AZ_RETURN_IF_FAILED(az_json_reader_next_token(&jr));

  // This can fail and return AZ_ERROR_INSUFFICIENT_SPAN_SIZE
  // Where is the span here? We have a char* ptr and int32_t length.

  // Returning something like AZ_ERROR_NOT_ENOUGH_SPACE is applicable and clearer.
  AZ_RETURN_IF_FAILED(az_json_token_get_string(&jr.token,
      output->name_string,
      output->name_length,
      &output->name_length));

  return AZ_OK;
}

int main(void)
{
  // buffer is too small
  char output_string[5] = { 0 };
  model m = { .name_string = output_string, .name_length = 5 };

  az_result res = _az_get_json_string(AZ_SPAN_FROM_STR("some large string"), &m);

  if (az_succeeded(res))
  {
    printf("%s\n", output_string);
  }
  else
  {
    printf("%d\n", res);
  }

  return 0;
}
```

The same applies to `az_iot_hub_client_get_user_name`.

And another example where the destination is not obvious as part of the function call:
```C
static az_result _az_append_nested(az_json_writer* writer, az_span nested_json)
{
  az_result result = az_json_writer_append_json_text(writer, nested_json);

  if (result == AZ_ERROR_INSUFFICIENT_SPAN_SIZE)
  {
      // What span? The input nested_json? Is the input too small or wrong?
  }

  // AZ_ERROR_NOT_ENOUGH_SPACE is an improvement.
  // Basically, wherever the JSON writer appends the data to, is full. That could be a file, some ptr to a buffer, etc.
  // We, as authors of the SDK, know that the allocator context returns az_span destinations, but at the local method
  // call site, stating that span is too small might lead the customer in the wrong direction when diagnosing the issue.

  return result;
}
```

**Comment by ahsonkhan** [comment]
If we are OK with the verbosity, this might be fine too: `AZ_ERROR_NOT_ENOUGH_SPACE_IN_DESTINATION`

**Comment by JeffreyRichter** [comment]
This is fine with me. I don't care much about verbosity. Error codes either help with a different code path for runtime recovery or for diagnosing an issue statically to fix code.

**Comment by RickWinter** [comment]
Why would have AZ_ERROR_NOT_ENOUGH_SPACE_IN_DESTINATION and AZ_ERROR_INSUFFICOENT_SPAN_SIZE.  

We should pick a pattern AZ_ERROR_INSUFFICIENT_<item>_SIZE.  This way the customer knows they can expect to get this error when the <item> is too small.

**Comment by ahsonkhan** [comment]
> Why would we have AZ_ERROR_NOT_ENOUGH_SPACE_IN_DESTINATION and AZ_ERROR_INSUFFICOENT_SPAN_SIZE.


We wouldn't. No one is proposing that we keep both. The proposal is to rename the existing one.
