### ISSUE TITLE
Make the build pipelines more resilient if the build directory already exists.

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-c#1122]
See https://github.com/Azure/azure-sdk-for-c/pull/1100#issuecomment-679399544 for details

cc @danieljurek

**Comment by kurtzeborn** [comment]
Changing the "EngSys" label to "Client" since these labels track _who_ is doing the work and not where the work needs to be done.  In this case, this is a pipeline change that the libraries team should feel empowered to do themselves and just include a member of the EngSys team for a code review.
