### ISSUE TITLE
Failure in CI builds

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-c#1137]
D:\a\1\s\sdk\samples\iot\paho_iot_hub_pnp_component_sample.c(511,1): error C2220: the following warning is treated as an error [D:\a\1\s\build\sdk\samples\iot\paho_iot_hub_pnp_component_sample.vcxproj] 
<no file> : warning C6282: Incorrect operator: assignment of constant in Boolean context. Consider using '==' instead. [D:\a\1\s\build\sdk\samples\iot\paho_iot_hub_pnp_component_sample.vcxproj] 
<no file> : warning C6282: Incorrect operator: assignment of constant in Boolean context. Consider using '==' instead. [D:\a\1\s\build\sdk\samples\iot\paho_iot_hub_pnp_component_sample.vcxproj] 
Generating Code... 
Building Custom Rule D:/a/1/s/sdk/samples/iot/CMakeLists.txt

**Comment by danieljurek** [comment]
There was a compiler change on the Windows images between these builds passing/failing: 

**Passing:**
-- The C compiler identification is MSVC 19.26.28806.0 

**Failing:**
-- The C compiler identification is MSVC 19.27.29111.0


Do we want to try to pin to MSVC 19.27?

**Comment by RickWinter** [comment]
The compiler got smarter and is catching some real issues.  We need to fix the underlying issues b/c the compiler is what customers may use and its catching real issues.

**Comment by danewalton** [comment]
Am I blind? These line numbers don't make sense (for blobs and the component pnp sample).

**Comment by danewalton** [comment]
This is weird. It seems to be specifically complaining about the `AZ_SPAN_NULL`

![image](https://user-images.githubusercontent.com/36710865/91363401-6c465e00-e7b1-11ea-8c95-926c9a414451.png)

**Comment by danewalton** [comment]
If I set it to a valid span instead of the macro it seems to go away.

**Comment by ahsonkhan** [comment]
If I had to guess, using the macros is confusing the analyzer so it is falsely detecting the following type of coding pattern as an issue with boolean assignment:
```C
if (az_failed(rc =some_method(...)))
{
  ...
}
```

And thinking it needs to be `==`:
https://docs.microsoft.com/sr-latn-rs/visualstudio/code-quality/c6282?view=vs-2015#example

**Comment by antkmsft** [comment]
I think you are right. So, the question is, do we want to rewrite it, or to suppress the warning? My PR that reenables `/analyze` is currently stuck on it. I would suppress. This is bad warning. Totally legitimate practice. There isn't even an assignment being used in boolean context. `rc = somemethod()` evalueates to an `az_result`, not to boolean. And we properly pass that to `az_failed()` which takes `az_result` and returns boolean. I would understand if it would complain about `if(rc = sosmemethod())` - but I believe GCC or Clang will warn us. But even `if((rc = somemethod()) != AZ_OK)` should be fine.

Rewriting them does not make the code better, it makes the analysis tool happy. There isn't really an issue that analysis tool found.

So, my decision is to suppress the warning, especially given that it is a minmalistic change that does not require us to rewrite our samples. If we chnage our opinion, we always can remove the warning suppression, and rewrite samples as separate PR.

So, my PR to fix Precondition will also fix this issue.

**Comment by ahsonkhan** [comment]
Let's first verify that is in fact the issue.

For now, suppressing is fine by me. But I would prefer changing the code. It isn't too cumbersome, and imo, it is clearer/easier to read to be explicit with the assignment outside the if block.

Also, a minor concern with suppressing, is that we might accidentally do the `while (i = 5)` and have that go undetected. However, that is super unlikely especially since gcc/clang will catch it, like you said. Dogfooding the analysis and giving feedback is good nonetheless :)

> If we chnage our opinion, we always can remove the warning suppression, and rewrite samples as separate PR.

I think it is fine to defer changing it to later.

**Comment by antkmsft** [comment]
Ok, so I **_had_** to rewrite the ifs() [not super happy about it], see the PR description for details.

**Comment by danieljurek** [comment]
To whom should this issue be assigned?

**Comment by danieljurek** [comment]
Removing myself from assignment. Let me know if you need help with the pipelines but I think this is an issue with the code that the compiler is raising.

**Comment by antkmsft** [comment]
Rewriting just those if()s that use AZ_SPAN_NULL is sufficient, no need to rewrite all of them. PR description has details.

**Comment by ahsonkhan** [comment]
Closing this issue now that the fix https://github.com/Azure/azure-sdk-for-c/pull/1139 is merged. @antkmsft - feel free to re-open if needed.
