### ISSUE TITLE
CI failure in the Install Dependencies (vcpkg) step possibly due to out-dated artifacts on the machine

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-c#1142]
CI failure in the `Install Dependencies (vcpkg)` step from https://github.com/Azure/azure-sdk-for-c/pull/1139

https://dev.azure.com/azure-sdk/public/_build/results?buildId=510971&view=logs&j=bc7ff4a5-0370-5b6c-2e51-844007afb52d&t=0a35b456-51b9-5a0b-b96e-7c034a4efd47​​​​​​​
```text
Starting: Install Dependencies (vcpkg) 
============================================================================== 
Task : Command line 
Description : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows 
Version : 2.164.2 
Author : Microsoft Corporation 
Help : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line 
============================================================================== 
Generating script. 
Script contents: 
vcpkg install cmocka 
========================== Starting Command Output =========================== 
"C:\windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "D:\a\_temp\88094ebc-7c44-4e00-af4b-813aeffa1f9f.cmd"" 
Computing installation plan... 
Found both manifest and CONTROL file in port C:\vcpkg\ports\cmocka; please rename one or the other 
##[error]Cmd.exe exited with code '1'. 
Finishing: Install Dependencies (vcpkg)
```

cc @danieljurek, @weshaggard

**Comment by kurtzeborn** [comment]
Swapping the "EngSys" label for "Client" since these are used to track/indicate _who_ is investigating or making the fix and not necessarily what area the issue is in.  "EngSys" and "Client" are intended to be mutually exclusive (hence the coloring).

**Comment by ahsonkhan** [comment]
With the workaround in place, this is no longer blocking the release. That said, we should definitely fix and bring back the caching mechanism since that substantially reduced our CI build times.

**Comment by RickWinter** [comment]
@ahsonkhan please verify and close

**Comment by ahsonkhan** [comment]
This has been fixed by the updated vcpkg caching work by @danieljurek: https://github.com/Azure/azure-sdk-for-c/pull/1217
