### ISSUE TITLE
[FEATURE REQ] Clang Build Flag at the Gate

### ISSUE THREAD

**Issue by danewalton** [Azure/azure-sdk-for-c#116]
**Is your feature request related to a problem? Please describe.**
Not a problem just a request for the build pipeline.

**Describe the solution you'd like**
Have the `-Wdocumentation` flag enabled for a clang build at the gate to catch doxygen documentation that mismatches the implemented code.

**Describe alternatives you've considered**
None

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x ] Description Added
- [x ] Expected solution specified

**Comment by danieljurek** [comment]
* What's the best thing to do for C? What level of warnings? 
* Will not having documentation throw a warning (a lack of doxygen)? 

Ensure that setting is available across projects/build environments. Individual services can opt out if they need to.

**Comment by danewalton** [comment]
From our testing with the ulib repo it will only parse and catch documentation with the "doxygen" comment. AKA `/**` (doxygen) instead of `/*` (regular c comment). If you want to add some comments on something but don't want it to be parsed by doxygen you can just use regular c comments.
We have it blocking a merge at the gate (treat warnings as errors). This prevents mis-documented code from getting merged and having it brought up later with a github issue.
This would be a compile flag, specific to only clang since it doesn't exist on gcc.
