### ISSUE TITLE
Install and use cmake 3.10 on the agent machines

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-c#1169]
This might be best done with containers. 

The agent images have 3.17 and 3.18. We want to support Ubuntu 18.04 (which has cmake 3.10.x installed by default). We need to land cmake 3.10.x on the machine and use it to build. 

It won't help to make 3.17 or 3.18 behave as 3.10 because new features not in 3.10 will still work and we want the build to fail.

**Comment by RickWinter** [comment]
@danieljurek Please investigate the cost to fix this

**Comment by ahsonkhan** [comment]
Btw, we also use `add_compile_definitions` which is a cmake 3.12 feature. I just tried on WSL (which uses 3.10.2), and it fails to build the SDK because of this:

https://github.com/Azure/azure-sdk-for-c/blob/644d483e039a1d43e848c4cee344cdc8f7547b67/CMakeLists.txt#L16-L34

> cmake -DUNIT_TESTING=ON -DTRANSPORT_CURL=ON ..
```text
CMake Error at CMakeLists.txt:32 (add_compile_definitions):
  Unknown CMake command "add_compile_definitions".


-- Configuring incomplete, errors occurred!
```

cc @vhvb1989, @barcharcraz

**Comment by danieljurek** [comment]
Costing estimate: 5 

* On Linux/Windows it may be preferable to use container infrastructure to bypass all of the customization done to the DevOps hosted images. 
* On MacOS work will have to be done to install the desired version of CMake on the agent either side-by-side or instead of the installed version of CMake.

**Comment by kurtzeborn** [comment]
@danieljurek  has provided swag of 5 days for this work.  Since he's on leave, I'm leaving this assigned to you @RickWinter.  My understanding is that this will not be release blocking, so it can wait until he returns.  If you need it before then, we should discuss further.
