### ISSUE TITLE
Providing an incomplete log classifications array results in AV

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-c#1172]
This is a reliability bug. The following user code, which may be buggy, should not cause the SDK to AV:
```C
static void test_az_log_incomplete_list_fails_gracefully()
{
  az_log_classification const classifications[] = { AZ_LOG_HTTP_REQUEST };
  az_log_set_classifications(classifications);
  az_log_set_callback(_log_listener);

  assert_int_equal(0, _log_retry);
  _log_retry = 0;
  assert_int_equal(2229, az_iot_retry_calc_delay(5, 1, 500, 100000, 1234));
  assert_int_equal(0, _log_retry);

  az_log_set_callback(NULL);
  az_log_set_classifications(NULL);
}
```

```text
2: [  ERROR   ] --- EXCEPTION_ACCESS_VIOLATION occurred at 00007FF604D9635C.
2:
2: To debug in Visual Studio...
2: 1. Select menu item File->Open Project
2: 2. Change 'Files of type' to 'Executable Files'
2: 3. Open this executable.
2: 4. Select menu item Debug->Start
2:
2: Alternatively, set the environment variable
2: UNIT_TESTING_DEBUG to 1 and rebuild this executable,
2: then click 'Debug' in the popup dialog box.
2:
2:
2: [  FAILED  ] test_az_iot_provisioning_client_logging_succeed
2: [ RUN      ] test_az_log_incomplete_list_fails_gracefully
2: [  ERROR   ] --- EXCEPTION_ACCESS_VIOLATION occurred at 00007FF604D9635C.
2:
2: [  FAILED  ] test_az_log_incomplete_list_fails_gracefully
```

**This partially signals that we shouldn't be using an "end" sentinel to denote the end of list.**

![image](https://user-images.githubusercontent.com/6527137/91631590-8dfd3c00-e98f-11ea-9900-610e76317c06.png)

cc @antkmsft, @JeffreyRichter

**Comment by JeffreyRichter** [comment]
We should not AV when the customer sets the classifications to NULL. However, this does not signal that we should not be using a sentinel to signal the end of the list. Because multiple threads may be logging simultaneously and we want to allow the customer to change the classifications on-the-fly, the change has to be done atomically. It is only possible to change the pointer to array atomically. It would not be possible to atomically change the pointer AND the array length atomically. If we did this, then we'd need to create a lock and take it & release it multiple places throughout the code base - this is more code, more error prone, and can hurt performance. So, I think this is best implemented the way it currently is.

**Comment by ahsonkhan** [comment]
Is the multi-threaded scenario important in the embedded space? How often will folks update the classifications array, that putting it under a lock would be a performance bottleneck?

Can we solve this differently which retains both the correctness when callers mutate the array in multiple threads, without the need for a lock, AND doesn't result in AV from a reasonable bug in the caller's code?

I have a partial fix for the issue here, that (at least for now), retains the current design: https://github.com/Azure/azure-sdk-for-c/pull/1174

Brainstorming some ideas, maybe the first element of the array can denote the length of the array. Alternatively, we have a pre-allocated array of a certain size (say 16), and we don't allow an array of classifications larger than that.

**Comment by JeffreyRichter** [comment]
The whole point of an RTOS is that it provides multiple threads. You'd also have to take a lock for each log message being produced in case the classifications we're being changed by another thread at the same time. This is where the expense comes in.

**Comment by ahsonkhan** [comment]
> You'd also have to take a lock for each log message being produced in case the classifications we're being changed by another thread at the same time. This is where the expense comes in.

If the classifications array updates are under a lock, why would searching for the classification and producing a log message require a lock too?

**Comment by JeffreyRichter** [comment]
The customer can change the pointer to the entire array. That is the parameter passed to the function.

**Comment by antkmsft** [comment]
I'd say if it is possible to pass an incorectly terminated list, it is also possible to pass an incorrect length (for example, INT32_MAX)  -and we will basically do the same as if the list is not terminated.

But if you are reviewing places like this, also look at the retry policy list for the HTTP codes.

**Comment by ahsonkhan** [comment]
> it is also possible to pass an incorrect length (for example, INT32_MAX)

That's certainly a good point. I would like to add some factors that distinguish the two types of bugs.
1) Having a bug in the integer length is less likely and more defensible given this is an established pattern for C arrays and strings. Forgetting to add a terminating element in the array will certainly be more common (especially if you add another "last" element, and overwrite it).
2) If the incorrect length is being passed, it will likely be an off-by-one type error. We don't have to defend against an intentionally malicious developer.
3) Though both are obviously not desired, having an infinite loop that goes over all the pointer addresses until hitting AV (or forever) is worst than a loop going over int max addresses and still terminates.

> But if you are reviewing places like this, also look at the retry policy list for the HTTP codes.

Nice call out. I included that as part of https://github.com/Azure/azure-sdk-for-c/issues/1184
That said, unlike logging, if its for internal use only, and we are doing the right thing already, it is lower priority.
