### ISSUE TITLE
Run policheck over the repo as part of the next release

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-c#1175]

**Comment by RickWinter** [comment]
It would be fantastic if DevOps could do nightly scans of our repos and file issues.  Even better would be to put this in as part of the CI gates (assuming it could be done quickly, which might be hard to guarantee on large repos).

cc: @kurtzeborn @weshaggard @danieljurek

**Comment by ahsonkhan** [comment]
Ran v5.9.5 against 8dc7062646a164f0fa8082c6b185db88b7a508d2 and found no issues, for the upcoming preview 5 release.

**Comment by ahsonkhan** [comment]
Ran v5.9.5 against 5e9d7b96dbd98ce7125e4beed385959a32b4c6c1 and found no issues, for the upcoming GA release. Closing.
