### ISSUE TITLE
Add 'AZ_NODISCARD bool az_span_is_empty(az_span span)' convenience method.

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-c#1185]
Follow up from https://github.com/Azure/azure-sdk-for-c/issues/1082

**Comment by RickWinter** [comment]
@ahsonkhan In the previous work we removed the distinction of null and empty.  This would then be _is_null_or_empty(....) .  Why though do we want this?

**Comment by ahsonkhan** [comment]
> In the previous work we removed the distinction of null and empty. This would then be _is_null_or_empty(....) .

I would say quite the opposite. We don't want folks to think about or care about the `null`-ness of the backing span ptr. There is no concept of a null span. Why would it be `_is_null_or_empty`?

 > Why though do we want this?

It is a convenience API for a question callers ask all the time. Is the span I want to read from/write to empty? Without it, some folks think to write: `az_span_ptr(span) == NULL` rather than `az_span_size(span) == 0` which is the wrong check. Having this convenience method hides that and encourages the right pattern to follow. We, as part of the implementation, can always do the right thing.

Also, there is a lot of precedence for such an API in other languages:
https://docs.microsoft.com/en-us/dotnet/api/system.span-1.isempty?view=netcore-3.1https://en.cppreference.com/w/cpp/container/span/empty
