### ISSUE TITLE
Add function for DPS payload support

### ISSUE THREAD

**Issue by matsujirushi** [Azure/azure-sdk-for-c#1188]
**Is your feature request related to a problem? Please describe.**

IoT Plug and Play need to set modelId to payload.
https://docs.microsoft.com/en-us/azure/iot-pnp/concepts-developer-guide#dps-payload

**Describe the solution you'd like**

Add function for create DPS payload.

**Describe alternatives you've considered**

**Additional context**

**Information Checklist**

- [ ] Description Added
- [ ] Expected solution specified

**Comment by ahsonkhan** [comment]
cc @danewalton

**Comment by ahsonkhan** [comment]
Also cc'ing @ericwol-msft

**Comment by danewalton** [comment]
Yea we have it on our radar. Will likely be coming soon.

**Comment by RickWinter** [comment]
@danewalton can you update the milestone for this item to specify when it will be completed.

**Comment by danewalton** [comment]
At this time, we have decided to leave this requirement up to the customer. The customer would only have to write about four lines of code to get it to work and we will provide guidance on how to do it (example of what the calls would look like). But ultimately, the user will use the JSON APIs to create it.
