### ISSUE TITLE
Make sure to clearly document the behavior and supported scenario for log classifications

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-c#1192]
We need explicit docs that state:
- The user cannot and should not modify the array after passing it to `az_log_set_classifications`
- The user must make sure to end the array with a terminator.
- What does passing `NULL` or an empty array mean, and why it is distinct.
- ~User-defined classifications are supported.~

cc @JeffreyRichter, @RickWinter

**Comment by JeffreyRichter** [comment]
User-defined classifications are NOT supported. They happen to work but we are not committed to this. Also, the function to log something is internal; not public.
