### ISSUE TITLE
remove `fprintf` before MVP

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-c#120]
remove `fprintf` :-)

_Originally posted by @sergey-shandar in https://github.com/_render_node/MDExOlB1bGxSZXF1ZXN0MzMyMjkwMDgz/timeline/more_items_

**Comment by antkmsft** [comment]
https://github.com/Azure/azure-sdk-for-c/pull/115/commits/f9e9b7b5a47b7652ce3d57fee4321d64bb824edb
