### ISSUE TITLE
KeyVault Keys MVP

### ISSUE THREAD

**Issue by gilbertw** [Azure/azure-sdk-for-c#122]
Breakdown the needs for KeyVault MVP

Nice to haves, but inefficient
- http_response_lookup header by name
- json_parser lookup json key by name

Structs:
- az_keyvault_keys_client
  - Creation requires a Uri (AZ_SPAN)
  - Pipeline w/Azure Credentials
- az_keyvault_keys_client_options
   - API version
   - Pipeline configuration settings
- az_keyvault_keys_keys_options
  - key size (size_t, typical default is 4096)
  - Expires date
  - All the REST options
- [FUTURE] az_keyvault_keys_keyvaultkeysresponse (name???)
  - maps to the REST return values

KeyVault Methods:
- az_result az_keyvault_keys_client_init(az_keyvault_keys_client * client, az_span uri, ?credentials?, az_keyvault_keys_client_options * options)
  - options can be null if you want default

AZ_KEYVAULT_KEYS_KEYTYPE_XXXX
- az_result az_keyvault_keys_createKey(az_keyvault_keys_client * client, AZ_SPAN keyname, az_span (AZ_KEYVAULT_KEYS...) keytype, az_keyvault_keys_keys_options * options, az_http_response * out)
  - options can be null as they are optional
  - [FUTURE] Provide another function that will convert the http_response into an az_keyvault_keys_keyvaultkeysresponse struct

-------
- az_keyvault_keys_get
  - Takes in the client and an AZ_SPAN with the keyName
- az_keyvault_keys_delete
  - For now skip the LRO helpers
  - Takes in the client an AZ_SPAN with the keyname

Define the following:
- [x] Namespace pattern
- [x] Method pattern
- [x] Client
- [x] Methods
- [x] Consistency with other languages, https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/keyvault/azure-security-keyvault-keys/src/main/java/com/azure/security/keyvault/keys/KeyClient.java

**Comment by vhvb1989** [comment]
I believe this is done

**Comment by joshfree** [comment]
Moving from the December to the March milestone, as part of closing out the old past-due milestone.
