### ISSUE TITLE
Please indicate what version of the esp8266 board package was used as well.

### ISSUE THREAD

**Issue by jbobotek** [Azure/azure-sdk-for-c#1222]
**Is your feature request related to a problem? Please describe.**

MD [file](https://github.com/Azure/azure-sdk-for-c/blob/master/sdk/samples/iot/docs/how_to_iot_hub_esp8266_nodemcu.md) does not have complete information, please also add what version of the esp8266 board package was used. This can affect results even more than the version of Arduino IDE.

**Describe the solution you'd like**
Specify what version of esp8266 board package was used.

**Describe alternatives you've considered**

**Additional context**

**Information Checklist**
Please make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report

- [ ] Description Added
- [ ] Expected solution specified

**Comment by momuno** [comment]
@jbobotek what file are you looking at?  @ewertons you worked on the how to guide for this sample, correct?

**Comment by jbobotek** [comment]
File linked by second word in first paragraph

**Comment by jbobotek** [comment]
Thanks for the update @momuno
