### ISSUE TITLE
The `add_compile_definitions` feature requires cmake 3.12

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-c#1235]
Split off from https://github.com/Azure/azure-sdk-for-c/issues/1169#issuecomment-687373077

**Goal:** Update the CMake files so that the SDK can be built using the required version: cmake 3.10.

We use `add_compile_definitions` which is a cmake 3.12 feature. I just tried on WSL (which uses 3.10.2), and it fails to build the SDK because of this:

https://github.com/Azure/azure-sdk-for-c/blob/644d483e039a1d43e848c4cee344cdc8f7547b67/CMakeLists.txt#L16-L34

> cmake -DUNIT_TESTING=ON -DTRANSPORT_CURL=ON ..
```text
CMake Error at CMakeLists.txt:32 (add_compile_definitions):
  Unknown CMake command "add_compile_definitions".


-- Configuring incomplete, errors occurred!
```

cc @vhvb1989, @barcharcraz

**Comment by vhvb1989** [comment]
Don't think this is a good idea.
We might want to add some help for users about how to install CMake 3.12 instead, (some link or docs, it is really not that hard)

**Comment by danewalton** [comment]
Can we just use [`add_definitions()`](https://cmake.org/cmake/help/latest/command/add_definitions.html#command:add_definitions) instead?
