### ISSUE TITLE
Make sure IoT test names are unique even across components

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-c#1247]
We have two different tests with the same name:
https://github.com/Azure/azure-sdk-for-c/blob/18bc763c9e7285251490b0aeca34fb0604497560/sdk/tests/iot/provisioning/test_az_iot_provisioning_client_parser.c#L496
https://github.com/Azure/azure-sdk-for-c/blob/07c055c11b6bac12b8e547f92ee181204095fa1e/sdk/tests/iot/common/test_az_iot_common.c#L247

cc @danewalton

**Comment by danewalton** [comment]
noticed that and fixed in #1245
