### ISSUE TITLE
AZJSON writer: get_total_write API

### ISSUE THREAD

**Issue by hihigupt** [Azure/azure-sdk-for-c#1255]
Current JSON writer API when used with non-contiguous memory only allow user to get the amount of bytes written in the last block of memory. If user wants to write a JSON and want to know the total number of bytes written by JSON writer, then additional state is required via application, which needs to be updated when allocation callback is called by writer and then at the end call az_json_writer_get_bytes_used to know size used in last block. This causes additional state management/updates for application side. If we have API, which application can call at the end of json writer, then application does not need to track of this state or only update at the end when all write is completed.

I see that az_json_writer has an internal field that keep track of this information. Can this field be exposed as a public field.

**Comment by RickWinter** [comment]
@ahsonkhan This api sounds nice to have but not required for GA.  Was this requested by a customer?

**Comment by ahsonkhan** [comment]
Based on discussion with @hihigupt, moving this issue back to October, but it can be done post-GA.
This will be needed for the upcoming PNP support.

**Comment by hihigupt** [comment]
JSON writer when used with chunk memory requires additional state/logic to keep track of number of bytes written by JSON writer. This additional state and logic required by caller can be removed if JSON writer exposes the API around existing field total_bytes_written.

**Comment by ahsonkhan** [comment]
We'll work to add this for the Feb milestone.
