### ISSUE TITLE
Add preconditions to the doxygen docs

### ISSUE THREAD

**Issue by danewalton** [Azure/azure-sdk-for-c#1263]
Discovered the `@pre` tag to list preconditions for functions. Would look something like:

![image](https://user-images.githubusercontent.com/36710865/93136030-1d913300-f690-11ea-9574-669ea384e3da.png)

![image](https://user-images.githubusercontent.com/36710865/93135976-08b49f80-f690-11ea-9100-fc3fc62d9d04.png)

Is this something we would want to add to all the API's?

**Comment by ahsonkhan** [comment]
Nice!

> Is this something we would want to add to all the API's?

I think we should add them. Good idea.

**Comment by ahsonkhan** [comment]
@RickWinter, @antkmsft, @vhvb1989, @JeffreyRichter - thoughts?

**Comment by JeffreyRichter** [comment]
I really like this too!

**Comment by danewalton** [comment]
Tackling IOT side of it with #1619
