### ISSUE TITLE
re-enable Mac pipeline after fixing vcpkg not found issue

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-c#127]
@vhvb1989 this is issue is not related to the PR. I would suggest create an issue (for @danieljurek) and a separate PR so we can revert it as soon as it's fixed.

_Originally posted by @sergey-shandar in https://github.com/Azure/azure-sdk-for-c/pull/115#issuecomment-548131248_

**Comment by barcharcraz** [comment]
sorry, allcaps was bugging me. (MAC means Mandatory Access Control in my head)
