### ISSUE TITLE
Generating doxygen docs locally shouldn't produce artifacts at the root of the repo that aren't git ignored

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-c#1273]
Run the following at the root of the repo, locally:
> doxygen doc\Doxyfile

Observe the `docs\` folder get created at the root (which does get gitignored) along with other artifacts like `html\`, `latex\` directories, which aren't gitignored.

Ideally, the entire doc generation occurs in the `docs\` folder and doesn't pollute the repo root, and doesn't require us to add more things to gitignore.

**Comment by vhvb1989** [comment]
fixed already
