### ISSUE TITLE
[FEATURE REQ] Use `memmove` instead of `memcpy`

### ISSUE THREAD

**Issue by sergey-shandar** [Azure/azure-sdk-for-c#128]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Description Added
- [ ] Expected solution specified

**Comment by vhvb1989** [comment]
This was for az_span_copy().
Right now memcpy is only used by curl for writing to network on upload operations witch is fine
