### ISSUE TITLE
The comments for public define macros in 'az_iot_common.h' don't show up in doxygen

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-c#1300]
The doc comments for these marcos aren't showing up in doxygen. They likely need to use a different comment format style.

https://azuresdkdocs.blob.core.windows.net/$web/c/docs/1.0.0-preview.5/az__iot__common_8h.html

![image](https://user-images.githubusercontent.com/6527137/93538222-6c460380-f902-11ea-94f2-cd872c18dd82.png)

https://github.com/Azure/azure-sdk-for-c/blob/4087aea7a328a86f92ee9135950058dab62bfd71/sdk/inc/azure/iot/az_iot_common.h#L75-L90

**Comment by danewalton** [comment]
![image](https://user-images.githubusercontent.com/36710865/93546596-fb114b00-f917-11ea-9911-24805cadb0db.png)

If you scroll down a little bit they do render :)
