### ISSUE TITLE
Enable live testing for release config

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-c#1307]
Similar to using `BuildType` for the CI tests, we should make sure the live tests run on release builds:

https://github.com/Azure/azure-sdk-for-c/blob/803d010ece9e442cfc01720f6b13367fdf87c780/eng/pipelines/templates/jobs/archetype-sdk-tests.yml#L8-L32

cc @danieljurek, @antkmsft

**Comment by ahsonkhan** [comment]
FYI, @RickWinter

**Comment by vhvb1989** [comment]
Linux uses release by default.
Windows would use a configuration from the cmakesettings.json
