### ISSUE TITLE
The count stated in the CI logs doesn't match the number of artifacts produced

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-c#1322]
For example, see the pipeline from a recent PR: https://dev.azure.com/azure-sdk/public/_build/results?buildId=544543&view=artifacts&type=publishedArtifacts

It doesn't include the code coverage report or the map file output. Currently, the real number is 8.

![image](https://user-images.githubusercontent.com/6527137/93660769-23c43e00-fa07-11ea-8962-9aa0e4538eee.png)

```text
GenerateReleaseArtifacts

View raw log

Pool: Azure Pipelines
Image: windows-2019
Agent: Azure Pipelines 2
Started: Today at 11:13 PM
Duration: 3m 18s

Job preparation parameters
7 queue time variables used
3 artifacts produced
```

cc @danieljurek, @weshaggard

**Comment by weshaggard** [comment]
@ahsonkhan you are comparing different things. That summary output only accounts for the artifacts produced in the GenerateReleaseArtifacts job. Other artifacts are produces from other jobs.

**Comment by ahsonkhan** [comment]
Ah yes, good point.

For example, this leg produces 1 of the artifacts (code coverage):
https://dev.azure.com/azure-sdk/public/_build/results?buildId=544543&view=logs&j=74751b56-698d-5a5a-5271-ec1dd5a1cbe8
![image](https://user-images.githubusercontent.com/6527137/93687467-25c3e680-fa73-11ea-8636-0d4ea43e63c5.png)
