### ISSUE TITLE
Build fails on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by CIPop** [Azure/azure-sdk-for-c#1330]
**Describe the bug**
Build break if unit tests are selected with cmake 3.12.1 (highest in APT on Ubuntu 20 LTS).

***Exception or Stack Trace***

**To Reproduce**
See https://github.com/Azure/azure-sdk-for-c/pull/1208#issuecomment-696312753

***Code Snippet***
N/A - build break.

**Expected behavior**
Builds

**Screenshots**

**Setup (please complete the following information):**

- OS: Ubuntu 20 LTS
- IDE: N/A
- Version of the Library used: master branch

**Additional context**
Related to map file gen and https://github.com/Azure/azure-sdk-for-c/pull/1208#issuecomment-696312753

**Information Checklist**
Please make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report

- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by ahsonkhan** [comment]
cc @RickWinter, @vhvb1989

**Comment by ahsonkhan** [comment]
Only impacts building tests, but we should definitely fix it. Removing blocking release.

**Comment by vhvb1989** [comment]
On ubuntu20, somehow ${CMOCKA_LIBRARIES} is not populated by cmake when using VCPKG (maybe a diff version)
A quick patch for this is to add:
```cmake
    # when using VCPKG, use the LIB Variable
    if(DEFINED ENV{VCPKG_ROOT} OR DEFINED ENV{VCPKG_INSTALLATION_ROOT})
        if(CMOCKA_LIBRARIES MATCHES "")
            # Ubuntu 20 fix
            set(CMOCKA_LIB cmocka::cmocka)
        else()
            set(CMOCKA_LIB ${CMOCKA_LIBRARIES})
        endif()
    else()
        # consume from system installed lib
        set(CMOCKA_LIB cmocka)
    endif()
```
To cmake create/add cmocka test module.

**Comment by vhvb1989** [comment]
I will create a PR once we update the cmake module for creating cmocka tests (PR #1368 )

**Comment by ahsonkhan** [comment]
If you follow the steps in the docs and use the pinned version of the dependencies/vcpkg, the issue isn't reproducible:
https://github.com/Azure/azure-sdk-for-c#vcpkg

This is by design and expected. Please re-open if you are still seeing the issue after checking out the version that we support:
https://github.com/Azure/azure-sdk-for-c/blob/17ee1d158e4def2cb5a333a92a16b270847f52b3/eng/vcpkg-commit.txt#L1

**Comment by CIPop** [comment]
@ahsonkhan if a particular version is to be used for vcpkg then the docs should be updated to also remove

> If you previously installed VCPKG and dependencies, you may need to run ./vcpkg upgrade --no-dry-run to upgrade to the latest packages.

I'll give it a try with the specified version when I have some time.

**Comment by ahsonkhan** [comment]
> if a particular version is to be used for vcpkg then the docs should be updated to also remove

Agreed. Good catch! https://github.com/Azure/azure-sdk-for-c/pull/1397

**Comment by CIPop** [comment]
I confirm this fixes the build issue.
