### ISSUE TITLE
Memory requirements

### ISSUE THREAD

**Issue by OlegHahm** [Azure/azure-sdk-for-c#1418]
**Query/Question**
What are the minimum requirements for the SDK, particularly in terms of memory (ROM and RAM)?

***Why is this not a Bug or a feature Request?***
Should be obvious. ;-)

**Setup (please complete the following information if applicable):**

**Comment by wduraes** [comment]
Hi Oleg, we added a Size Char section to our docs as you'll find in [this page](https://github.com/Azure/azure-sdk-for-c/tree/master/sdk/docs/iot#size-chart).

**Comment by danewalton** [comment]
I'm going to go ahead and close this for inactivity. @OlegHahm please let us know if you would like this reopened.
