### ISSUE TITLE
Make sure to clean up or ignore unnecessary artifacts created as part of the CI build process

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-c#1422]
**Tasks:**
1) Add `tools/` to the .gitignore (and update the comment)
2) Remove/cleanup the `grepResults` file as part of the `Validate Characters are ASCII` step

**Where to make the change:**
1) 
https://github.com/Azure/azure-sdk-for-c/blob/028dc79a7defbae3b57ca883a3b39f108c3c586e/.gitignore#L273-L275
2) https://github.com/Azure/azure-sdk-for-c/blob/028dc79a7defbae3b57ca883a3b39f108c3c586e/eng/pipelines/templates/jobs/archetype-sdk-client.yml#L321-L330

See the following which ran `git status --ignored --untracked=all` to see what untracked files are left behind on the CI machine:
https://dev.azure.com/azure-sdk/public/_build/results?buildId=568858&view=logs&j=fdb9ce2e-b1c4-56cd-06a6-8aba558b4164&t=13e7785a-4853-5ba0-cc0f-661c14d09186

```text
HEAD detached at pull/1361/merge
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	BuildQualityChecksSummary.md
	grepResults
	tools/.store/dotnet-reportgenerator-globaltool/4.7.0/dotnet-reportgenerator-globaltool/4.7.0/.nupkg.metadata
	tools/.store/dotnet-reportgenerator-globaltool/4.7.0/dotnet-reportgenerator-globaltool/4.7.0/.signature.p7s
	tools/.store/dotnet-reportgenerator-globaltool/4.7.0/dotnet-reportgenerator-globaltool/4.7.0/LICENSE.txt
	tools/.store/dotnet-reportgenerator-globaltool/4.7.0/dotnet-reportgenerator-globaltool/4.7.0/Readme.txt
	tools/.store/dotnet-reportgenerator-globaltool/4.7.0/dotnet-reportgenerator-globaltool/4.7.0/dotnet-reportgenerator-globaltool.4.7.0.nupkg
...
```

**Comment by mitchdenny** [comment]
@ahsonkhan @TarenLewis kindly submitted a PR in response to this issue:

https://github.com/Azure/azure-sdk-for-c/pull/1531#issuecomment-735476242

I raised a couple of questions about it.

**Comment by ahsonkhan** [comment]
Fixed in https://github.com/Azure/azure-sdk-for-c/pull/1531
