### ISSUE TITLE
[FEATURE REQ] Find JSON value by path

### ISSUE THREAD

**Issue by gilbertw** [Azure/azure-sdk-for-c#143]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Description Added
- [ ] Expected solution specified

**Comment by sergey-shandar** [comment]
PR #148

**Comment by sergey-shandar** [comment]
Proposed API design

## JSON value (az_json_value.h)

```c
typedef enum {
  AZ_JSON_VALUE_NONE = 0,
  AZ_JSON_VALUE_NULL = 1,
  AZ_JSON_VALUE_BOOLEAN = 2,
  AZ_JSON_VALUE_NUMBER = 3,
  AZ_JSON_VALUE_STRING = 4,
  AZ_JSON_VALUE_OBJECT = 5,
  AZ_JSON_VALUE_ARRAY = 6,
} az_json_value_kind;

typedef struct {
  az_json_value_kind kind;
  union {
    bool boolean;
    az_span string;
    double number;
  } data;
} az_json_value;

az_result az_json_value_get_boolean(az_json_value * self, bool * out);
az_result az_json_value_get_number(az_json_value * self, double * out);
az_result az_json_value_get_string(az_json_value * self, az_span * out);
```

## JSON reference (az_json_ref.h)

A JSON reference is based on this draft https://tools.ietf.org/html/draft-pbryan-zyp-json-ref-03

Only relative references will work (eg. `/a/35/foo/bar`).

```c
/**
 * Returns next item in the JSON reference.
 */
az_result az_json_ref_parser_get(az_span_reader * self, az_span * out);
```

## JSON get by reference (az_json_get.h)

```c
az_result az_json_get_by_ref(az_span self, az_span ref, az_json_value * out);
```

**Comment by JeffreyRichter** [comment]
Yes I like this signature but I think the parameter names could be better. I'm questioning 'self' because it doesn't indicate that the first parameter must be a span over a json string. And, should ref be pointer to reflect the format of the string/span that must be passed here?

**Comment by sergey-shandar** [comment]
@JeffreyRichter Agree. I've changed the parameter names. Thank you for the feedback.

**Comment by sergey-shandar** [comment]
Proposed API design

## JSON value (az_json_value.h)

```c
typedef enum {
  AZ_JSON_VALUE_NONE = 0,
  AZ_JSON_VALUE_NULL = 1,
  AZ_JSON_VALUE_BOOLEAN = 2,
  AZ_JSON_VALUE_NUMBER = 3,
  AZ_JSON_VALUE_STRING = 4,
  AZ_JSON_VALUE_OBJECT = 5,
  AZ_JSON_VALUE_ARRAY = 6,
} az_json_value_kind;

typedef struct {
  az_json_value_kind kind;
  union {
    bool boolean;
    az_span string;
    double number;
  } data;
} az_json_value;

az_result az_json_value_get_boolean(az_json_value * self, bool * out);
az_result az_json_value_get_number(az_json_value * self, double * out);
az_result az_json_value_get_string(az_json_value * self, az_span * out);
```

## JSON pointer (az_json_pointer_parser.h)

JSON pointer: https://tools.ietf.org/html/rfc6901

```c
/**
 * Returns a next item in the JSON pointer.
 */
az_result az_span_reader_read_json_pointer_token(az_span_reader * self, az_span * out_pointer_token);
```

## JSON get by pointer (az_json_get.h)

```c
az_result az_json_get_by_pointer(az_span json, az_span pointer, az_json_value * out);
```

**Comment by sergey-shandar** [comment]
Merged.
