### ISSUE TITLE
Deserialize JSON into objects

### ISSUE THREAD

**Issue by gilbertw** [Azure/azure-sdk-for-c#144]
Problems:

## Unknown Structure Size Problem

For strings, dictionaries and arrays we don't now structure size. There is two possible solutions:
1. allocate using user's fucntion.
2. a visitor pattern.

**Comment by sergey-shandar** [comment]
## Optional Properties

### Option # 1

```c
typedef struct {
  az_keyvault_json_web_key key;
  az_keyvault_key_attributes attributes;
  az_pair_span tags;
  bool managed;
  struct {
    bool key : 1;
    bool attributes : 1;
    bool tags : 1;
    bool managed : 1;
  } disabled_properties;
} az_keyvault_key_bundle;
```

### Option # 2

```c
typedef struct {
  struct {
    az_keyvault_json_web_key key;
    az_keyvault_key_attributes attributes;
    az_pair_span tags;
    bool managed;
  } properties;
  struct {
    bool key : 1;
    bool attributes : 1;
    bool tags : 1;
    bool managed : 1;
  } disabled_properties;
} az_keyvault_key_bundle;
```

**Comment by gilbertw** [comment]
Are disabled_properties equivalent to readonly?

**Comment by sergey-shandar** [comment]
@dilbertw no, `disabled_properties` contains flags for all optional properties. An optional property is a property that is not in `"required"` array. I will update an example to include required properties.

**Comment by sergey-shandar** [comment]
@gilbertw should I rename it to `disabled_optional_properties`?

**Comment by gilbertw** [comment]
How will the disabled_properties get used?  The other SDK languages ignore specifying whether a property is optional.

**Comment by vhvb1989** [comment]
@sergey-shandar  let's use az_optional_[type] as we discuss
```
// for instance, for bool
typedef struct {
  bool is_set : 1;
  bool value : 1;
} az_optional_bool;
```
This way we can let anything be 'non set' and use `AZ_INLINE bool AZ_BOOL_OPTIONAL_CREATE(bool value)` macro to assign this types.

**Comment by sergey-shandar** [comment]
@gilbertw other SDKs use nullable, optional types etc. As far as I understood OpenAPI 2.0 and JSON-Schema, an omitted property doen't mean a default value.
