### ISSUE TITLE
SDK no longer builds on Ubuntu 18.04

### ISSUE THREAD

**Issue by markrad** [Azure/azure-sdk-for-c#1514]
CMakeLists.txt file in repository root now has [the line](https://github.com/Azure/azure-sdk-for-c/blob/ae9548d71d2b39df1d52eb2c01fd52a92d171ea7/CMakeLists.txt#L49):
```cmake
cmake_policy(SET CMP0091 NEW) # https://cmake.org/cmake/help/v3.15/variable/CMAKE_MSVC_RUNTIME_LIBRARY.html
```
When attempting to build the SDK on Ubuntu 18.04 this causes the following failure:
```
markrad@markradedge:~/source/azure-sdk-for-c/build$ cmake ..
CMake Error at CMakeLists.txt:49 (cmake_policy):
  Policy "CMP0091" is not known to this version of CMake. 
-- The C compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Read version from /home/markrad/source/azure-sdk-for-c/sdk/inc/azure/core/az_version.h
-- AZ_SDK_VERSION_MAJOR 1
-- AZ_SDK_VERSION_MAJOR 1
-- AZ_SDK_VERSION_PATCH 0
-- AZ_SDK_VERSION_PRERELEASE beta.2
-- Configuring incomplete, errors occurred!
See also "/home/markrad/source/azure-sdk-for-c/build/CMakeFiles/CMakeOutput.log".
```
The problem here is twofold. First this particular policy is only supported in cmake 3.15 and yet the CMakeLists.txt file indicates that the minimum version required is __3.10__. From the file in question, [line 4](https://github.com/Azure/azure-sdk-for-c/blob/ae9548d71d2b39df1d52eb2c01fd52a92d171ea7/CMakeLists.txt#L4):
```cmake
cmake_minimum_required (VERSION 3.10)
```
The other problem, though not necessarily a bug is that the latest version of cmake available for Ubuntu 18:04 is __3.10.2__ as shown by:
```bash
markrad@markradedge:~/source/azure-embedded-sdk-sys/azure-sdk-for-c$ apt search cmake | grep ^cmake/

cmake/bionic-updates,now 3.10.2-1ubuntu2.18.04.1 amd64 [installed]
```
This is further frustrating because the policy only relevant to Windows builds so this could have been easily avoided.

**To Reproduce**
Clone repository and build as documented.

**Expected behavior**
Either the cmake script should accurately specify the version of cmake required or the cmake facilities that use higher versions should be removed. The latter would be my preferred solution since a lot of people are still on Ubuntu 18.04.

**Setup (please complete the following information):**

- OS: Ubuntu 18.04
- IDE: None - built from command line
- Commit: ae9548d71d2b39df1d52eb2c01fd52a92d171ea7

**Information Checklist**
Please make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report

- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by ahsonkhan** [comment]
Thanks for reporting the issue!

This was introduced in https://github.com/Azure/azure-sdk-for-c/pull/1394
@BillyONeal - got any suggestions that will fixe the underlying issue in a way that is compatible with cmake 3.10?

> This is further frustrating because the policy only relevant to Windows builds so this could have been easily avoided.

Right. We should at least move it to a windows only "ifdef" to reduce its impact on other platforms.

> The other problem, though not necessarily a bug is that the latest version of cmake available for Ubuntu 18:04 is 3.10.2 as shown by

You bring a reasonable concern. Our goal is to be cmake 3.10 compatible as best we can (see related issue: https://github.com/Azure/azure-sdk-for-c/issues/1235).

**Comment by BillyONeal** [comment]
I believe you could guard the whole thing with a check similar to:

https://github.com/microsoft/vcpkg/blob/5dc53211caedebf4387d590155ed53ee44161f10/scripts/cmake/vcpkg_common_definitions.cmake#L29-L33

Alternately you could provide instructions for users to use a current version of cmake on such systems. vcpkg deploys its own for example so we always build the ports tree with (currently) 3.18.

**Comment by markrad** [comment]
@BillyONeal Alternatively you could check what version of cmake is being used: https://gitlab.kitware.com/cmake/community/-/wikis/doc/cmake/Useful-Variables#system-compiler-information
