### ISSUE TITLE
How to use DPS-obtained data to connect to IoT hub?

### ISSUE THREAD

**Issue by FreddieChopin** [Azure/azure-sdk-for-c#1532]
With DPS you use SAS or X.509 certificate + key to authenticate the device. In return you get hostname and device ID. Should I now use just these two values (no password, no certificate) to connect to the IoT hub? Or maybe while connecting to the IoT hub I should reuse the SAS or X.509 certificate + key that I used with DPS?

**Comment by ericwol-msft** [comment]
Yes, you are correct. You get the assigned hub name from DPS.

**CERT**
The MQTT password is empty for cert auth. The same device cert is presented to both DPS and Hub endpoints. When DPS previsions the device in the hub, it will config it to use the device cert for auth.

**SAS**
For SAS auth, the password is generated on the device as a azure SAS token (the device key is a HMAC hash of the enrollment group and device id).

**Comment by danewalton** [comment]
Adding some extra docs for SAS just in case you or others would like it as a resource:
https://docs.microsoft.com/en-us/azure/iot-dps/concepts-symmetric-key-attestation#detailed-attestation-process

**Comment by FreddieChopin** [comment]
Thanks!
