### ISSUE TITLE
In the NodeMCU ESP8266 sample ca.h file is missing when one follow the steps using Windows and Powershell

### ISSUE THREAD

**Issue by vafzamora** [Azure/azure-sdk-for-c#1533]
If you follow the steps to run the sample for ESP8266 the file ca.h is generated in the bash script downloading the Baltimore root certificate and xxd in linux. 
The .ps1 version of the script doesn't do the same steps and as a result the ca.h file will be missing while compiling the sample. Wasn't hard to figure out the problem and build the file using WSL but is a missing step that took me some time. 

Sample url: [https://github.com/Azure/azure-sdk-for-c/blob/master/sdk/samples/iot/docs/how_to_iot_hub_esp8266_nodemcu.md](https://github.com/Azure/azure-sdk-for-c/blob/master/sdk/samples/iot/docs/how_to_iot_hub_esp8266_nodemcu.md) 

Regards,

**Comment by momuno** [comment]
@vafzamora Thank you for bringing this to our attention.  I am also glad you were able to find a workaround.

While a solution is developed and reviewed, for anyone else who encounters this issue using PowerShell, please use WSL to run the bash script.  This will create the ca.h file needed for the build.
