### ISSUE TITLE
[FEATURE REQ] Remove `const` in functions declarations

### ISSUE THREAD

**Issue by sergey-shandar** [Azure/azure-sdk-for-c#154]
Because of VC bug, our code looks like this 

```c
double sqr(double const x);

double sqr(double const x) { return x * x; }
```

In the future (when the bug is fixed), we can remove `const` from function declarations

```c
double sqr(double x);

double sqr(double const x) { return x * x; }
```

**Comment by gilbertw** [comment]
@vhvb1989 Your const cleanup I believe covers this work

**Comment by vhvb1989** [comment]
well, it covers it indirectly..  This was an issue preventing us to declare functions on headers as definition only with no const on them and then use const in .c files.
However, we have remove all const from header and .c files.  So, yes, this is covered but in a different way 🗡
