### ISSUE TITLE
We need a linter for C code

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-c#155]
These things should not be possible:
```c
az_curl_done(CURL ** pp);
...
CURL * p_curl;
az_curl_done(p_curl); // <-- does compile
```

or
```c
do_something(uint8_t const * x);
...
az_span span = (az_span){ .begin = ..., .size = ... };
do_something(span); // happy debugging!
```

@sergey-shandar suggested to assign this to you @barcharcraz, so that maybe you can rescommend us something we should use.

**Comment by barcharcraz** [comment]
I can't get the second example to compile.

```c
void do_something(uint8_t const *test)
{
    (void)test;
}
typedef struct az_span
{
    int size;
    uint8_t *data;
} az_span;
int main()
{
    az_span span = (az_span){.size = 8, .data = 0};
    do_something(span);
}
```

**Comment by barcharcraz** [comment]
Ah I see what's going on now.

CURL is:
```c
typedef void CURL;
```
so the first example is:

```c
az_curl_done(void** pp);

void* p_curl;
az_curl_done(p_curl); <- implicit conversion here
```

**Comment by barcharcraz** [comment]
for curl in particular it looks like there's a macro `CURL_STRICTER` that, when defined, gives a better typedef here, and would prevent this problem. Shame there's no easy way to find out about it by reading the user-facing docs.

**Comment by joshfree** [comment]
Any concern with using clang-tidy?

**Comment by sergey-shandar** [comment]
@joshfree I'm ok with anything if it solves such problems and not introducing more problems :-)

**Comment by vhvb1989** [comment]
I think @ahsonkhan  did something about adding Lint...  Can you confirm Ahson?

**Comment by ahsonkhan** [comment]
I ran the linter across our repo before GA, yes, but we should leave this issue open until that has been added to CI for automated checks.
