### ISSUE TITLE
Fix spelling errors in code

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-c#1557]
Follow this process to eliminate spelling errors: https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/406/Spell-Checking

See `ignorePaths` in `cspell.json` (when checked in https://github.com/Azure/azure-sdk-for-c/pull/1554) to find files which contain spelling errors. Files that are in `ignorePaths` will not be checked for spelling errors until they are removed from `ignorePaths`. 

Spelling errors may be as innocuous as misspelled words in comments, false positives (words that are correctly spelled but not recognized by the spell checker), or more severe resulting in interface changes (e.g. changing the name of a class or method name). Spelling errors should be examined and fixed by an appropriate SME.

_This work item might be larger than a single issue. It might make sense to convert this to an epic and create issues for different areas of ownership (like per-service or per-package)._

**Comment by RickWinter** [comment]
@danieljurek What remains to close out this issue?

**Comment by danieljurek** [comment]
Judging by the lack of specific file paths in cspell.json's `ignorePaths` entry, this is done. Thanks!
