### ISSUE TITLE
[FEATURE REQ] Configure VS debugger visualizations for az_spans

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-c#156]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Description Added
- [ ] Expected solution specified

**Comment by sergey-shandar** [comment]
- https://docs.microsoft.com/en-us/visualstudio/debugger/create-custom-views-of-native-objects?view=vs-2019
- https://bitbucket.org/eigen/eigen/src/default/debug/msvc/eigen.natvis

**Comment by ahsonkhan** [comment]
Folks in the embedded space tend to use several different IDEs, such as MPLab, STM32Cube, etc. A VS-centric solution wouldn't benefit those users.

The type `az_span` wraps around byte buffers, which may contain UTF-8 encoded text or just binary data. It is difficult to come up with context-specific debugger visualization for C99, especially one that works across various IDEs.

The debugger display in VS, for span, looks reasonable:
![image](https://user-images.githubusercontent.com/6527137/88999701-2083c000-d2aa-11ea-9761-ff758df95e54.png)

This is similar to the locals view:
![image](https://user-images.githubusercontent.com/6527137/88999778-5a54c680-d2aa-11ea-8fb1-036e23eb6142.png)

If you click on the text visualizer, you'll see the string contents as well:
![image](https://user-images.githubusercontent.com/6527137/88999741-3b563480-d2aa-11ea-9177-8851add29673.png)

Hence, closing. Feel free to re-open if you had a different visualization in mind that might be more useful in certain scenarios, and if you have ideas on how to achieve it.
