### ISSUE TITLE
Need to know how to use this on embedded

### ISSUE THREAD

**Issue by Abhi2109** [Azure/azure-sdk-for-c#1572]
**Query/Question**
Hi,

I need to know how to use this or package this for using on embedded devices with some 4 MB as total memory.

Please help me in step by step manner.

As when i have taken this solution and tried to package it using CMake(Windows) with my own wrapper for few functionality its giving a size of  10.4 MB on disk.

**Setup (please complete the following information if applicable):**

- IDE: [e.g. IntelliJ]
- Version of the Library used: 1.3.9

**Comment by danewalton** [comment]
Hey @Abhi2109 do you mean compiling it for embedded devices (binary size) or somehow packaging it like an apt-get for usage in development?

**Comment by Abhi2109** [comment]
somehow packaging it like an apt-get for usage in development?

Yes , packaging as installable with all the headers and .lib files (Windows).

One more catch here is the OS is Linux , so will the size(Memory Footprint) may vary between Windows --> Linux (I have no Idea).

**Comment by Abhi2109** [comment]
I have Few observation here.

1) To compile this for mbed we need a build folder in each sub-folder and then few supporting file.txt and CmakeList.Txt , just wanted to know to build this setup which option we need to enabled in our parent CmakeList.txt

**Comment by danewalton** [comment]
Do you have an example to point to which would be the kind of ideal support/scenario you're looking for?

**Comment by Abhi2109** [comment]
you can close this.
