### ISSUE TITLE
Platform_deinit is throwing Access write voilation

### ISSUE THREAD

**Issue by Abhi2109** [Azure/azure-sdk-for-c#1591]
Hi,
I am observing an issue while trying to get DeviceList so issue out here is Platform_init() and platform_deinit() is throwing Access write violation very sporadically.

Need to know the reason behind this. Any help would be highly appreciated.

**Comment by RickWinter** [comment]
@danewalton Is this SDK related or general IoT.  If its general IoT issue what is the correct location for those issues/questsions

**Comment by ericwol-msft** [comment]
Platform_init() is not part of this SDK.

**Comment by RickWinter** [comment]
@Abhi2109 This repo is for the azure-sdk-for-c.  It does not cover general purpose device issues.  Those issues should be filed to the device manufacturer.

**Comment by Abhi2109** [comment]
Sure you close this issue then.
