### ISSUE TITLE
Embedded C IoT Hub Certificate Samples on Linux don't compile

### ISSUE THREAD

**Issue by PascalBod** [Azure/azure-sdk-for-c#1597]
**Describe the bug**
The Embedded C IoT Hub Certificate Samples on Linux don't compile.

***Exception or Stack Trace***
None.

**To Reproduce**
* follow [the instructions](https://github.com/Azure/azure-sdk-for-c/blob/master/sdk/samples/iot/docs/how_to_iot_hub_samples_linux.md) up to and including section 4 of *Configure and Run the Samples*
* the result of the `cmake --build .` command of section 5 is:

```
/home/pascalb/azure-sdk-for-c/sdk/samples/iot/paho_iot_provisioning_sas_sample.c:152:3: error: missing initializer for field ‘httpsProxy’ of ‘MQTTClient_connectOptions’ {aka ‘struct <anonymous>’} [-Werror=missing-field-initializers]
  152 |   MQTTClient_connectOptions mqtt_connect_options = MQTTClient_connectOptions_initializer;
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~
```

***Code Snippet***
See above.

**Expected behavior**
Should compile.

**Screenshots**
None.

**Setup (please complete the following information):**

- OS: Linux Mint 20.1
- IDE: none
- Version of the Library used: not applicable

**Additional context**
None.

**Information Checklist**
Please make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report

- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by danewalton** [comment]
Interesting this seems to happen with the newest version of the vcpkg paho-mqtt. For now, I would recommend using the vcpkg version which we have [here](https://github.com/Azure/azure-sdk-for-c/blob/master/eng/vcpkg-commit.txt) which we support.

**Comment by danewalton** [comment]
I have a issue [here](https://github.com/eclipse/paho.mqtt.c/issues/1066) on paho for it.

**Comment by danewalton** [comment]
Going to go ahead and close this for now since we have a working vcpkg hash and the issue was opened on Paho.

**Comment by danewalton** [comment]
PR
https://github.com/eclipse/paho.mqtt.c/pull/1068

**Comment by danewalton** [comment]
This fix has been merged on paho
