### ISSUE TITLE
Is 1.0.0 LTS release

### ISSUE THREAD

**Issue by mrmubi** [Azure/azure-sdk-for-c#1620]
Hi There,

Just wondering if 1.0.0 is LTS release.

Thanks,
Mubi

**Comment by ahsonkhan** [comment]
@RickWinter can help answer this question.

**Comment by mrmubi** [comment]
Hi @RickWinter is that something you can help with.

**Comment by RickWinter** [comment]
The Azure SDKs all follow the [Support Polices](https://azure.github.io/azure-sdk/policies_support.html).  
I've added the relevant sections below for ease of access.  See the above link for the complete lifecycle support policy.

> ### Azure SDK lifecycle and support policy
> Azure SDK Lifecycle and support are governed by the latest [Microsoft Modern Lifecycle Policy](https://docs.microsoft.com/en-US/lifecycle/policies/modern), which will prevail in case of any conflicts with the information below.

The 1.0 release is in the Active stage

> 2. **Active** - The SDKs are generally available and fully supported, will receive new feature updates, as well as bug and security fixes.
> The major version will remain active for at least 12 months from the release date. Compatible updates for the major release are provided through minor versions, or patch versions.
> Customers are encouraged to use the latest version as that is the version that will get fixes and updates.
