### ISSUE TITLE
paho_iot_hub_telemetry_sample.c:connect_mqtt_client_to_iot_hub() failed with return value -1

### ISSUE THREAD

**Issue by shrinivasragolu** [Azure/azure-sdk-for-c#1624]
Hi All,

I tried using the instructions from below link to build and run telemetry application on Ubuntu 18.04 and I tried the same steps on my embedded Linux custom board. 

Link: https://github.com/Azure/azure-sdk-for-c/blob/master/sdk/samples/iot/docs/how_to_iot_hub_samples_linux.md

Please help me in resolving the issue.

Error Log:
--------------
AZ_IOT_HUB_HOSTNAME = Srinivas-IoTHub.azure-devices.net
AZ_IOT_HUB_DEVICE_ID = testdevice-x509
AZ_IOT_DEVICE_X509_CERT_PEM_FILE_PATH = /usr/sbin/device_cert_store.pem
AZ_IOT_DEVICE_X509_TRUST_PEM_FILE_PATH = 
		 
SUCCESS:	MQTT endpoint created at "ssl://Srinivas-IoTHub.azure-devices.net:8883".

                   Trace Output
Product name: Eclipse Paho Synchronous MQTT C Client Library
Version: 1.3.8
Build level: 2021-02-26T13:50:53Z
OpenSSL version: OpenSSL 1.1.1i  8 Dec 2020
OpenSSL flags: compiler: /home/srinivas/yocto/bolt-rev-a0-firmware-v1.0-202101250049/build/tmp/work/cortexa32-neon-poky-linux-musleabi/libproxy/0.4.15-r0/recipe-sysroot-native/usr/bin/arm-poky-linux-musleabi/arm-poky-linux-musleabi-gcc -fPIC -pthread -Wa,--noexecstack -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/home/srinivas/yocto/bolt-rev-a0-firmware-v1.0-202101250049/build/tmp/work/cortexa32-neon-poky-linux-musleabi/libproxy/0.4.15-r0=/usr/src/debug/libproxy/0.4.15-r0                 
OpenSSL build timestamp: built on: Fri Feb 26 13:47:18 2021 UTC
OpenSSL platform: platform: linux-generic32
OpenSSL directory: OPENSSLDIR: "/etc/ssl"
/proc/version: Linux version 5.4.25-yocto-standard (oe-user@oe-host) (gcc version 9.2.0 (GCC)) #1 Wed Dec 9 10:50:25 UTC 2020

=========================================================
19700101 000000.000 (3069792260)  (1)> Socket_outInitialize:132
19700101 000000.000 (3069792260)   (2)> SocketBuffer_initialize:106
19700101 000000.000 (3069792260)   (2)< SocketBuffer_initialize:114 (0)
19700101 000000.000 (3069792260)  (1)< Socket_outInitialize:145
19700101 000000.000 (3069792260)  (1)> SSLSocket_initialize:449
19700101 000000.000 (3069792260)   (2)> SSL_create_mutex:348
19700101 000000.000 (3069792260)   (2)< SSL_create_mutex:354 (0)
19700101 000000.000 (3069792260)   (2)> SSL_create_mutex:348
19700101 000000.000 (3069792260)   (2)< SSL_create_mutex:354 (0)
19700101 000000.000 (3069792260)  (1)< SSLSocket_initialize:495 (1)
19700101 000000.000 (3069792260)  (1)> MQTTStrncpy:917
19700101 000000.000 (3069792260)  (1)< MQTTStrncpy:927
19700101 000000.000 (3069792260)  (1)> MQTTStrncpy:917
19700101 000000.000 (3069792260)  (1)< MQTTStrncpy:927
19700101 000000.000 (3069792260)  (1)> Thread_create_sem:194
19700101 000000.000 (3069792260)  (1)< Thread_create_sem:219 (0)
19700101 000000.000 (3069792260)  (1)> Thread_create_sem:194
19700101 000000.000 (3069792260)  (1)< Thread_create_sem:219 (0)
19700101 000000.000 (3069792260)  (1)> Thread_create_sem:194
20210301 163549.639 (3069792260)  (1)< Thread_create_sem:219 (0)
20210301 163549.639 (3069792260)  (1)> Thread_create_sem:194
20210301 163549.639 (3069792260)  (1)< Thread_create_sem:219 (0)
20210301 163549.639 (3069792260)  (1)> MQTTPersistence_create:56
20210301 163549.639 (3069792260)  (1)< MQTTPersistence_create:104 (0)
20210301 163549.639 (3069792260)  (1)> MQTTPersistence_initialize:119
20210301 163549.639 (3069792260)  (1)< MQTTPersistence_initialize:127 (0)
20210301 163549.639 (3069792260)  (1)> MQTTPersistence_restoreMessageQueue:864
20210301 163549.639 0 queued messages restored for client testdevice-x509
20210301 163549.639 (3069792260)  (1)< MQTTPersistence_restoreMessageQueue:904 (0)
20210301 163549.639 (3069792260) (0)< MQTTClient_createWithOptions:508 (0)
SUCCESS:	Client created and configured.
20210301 163549.639 (3069792260) (0)> MQTTClient_connectAll:1692
20210301 163549.639 (3069792260)  (1)> UTF8_validateString:160
20210301 163549.639 (3069792260)   (2)> UTF8_validate:134
20210301 163549.639 (3069792260)   (2)< UTF8_validate:146 (1)
20210301 163549.639 (3069792260)  (1)< UTF8_validateString:165 (1)
20210301 163549.639 (3069792260)  (1)> MQTTClient_connectURI:1457
20210301 163549.639 (3069792260)   (2)> MQTTStrncpy:917
20210301 163549.639 (3069792260)   (2)< MQTTStrncpy:927
20210301 163549.639 (3069792260)   (2)> MQTTStrncpy:917
20210301 163649.780 (3069792260)   (2)< MQTTStrncpy:927
20210301 163649.780 (3069792260)   (2)> MQTTClient_connectURIVersion:1178
20210301 163649.780 Connecting to serverURI Srinivas-IoTHub.azure-devices.net:8883 with MQTT version 4
20210301 163649.780 (3069792260)    (3)> MQTTProtocol_connect:218
20210301 163649.780 (3069792260)     (4)> MQTTProtocol_addressPort:60
20210301 163649.780 (3069792260)     (4)< MQTTProtocol_addressPort:92
20210301 163649.780 (3069792260)     (4)> Socket_new:696
20210301 163649.780 New socket 3 for Srinivas-IoTHub.azure-devices.net:8883, port 8883
20210301 163649.780 (3069792260)      (5)> Socket_addSocket:174
20210301 163649.780 (3069792260)       (6)> Socket_setnonblocking:86
20210301 163649.780 (3069792260)       (6)< Socket_setnonblocking:91 (0)
20210301 163649.780 (3069792260)      (5)< Socket_addSocket:209 (0)
20210301 163649.780 Connect pending
20210301 163649.780 (3069792260)     (4)< Socket_new:852 (115)
20210301 163649.780 (3069792260)    (3)< MQTTProtocol_connect:340 (115)
20210301 163649.780 (3069792260)    (3)> MQTTClient_waitfor:2585
20210301 163649.780 (3069792260)     (4)> MQTTClient_cycle:2486
20210301 163649.780 (3069792260)      (5)> Socket_getReadySocket:252
20210301 163649.780 (3069792260)       (6)> Socket_continueWrites:995
20210301 163649.780 (3069792260)       (6)< Socket_continueWrites:1025 (0)
20210301 163759.703 (3069792260)       (6)> isReady:226
20210301 163759.703 (3069792260)       (6)< isReady:231 (1)
20210301 163759.703 (3069792260)      (5)< Socket_getReadySocket:328 (3)
20210301 163759.703 (3069792260)      (5)> MQTTClient_retry:2466
20210301 163759.703 (3069792260)       (6)> MQTTProtocol_keepalive:664
20210301 163759.703 (3069792260)       (6)< MQTTProtocol_keepalive:700
20210301 163759.703 (3069792260)       (6)> MQTTProtocol_retry:788
20210301 163759.703 (3069792260)       (6)< MQTTProtocol_retry:807
20210301 163759.703 (3069792260)      (5)< MQTTClient_retry:2476
20210301 163759.703 (3069792260)     (4)< MQTTClient_cycle:2574 (0)
20210301 163759.703 (3069792260)    (3)< MQTTClient_waitfor:2683 (0)
20210301 163759.703 (3069792260)    (3)> MQTTProtocol_addressPort:60
20210301 163759.703 (3069792260)    (3)< MQTTProtocol_addressPort:92
20210301 163759.703 (3069792260)    (3)> SSLSocket_setSocketForSSL:709
20210301 163759.703 (3069792260)     (4)> SSLSocket_createContext:550
20210301 163759.703 (3069792260)     (4)< SSLSocket_createContext:699 (1)
20210301 163759.703 SSL cipher available: 0:TLS_AES_256_GCM_SHA384
20210301 163759.703 SSL cipher available: 1:TLS_CHACHA20_POLY1305_SHA256
20210301 163759.703 SSL cipher available: 2:TLS_AES_128_GCM_SHA256
20210301 163759.703 SSL cipher available: 3:ECDHE-ECDSA-AES256-GCM-SHA384
20210301 164053.317 SSL cipher available: 4:ECDHE-RSA-AES256-GCM-SHA384
20210301 164053.317 SSL cipher available: 5:DHE-RSA-AES256-GCM-SHA384
20210301 164053.317 SSL cipher available: 6:ECDHE-ECDSA-CHACHA20-POLY1305
20210301 164053.317 SSL cipher available: 7:ECDHE-RSA-CHACHA20-POLY1305
20210301 164053.317 SSL cipher available: 8:DHE-RSA-CHACHA20-POLY1305
20210301 164053.317 SSL cipher available: 9:ECDHE-ECDSA-AES128-GCM-SHA256
20210301 164053.317 SSL cipher available: 10:ECDHE-RSA-AES128-GCM-SHA256
20210301 164053.317 SSL cipher available: 11:DHE-RSA-AES128-GCM-SHA256
20210301 164053.317 SSL cipher available: 12:ECDHE-ECDSA-AES256-SHA384
20210301 164053.317 SSL cipher available: 13:ECDHE-RSA-AES256-SHA384
20210301 164053.317 SSL cipher available: 14:DHE-RSA-AES256-SHA256
20210301 164053.317 SSL cipher available: 15:ECDHE-ECDSA-AES128-SHA256
20210301 164053.317 SSL cipher available: 16:ECDHE-RSA-AES128-SHA256
20210301 164053.317 SSL cipher available: 17:DHE-RSA-AES128-SHA256
20210301 164053.317 SSL cipher available: 18:ECDHE-ECDSA-AES256-SHA
20210301 164053.317 SSL cipher available: 19:ECDHE-RSA-AES256-SHA
20210301 164053.317 SSL cipher available: 20:DHE-RSA-AES256-SHA
20210301 164053.317 SSL cipher available: 21:ECDHE-ECDSA-AES128-SHA
20210301 164053.317 SSL cipher available: 22:ECDHE-RSA-AES128-SHA
20210301 164053.317 SSL cipher available: 23:DHE-RSA-AES128-SHA
20210301 164227.517 SSL cipher available: 24:RSA-PSK-AES256-GCM-SHA384
20210301 164227.517 SSL cipher available: 25:DHE-PSK-AES256-GCM-SHA384
20210301 164227.517 SSL cipher available: 26:RSA-PSK-CHACHA20-POLY1305
20210301 164227.517 SSL cipher available: 27:DHE-PSK-CHACHA20-POLY1305
20210301 164227.517 SSL cipher available: 28:ECDHE-PSK-CHACHA20-POLY1305
20210301 164227.517 SSL cipher available: 29:AES256-GCM-SHA384
20210301 164227.517 SSL cipher available: 30:PSK-AES256-GCM-SHA384
20210301 164227.517 SSL cipher available: 31:PSK-CHACHA20-POLY1305
20210301 164227.517 SSL cipher available: 32:RSA-PSK-AES128-GCM-SHA256
20210301 164227.517 SSL cipher available: 33:DHE-PSK-AES128-GCM-SHA256
20210301 164227.517 SSL cipher available: 34:AES128-GCM-SHA256
20210301 164227.517 SSL cipher available: 35:PSK-AES128-GCM-SHA256
20210301 164227.517 SSL cipher available: 36:AES256-SHA256
20210301 164227.517 SSL cipher available: 37:AES128-SHA256
20210301 164227.517 SSL cipher available: 38:ECDHE-PSK-AES256-CBC-SHA384
20210301 164227.517 SSL cipher available: 39:ECDHE-PSK-AES256-CBC-SHA
20210301 164227.517 SSL cipher available: 40:SRP-RSA-AES-256-CBC-SHA
20210301 164227.517 SSL cipher available: 41:SRP-AES-256-CBC-SHA
20210301 164227.517 SSL cipher available: 42:RSA-PSK-AES256-CBC-SHA384
20210301 164227.517 SSL cipher available: 43:DHE-PSK-AES256-CBC-SHA384
20210301 164425.764 SSL cipher available: 44:RSA-PSK-AES256-CBC-SHA
20210301 164425.764 SSL cipher available: 45:DHE-PSK-AES256-CBC-SHA
20210301 164425.764 SSL cipher available: 46:AES256-SHA
20210301 164425.764 SSL cipher available: 47:PSK-AES256-CBC-SHA384
20210301 164425.764 SSL cipher available: 48:PSK-AES256-CBC-SHA
20210301 164425.764 SSL cipher available: 49:ECDHE-PSK-AES128-CBC-SHA256
20210301 164425.764 SSL cipher available: 50:ECDHE-PSK-AES128-CBC-SHA
20210301 164425.764 SSL cipher available: 51:SRP-RSA-AES-128-CBC-SHA
20210301 164425.764 SSL cipher available: 52:SRP-AES-128-CBC-SHA
20210301 164425.764 SSL cipher available: 53:RSA-PSK-AES128-CBC-SHA256
20210301 164425.764 SSL cipher available: 54:DHE-PSK-AES128-CBC-SHA256
20210301 164425.764 SSL cipher available: 55:RSA-PSK-AES128-CBC-SHA
20210301 164425.764 SSL cipher available: 56:DHE-PSK-AES128-CBC-SHA
20210301 164425.764 SSL cipher available: 57:AES128-SHA
20210301 164425.764 SSL cipher available: 58:PSK-AES128-CBC-SHA256
20210301 164425.764 SSL cipher available: 59:PSK-AES128-CBC-SHA
20210301 164425.764 (3069792260)     (4)> MQTTStrncpy:917
20210301 164425.764 the src string is truncated
20210301 164425.764 (3069792260)     (4)< MQTTStrncpy:927
20210301 164425.764 (3069792260)    (3)< SSLSocket_setSocketForSSL:753 (1)
20210301 164627.464 (3069792260)    (3)> SSLSocket_connect:764
20210301 164627.464 SSL handshake started write:unknown:unknown
20210301 164627.464 SSL state connect:before SSL initialization:(NONE)
20210301 164627.464 sent 0 256 buflen 5
20210301 164627.464 sent 772 22 buflen 330
20210301 164627.464 SSL state connect:SSLv3/TLS write client hello:(NONE)
20210301 164627.464 SSL connect:SSLv3/TLS write client hello
20210301 164627.464 (3069792260)     (4)> SSLSocket_error:101
20210301 164627.464 SSLSocket error (5) in SSL_connect for socket 3 rc -1 errno 22 Invalid argument

20210301 164627.464 (3069792260)     (4)< SSLSocket_error:121 (-3)
20210301 164627.464 (3069792260)    (3)< SSLSocket_connect:822 (-3)
20210301 164627.464 (3069792260)    (3)> MQTTClient_disconnect1:1866
20210301 164627.464 (3069792260)     (4)> MQTTClient_closeSession:1065
20210301 164627.464 (3069792260)      (5)> WebSocket_close:527
20210301 164627.464 (3069792260)      (5)< WebSocket_close:575
20210301 164627.464 (3069792260)      (5)> SSLSocket_close:940
20210301 164627.464 (3069792260)       (6)> SSLSocket_destroyContext:927
20210301 164627.464 (3069792260)       (6)< SSLSocket_destroyContext:931
20210301 164627.464 (3069792260)      (5)< SSLSocket_close:953 (-1)
20210301 164627.464 (3069792260)      (5)> Socket_close:636
20210301 165103.617 (3069792260)       (6)> Socket_close_only:610
20210301 165103.617 (3069792260)       (6)< Socket_close_only:624 (0)
20210301 165103.617 (3069792260)       (6)> Socket_abortWrite:961
20210301 165103.617 (3069792260)       (6)< Socket_abortWrite:979 (0)
20210301 165103.617 (3069792260)       (6)> SocketBuffer_cleanup:153
20210301 165103.617 (3069792260)       (6)< SocketBuffer_cleanup:165
20210301 165103.617 Removed socket 3
20210301 165103.617 (3069792260)      (5)< Socket_close:663
20210301 165103.617 (3069792260)     (4)< MQTTClient_closeSession:1092
20210301 165103.617 (3069792260)    (3)< MQTTClient_disconnect1:1897 (0)
20210301 165103.617 (3069792260)   (2)< MQTTClient_connectURIVersion:1430 (-1)
20210301 165103.617 (3069792260)   (2)> MQTTClient_connectURIVersion:1178
20210301 165103.617 Connecting to serverURI Srinivas-IoTHub.azure-devices.net:8883 with MQTT version 3
20210301 165103.617 (3069792260)    (3)> MQTTProtocol_connect:218
20210301 165103.617 (3069792260)     (4)> MQTTProtocol_addressPort:60
20210301 165103.617 (3069792260)     (4)< MQTTProtocol_addressPort:92
20210301 165103.617 (3069792260)    (3)< MQTTProtocol_connect:340 (-1)
20210301 165103.617 (3069792260)    (3)> MQTTClient_disconnect1:1866
20210301 165103.617 (3069792260)     (4)> MQTTClient_closeSession:1065
20210301 165103.617 (3069792260)     (4)< MQTTClient_closeSession:1092
20210301 165409.408 (3069792260)     (4)> MQTTClient_stop:998
20210301 165409.408 (3069792260)     (4)< MQTTClient_stop:1033 (0)
20210301 165409.408 (3069792260)    (3)< MQTTClient_disconnect1:1897 (0)
20210301 165409.408 (3069792260)   (2)< MQTTClient_connectURIVersion:1430 (-1)
20210301 165409.408 (3069792260)  (1)< MQTTClient_connectURI:1649 (-1)
20210301 165409.408 (3069792260) (0)< MQTTClient_connectAll:1850 (-1)
ERROR:		/usr/src/debug/libproxy/0.4.15-r0/azure-sdk-for-c/sdk/samples/iot/paho_iot_hub_telemetry_sample.c:connect_mqtt_client_to_iot_hub():136: Failed to connect: MQTTClient return code -1.
If on Windows, confirm the AZ_IOT_DEVICE_X509_TRUST_PEM_FILE_PATH environment variable is set correctly.

Thanks,
Srinivas.

**Comment by ericwol-msft** [comment]
Your issues is not the the SDK. From the logs, it looks like the issues is in your SSL layer. Have you investigated this issue and error code?

20210301 164627.464 SSL connect:SSLv3/TLS write client hello
20210301 164627.464 (3069792260) (4)> SSLSocket_error:101
**20210301 164627.464 SSLSocket error (5) in SSL_connect for socket 3 rc -1 errno 22 Invalid argument**

20210301 164627.464 (3069792260) (4)< SSLSocket_error:121 (-3)
20210301 164627.464 (3069792260) (3)< SSLSocket_connect:822 (-3)

**Comment by srinivas1506** [comment]
Hi Eric,
 
I understand it is not from SDK. I have used VCPKG instructions mentioned from the link https://github.com/Azure/azure-sdk-for-c/blob/master/sdk/samples/iot/docs/how_to_iot_hub_samples_linux.md
VCPKG fetches all dependent packages and build static libraries, which are linked while building the sample applications.

I have tried to find out the SSL error. But could not succeed. Any suggestions or what this error about?
Could you please help me in decoding this error

Thanks,
Srinivas.

**Comment by ericwol-msft** [comment]
You use SSL_get_error() to get the error code

```
if ((ret = SSL_connect(c->ssl)) <= 0) {
    ret = SSL_get_error(c->ssl, ret);
    if((err = ERR_get_error())) {
        SSL_load_error_strings();
        ERR_load_crypto_strings();
        CRERROR(LOGSSLUTILS, "SSL connect err code:[%lu](%s)\n", err, ERR_error_string(err, NULL));
        CRERROR(LOGSSLUTILS, "Error is %s \n",ERR_reason_error_string(err));
    }
}
```
More info in the following links:
https://www.openssl.org/docs/man1.0.2/man3/SSL_connect.html
https://www.openssl.org/docs/man1.0.2/man3/SSL_get_error.html
