### ISSUE TITLE
How to connect to Iot Cental with azure-sdk-for-c? Thanks!

### ISSUE THREAD

**Issue by vuhuyhop197** [Azure/azure-sdk-for-c#1662]
**Query/Question**
A clear and concise ask/query.

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?

**Setup (please complete the following information if applicable):**

- IDE: [e.g. IntelliJ]
- Version of the Library used

 **Information Checklist**
 Please make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report

- [ ] Query Added
- [ ] Setup information Added

**Comment by RickWinter** [comment]
@danewalton @ericwol-msft Can you triage this question.

**Comment by ericwol-msft** [comment]
Iot Central uses Azure Device Provisioning Services (DPS) to onboard devices.

This SDK sample uses DPS
https://github.com/Azure/azure-sdk-for-c/blob/master/sdk/samples/iot/paho_iot_provisioning_sas_sample.c

You can get your id_scope from Central at this location
Administration -> Device connection

**Comment by vafzamora** [comment]
Sorry if it's a silly question, but for a complete scenario where my device is provisioned and immediately starts sending telemetry to IoT Central I need to combine the **paho_iot_provisioning_sas_sample.c** with the **paho_iot_hub_sas_telemetry_sample.c**. 

Is that correct?

**Comment by ericwol-msft** [comment]
yes. Here is a device sample of that.
 https://github.com/Azure-Samples/Microchip-PIC-IoT-Wx

**Comment by vuhuyhop197** [comment]
> Sorry if it's a silly question, but for a complete scenario where my device is provisioned and immediately starts sending telemetry to IoT Central I need to combine the **paho_iot_provisioning_sas_sample.c** with the **paho_iot_hub_sas_telemetry_sample.c**.
> 
> Is that correct?

You need to provisioning with IoT Central (It has a build-in DPS). You should send the model ID to apply the device template during this process too. After your device is provisioned, you can get the Hub Name and device ID to make the connection to IoT Central.

**Comment by vuhuyhop197** [comment]
> Iot Central uses Azure Device Provisioning Services (DPS) to onboard devices.
> 
> This SDK sample uses DPS
> https://github.com/Azure/azure-sdk-for-c/blob/master/sdk/samples/iot/paho_iot_provisioning_sas_sample.c
> 
> You can get your id_scope from Central at this location
> Administration -> Device connection

If following this example, I can provision the device with IoT Central. But the device is not automatically assigned the device template.

**Comment by vuhuyhop197** [comment]
I have found the solution [here](https://docs.microsoft.com/en-us/azure/iot-dps/how-to-send-additional-data), Thanks for your support.

**Comment by danewalton** [comment]
awesome I'll go ahead and close this for now
