### ISSUE TITLE
SAS token based authentication doesn’t work for DPS (Device Provisioning Service) sample app in Azure C SDK

### ISSUE THREAD

**Issue by cy-arsm** [Azure/azure-sdk-for-c#1677]
**Query/Question**
In case of DPS application, not able to validate device identity by validating the registration ID and key against the enrollment list entry using SAS tokens.

***Why is this not a Bug or a feature Request?***
1. From our application we are able to validate the device identity by validating the registration ID and key against the enrollment list entry using standard X.509 verification (X.509) by following,
    -  Certificate generation process: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-create-test-certificates?view=iotedge-2018-06
    -  Certificate Registration process: https://docs.microsoft.com/en-us/azure/iot-dps/tutorial-provision-device-to-hub
2. However we are not able to validate the device identity using SAS token. 
    -  We followed the link https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-security#security-token-structure for SAS token generation. 
    - Device validation fails for generated SAS token, registration ID and ID scope combination. Server returning "Device is not authorized" error.

*NOTE*:
For all HUB applications like C2D, direct method, telemetry etc we are able to connect and communicate to Azure cloud using SAS tokens (generated using "Visual code" IDE) and x509 certificates.

**Setup (please complete the following information if applicable):**

- OS: [FreeRTOS]
- IDE: [Eclipse]
- Version of the Library used: [v1.1.0]

 **Information Checklist**
 Please make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report

- [x] Query Added
- [x] Setup information Added

**Comment by sathishm6** [comment]
This issue was originally discussed in this link : https://docs.microsoft.com/en-us/answers/questions/277863/index.html

**Comment by CIPop** [comment]
@sathishm6 I'm not sure if I understand your question/bug. From the Q&A forum it appears that you are trying to use the X509 

We have a sample at https://github.com/Azure/azure-sdk-for-c/blob/master/sdk/samples/iot/paho_iot_provisioning_sas_sample.c for how to provision a device using SAS tokens.

I can run and provision the device for my setup (running on Ubuntu 20 with Paho):

```
AZ_IOT_PROVISIONING_ID_SCOPE = 0ne0000****
AZ_IOT_PROVISIONING_SAS_REGISTRATION_ID = my-sas-device1
AZ_IOT_PROVISIONING_SAS_KEY = ***
AZ_IOT_SAS_KEY_DURATION_MINUTES = 120
AZ_IOT_DEVICE_X509_TRUST_PEM_FILE_PATH =

[...]

                Status: 200
SUCCESS:        Client parsed registration status message.
SUCCESS:        Device provisioned:
                Hub Hostname: ***.azure-devices.net
                Device Id: my-sas-device1
```

Within my Device Provisioning Service portal I have created an individual enrollment with Symmetric Key authentication:
![image](https://user-images.githubusercontent.com/8635911/114937837-2cd98a00-9df3-11eb-8630-f16a1ea5b245.png)

Our sample present one way of deriving a SAS token using our public APIs. The application code needs to provide the HMAC-SHA256 and Base64 encoder. The flow is described here:
https://github.com/Azure/azure-sdk-for-c/blob/master/sdk/docs/iot/mqtt_state_machine.md#device-provisioning-service

and here:
https://github.com/Azure/azure-sdk-for-c/blob/master/sdk/docs/iot/mqtt_state_machine.md#connecting

We recommend that the Shared Access Key is stored within a Hardware Security Module capable of HMAC-SHA256.

**Comment by CIPop** [comment]
If you are trying to authenticate with an Enrollment Group (instead of an Individual Enrollment) you need to use additional steps during the device factory provisioning to derive a device-specific Shared Access Key from the Enrollment Group key.

These are described here: https://docs.microsoft.com/en-us/azure/iot-dps/concepts-symmetric-key-attestation#group-enrollments

To simplify things a bit, I've created a Github Gist: https://gist.github.com/CIPop/b719c12798461d5fad614b0148f6243a

I've tested this to work with the current release as well. Please reopen this issue if the scenario doesn't work for you.

**Comment by sathishm6** [comment]
Thanks for the details @CIPop. We will give it a try and get back / re-open the issue if needed, as suggested.

**Comment by CIPop** [comment]
@sathishm6 I just learned that Azure CLI has a tool to generate device-specific SAS tokens:
https://docs.microsoft.com/en-us/cli/azure/iot/dps?view=azure-cli-latest#az_iot_dps_compute_device_key

**Comment by CIPop** [comment]
Opened https://github.com/MicrosoftDocs/azure-docs/issues/73923 to track the documentation update.

**Comment by cy-arsm** [comment]
@CIPop , Still im not able to establish the connection with Azure cloud for DPS using SAS tokens.

- I generated the tokens using the CLI link shared by you https://docs.microsoft.com/en-us/cli/azure/iot/dps?view=azure-cli-latest#az_iot_dps_compute_device_key

command : 
az iot dps compute-device-key --key --registration-id
$ az iot dps compute-device-key --key cVgZz3XvNgUeaT6wy4fFATOso7edNAw2uyXyGj1qeNTlzTbGZpCj+Vdwnq+0EbDXYovWGChYusSMbiYmuEAKLA== --registration-id arsm-sas-regID
![Generate_SAS_Key](https://user-images.githubusercontent.com/57741068/115381953-be7d3900-a1f1-11eb-97e1-b8c3d6d1c4a3.PNG)

- I tried with both primary and secondary key of "Authentication : Symmetric Key" as key value in the above command  to generate SAS key.

- I assigned the generated output to "env_vars.hub_sas_key" in the application,

- With the above changes I executed the code and seeing connection failure.

Can you confirm above steps are correct? or any additional things has to be added.

**Comment by sathishm6** [comment]
@CIPop - Can you reopen this ticket to track this issue further and to get this to closure. Thanks.

**Comment by CIPop** [comment]
@cy-arsm for security reasons, you may want to change the DPS group key and device key you have shared above.

@sathishm6, @cy-arsm please first try the Paho sample to avoid any issues with the keys and registration ID and share your logs if it doesn't work.

If you are using Azure RTOS, please open a GH issue in their repo instead.

If you are using a different RTOS and your own implementation for SAS signatures and the sample worked for you, please check that your code follows the flow outlined here: https://github.com/Azure/azure-sdk-for-c/blob/master/sdk/docs/iot/mqtt_state_machine.md#device-provisioning-service 
and, in pseudocode here: https://github.com/Azure/azure-sdk-for-c/blob/master/sdk/docs/iot/mqtt_state_machine.md#connecting

You would need to provide your own HMAC256, Base64 functions that are compliant with the ones provided as example in our samples. (For example, I recommend checking that using the same expiration time you are getting the exact same SAS token and signature.)

**Comment by cy-arsm** [comment]
@CIPop , Changed the group key and device key mentioned in previous comment.
Im not using AZure RTOS, hence generating the key manually. 
Im using the Microsoft Python scripts (https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-security#security-token-structure)  which has HMAC256, Base64 functions for SAS key generation.
Connection failure is seeing with this approach.

Can you confirm the SAS token generation approach i'm using is correct.

**Comment by CIPop** [comment]
> Can you confirm the SAS token generation approach i'm using is correct.

It is not. You are trying to use a SAS token for IoT Hub to perform Device Provisioning.

Please follow the instructions above to use the Embedded C SDK for SAS token generation by using the Shared Access Key you've correctly generated for your `arsm-sas-regID` registration ID. 

You would need to set the following environment variables to run our sample on Windows or Linux:

```
export AZ_IOT_PROVISIONING_ID_SCOPE=0ne0?????
export AZ_IOT_PROVISIONING_SAS_REGISTRATION_ID=arsm-sas-regID
export AZ_IOT_PROVISIONING_SAS_KEY=<the output of the compute device key above>
```

**Comment by cy-arsm** [comment]
@CIPop , i'm trying to generate logs by compiling the Paho sample Azure SDK as mentioned in https://github.com/Azure/azure-sdk-for-c/blob/master/sdk/samples/iot/README.md.
However logs are not getting generated. Is there anything has to be enabled for logs to display?

**Comment by CIPop** [comment]
To enable Paho logs you need to set the following environment variables:

```
MQTT_C_CLIENT_TRACE=ON
MQTT_C_CLIENT_TRACE_LEVEL=PROTOCOL
or 
MQTT_C_CLIENT_TRACE_LEVEL=MAXIMUM
```

**Comment by cy-arsm** [comment]
@CIPop ,
We are able to run SAS DPS application on windows and were successfully able to register with Azure cloud.

We are also able to generate the SAS token using the python script https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-dev-guide-sas?tabs=python#security-token-structure and perform the registration successfully from our application on cortex-m4.

**Comment by CIPop** [comment]
Awesome! Great to hear @cy-arsm!
