### ISSUE TITLE
Which topic to be used for Subscribing to sent message in IOT HUB using MQTT

### ISSUE THREAD

**Issue by Abhi2109** [Azure/azure-sdk-for-c#1690]
Hi,
I would like to know just like when we are publishing the data/Payload to the 
Topic : devices/<deviceName>/messages/events/DeviceID=<deviceName>&%24.cid=11632&%24.mid=1527.

Can we have a provision to Subscribe to the topic which will send the receive acknowledgement such that device can receive the sent data simultaneously?

**Comment by Abhi2109** [comment]
Can i have update on this?

**Comment by danewalton** [comment]
Can you clarify the scenario a bit? The topic that you listed there is the topic to which you send telemetry. Acknowledgements for those messages will be by the MQTT protocol. What is the subscribe scenario you are talking about here?

**Comment by Abhi2109** [comment]
Ok.
1) Scenario : As soon i will send/Publish the data to MQTT,  i should get the data by virtue of subscribing to the same topic using MQTT.

Let's say i publish a josn data using MQTT to a particular Topic ,now my requirement is i should get that data back using MQTT protocol on same Topic.

**Comment by danewalton** [comment]
So you want a full loop? Basically a ping-pong scenario?

[IoT Hub is not a full MQTT broker at the moment](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-support) so what you're describing would have to be implemented with a service SDK. Essentially it would be telemetry sent to the service via telemetry, then the service would receive that message and send it back as a C2D message. So send to the telemetry topic and then subscribe to the C2D topic.

**Comment by Abhi2109** [comment]
Yes, you are right. Can i get this thing done for C any time soon from Microsoft side?

**Comment by Abhi2109** [comment]
If you can show me some code example then i can also give it a try from my side.

**Comment by danewalton** [comment]
The C service SDK is deprecated so I would recommend using something like the python or node SDKs. [Node SDK here](https://github.com/Azure/azure-iot-sdk-node). Here is an example of sending C2D messages from the service SDK ([here](https://github.com/Azure/azure-iot-sdk-node/blob/master/service/samples/javascript/send_c2d_message.js)). You can combine that with receiving telemetry using the Event Hub SDK [here](https://github.com/Azure/azure-iot-sdk-node/issues/917).

**Comment by Abhi2109** [comment]
I guess this ping pong technique is used sending/Receiving Device Twin. Why can't we use the same for telemetry data?

**Comment by danewalton** [comment]
Not exactly. Sending and receiving of twin properties are sent and received on different topics. Not only that but there is formatting required for that in the payload. At least for now this exact scenario isn't natively supported. Capabilities are limited to the features advertised on IoT Hub.

**Comment by Abhi2109** [comment]
So cannot you guys take this for a requested feature for upcoming IoT SDk releases?

**Comment by danewalton** [comment]
While we generally do take feature requests, we cannot take this one as it would necessitate rearchitecting the IoT Hub cloud offering. That is outside the scope of what we do on the SDK side. IoT Hub does not have full MQTT broker support at this time.
