### ISSUE TITLE
unable to Monitor the telemetry messages sent to the Azure IoT Hub

### ISSUE THREAD

**Issue by M-ichae-l** [Azure/azure-sdk-for-c#1716]
Under "azure-sdk-for-c/sdk/samples/iot/aziot_realtek_amebaD/" at "10.Monitor the telemetry messages sent to the Azure IoT Hub." the code below is not able to get the result 
`$ az iot hub monitor-events --login <your Azure IoT Hub connection string in quotes> --device-id <your device id>`
The "string" in code that asked is different from "Primary Connection String" given. According to [https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-get-connection-string ](https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-get-connection-string ) should change "Deviceid" into "SharedAccessKeyName"
However, still could not get the "Expected telemetry output:"

**Comment by danewalton** [comment]
Hi @M-ichae-l 
Can you try using the Primary Connection String which pops up after going here on the portal for IoT Hub:

![iothubcs](https://user-images.githubusercontent.com/36710865/115901165-b1409400-a415-11eb-8c4a-9fdb97c43015.png)

**Comment by S10143806H** [comment]
Hi @danewalton,
I have encountered the same issue, after executing 
`$ az iot hub monitor-events --login <your Azure IoT Hub connection string in quotes> --device-id <your device id>`
in PowerShell, the execution will hang at this line:
`uamqp.receiver: Receiver link failed to open - expecting to receive DETACH frame.,`.
The full error log has been attached below:
[error_log.txt](https://github.com/Azure/azure-sdk-for-c/files/6383666/error_log.txt)

I would like to seek your help with this issue. Many appreciate ~

**Comment by danewalton** [comment]
@S10143806H that seems to be a separate issue from what @M-ichae-l was originally asking about. Could you direct that issue to the azure cli GH repo?
https://github.com/Azure/azure-cli/issues

**Comment by M-ichae-l** [comment]
@danewalton I have tried your method. it works. So I suggested the readme should update to make the steps clear. Thank you!

**Comment by danewalton** [comment]
Thanks for the feedback @M-ichae-l I have a PR here to update that:
https://github.com/Azure/azure-sdk-for-c/pull/1723

Glad to hear it's working now!
