### ISSUE TITLE
VCPKG build error on 2020.06 tag

### ISSUE THREAD

**Issue by kalijana** [Azure/azure-sdk-for-c#1719]
the ./bootstrap-vcpkg.sh fails to build while compiling 
 **CMakeFiles/vcpkglib.dir/src/vcpkg/base/cofffilereader.cpp.o**
please find the attached file for details

**Comment by danewalton** [comment]
Hi @kalijana this looks to be an issue with vcpkg itself. Can you please reopen it on their repo?
https://github.com/Microsoft/vcpkg
