### ISSUE TITLE
ESP32 Sample needs small fixes

### ISSUE THREAD

**Issue by wduraes** [Azure/azure-sdk-for-c#1734]
The data being sent id not valid JSON. I think we miss setting the content encoding/type.

We should not add the device-id to the payload. Hub already adds that as "iothub-connection-device-id" to the payload automatically, so we are wasting bytes.

**Comment by sadranyi** [comment]
Any updates on this

**Comment by danewalton** [comment]
I'm not sure this is still the case. Have you found otherwise @sadranyi?

Here is the JSON payload being generated: https://github.com/Azure/azure-sdk-for-c-arduino/blob/952b528af99831d234f4152224261c1600d4a4ca/examples/Azure_IoT_Central_ESP32_AzureIoTKit/Azure_IoT_PnP_Template.cpp#L250-L259

**Comment by sadranyi** [comment]
Thanks

**Comment by danewalton** [comment]
Going to close this for now.
