### ISSUE TITLE
IAR compiler not supported in CMake

### ISSUE THREAD

**Issue by ryanwinter** [Azure/azure-sdk-for-c#1739]
**Describe the bug**
Current the CMake assumes that the user is either using MSVC, clang or gnu compilers as defined in this file. If the compiler is MSVC or clang then it assumes it's GNU.
https://github.com/Azure/azure-sdk-for-c/blob/de29097e07a2a9d7268e2dc6cd0b2a6e5ea8c495/eng/cmake/global_compile_options.txt#L20

When trying to compile with IAR, the copmile fails as the IAR compiler doesnt recognise the GNU compiler flags.

***Exception or Stack Trace***
NA

**To Reproduce**
1. Install IAR compiler
1. Recursive clone the [GSG ](https://github.com/azure-rtos/getting-started)
1. Configure the IAR path [here](https://github.com/azure-rtos/getting-started/blob/04e4d630b8a13a162083e051e6fabd0e11299097/cmake/arm-iar-cortex-toolchain.cmake#L4)
1. Change to "STMicroelectronics/STM32L4_L4+"
1. Run `cmake -Bbuild -GNinja -DCMAKE_TOOLCHAIN_FILE="../../cmake/arm-iar-cortex-m4.cmake"`
1. Run `cmake --build build`
1. Observe compiler error due to GNU compiler flags

***Code Snippet***
There error is from here, where it assumes the compiler is GNU even when it isnt.
https://github.com/Azure/azure-sdk-for-c/blob/de29097e07a2a9d7268e2dc6cd0b2a6e5ea8c495/eng/cmake/global_compile_options.txt#L20

**Expected behavior**
Only add GNU compiler flags if using the GNU compiler. If the compiler is unknown to the C-SDK, then dont add additional compiler flags.

**Screenshots**
NA

**Setup (please complete the following information):**
- OS: Windows
- IDE: CMake
- master

**Additional context**
NA

**Information Checklist**
Please make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report

- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by danewalton** [comment]
Hey Ryan thanks for the feedback. Mind taking a look here for a potential fix?
https://github.com/Azure/azure-sdk-for-c/pull/1741
