### ISSUE TITLE
Add public depth field for JSON reader

### ISSUE THREAD

**Issue by danewalton** [Azure/azure-sdk-for-c#1744]
This will be needed for PnP property reader. Example usage here:
https://github.com/Azure/azure-sdk-for-c/blob/93fb3362a37753c67aca4b52b852441e097f4dbf/sdk/src/azure/iot/az_iot_pnp_client_property.c#L240

**Comment by ahsonkhan** [comment]
New usage link:
https://github.com/Azure/azure-sdk-for-c/blob/75afd98a1efd41d0c1f4475f692da88547a61582/sdk/src/azure/iot/az_iot_hub_client_properties.c#L242

From:
https://github.com/Azure/azure-sdk-for-c/blob/feature/iot_pnp_stage/sdk/src/azure/iot/az_iot_hub_client_properties.c#L242
