### ISSUE TITLE
i think my corporate firewall is blocking SNTP

### ISSUE THREAD

**Issue by graySquirrel** [Azure/azure-sdk-for-c#1756]
**Query/Question**
Can I skip the SNTP time sync?  ow what can i do?
i am running the aziot_esp32 sample app with no changes (other than configs)

***Why is this not a Bug or a feature Request?***
I think it has to do with my environment.

**Setup (please complete the following information if applicable):**

- OS: arduino
- IDE: arduino IDE 1.8.15
- Version of the Library used

 **Information Checklist**
 Please make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report

- [ ] Query Added
- [ ] Setup information Added

**Comment by ericwol-msft** [comment]
No, TLS certificate validation requires an accurate clock.

**Comment by RickWinter** [comment]
@danewalton Can this issue be closed?

**Comment by ericwol-msft** [comment]
yes
