### ISSUE TITLE
ESP8266 not working with latest ESP board library (3.0.0)

### ISSUE THREAD

**Issue by 17lukassantos** [Azure/azure-sdk-for-c#1759]
"C:\\Users\\Lukas\\AppData\\Local\\Arduino15\\packages\\esp8266\\tools\\xtensa-lx106-elf-gcc\\3.0.0-newlib4.0.0-gnu23-48f7b08/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-IC:\\Users\\Lukas\\AppData\\Local\\Arduino15\\packages\\esp8266\\hardware\\esp8266\\3.0.0/tools/sdk/include" "-IC:\\Users\\Lukas\\AppData\\Local\\Arduino15\\packages\\esp8266\\hardware\\esp8266\\3.0.0/tools/sdk/lwip2/include" "-IC:\\Users\\Lukas\\AppData\\Local\\Arduino15\\packages\\esp8266\\hardware\\esp8266\\3.0.0/tools/sdk/libc/xtensa-lx106-elf/include" "-IC:\\Users\\Lukas\\AppData\\Local\\Temp\\arduino_build_976857/core" -c -w -Os -g -free -fipa-pta -mlongcalls -mtext-section-literals -fno-rtti -falign-functions=4 -std=gnu++17 -MMD -ffunction-sections -fdata-sections -fno-exceptions -DMMU_IRAM_SIZE=0x8000 -DMMU_ICACHE_SIZE=0x8000 -DNONOSDK22x_190703=1 -DF_CPU=80000000L -DLWIP_OPEN_SRC -DTCP_MSS=536 -DLWIP_FEATURES=1 -DLWIP_IPV6=0 -DARDUINO=10815 -DARDUINO_ESP8266_NODEMCU_ESP12E -DARDUINO_ARCH_ESP8266 "-DARDUINO_BOARD=\"ESP8266_NODEMCU_ESP12E\"" -DLED_BUILTIN=2 -DFLASHMODE_DIO -DESP8266 "-IC:\\Users\\Lukas\\AppData\\Local\\Arduino15\\packages\\esp8266\\hardware\\esp8266\\3.0.0\\cores\\esp8266" "-IC:\\Users\\Lukas\\AppData\\Local\\Arduino15\\packages\\esp8266\\hardware\\esp8266\\3.0.0\\variants\\nodemcu" "-IC:\\Users\\Lukas\\AppData\\Local\\Arduino15\\packages\\esp8266\\hardware\\esp8266\\3.0.0\\libraries\\ESP8266WiFi\\src" "-IC:\\Users\\Lukas\\Documents\\Arduino\\libraries\\PubSubClient\\src" "-IC:\\Users\\Lukas\\Documents\\Arduino\\libraries\\azure-sdk-for-c" "C:\\Users\\Lukas\\AppData\\Local\\Temp\\arduino_build_976857\\sketch\\aziot_esp8266.ino.cpp" -o "C:\\Users\\Lukas\\AppData\\Local\\Temp\\arduino_build_976857\\sketch\\aziot_esp8266.ino.cpp.o"
C:\Users\Lukas\Documents\azure-sdk-for-c-master\azure-sdk-for-c-master\sdk\samples\iot\aziot_esp8266\aziot_esp8266.ino: In function 'void initializeClients()':
aziot_esp8266:110:20: error: 'class BearSSL::WiFiClientSecure' has no member named 'setCACert'
  110 |   if (!wifi_client.setCACert((const uint8_t*)ca_pem, ca_pem_len))
      |                    ^~~~~~~~~
Usando a biblioteca ESP8266WiFi na versão 1.0 na pasta: C:\Users\Lukas\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.0\libraries\ESP8266WiFi 
Usando a biblioteca PubSubClient na versão 2.8 na pasta: C:\Users\Lukas\Documents\Arduino\libraries\PubSubClient 
Usando biblioteca azure-sdk-for-c na pasta: C:\Users\Lukas\Documents\Arduino\libraries\azure-sdk-for-c (legacy)
exit status 1
'class BearSSL::WiFiClientSecure' has no member named 'setCACert'

**Comment by ChottaBhaii** [comment]
yah. says 'class BearSSL::WiFiClientSecure' has no member named 'setCACert'. I think setCACert has been removed from the BearSSL. is there any solution for this

**Comment by tomaszblachowiak** [comment]
You can downgrade ESP8266 Boards to 2.7.4.

**Comment by RickWinter** [comment]
@danewalton @ericwol-msft This looks unrelated to the Azure SDK.  Is there a repo this issue should be transferred to?

**Comment by danewalton** [comment]
Yes and no it's related to the sample we have but not core SDK functionality. We should keep this open while we investigate.

**Comment by ewertons** [comment]
Hi @17lukassantos ,

there is a new Espressif ESP8266 board library version published (3.0.1) and it no longer shows the the compilation issue from the previous version (3.0.0).

**Comment by ewertons** [comment]
We will close this issue, but if you find any other problems related to this matter, please feel free to reopen it.
