### ISSUE TITLE
[BUG] a JSON string parser and a JSON pointer parser should return correct UNICODE code-points

### ISSUE THREAD

**Issue by sergey-shandar** [Azure/azure-sdk-for-c#178]
**Describe the bug**
Currently JSON pointer parser and JSON string parser returns bytes instead of UNICODE code points. It may return incorrect result when we compare a JSON member name with a JSON pointer token.

**Comment by JeffreyRichter** [comment]
Right now, we don't even have the JSON pointer support so I'm just closing this issue.
