### ISSUE TITLE
Allow updating Compile option for SDK

### ISSUE THREAD

**Issue by hihigupt** [Azure/azure-sdk-for-c#1792]
When using Embedded sdk in ESP32 Azure IoT kit project (https://www.espressif.com/en/products/devkits/esp32-azure-kit/overview), cmake build is failing with warning.  As azure-sdk-for-c treats this waring as error in  gcc based build, building Embedded sdk is failing. Is it possible to allow caller of cmake to control atleast which warning are treated as error? 

Current warning treated as error is because of flag: -pedantic

Warning in our code is:

<>/Code/esp/stable/esp-idf/components/newlib/platform_include/assert.h:24:2: error: #include_next is a GCC extension [-Werror]
 #include_next <assert.h>

**Comment by danewalton** [comment]
likely closes this but I'll tag @RickWinter and @ahsonkhan to verify
https://github.com/Azure/azure-sdk-for-c/pull/1791

**Comment by ewertons** [comment]
[log_esp2 (1).txt](https://github.com/Azure/azure-sdk-for-c/files/6689435/log_esp2.1.txt)
[log_esp1.txt](https://github.com/Azure/azure-sdk-for-c/files/6689438/log_esp1.txt)
[log_esp4 (1).txt](https://github.com/Azure/azure-sdk-for-c/files/6689439/log_esp4.1.txt)
[log_esp3.txt](https://github.com/Azure/azure-sdk-for-c/files/6689440/log_esp3.txt)

**Comment by danewalton** [comment]
closed by #1791
