### ISSUE TITLE
Blob Upload Support

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-c#1796]
This tracks the [Storage] Blob Upload/Download Support - Embedded-C for the Azure SDK team

**Comment by jameszah** [comment]
Hi, does this imply your planning a blob upload in Nov 2021?

Would that be similar to the Storage_Blobs  branch?

I have been using this: IoTHubDeviceClient_LL_UploadToBlob() which works but seems much slower than normal upload traffic from esp32.

Would this bypass the iothub and go directly to the a azure Storage blob system?  ... and potentially faster?

**Comment by jameszah** [comment]
This is the activity I assume:
https://github.com/Azure/azure-sdk-for-c/pull/1943

I'm using this on an esp32 to upload to azure blobs.  Had a struggle getting the IOTHub blob-upload to work - starting with the standard arduino libraries, then a bit of fiddling with blob.h / blob.c to get it working.  It would be nice to get the IOTHub and regular blob-upload into the arduino library system.

**Comment by jameszah** [comment]
Hi, thanks for the response.  I got the IOTHub upload-to-blob working, but I think azure-sdk-for-c upload-to-blob would work better -- maybe faster with less memory.  I was hoping to get the attention of the "azure iot"  team.  

"azure-sdk-for-c" seems normally to be build on top of libcurl, but has the option of providing your own http stack -- which I assume the many "azure arduino iot" libraries (5-6 of them) would implement, or the esp-azure specifically for the esp <-> azure interaction. 
az_http_client_send_request seems to be the interface point -- but I cannot figure out that interface.  

I think 2 rest-api's would do the job, without libraries -- create-blob and store-block-to-blob ??? -- but a library is nicer.

Thanks
