### ISSUE TITLE
Azure Core: handling of long-running operations

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-c#18]
The core must provide facilities for handling Azure async operations.  This would likely contain primitives for custom end-to-end polling (e.g. some kind of promise/future abstraction) along with a synchronous blocking call.

**Comment by ahsonkhan** [comment]
@RickWinter, @JeffreyRichter - Is this issue still relevant for embedded C or can we close it?

**Comment by JeffreyRichter** [comment]
Close it for now. We have nothing that requires this at this time.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
