### ISSUE TITLE
Measure and investigate feasibility of some code size optimizations for Base64 APIs

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-c#1817]
Follow-up from https://github.com/Azure/azure-sdk-for-c/pull/1816

cc @RickWinter

**Comment by ahsonkhan** [comment]
@danewalton let me know the before/after for code size if you notice a large spike in either direction.

**Comment by danewalton** [comment]
| Lib | Size (Bytes) |
| --- | ------------- |
| Embedded (No precond) | `0x339 (825)` |
| mbedTLS | `0x314 (788)`  |
| AzureRTOS/FreeRTOS middleware impl | `0x2BE (702)` |
