### ISSUE TITLE
Make sure to update all references to IoT pnp and targets to point to the right place.

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-c#1825]
For example, this still points to the old cmake target, which no longer exists:
https://github.com/Azure/azure-sdk-for-c/blob/feature/iot_pnp/sdk/docs/iot/README.md#build

![image](https://user-images.githubusercontent.com/6527137/125141383-cb5f4980-e0c9-11eb-863d-52f2dc5ec990.png)

We probably want to do a search for all such places and fix them up.

cc @jspaith, @danewalton

**Comment by jspaith** [comment]
Thanks for catching this.  I'm naively assuming that the fix for this and other bugs will continue to be `feature/iot_pnp`, correct?  Does the beta/release-snap work change this or introduce anything else I should be aware of here?

**Comment by ahsonkhan** [comment]
Since this file and issue already exists in the README.md in `main`, it is cleaner to fix this in main and have that be backported to the feature branch when the "pull from main happens". And, in this case, we want the contents in `main` to be correct anyway.

It is largely up to you, but it is a good idea to try to make changes that minimize merge conflicts or "conflate" the source of truth, particularly when changing files that are being modified in both branches. One way to do that is to isolate and minimize the changes in the feature branch to **only** what is relevant to that particular feature.

> Does the beta/release-snap work change this or introduce anything else I should be aware of here?

Nothing significant has changed, or comes to mind atm. I did mention the process to avoid "squash and merge" using the GitHub UI when doing any future merges from main in our weekly meeting. The steps for that are as follows:
https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/16/FAQ?anchor=i-have-a-special-case-where-i-do-not-want-to-squash-and-merge-a-pr.--what-should-i-do%3F

**Comment by jspaith** [comment]
Fixed in #1891.
