### ISSUE TITLE
Decoupling from Azure

### ISSUE THREAD

**Issue by SamuelMarks** [Azure/azure-sdk-for-c#1837]
**Is your feature request related to a problem? Please describe.**
Looking through your repo, a large portion of it seems to be generic and thus useful for consuming other APIs; outside Microsoft's official Azure one.

**Describe the solution you'd like**
Auth, example input, example output, sequence diagrams coupled with mock API showing how this all works. All without needing to call any Azure APIs (e.g., have a little server in your `test` directory which serves a little API using simple sockets (Windows + POSIX, à la [src/tiny_web_server.cpp#L118-L122](https://github.com/SamuelMarks/oauth2/blob/bc0cf92/cpp/src/tiny_web_server.cpp#L118-L122) but fully C).

**Describe alternatives you've considered**
Write a new one from scratch (benefit: I could license it under `(Apache-2.0 OR MIT)`; and [initially] wouldn't have to worry about backwards-compatibility; disadvantage: time, [maybe] would make alt decisions you made better ones for).

**Additional context**
Would be good to just have your insights here. Like if there's any reason it couldn't be decoupled, and if it were decoupled what parts would you want to keep in this repo, or if you're encouraging a fork instead. Or if you want to keep the `az` namespace but still allow it to be generic, e.g., implementations for other client libraries, with their code either contributions directly to this repo or just listed in the "Used by" section of your `README.md`.

**Information Checklist**
Please make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report

- [x] Description Added
- [x] Expected solution specified

**Comment by RickWinter** [comment]
Thank you for taking the time to use the SDK and provide feedback.  It is true the SDK may appear general purpose and parts of it could in theory serve other purposes.  However with that said, the repo and the SDK are designed for, provided, and maintained to enable developers targeting Azure.  We have no current plans to general purpose any part of this repository.
