### ISSUE TITLE
Release pipelines need to update the version in main

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-c#1841]

**Comment by ahsonkhan** [comment]
This is relevant whenever the release is triggered from a feature branch.

cc @danieljurek

**Comment by danieljurek** [comment]
One edge case we should consider is if a hotfix release from a hotfix branch and that version is behind what is in `main` ... In that case we want to only update the version in the hotfix branch and not the version in `main`.

**Comment by kurtzeborn** [comment]
@ahsonkhan, what scenarios are you releasing out of a feature branch that would require the version in main to be bumped?  Feature versions should already be at a higher preview version than main.

**Comment by kurtzeborn** [comment]
In general, we don't support doing this anywhere else for other language repos.
