### ISSUE TITLE
KeyVault Keys complete APIs

### ISSUE THREAD

**Issue by gilbertw** [Azure/azure-sdk-for-c#189]
- [x] Create Key
https://docs.microsoft.com/en-us/rest/api/keyvault/createkey
POST {vaultBaseUrl}/keys/{key-name}/create?api-version=7.0
- [ ] Update Key
https://docs.microsoft.com/en-us/rest/api/keyvault/updatekey/updatekey
PATCH {vaultBaseUrl}/keys/{key-name}/{key-version}?api-version=7.0
- [x] Delete Key
https://docs.microsoft.com/en-us/rest/api/keyvault/deletekey
DELETE {vaultBaseUrl}/keys/{key-name}?api-version=7.0
- [ ] Get Deleted Key
https://docs.microsoft.com/en-us/rest/api/keyvault/getdeletedkey
GET {vaultBaseUrl}/deletedkeys/{key-name}?api-version=7.0
- [ ] Get Deleted Keys
https://docs.microsoft.com/en-us/rest/api/keyvault/getdeletedkeys
GET {vaultBaseUrl}/deletedkeys?api-version=7.0
- [x] Get Key
https://docs.microsoft.com/en-us/rest/api/keyvault/getkey
GET {vaultBaseUrl}/keys/{key-name}/{key-version}?api-version=7.0
- [ ] Get Key Versions
https://docs.microsoft.com/en-us/rest/api/keyvault/getkeyversions
GET {vaultBaseUrl}/keys/{key-name}/versions?api-version=7.0
GET {vaultBaseUrl}/keys/{key-name}/versions?maxresults={maxresults}&api-version=7.0
- [ ] Get Keys
https://docs.microsoft.com/en-us/rest/api/keyvault/getkeys
GET {vaultBaseUrl}/keys?api-version=7.0
GET {vaultBaseUrl}/keys?maxresults={maxresults}&api-version=7.0
- [ ] Import Key
https://docs.microsoft.com/en-us/rest/api/keyvault/importkey
PUT {vaultBaseUrl}/keys/{key-name}?api-version=7.0
- [ ] Purge Deleted Key
https://docs.microsoft.com/en-us/rest/api/keyvault/purgedeletedkey
DELETE {vaultBaseUrl}/deletedkeys/{key-name}?api-version=7.0
- [ ] Recover Deleted Key
https://docs.microsoft.com/en-us/rest/api/keyvault/recoverdeletedkey
POST {vaultBaseUrl}/deletedkeys/{key-name}/recover?api-version=7.0
- [ ] Update Key
https://docs.microsoft.com/en-us/rest/api/keyvault/updatekey/updatekey
PATCH {vaultBaseUrl}/keys/{key-name}/{key-version}?api-version=7.0
- [ ] Unwrap Key
https://docs.microsoft.com/en-us/rest/api/keyvault/unwrapkey/unwrapkey
POST {vaultBaseUrl}/keys/{key-name}/{key-version}/unwrapkey?api-version=7.0

---- Optional

- [ ] Restore Key
https://docs.microsoft.com/en-us/rest/api/keyvault/restorekey
POST {vaultBaseUrl}/keys/restore?api-version=7.0
- [ ] Backup Key
https://docs.microsoft.com/en-us/rest/api/keyvault/backupkey
POST {vaultBaseUrl}/keys/{key-name}/backup?api-version=7.0

**Comment by sergey-shandar** [comment]
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/keyvault/resource-manager/Microsoft.KeyVault/stable/2019-09-01/keyvault.json

**Comment by sergey-shandar** [comment]
PR #196 getkey

**Comment by gilbertw** [comment]
MVP completed as Sample
