### ISSUE TITLE
Need changelog.md text for PnP

### ISSUE THREAD

**Issue by jspaith** [Azure/azure-sdk-for-c#1894]
For PnP release, we need text guidance for what we should describe with PnP.  We have the beta documentation we could re-package.

While #1891 is open, we need to figure out how to handle the feedback @ahsonkhan brought up [here](https://github.com/Azure/azure-sdk-for-c/pull/1891#discussion_r701328261); namely the changelog is referencing a branch which we'll soon delete.  My vote for what to do in the discussion section there.

**Comment by ahsonkhan** [comment]
> While #1891 is open, we need to figure out how to handle the feedback @ahsonkhan brought up [here](https://github.com/Azure/azure-sdk-for-c/pull/1891#discussion_r701328261); namely the changelog is referencing a branch which we'll soon delete.  My vote for what to do in the discussion section there.

Is this a good enough fix to the issue @jspaith?
https://github.com/Azure/azure-sdk-for-c/pull/1899

**Comment by jspaith** [comment]
@ahsonkhan - yes.  I just double checked and only reference to `feature/iot_pnp` in the tree at this point is the one you're removing in #1899.

**Comment by ahsonkhan** [comment]
Fixed in https://github.com/Azure/azure-sdk-for-c/pull/1899 and https://github.com/Azure/azure-sdk-for-c/pull/1897

**Comment by ahsonkhan** [comment]
@jspaith feel free to re-open if there is more work related to this issue.
