### ISSUE TITLE
Codespaces Support Currently Broken

### ISSUE THREAD

**Issue by danewalton** [Azure/azure-sdk-for-c#1895]
Codespaces support is broken as of right now. The launch.json which runs the IoT samples is broken in Codespaces but works in a local version of VSCode. There is some bug on Codespaces it seems. Tracking here until the solution if found.

**Comment by CIPop** [comment]
Looks like a cmake tooling or version issue:

```
 *  Executing task: mkdir -p build && cd build && rm -rf * && cmake -DTRANSPORT_PAHO=ON -DCMAKE_BUILD_TYPE=Debug .. && cmake --build . 

Vcpkg integrate step.
CMAKE_TOOLCHAIN_FILE is not defined. Define it for the user.
AZURE_SDK_DISABLE_AUTO_VCPKG is not defined. Fetch a local copy of vcpkg.
Vcpkg commit string used: 94ce0dab56f4d8ba6bd631ba59ed682b02d45c46
CMake Error at cmake-modules/AzureVcpkg.cmake:25 (include):
  include could not find load file:

    FetchContent
Call Stack (most recent call first):
  CMakeLists.txt:19 (az_vcpkg_integrate)


CMake Error at cmake-modules/AzureVcpkg.cmake:26 (FetchContent_Declare):
  Unknown CMake command "FetchContent_Declare".
Call Stack (most recent call first):
  CMakeLists.txt:19 (az_vcpkg_integrate)


-- Configuring incomplete, errors occurred!

 *  The terminal process "/bin/bash '-c', 'mkdir -p build && cd build && rm -rf * && cmake -DTRANSPORT_PAHO=ON -DCMAKE_BUILD_TYPE=Debug .. && cmake --build .'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 
 ```

This is very likely due to an old   `"image": "aziotbld/embedded-codespace"` within `devcontainer.json` using cmake v3.10.

**Comment by vhvb1989** [comment]
Readme is asking for CMake 3.10 or later:
https://github.com/Azure/azure-sdk-for-c/tree/main#cmake

We need to update this to 3.11, as `FetchContent_Declare` was added on 3.11

**Comment by vhvb1989** [comment]
We should also have the source docker file for the devcontainer img within the same repo. That way anyone can update/fix it and use it.  Was it created by @danieljurek ?

**Comment by CIPop** [comment]
> We need to update this to 3.11, as FetchContent_Declare was added on 3.11

Sounds like a doc bug: could we file that separately? We didn't need FetchContent in the past.

> We should also have the source docker file for the devcontainer img within the same repo. That way anyone can update/fix it and use it. Was it created by @danieljurek ?

Agreed: right now, the issue is low in priority. I'll need to check if we have the source.

**Comment by CIPop** [comment]
@vhvb1989, unfortunately, it's unlikely we have the docker sources. Part of this issue we would have to create a new container from scratch. Should be easier now that VCPKG uses CMake for the deps install.

**Comment by danieljurek** [comment]
Dev containers were added by Cristian and Dane. The container image appears to have been last updated 2 years ago... Here's an enumeration of the layers that might aid in creating a Dockerfile in the repo. 

https://hub.docker.com/layers/aziotbld/embedded-codespace/latest/images/sha256-61d0d8503ddf1a2475bd5b3da770b2dcf22f477eb98a7d8cb9d7de6d765add80?context=explore
