### ISSUE TITLE
KeyVault Keys Crypto APIs

### ISSUE THREAD

**Issue by gilbertw** [Azure/azure-sdk-for-c#190]
Add support for crypto operations on KeyVault Keys

- [ ] decrypt
https://docs.microsoft.com/en-us/rest/api/keyvault/decrypt
- [ ] encrypt
https://docs.microsoft.com/en-us/rest/api/keyvault/encrypt
- [ ] sign
https://docs.microsoft.com/en-us/rest/api/keyvault/sign
- [ ] unwrap key
https://docs.microsoft.com/en-us/rest/api/keyvault/unwrapkey
- [ ] verify
https://docs.microsoft.com/en-us/rest/api/keyvault/verify
- [ ] wrap key
https://docs.microsoft.com/en-us/rest/api/keyvault/wrapkey

**Comment by ahsonkhan** [comment]
Should we close this issue? We can re-open later, if needed.
