### ISSUE TITLE
non-allocating XML serializer/deserializer

### ISSUE THREAD

**Issue by katmsft** [Azure/azure-sdk-for-c#193]
**Is your feature request related to a problem? Please describe.**
Some components (Azure Storage for sure) needs the XML builder/parser for some RESTful request.

**Describe the solution you'd like**
Current plan is to use libexpat.

**Describe alternatives you've considered**
libxml2.

**Additional context**
None.

**Information Checklist**
I am currently working on this, will send out a interface review soon.

**Comment by gilbertw** [comment]
The embedded C SDK has no current plans for adding XML helpers, https://github.com/Azure/azure-sdk-for-c/issues/55.

See the C++ SDK for XML support https://github.com/Azure/azure-sdk-for-cpp
