### ISSUE TITLE
Embedded C SDk for RP2040

### ISSUE THREAD

**Issue by kalijana** [Azure/azure-sdk-for-c#1933]
**Query/Question**
Would like to compile  embedded C SDK for Nano RP 2040 which is 32 bit ARM Arduino board 

***Why is this not a Bug or a feature Request?***
need some help or directions to acheive this 

**Setup (please complete the following information if applicable):**

raspberry PI microcontroller

**Comment by danewalton** [comment]
Hi @kalijana thanks for the question. 

We have directions on our README for integrating our source files into any given build environment. We natively support CMake but if you want to drag and drop files and integrate using something else, please see this section here:
https://github.com/Azure/azure-sdk-for-c#source-files-ide-command-line-etc

It looks like this may be based on the Arduino platform and while we don't have the public library support for Arduino, we do have an example which builds on the [Realtek AmebaD board](https://github.com/Azure/azure-sdk-for-c/tree/main/sdk/samples/iot/aziot_realtek_amebaD). There, we have instructions and a script which zips our file into a library. Please see [this section for those instructions](https://github.com/Azure/azure-sdk-for-c/tree/main/sdk/samples/iot/aziot_realtek_amebaD#setup-and-run-instructions).

Hopefully that helps you get off the ground!

**Comment by kalijana** [comment]
hi dane
Thanks a lot for the pointer ,  this definitely got me started. Just couple of things left to get the sample code compiled .

1. The "rom_hmac_sha256" , is there a source code or header for this ?
2. same for sntp_get_lasttime  method

**Comment by danewalton** [comment]
Those are extern c functions which needs to be resolved *externally* in a different c source code file. If you would like to port the file to your board, you can replace those functions with others that do the same thing (generate sha256 of bytes).
