### ISSUE TITLE
Sample project problems with authorization

### ISSUE THREAD

**Issue by markpope** [Azure/azure-sdk-for-c#1937]
**Query/Question**
The sample project fails to connect the mqtt_client. The return status code is 5, from reviewing the PubSubClient API docs this appears to be an authorization failure. I tried to publish to a different IoT Device/Hub that is working for a different client developed in VS Code with the same results. How do I debug this?

***Why is this not a Bug or a feature Request?***
I feel others would be raising this as an issue but haven't found any other posts.

**Setup (please complete the following information if applicable):**

- OS: Arduino ESP8266
- IDE: Arduino IDE
- Latest of all libraries, removed potential conflicts.

 **Information Checklist**
 Please make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report

- [ ] Query Added
- [ ] Setup information Added

**Comment by ericwol-msft** [comment]
Yes, this is an auth error.

> I tried to publish to a different IoT Device/Hub that is working for a different client developed in VS Code with the same results.

What does 'same results' mean? Auth error? Please explain in more detail.

What sample are you using? Also, common auth errors are due to your clock is not set to the current time.

**Comment by markpope** [comment]
I get the same status code, 5, when trying to publish to different IoT Hubs.
The program I'm using is https://github.com/Azure/azure-sdk-for-c/blob/main/sdk/samples/iot/aziot_esp8266/aziot_esp8266.ino

**Comment by ericwol-msft** [comment]
Please validate your clock is getting set via the SNTP server.

https://github.com/Azure/azure-sdk-for-c/blob/e148185f8a324a2de913ea1e50120c0d4f4e2464/sdk/samples/iot/aziot_esp8266/aziot_esp8266.ino#L71

**Comment by markpope** [comment]
Yep, I am using the same two NTP_SERVERS

**Comment by ericwol-msft** [comment]
Other common problems
- Wrong IoT Hub endpoint
- incorrect Device id
- incorrect device key (don't use the hub key)
- device is disabled

**Comment by markpope** [comment]
I've double checked those, used new ones that work with other clients. Since this a very simple example, I suspect the problem is on my end, but am stuck on further debugging it.

**Comment by ericwol-msft** [comment]
Please send a private message to me with your hub name and device ID

**Comment by ericwol-msft** [comment]
Closing issue. Customer was using a connection string and not the device key.
