### ISSUE TITLE
[FEATURE REQ] Consider to replace `size` field in a span to `end`.

### ISSUE THREAD

**Issue by sergey-shandar** [Azure/azure-sdk-for-c#194]
Advantages of `begin`, `end`:
- in this case, `begin` can be moved independently. It's useful to move `begin` forward (`++begin`)
- a pair of `begin` and `end` doesn't depend on a type and can be casted to another type span without a problem.
- compatibility with C++ iterators.

**Comment by vhvb1989** [comment]
not applicable anymore since span was updated to be begin, length and capacity
