### ISSUE TITLE
Improve branch coverage of storage client when running unit tests

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-c#2000]
Line coverage is great, but we could add a few "failure" tests to cover some of the edge branch branches

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1187023&view=codecoverage-tab
![image](https://user-images.githubusercontent.com/6527137/141024227-828cac08-0ffd-4b36-b3ad-f7063ef16e84.png)

https://github.com/Azure/azure-sdk-for-c/blob/3834fbb0bc357d6c40c19ab3be7ba3ce48726b4d/sdk/src/azure/storage/az_storage_blobs_blob_client.c#L52-L76

![image](https://user-images.githubusercontent.com/6527137/141024350-bf9ebe41-1eaf-4db4-a9f6-924881096219.png)

cc @antkmsft

**Comment by antkmsft** [comment]
Closed a while ago in #2052
