### ISSUE TITLE
Add Storage category for the published docs

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-c#2002]
With the release of https://github.com/Azure/azure-sdk-for-c/releases/tag/1.3.0-beta.1, with basic Storage Blobs support, we may want to add back the `Storage` category to the docs.

https://azure.github.io/azure-sdk-for-c/

![image](https://user-images.githubusercontent.com/6527137/141031087-d6a579fe-af13-4c8b-92d5-2bc4612875c0.png)

cc @antkmsft, @danieljurek, @weshaggard

**Comment by weshaggard** [comment]
This automation depends on the storage package being unhidden in https://github.com/Azure/azure-sdk/blob/main/_data/releases/latest/c-packages.csv.

**Comment by RickWinter** [comment]
@antkmsft Please update the c-packages.csv to declare the Beta.

cc: @kyle-patterson
