### ISSUE TITLE
how does this library support SNI working with TLS hostname validation

### ISSUE THREAD

**Issue by edwardt** [Azure/azure-sdk-for-c#2012]
General question
It is not clear from documentation how the library works under TLS hostname validation under the case of SNI (Server name indication: https://datatracker.ietf.org/doc/html/rfc3546
). Does it use the hostname set by SNI extension to validation the cert or how that works? How that behavior in library justified against published RFC?

**Comment by danewalton** [comment]
Hi @edwardt this library uses Paho MQTT for the transport. [In it, there is support for SNI.](https://eclipse.github.io/paho.mqtt.c/MQTTClient/html/struct_m_q_t_t_client___s_s_l_options.html#a94900629685d5ed08f66fd2931f573ce)

![image](https://user-images.githubusercontent.com/36710865/142054819-2121053f-833f-4cb9-ba86-31a5e4384f53.png)

[Confirmation of it being added by the maintainer here.](https://github.com/eclipse/paho.mqtt.c/issues/171)

**Comment by danewalton** [comment]
Closing since this is outside the scope of this library. Our samples using outside dependencies do use it though.
