### ISSUE TITLE
could i replace the paho.mqtt library dependency to mosquitto library?  

### ISSUE THREAD

**Issue by pppaulpeter** [Azure/azure-sdk-for-c#2014]
**Query/Question**
could i replace the paho.mqtt library dependency to mosquitto library?  

***Why is this not a Bug or a feature Request?***
i am not familar with paho.mqtt , it seems based on python.

**Comment by danewalton** [comment]
Hi @pppaulpeter yes this SDK allows you to substitute other MQTT libraries in. You can use the implementation with paho as a guide to bring in mosquitto. As a note, paho in this case is the [library written in C not python](https://github.com/eclipse/paho.mqtt.c).

**Comment by pppaulpeter** [comment]
> Hi @pppaulpeter yes this SDK allows you to substitute other MQTT libraries in. You can use the implementation with paho as a guide to bring in mosquitto. As a note, paho in this case is the [library written in C not python](https://github.com/eclipse/paho.mqtt.c).

thanks for you quick response! i just download the paho library and try to compile the sample, but encounter the following error:
(base) ubuntu@ubuntu-XPS-8930:~/Downloads/azure-sdk-for-c/build_new$ cmake -DTRANSPORT_PAHO=ON ..
-- Read version from /home/ubuntu/Downloads/azure-sdk-for-c/sdk/inc/azure/core/az_version.h
-- AZ_SDK_VERSION_MAJOR 1
-- AZ_SDK_VERSION_MINOR 3
-- AZ_SDK_VERSION_PATCH 0
-- AZ_SDK_VERSION_PRERELEASE beta.2
-- Could NOT find OpenSSL (missing: OpenSSL_DIR)
-- Configuring done
CMake Error at sdk/samples/iot/CMakeLists.txt:59 (add_executable):
  Target "paho_iot_hub_methods_sample" links to target
  "eclipse-paho-mqtt-c::paho-mqtt3cs-static" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


CMake Error at sdk/samples/iot/CMakeLists.txt:107 (add_executable):
  Target "paho_iot_pnp_component_sample" links to target
  "eclipse-paho-mqtt-c::paho-mqtt3cs-static" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


CMake Error at sdk/samples/iot/CMakeLists.txt:167 (add_executable):
  Target "paho_iot_provisioning_sas_sample" links to target
  "eclipse-paho-mqtt-c::paho-mqtt3cs-static" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


CMake Error at sdk/samples/iot/CMakeLists.txt:47 (add_executable):
  Target "paho_iot_hub_c2d_sample" links to target
  "eclipse-paho-mqtt-c::paho-mqtt3cs-static" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


CMake Error at sdk/samples/iot/CMakeLists.txt:155 (add_executable):
  Target "paho_iot_provisioning_sample" links to target
  "eclipse-paho-mqtt-c::paho-mqtt3cs-static" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


CMake Error at sdk/samples/iot/CMakeLists.txt:71 (add_executable):
  Target "paho_iot_hub_telemetry_sample" links to target
  "eclipse-paho-mqtt-c::paho-mqtt3cs-static" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


CMake Error at sdk/samples/iot/CMakeLists.txt:83 (add_executable):
  Target "paho_iot_hub_sas_telemetry_sample" links to target
  "eclipse-paho-mqtt-c::paho-mqtt3cs-static" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


CMake Error at sdk/samples/iot/CMakeLists.txt:23 (add_library):
  Target "az_iot_sample_common" links to target
  "eclipse-paho-mqtt-c::paho-mqtt3cs-static" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


CMake Error at sdk/samples/iot/CMakeLists.txt:95 (add_executable):
  Target "paho_iot_hub_twin_sample" links to target
  "eclipse-paho-mqtt-c::paho-mqtt3cs-static" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


CMake Error at sdk/samples/iot/CMakeLists.txt:142 (add_executable):
  Target "paho_iot_pnp_with_provisioning_sample" links to target
  "eclipse-paho-mqtt-c::paho-mqtt3cs-static" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


CMake Error at sdk/samples/iot/CMakeLists.txt:129 (add_executable):
  Target "paho_iot_pnp_sample" links to target
  "eclipse-paho-mqtt-c::paho-mqtt3cs-static" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
(base) ubuntu@ubuntu-XPS-8930:~/Downloads/azure-sdk-for-c/build_new$
and this is my openssl version:
ubuntu@ubuntu-XPS-8930:~/Downloads/azure-sdk-for-c/build_new$ openssl
OpenSSL> version
OpenSSL 1.1.1k  25 Mar 2021
please shad some light on this problem, thanks!

**Comment by danewalton** [comment]
Yes this looks like you don't have VCPKG set up correctly. Can you please [this section here in our docs](https://github.com/Azure/azure-sdk-for-c#vcpkg) to set that up?

**Comment by pppaulpeter** [comment]
Hi, 
eventually i want to use this code in the arm embedded device, so i don't want to relay on the vcpkg.

**Comment by danewalton** [comment]
If you want to use the library with mosquitto, I would recommend creating your own CMake project which is based off of the samples we have and link to the CMake targets which we have for our repo ([example here](https://github.com/Azure/azure-sdk-for-c/blob/a0502033e456f962a6e617d9ae4948a9da09a4be/sdk/samples/iot/CMakeLists.txt#L28-L32)). I would not recommend trying to change the samples in place and substitute in mosquitto. As it stands currently, our samples use paho and that requires vcpkg.

**Comment by pppaulpeter** [comment]
clear, thanks a lot!

**Comment by danewalton** [comment]
going to close this for now. let us know if you have any other questions!
