### ISSUE TITLE
AuthenticationClient needs its own pipeline

### ISSUE THREAD

**Issue by gilbertw** [Azure/azure-sdk-for-c#202]
AuthClient should handle retrieving the auth token and refresh token.  It should also ensure the token is preemptively refreshed to prevent Unauthorized due to expiration.

The AuthClient performs it calls with its own pipeline.  Add the pipeline to the AuthClient similar to the KeyVault client pipeline

**Comment by antkmsft** [comment]
https://github.com/Azure/azure-sdk-for-c/pull/205
