### ISSUE TITLE
Should `gh-pages` and `gh-pages-root` be CheckEnforced?

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-c#2021]
This is an issue for EngSys team.

In C++ we have CheckEnforcer enabled for these branches.
(BTW, do we need these branches at all? Do we need both?

https://github.com/Azure/azure-sdk-for-c/branches/all

**Comment by weshaggard** [comment]
gh-pages and gh-pages-root are placeholder branches that should only be pushed to by our automation to update the github.io site. They should have been protected branches, which I just fixed.

What do you mean by we have CheckEnforcer enabled on these branches?

**Comment by antkmsft** [comment]
I'm sorry I thought CheckEnforcer and being a protected branch is the same thing. I meant a "protected branch", the shield icon next to it, which is what you did. Thank you Wes!

**Comment by weshaggard** [comment]
OK I'll close this issue then.
