### ISSUE TITLE
CI pipelines need step building with cmake 3.10

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-c#2054]
We expect the SDK to be buildable for customers and work with cmake 3.10:
https://github.com/Azure/azure-sdk-for-c/blob/a82520bc0ea03a8de22ecc4f99206dcf1c18a45a/CMakeLists.txt#L4

Having a pipeline step that verifies this works would be great.

https://dev.azure.com/azure-sdk/public/_build/results?buildId=1251956&view=logs&j=bd7cfc7a-9e05-507b-5103-65c9a747e93d&t=1b156c19-3f27-5a7d-f3ba-6e75c342737c

Currently, most of the build pipelines use what comes out of the box, which is 3.22.1.

Corresponding C++ issue:
https://github.com/Azure/azure-sdk-for-cpp/issues/3192

cc @danieljurek

**Comment by kurtzeborn** [comment]
Clearing daniel from the assignee. If this is important to the C libraries team, they can do the work to install cmake 3.10 on windows/linux/mac and validate that things build with this.
