### ISSUE TITLE
Trying to build the sample Azure_IoT_Hub_ESP8266 but get an  error: 'X509List' does not name a type

### ISSUE THREAD

**Issue by Pelago** [Azure/azure-sdk-for-c#2068]
**Describe the bug**
Trying to build the sample Azure_IoT_Hub_ESP8266 but get an  error: 'X509List' does not name a type

***Exception or Stack Trace***
Azure_IoT_Hub_ESP8266:68:8: error: 'X509List' does not name a type
 static X509List cert((const char*)ca_pem);
        ^
C:\Users\PATRIK~1\AppData\Local\Temp\arduino_modified_sketch_25349\Azure_IoT_Hub_ESP8266.ino: In function 'void initializeClients()':
Azure_IoT_Hub_ESP8266:145:15: error: 'class axTLS::WiFiClientSecure' has no member named 'setTrustAnchors'
   wifi_client.setTrustAnchors(&cert);
               ^
Azure_IoT_Hub_ESP8266:145:32: error: 'cert' was not declared in this scope
   wifi_client.setTrustAnchors(&cert);
                                
exit status 1
'X509List' does not name a type

**To Reproduce**
Just create a new project in Arduino IDE and make appropriate changes in the iot_configs.h file and build the sketch

***Code Snippet***
static X509List cert((const char*)ca_pem);

**Expected behavior**
I would expect the sample to work or at least in the code explain how this X509List has to be created

**Screenshots**
![image](https://user-images.githubusercontent.com/12788971/150173547-c13fe12e-025a-4e68-a1be-6fb3bafe91bc.png)

.

**Setup (please complete the following information):**

- OS: Windows 10
- IDE: Arduino 1.8.19
- Version of the Library used

**Additional context**
I'm looking for a way to connect an ESP8266 to a IotEdgeGateway 1.1 sending data to be relayed to Azure IoTHub. This sample looked as if it was using X.509 cert and i wanted to find out if this sample could lead the way to my solution. I have been working  this problem for weeks googling everything but i can't find any working samples for my Leaf/child device to connect to my IotEdgeGateway and pass the telemetry data

 
**Information Checklist**
Please make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report

- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by asergaz** [comment]
This relates with: https://stackoverflow.com/questions/70754868/how-to-connect-esp8266-through-iotedgegateway-running-on-rpi-ubuntu-using-azur
