### ISSUE TITLE
Multi-block blob transfer in Storage client 

### ISSUE THREAD

**Issue by ghost** [Azure/azure-sdk-for-c#2079]
The 1.3.0 version preview provides the Storage client for sending blobs to the Azure Storage service. However, this client allows only for sending one HTTP request with the whole blob content as the request body. Let's take the situation where the microcontroller device is acquiring lots of data from sensors (e.g. 10 seconds of 16 kHz, 3-axis accelerometer = ~2MB) and saving those data in the external flash memory. The device has only ~100 kB of free RAM. Without the multi-block blob transfer, the only solution I see with this Storage client is to create over a dozen files for one data acquisition instead of one, which is of course possible, but very inconvenient for future processing.
 
Are there any plans to implement a multi-block transfer similar to the one in the Azure IoT C SDK?

**Comment by JeffreyRichter** [comment]
We could implement this; we've been waiting to see if any customers really needed the behavior.
We could implement uploading multiple blocks to a block blob or we could implement appending blocks to an append blob.
Do you have a preference? Seems like the append blob is perfect for your scenario.

**Comment by szymsta** [comment]
Support for the append blob sounds good. It will be great if the library supports sending MD5 or CRC64 hash of the append block content to verify the integrity of the block during transport.

**Comment by JeffreyRichter** [comment]
Don't you think that just using HTTP(S) is good enough for verifying the integrity ?

**Comment by szymsta** [comment]
Most probably, yes. I just saw this option in the append block documentation: https://docs.microsoft.com/en-us/rest/api/storageservices/append-block

**Comment by JeffreyRichter** [comment]
It will take our team a while to get to this request but we'd love to do it. It also wouldn't be difficult for someone to copy/paste this [code](https://github.com/Azure/azure-sdk-for-c/blob/feature/storage-blobs/sdk/src/azure/storage/az_storage_blobs_blob_client.c#L232) and tweak it to create a new az_storage_blobs_appendblob_appendBlock function which wraps this [operation](https://docs.microsoft.com/en-us/rest/api/storageservices/append-block). Another az_storage_blobs_appendblob_create function is required that wraps this [operation](https://docs.microsoft.com/en-us/rest/api/storageservices/put-blob).

If you wrote these 2 functions, you'd be up and running quickly and, of course, we'd love you to make a PR to this repo :)

**Comment by szymsta** [comment]
Hi there, I've made a pull request with the code related to this issue. As different blob types are useful for different use cases I've decided to implement both multi-block and append blobs functionalities. I've also implemented sending blobs using IoT Hub, but the code relies on this PR, so I will make another contribution with this functionality after this PR will be merged with the feature branch.

Regards,
Szymon Stanik

**Comment by antkmsft** [comment]
Hi @szymsta,

Thank you for the PR.

We could take  `az_storage_blobs_appendblob_create()` and `az_storage_blobs_appendblob_append_block()`, but not `az_storage_blobs_multiblock_blob_upload()` as it is.

Instead of `az_storage_blobs_multiblock_blob_upload()` being a function with a callback, we would create 2 functions: one to upload a block (taking int64 block id and an az_span instead of callback), and one to commit the block list.

With current design, it is not clear what should be done if error occurs in the middle of upload.

With 2 functions, user can wrap them to essentially do what `az_storage_blobs_multiblock_blob_upload()` currently does: it could iterate over blocks, and then commit the result, if there were no errors (or with some errors it thinks are acceptable).

BTW, I saw that you are doing `snprintf()` of block id to perform "itoa". That is not necessary. The block id is a binary-value int64 that is Base64-encoded.

**Comment by JeffreyRichter** [comment]
The block ID is a 64 BYTE (not bit) value that is base-64 encoded. Please see https://learn.microsoft.com/en-us/rest/api/storageservices/put-block. Then, this function needs the list of base-64 strings after all the blocks have been uploaded: https://learn.microsoft.com/en-us/rest/api/storageservices/put-block-list.

We're basically OK with replicating these function from our Go SDK; use these as a model: 
https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/blockblob/client.go#L170
https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/blockblob/client.go#L202

**Comment by RickWinter** [comment]
We are not currently planning to add this to the C SDK.  If you are able to use C++ the Storage SDK in C++ has many of these features.
