### ISSUE TITLE
Azure_IoT_Central_ESP32 fails when deviceID is 64 characters

### ISSUE THREAD

**Issue by torntrousers** [Azure/azure-sdk-for-c#2085]
I'm trying to run the [Azure_IoT_Central_ESP32](https://github.com/Azure/azure-sdk-for-c-arduino/tree/main/examples/Azure_IoT_Central_ESP32) sample with an IoT Central device that uses Individual Enrollement with X509 certificates and has a "Device name" and "Device ID" that is 64 characters long, but it fails to connect:
```
1970/1/1 00:00:04 [INFO] WiFi connected, IP address: 192.168.1.78
1970/1/1 00:00:04 [INFO] Setting time using SNTP
.......
2022/2/1 09:15:49 [INFO] Time initialized!
2022/2/1 09:15:49 [INFO] Azure IoT client initialized (state=2)
2022/2/1 09:15:49 [INFO] MQTT client using X509 Certificate authentication
2022/2/1 09:15:49 [INFO] MQTT client target uri set to 'mqtts://global.azure-devices-provisioning.net'
2022/2/1 09:15:49 [INFO] MQTT client connecting.
2022/2/1 09:15:51 [INFO] MQTT client connected (session_present=0).
2022/2/1 09:15:51 [INFO] MQTT client subscribing to '$dps/registrations/res/#'
2022/2/1 09:15:51 [INFO] MQTT topic subscribed (message id=19137).
2022/2/1 09:15:51 [INFO] MQTT client publishing to '$dps/registrations/PUT/iotdps-register/?$rid=1{"modelId":"dtmi:azureiot:devkit:freertos:Esp32AzureIotKit;1"}{"registrationId":"1df33b6ac17a2273d693c4c234d89debffcdf73c2511c180d2844398100c0b75","payload":{"modelId":"dtmi:azureiot
2022/2/1 09:15:52 [INFO] MQTT message received.
2022/2/1 09:15:52 [INFO] MQTT client publishing to '$dps/registrations/GET/iotdps-get-operationstatus/?$rid=1&operationId=5.4483c78c503bf433.1eb2a08f-e383-4af0-87d5-7025adf3db72'
2022/2/1 09:15:52 [INFO] MQTT message received.
2022/2/1 09:15:55 [INFO] MQTT client publishing to '$dps/registrations/GET/iotdps-get-operationstatus/?$rid=1&operationId=5.4483c78c503bf433.1eb2a08f-e383-4af0-87d5-7025adf3db72'
2022/2/1 09:15:55 [INFO] MQTT message received.
2022/2/1 09:15:55 [INFO] MQTT client being disconnected.
2022/2/1 09:15:55 [ERROR] Failed to get MQTT client username.
2022/2/1 09:15:55 [ERROR] Failed getting MQTT client configuration for connecting to IoT Hub.
2022/2/1 09:15:55 [ERROR] Azure IoT client is in error state.
```
I tried updating `MQTT_CLIENT_ID_BUFFER_SIZE` and `MQTT_USERNAME_BUFFER_SIZE` [here ](https://github.com/Azure/azure-sdk-for-c-arduino/blob/main/examples/Azure_IoT_Central_ESP32/AzureIoT.cpp#L24-L25) from 256 to 512 but that gives:
```
1970/1/1 00:00:04 [INFO] WiFi connected, IP address: 192.168.1.78
1970/1/1 00:00:04 [INFO] Setting time using SNTP
........
2022/2/1 09:18:58 [INFO] Time initialized!
2022/2/1 09:18:58 [INFO] Azure IoT client initialized (state=2)
(just hangs here forever)
```
Any ideas on how I can get it to work with 64 character device ID's?

**Comment by danewalton** [comment]
Do you still see it truncated even with the larger buffer you allocated?

**Comment by danewalton** [comment]
Try increasing the size of this buffer to something like 1.5k or 2k:
https://github.com/Azure/azure-sdk-for-c-arduino/blob/c54e12b26c8d4fb73469c4ac90b5278cee80a922/examples/Azure_IoT_Central_ESP32/Azure_IoT_Central_ESP32.ino#L99

**Comment by torntrousers** [comment]
> Try increasing the size of this buffer to something like 1.5k or 2k: https://github.com/Azure/azure-sdk-for-c-arduino/blob/c54e12b26c8d4fb73469c4ac90b5278cee80a922/examples/Azure_IoT_Central_ESP32/Azure_IoT_Central_ESP32.ino#L99

I've tried that but it doesn;t make any difference - the iotdps-register is still truncated in exactly the same place.

**Comment by danewalton** [comment]
Are you able to try out this branch with readjusted buffer sizes? I believe I have a device ID that is 88 characters long working with that.

https://github.com/Azure/azure-sdk-for-c-arduino/tree/dane/wip

**Comment by torntrousers** [comment]
@danewalton I've tried those changes and yes it looks like that fixes it. Thanks so much for the quick fix!

**Comment by danewalton** [comment]
> @danewalton I've tried those changes and yes it looks like that fixes it. Thanks so much for the quick fix!

Perfect! I'll look to double check the size increases and add some documentation on tested device ID sizes. Thanks for letting us know!

**Comment by danewalton** [comment]
PR to fix: https://github.com/Azure/azure-sdk-for-c-arduino/pull/12

**Comment by danewalton** [comment]
The PR has been merged so closing this issue.
