### ISSUE TITLE
Need azure service bus support for C/C++

### ISSUE THREAD

**Issue by raphaelamorim** [Azure/azure-sdk-for-c#209]
We currently have some devices connected thru JMS and there are some tiny C\C++ based we would like to provide a library to connect to the same bus we've already have.

I've tried to use Qpid, which is an apache library, sample on: https://qpid.apache.org/releases/qpid-proton-master/proton/cpp/api/service_bus_8cpp-example.html, but it doesn't work anymore.

**Comment by gilbertw** [comment]
@raphaelamorim This SDK (C99) is targeting a subset of IoT scenarios.  That includes a select few services necessary for those scenarios.

There is work underway on a C++ SDK, https://github.com/Azure/azure-sdk-for-cpp.  The C++ SDK will be a full SDK with support for many services.  Would Service Bus support in a C++ SDK meet your needs?
