### ISSUE TITLE
❓Survey: Your experience in this repo 

### ISSUE THREAD

**Issue by lilyjma** [Azure/azure-sdk-for-c#2093]
Whether you're a frequent visitor or a relatively new visitor of the repo, please tell us about your experience with our issue support and/or PR contribution process. The survey should only take a few minutes, and you can answer for up to 3 repos:

https://www.surveymonkey.com/r/8QTQTGJ?Source=azure-sdk-for-c

**Comment by uklatt** [comment]
Sone comments:

1. Why are there (almost empty)` samples/` and `sdk/samples/` directories?

2. I prefer a simple makefile to compile source for different architectures.
For small projects like this I personaly find that cmake is overkill.

3. There are many projects and C examples for **Azure IoT Hub**. I found it difficult to choose the best fitting one.

4. Thank you for open source projects!

Tschau
Uwe

**Comment by danewalton** [comment]
Thanks for the feedback @uklatt !

It's useful to see here in real time. If it isn't too much trouble, can you also provide that feedback in the link above (if not done already).

Thanks!

**Comment by lilyjma** [comment]
Thank you for your interest in the experience survey. The survey has now been closed.
If you didn't get a chance to provide feedback this time, please look out for future surveys.
