### ISSUE TITLE
Bug in sdk/samples/iot/vxworks/azureClientSample.c

### ISSUE THREAD

**Issue by uklatt** [Azure/azure-sdk-for-c#2094]
Hello,

I found a bug in sdk/samples/iot/vxworks/azureClientSample.c:
https://github.com/Azure/azure-sdk-for-c/blob/d829ed8b6485cd1cf32bf0f0aeefdb730740acf1/sdk/samples/iot/vxworks/azureClientSample.c#L1085

When creating the MQTT client the third parameter of `mosquitto_new(azureClientId, true, azureClient);` is later passed to all MQTT callback functions. In this case it should be a pointer to the azure client.

In this example the third parameter is wrong!
It should be 
`mqqtClient = mosquitto_new(azureClientId, true, azureClient);` 
instead of 
`mqqtClient = mosquitto_new(azureClientId, true, &azureClient);`

Tschau
Uwe

**Comment by danewalton** [comment]
Hi @uklatt thanks for the find! [Based on the docs here](https://mosquitto.org/api/files/mosquitto-h.html#mosquitto_new) I believe you are right.

Would you like to submit a PR to contribute or would you like us to take care of this for you (don't want to steal your credit if you want to submit 😀 )

**Comment by uklatt** [comment]
I created a pull request.

Uwe
