### ISSUE TITLE
Make sure the auto-increment PR after a GA release can be merged without manual intervention

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-c#2108]
Closing this in favor of https://github.com/Azure/azure-sdk-for-c/pull/2104 which updates the az_version.h post-GA properly, and gets rid of the `undef`.

@danieljurek for beta releases out of main (which will now be less likely for Embedded C), the auto-increment PR works great. However, for GA releases, since we add an `undef` for the pre-release macro, it doesn't work too well. So, we have to create a manual PR.

Can we fix that to account for the GA case and remove the `undef` for us to avoid the manual update?

See these PRs in order:
1) Update version for GA release: https://github.com/Azure/azure-sdk-for-c/pull/2087
2) After release, we get this auto-increment PR: https://github.com/Azure/azure-sdk-for-c/pull/2103
3) The actual change we want: https://github.com/Azure/azure-sdk-for-c/pull/2104

For beta releases things work fine, for example:
https://github.com/Azure/azure-sdk-for-c/pull/2001
But, in those cases, we might still end up manually creating them, if we release a beta version from a feature branch instead of main:
https://github.com/Azure/azure-sdk-for-c/pull/2003

_Originally posted by @ahsonkhan in https://github.com/Azure/azure-sdk-for-c/issues/2103#issuecomment-1033289886_

**Comment by danieljurek** [comment]
In the case of a GA release we should see: 

```cpp
#define AZ_SDK_VERSION_PRERELEASE
#undef AZ_SDK_VERSION_PRERELEASE
```

In the case of a preview release we should see something like: 

```cpp
#define AZ_SDK_VERSION_PRERELEASE "beta.1"
```

Instead of the 2 `#define`s 

Is that right?

**Comment by ahsonkhan** [comment]
> In the case of a GA release we should see:

I don't follow this scenario. I don't think the auto-increment PR ever needs to create a PR to go from beta -> GA, that's always manual (where we add the undef and remove the beta version string).

The auto-PR happens **after** a release, so it's easier for me to frame it that way.

So, for example, after a GA release is triggered and successful, we, as in the auto-increment-PR, needs to go from:
```cpp
#define AZ_SDK_VERSION_PRERELEASE
#undef AZ_SDK_VERSION_PRERELEASE
```
To:
```cpp
#define AZ_SDK_VERSION_PRERELEASE "beta.1"
```
This is what's broken atm (likely some regex issue), since instead we end up doing this:
```cpp
#define AZ_SDK_VERSION_PRERELEASE "beta.1"
#undef AZ_SDK_VERSION_PRERELEASE "beta.1"
```

And you are right, in the case of beta releases, we'd go from the following:
```cpp
#define AZ_SDK_VERSION_PRERELEASE "beta.1"
```
To:
```cpp
#define AZ_SDK_VERSION_PRERELEASE "beta.2"
```

Which works fine today.

When we are preparing to GA from a beta release, we manually make this change before the release:
From:
```cpp
#define AZ_SDK_VERSION_PRERELEASE "beta.2"
```
To:
```cpp
#define AZ_SDK_VERSION_PRERELEASE
#undef AZ_SDK_VERSION_PRERELEASE
```
