### ISSUE TITLE
OTA Provisioning of the ESP32 based on Arduino Platform from Azure IoT Central

### ISSUE THREAD

**Issue by GregDavid123** [Azure/azure-sdk-for-c#2112]
**Is your feature request related to a problem? 
Most users of Azure IoT Central, will often like to update the firmware of multiple divices directly from their IoT Central platform. This important feature is unfortunate not present in IoT Central.

**Describe the solution you'd like**
Firmware provising of multiple devices connected IoT Cenral by 
- comparing the present version to the new one
- selecting the related devices
- etc

thanks

**Comment by wduraes** [comment]
Hi @GregDavid123 this is indeed a very important feature, and it already is on the Azure Device update team's backlog. However, it was not prioritized yet, so they don't have an estimate of when this will be available. Thank you for your feedback.
