### ISSUE TITLE
Share properties and control ESP32 based on Arduino Platform from Azure IoT Central using a self desinged android or iOS mobile App

### ISSUE THREAD

**Issue by GregDavid123** [Azure/azure-sdk-for-c#2113]
**Is your feature request related to a problem? Please describe.**
Mot iot users share properties and control ESP32 based on Arduino Platform from Azure IoT Central using a self desinged android or iOS mobile App. I was not able to find a sample or example mobile app that could help me design a software ( with Azure backend), with authentification and direct communication with a specific ESP32 device connected to IoT Central.

**Describe the solution you'd like**
Present a clear example with Java, kotlin and iOS that can be followed for production.

Thanks

**Comment by danewalton** [comment]
This is a pretty large feature ask and is very unlikely to happen from our team. That would effectively be a service side application on an iPhone or Android.

We do have a device side offering using this SDK in Swift for iOS. Our library can be found [here](https://github.com/Azure-Samples/azure-sdk-for-c-swift) and the sample iOS application [here](https://github.com/Azure-Samples/azure-sdk-for-c-ios)
