### ISSUE TITLE
Compile Error : fatal error: hal/gpio_types.h: No such file or directory

### ISSUE THREAD

**Issue by fcanelasv** [Azure/azure-sdk-for-c#2127]
Hello,

I am getting the following error when trying to compile example: [Azure_IoT_Central_ESP32_AzureIoTKit](https://github.com/Azure/azure-sdk-for-c-arduino/tree/main/examples/Azure_IoT_Central_ESP32_AzureIoTKit)

Arduino: 1.8.20 Hourly Build 2021/12/20 07:34 (Mac OS X), Board: "ESP32 Wrover Module, Default 4MB with spiffs (1.2MB APP/1.5MB SPIFFS), QIO, 80MHz, 921600, None"

/Users/fcanelas/Documents/Arduino/libraries/Espressif_ESP32_Azure_IoT_Kit_Sensors/src/led.c:5:28: fatal error: hal/gpio_types.h: No such file or directory
compilation terminated.
exit status 1
Error compiling for board ESP32 Wrover Module.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by danewalton** [comment]
Hi @fcanelasv
Did you go through step 3 listed here?:
https://github.com/Azure/azure-sdk-for-c-arduino/tree/main/examples/Azure_IoT_Central_ESP32_AzureIoTKit#setup-and-run-instructions

**Comment by danewalton** [comment]
Going to go ahead and close this for now. Please let us know if you have any other questions.
