### ISSUE TITLE
How to send custom sensor data in Azure Iot SDK for C sample file variable telementry_payload[[128].

### ISSUE THREAD

**Issue by sushil25** [Azure/azure-sdk-for-c#2143]
Hello Team , 
I am using newly release https://github.com/Azure/azure-sdk-for-c-arduino/blob/main/examples/Azure_IoT_Hub_ESP32/readme.md
Got success with connection and data sending on azure which was default data in sample example But 
Can you please help me, how to embedded my custom sensor data in Azure SDK for C IotHub Arduino Sample example for esp32 file name (Azure_IoT_Hub_ESP32.ino) in telemetry_payload[128] variable , i tried multiple thing but not sure how to insert my data in that variable to send to IoThub .

![image](https://user-images.githubusercontent.com/14310848/157637737-7e9edb3c-ada7-4e5e-81aa-8cdda984a004.png)

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?
Answer : 
This is not a bug or Feature Request since i got success in sample code running in my device . this is just a technical support request.

**Setup (please complete the following information if applicable):**

- OS: [Windows 10] 
- IDE: [e.g. Ardunio IDE 1.8.13]
- Version of the Library used : Azure Sdk for C version 1.0.0.beta.3

- [x] Query Added - Yes 
- [x] Setup information Added -Yes

**Comment by danewalton** [comment]
Hi @sushil25 

I would recommend using either the span APIs that we have to populate buffers of raw data or using our JSON APIs to create JSON payloads.

Note that from a high level, spans are just buffer pointers with a size associated with it. So we bundle a pointer with size to make it easier to pass around to other API calls.

[Span APIs](https://github.com/Azure/azure-sdk-for-c/blob/main/sdk/inc/azure/core/az_span.h)
[JSON APIs](https://github.com/Azure/azure-sdk-for-c/blob/main/sdk/inc/azure/core/az_json.h)

**Comment by danewalton** [comment]
Going to go ahead and close for inactivity. Please let us know if you would like it reopened.
