### ISSUE TITLE
Arduino - decoding SAS key

### ISSUE THREAD

**Issue by rploeg** [Azure/azure-sdk-for-c#2153]
I am running on beta 3 of Azure SDK C with latest update from Arduino on Windows 11. If I use the example of the Sketch library to connect to Azure IoT Central I get this message as output of the device:

19:18:36.381 -> 2022/3/17 18:18:36 [INFO] WiFi connected, IP address: 192.168.1.81
19:18:36.381 -> 2022/3/17 18:18:36 [ERROR] Failed decoding SAS key.
19:18:36.381 -> 2022/3/17 18:18:36 [ERROR] Failed creating mqtt password for DPS connection.
19:18:36.381 -> 2022/3/17 18:18:36 [ERROR] Failed initializing MQTT client.
19:18:36.381 -> 2022/3/17 18:18:36 [ERROR] Azure IoT client is in error state.

I know for sure that the SAS key is correct. any idea what I am doing wrong? I am using the SAS key from Security/ SAS IoT Devices in IoT Central.

**Comment by rploeg** [comment]
The primary key. But do I need to create a device in advance? I thought with PnP the device would automatically be provisioned with the right template. (also if I see the code). I think your screenshot is also from the IoT Hub, I am using IoT Central from the SDK example library.

**Comment by danewalton** [comment]
Ahh I see. Interesting...to be honest I haven't tried this method of connecting devices. It looks like the key in this case is much longer than just the individual device. I'm guessing some buffer isn't large enough in our code to accommodate the larger key. Let me double check on this.

**Comment by rploeg** [comment]
Ok! So your advice is to create a device in IoT central and put the device ID and SAS key of the device in the Arduino example? I am not at home now to test this/ will be later tonight

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rploeg** [comment]
I can confirm if I create a device manually and use the primary key from that created device, it works. I would be great if the other option can also work.

**Comment by danewalton** [comment]
Okay thank you for confirming. Yea I'm guessing we have a buffer size problem considering the size of the key is that much larger. I will make a note of this and get back here with updates.

**Comment by danewalton** [comment]
Okay after a bit of research, it looks like the key which you are using should be used to generate individual SAS keys, not as an authentication itself.

https://docs.microsoft.com/en-us/azure/iot-central/core/concepts-device-authentication#automatically-register-devices

I would recommend going through the `Devices->Connect->` method of getting the device auth.

**Comment by rploeg** [comment]
Ok thanks! So in the SDK there is no standard possiblity to create a device (without creating it first in IoT Central) based on the pnp template?

**Comment by danewalton** [comment]
I think this issue is solved. But please let us know if you have any other follow up questions or would like this reopened.
