### ISSUE TITLE
[FEATURE REQ] Clear distinguish between public and private API.

### ISSUE THREAD

**Issue by sergey-shandar** [Azure/azure-sdk-for-c#216]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Description Added
- [ ] Expected solution specified

**Comment by barcharcraz** [comment]
Can you fill in additional information about this request please? It's really hard to take action on an issue with just the default template.

**Comment by sergey-shandar** [comment]
@barcharcraz I think, we discussed this one in our meeting. We should use `_az_` for internal things (functions, constants, etc.).

**Comment by gilbertw** [comment]
Internal is distinguished with _az_

**Comment by JeffreyRichter** [comment]
We agreed to _az_* (leading underscore)
