### ISSUE TITLE
az_span_copy, az_span_from_str backsplash escape issue 

### ISSUE THREAD

**Issue by HaoHoo** [Azure/azure-sdk-for-c#2172]
**Describe the bug**
I'm just try to study the sample code. I notice that the message sent to IoT Hub looks like not process the backslash escape (\") and send them to IoT Hub directly.
 
The code which I use list here:
 
static void getTelemetryPayload(az_span payload, az_span* out_payload)
{
  az_span original_payload = payload;
 
  TempAndHumidity  data = dhtSensor.getTempAndHumidity();
  Serial.println("--- Temperature: " + String(data.temperature, 1) + "°C" + ", Humidity: " + String(data.humidity, 1) + "% ---");
 
  payload = az_span_copy(payload, AZ_SPAN_FROM_STR("{\\"messageId\\": "));
  (void)az_span_u32toa(payload, telemetry_send_count++, &payload);
  payload = az_span_copy(payload, AZ_SPAN_FROM_STR(", \\"deviceId\\": \\"ESP32\\""));
  payload = az_span_copy(payload, AZ_SPAN_FROM_STR(", \\"temperature\\": "));
  (void)az_span_dtoa(payload, data.temperature, 2, &payload);
  payload = az_span_copy(payload, AZ_SPAN_FROM_STR(", \\"humidity\\": "));
  (void)az_span_dtoa(payload, data.humidity, 2, &payload);
  payload = az_span_copy(payload, AZ_SPAN_FROM_STR(" }"));
  payload = az_span_copy_u8(payload, '\0');
 
  *out_payload = az_span_slice(original_payload, 0, az_span_size(original_payload) - az_span_size(payload));
}
 
 
The messages example list below:
 
[IoTHubMonitor] Start monitoring message arrived in built-in endpoint for device [vIoTEdgeDevice] ...
[IoTHubMonitor] Created partition receiver [0] for consumerGroup [$Default]
[IoTHubMonitor] Created partition receiver [1] for consumerGroup [$Default]
[IoTHubMonitor] [7:06:58 PM] Message received from [vIoTEdgeDevice]:
"{\\"messageId\\": 24, \\"deviceId\\": \\"ESP32\\", \\"temperature\\": 32.2, \\"humidity\\": 62 }\u0000"
[IoTHubMonitor] [7:07:06 PM] Message received from [vIoTEdgeDevice]:
"{\\"messageId\\": 25, \\"deviceId\\": \\"ESP32\\", \\"temperature\\": 32.2, \\"humidity\\": 62 }\u0000"
 
Could you please help me to resolve this problem?

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**
 payload = az_span_copy(payload, AZ_SPAN_FROM_STR(" \\" "));
//output is \\"

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**
//output is "

**Screenshots**

**Setup (please complete the following information):**

- OS: [e.g. iOS] Mac OS - Edge browser.
- IDE: [e.g. IntelliJ] wokwi.com 
- Version of the Library used : beta 0.3

**Additional context**

**Information Checklist**
Please make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report

- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by danewalton** [comment]
Hi @HaoHoo 
Are you using the azure CLI to monitor the messages? We haven't seen the escaped characters also being sent as that is a C language behavior to unescape them.

**Comment by HaoHoo** [comment]
> Hi @HaoHoo Are you using the azure CLI to monitor the messages? We haven't seen the escaped characters also being sent as that is a C language behavior to unescape them.

Thank you for the response.

I'll try Azure CLI and feedback later. Currently I just use VS Code IoT toolkit extension to receive the IoT Hub D2C message.

The sample code which I use is running on https://wokwi.com/projects/328102367605031506 . And I've tested the backslash escaped characters directly and it looks like normal.

**Comment by danewalton** [comment]
One thing, for this value here, can you subtract 1?

![image](https://user-images.githubusercontent.com/36710865/164512185-078939e9-a9cb-4277-8212-0ec6f488ca9e.png)


AKA make it `az_span_size(telemetry) - 1`. I see in the logs you are sending the null character.

**Comment by HaoHoo** [comment]
Result is correct after change code here.
![image](https://user-images.githubusercontent.com/10110568/165009983-52b10e61-0fb9-4cf8-bd2a-5986a616a153.png)

The D2C message is OK:
<img width="742" alt="image" src="https://user-images.githubusercontent.com/10110568/165009858-11155450-350b-4fdb-95bf-284f8245eb4f.png">

Thank you.

**Comment by danewalton** [comment]
Ahh so it was the extra `NULL` character which was the culprit? If it is I can double check the code to make sure it's right.
