### ISSUE TITLE
"'AZ_RETURN_IF_FAILED' was not declared in this scope Error" while trying to generate json telemetry payload.

### ISSUE THREAD

**Issue by sadranyi** [Azure/azure-sdk-for-c#2189]
**Query/Question**
I have been exploring setting up and sending telemetry to IoT Hub using an ESP32 and the New SDK using the steps provided in the Github repo found [here ](https://github.com/Azure/azure-sdk-for-c-arduino/tree/main/examples/Azure_IoT_Hub_ESP32).
So far I have been able to connect and send dummy telemetry as stated in the example.

In other to make the sample more relateable, I added a DHT11 temperature and humidity sensor to the sketch and was able to get and send the data using a workaround that is not really clean and scalable, hence wanting to send the telemetry as JSON. I looked into the documentation but there was not much to work with using JSON.  After days of research I managed to put some code together but keep getting into an error with one of the macros **"AZ_RETURN_IF_FAILED"**

I would appreciate it if some pointers or help could be provided. 

***Why is this not a Bug or a Feature Request?***
I am not entirely sure if this is a bug or just me missing something, but I am adding my code here for referral and guidance.

```
// C99 libraries
#include <cstdlib>
#include <string.h>
#include <time.h>

// Libraries for MQTT client and WiFi connection
#include <WiFi.h>
#include <mqtt_client.h>

// Azure IoT SDK for C includes
#include <az_core.h>
#include <az_iot.h>
#include <azure_ca.h>

// Additional sample headers 
#include "AzIoTSasToken.h"
#include "SerialLogger.h"
#include "iot_configs.h"

// When developing for your own Arduino-based platform,
// please follow the format '(ard;<platform>)'. 
#define AZURE_SDK_CLIENT_USER_AGENT "c/" AZ_SDK_VERSION_STRING "(ard;esp32)"

static az_result generateTelemetryPayload(az_span* payload)
{
  az_json_writer json_writer;
  AZ_RETURN_IF_FAILED(az_json_writer_init(&json_writer, AZ_SPAN_FROM_BUFFER(payload), NULL));
  AZ_RETURN_IF_FAILED(az_json_writer_append_begin_object(&json_writer));
  AZ_RETURN_IF_FAILED(az_json_writer_append_property_name(&json_writer, celsius_telemetry_name));
  AZ_RETURN_IF_FAILED(az_json_writer_append_double(&json_writer, celsius_temperature_value));
  AZ_RETURN_IF_FAILED(az_json_writer_append_end_object(&json_writer));

  *payload = az_json_writer_get_bytes_used_in_destination(&json_writer);
  return AZ_OK;
}
```

The error I keep getting is **AZ_RETURN_IF_FAILED was not declared in this scope**
Which macro should I be using instead 

**Setup (please complete the following information if applicable):**

- OS: **Windows 11 Pro Workstations**
- IDE: **Arduino IDE v1.8.13**
- Version of the Library used: **Azure SDK for C 1.0.0-beta.3**

**Information Checklist Please make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report**

-  [X] Query Added 
-  [X] Setup information Added

**Comment by danewalton** [comment]
Hi @sadranyi 
The API `AZ_RETURN_IF_FAILED()` was removed and moved to an internal header with this release [here](https://github.com/Azure/azure-sdk-for-c/releases/tag/1.0.0-preview.5). You can feel free to create a similar macro which does the same thing. If other users find it to be useful we may make it a public one.

https://github.com/Azure/azure-sdk-for-c/blob/9e84ee870ed7a5ca5cb63dedd6a2edcaa0839b72/sdk/inc/azure/core/internal/az_result_internal.h#L28

**Comment by sadranyi** [comment]
I will try this and give you feedback

**Comment by danewalton** [comment]
Going to close this for now. Let us know if you run into the same issue.
