### ISSUE TITLE
[BUG] Response buffer contains garbage

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-c#219]
so, az_http_client_send_request()'s signature it this:
```c
az_result az_http_client_send_request(
    az_http_request_builder * const p_hrb,
    az_mut_span const * const response)
```
and also pipeline's signature is this:
```c
az_result az_http_pipeline_process(
    az_http_request_builder * const hrb,
    const az_mut_span * const response,
    az_http_pipeline * pipeline)
```
And I think that `az_mut_span const * const response` is a design problem.
It actually has a bug today:
```c
az_mut_span response_buffer = { .begin = /*pointer to a buffer containing garbage*/, size = 10240 };
az_http_pipeline_process(..., & response_buffer, ...);

//response was actually 500 bytes

assert(response_buf.size == 500); // fails

body = parse_body(response_buf); // going to get body, including the old garbage that was in the buffer

json = parse_json(body) // in case there was json in the buffer before we sent a request, we're probably going to parse that too
```

So, right away, we at least need a quick fix, which would be to update mutable span's size to the actual response size.

This bug was unnoticed because it happened so that we initialize all buffers with zeros, and also everything we ever do is JSON parse, and that JSON parser is pretty solid.

But, more proper solution is to chose either of two designs:
1.
```c
func(..., az_mut_span response_buf, az_(mut)_span * const actual_response);
```

2.
```c
func(..., az_span_builder * const response_builder);
```

I prefer 2.

**Comment by antkmsft** [comment]
I know that now we changed az_mut_span to az_http_response, but the problem is essentially the same

**Comment by vhvb1989** [comment]
would it work if transport policy writes \0 at the end of response? (wonder if the standar http response already adds it.. since it adds \n\n before body)
the json parser knows where it's body's end

**Comment by vhvb1989** [comment]
Confirming, curl adapter is adding \0 to end of response when response is CURL_OK
```
// make sure to set the end of the body response as the end of the complete response
  if (az_succeeded(result)) {
    AZ_RETURN_IF_FAILED(az_span_builder_append(&response_builder, AZ_STR_ZERO));
  }
```

@sergey-shandar , can we have az_http_response_parser updated to read body until \0 and not until end of buffer?

**Comment by sergey-shandar** [comment]
@vhvb1989 we shouldn't rely on zero at the end. 
1. we may change PAL (CURL) in the future.
1. Body may contain `0` in the middle.
