### ISSUE TITLE
Azure IoT Edge Hub as Transparent Gateway with ESP32

### ISSUE THREAD

**Issue by arkapravasinha** [Azure/azure-sdk-for-c#2212]
**Query/Question**
How to use this sdk for  Azure IoT Edge Hub with ESP32?

***Why is this not a Bug or a feature Request?***
I am adding the root ca created for Azure IoT Edge Hub in the example for Azure IoT Hub ESP 32 example, am getting an SSL Handshake error.

**Setup (please complete the following information if applicable):**

- IDE: [e.g. IntelliJ]
- Version of the Library used

 **Information Checklist**
 Please make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report

- [ ] Query Added
- [ ] Setup information Added

**Comment by arkapravasinha** [comment]
The Error I am getting:
22:29:13.156 -> 2022/5/19 16:59:15 [INFO] MQTT event MQTT_EVENT_BEFORE_CONNECT
22:29:13.532 -> E (74107) esp-tls-mbedtls: mbedtls_ssl_handshake returned -0x2700
22:29:13.532 -> E (74108) esp-tls: Failed to open new connection
22:29:13.532 -> E (74108) TRANSPORT_BASE: Failed to open a new connection
22:29:13.532 -> E (74114) MQTT_CLIENT: Error transport connect
22:29:13.532 -> 2022/5/19 16:59:15 [INFO] MQTT event MQTT_EVENT_ERROR
22:29:13.532 -> 2022/5/19 16:59:15 [INFO] MQTT event MQTT_EVENT_DISCONNECTED

**Comment by ericwol-msft** [comment]
Here is a thread on mbedtls talking about debug steps for error -0x2700

https://forums.mbed.com/t/mbedtls-ssl-handshake-return-error-0x2700/5354
