### ISSUE TITLE
[FEATURE REQ] JSON Builder should handle floating-point numbers

### ISSUE THREAD

**Issue by sergey-shandar** [Azure/azure-sdk-for-c#222]
json builder uses next function to append a number
```c
AZ_NODISCARD az_result az_span_append_dtoa(az_span destination, double source, az_span* out_span)
```
This function is the one that would need to implement floating point less than 0.001
// eg. 0.0012
  if (source < 0.001)
  {
    // D.*De-*D
    // TODO:
    return AZ_ERROR_NOT_IMPLEMENTED;
  }

  // eg. 1.2e-4
  {
    // *D.*D
    // TODO:
    return AZ_ERROR_NOT_IMPLEMENTED;
  }

**Comment by JeffreyRichter** [comment]
@ahsonkhan : We can discuss how to best handle this. I suspect you know more than I do about this.

**Comment by vhvb1989** [comment]
we are not even covering numbers > 0.001 and < 1
if we run 
```c
TEST_EXPECT_SUCCESS(az_json_builder_append_array_item(&builder, az_json_token_number(0.9)));
```
this just adds a 0,
