### ISSUE TITLE
Device Provisioning IoT Hub ESP32

### ISSUE THREAD

**Issue by BoeykensBrooklyn** [Azure/azure-sdk-for-c#2222]
For a project at school use an ESP32 running an IoT Hub script for connecting to the cloud.

Now this is all static and in practice this should be possible across a few 100 devices. I had thought about DPS for this purpose.

In case: "Zero-touch provisioning to a single IoT solution without hardcoding IoT Hub connection information at the factory (initial setup)"

Does anyone have a sample script? I can "t found out for using it on a ESP32.

What I would like is that when it has WiFi connection at its intial startup that it would create a device via the MAC Address. 

Thanks in advance

**Comment by danewalton** [comment]
Hi @BoeykensBrooklyn 
Are you asking for a script which creates connection information for the device, flashes it to the device, and then the device can connect to the Device Provisioning Service?

**Comment by BoeykensBrooklyn** [comment]
Yes,
The project is for a startup and we need to think about connecting to the cloud easily. Now I find IoT Hub very cool to work with and I wanted to connect to the cloud through IoT Hub. 

Now the startup told me that when they come to install it at a customer of theirs they want to do nothing more than just set up WiFi (which I will probably change to LTE connection) and the device will be created in the Cloud as device id its MAC ADDRESS.

So I wanted to see if anyone had a sample/basic script of DPS + IoT Hub for the ESP32. 

I already have a script with IoT Hub on the ESP32 , this works but of course need to set the data static, want to modify this so that the device_Id = WiFi.MacAdress();
And this I would like to do via DPS.

Translated with www.DeepL.com/Translator (free version)

**Comment by danewalton** [comment]
So what you're looking for is probably some kind of group enrollment. It creates an umbrella for many devices to provision based on some kind of root auth (certificate or symmetric key). 

Details on that here: https://docs.microsoft.com/en-us/azure/iot-dps/concepts-service#enrollment-group
For sas key group enrollment: https://docs.microsoft.com/en-us/azure/iot-dps/concepts-symmetric-key-attestation?tabs=windows#group-enrollments
For x509 group enrollment: https://docs.microsoft.com/en-us/azure/iot-dps/concepts-x509-attestation#controlling-device-access-to-the-provisioning-service-with-x509-certificates

If using sas keys, you would need some mechanism to pull the MAC address from the device, create a symmetric key derived from the group master key, then flash that auth info to the device along with the firmware.
