### ISSUE TITLE
Incorrect Calculation  _az_http_policy_logging_append_http_request_msg()

### ISSUE THREAD

**Issue by ericwol-msft** [Azure/azure-sdk-for-c#2224]
File : sdk\src\azure\core\az_http_policy_logging.c
• API : _az_http_policy_logging_append_http_request_msg( )
• Line : 73
• Issue : Incorrect calculation of required_length.
• The value needs to be incremented, not reassigned.
• Required length is being calculated using four values:
• “HTTP Request : ” 15 in length (http_request_string)
• HTTP Method used (_internal.method)
• Space
• Actual length of URL (_internal.url_length)
The length of http_request_string is missing from the calculation.
• Effect : Machine goes to Infinite Loop.
• **Recommendation: Modify “=” to “+=” in L:73**

![image](https://user-images.githubusercontent.com/37418465/172945738-892ad9f9-5fe2-4bef-b6dd-76f453c4487e.png)

**Comment by ahsonkhan** [comment]
Although there are no callers for the internal policies in `main` yet, this looks like a valid correctness bug which we may want to prioritize fixing (verified from https://github.com/Azure/azure-sdk-for-c/pull/549, the intent is to add the `http_request_string` length).

https://github.com/Azure/azure-sdk-for-c/blob/9f5a6334863ebbf214c6e2fbd5d6e3fce52fe0de/sdk/src/azure/core/az_http_policy_logging.c#L66-L74

Moving to July milestone, to try and catch the next release cycle.

**Comment by ahsonkhan** [comment]
cc @RickWinter

**Comment by antkmsft** [comment]
Thank you @ericwol-msft, this is a bug, we should fix it. And thank you for the detailed info, you basically wrote the fix as well!
@ahsonkhan, you are right, there should be no callers in `main` branch at this moment.

**Comment by RickWinter** [comment]
@antkmsft Lets fix this for the next release
