### ISSUE TITLE
Blog - running on ublox w106

### ISSUE THREAD

**Issue by tcpipchip** [Azure/azure-sdk-for-c#2225]
https://blinky-nina-w102.blogspot.com/2022/06/nina-w106-sendo-programado-em-basic.html?m=1

**Comment by danewalton** [comment]
Hi @tcpipchip thanks for the message!

Are you only calling out that this was featured in the blog post or is there some assistance needed to get this to work?

**Comment by tcpipchip** [comment]
> Hi @tcpipchip thanks for the message!
> 
> Are you only calling out that this was featured in the blog post or is there some assistance needed to get this to work?

Hi, just to contribute!

**Comment by tcpipchip** [comment]
> > Hi @tcpipchip thanks for the message!
> > Are you only calling out that this was featured in the blog post or is there some assistance needed to get this to work?
> 
> Hi, just to contribute!

And show that works fine!!!!

**Comment by danewalton** [comment]
Awesome glad to hear it! I will go ahead and close this and people can hopefully find this in the future if they search for it in the issue list. Please let us know if there's any improvements we can make!
