### ISSUE TITLE
[FEATURE REQ] We should publish VCPKG and test/CI ???.

### ISSUE THREAD

**Issue by sergey-shandar** [Azure/azure-sdk-for-c#223]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Description Added
- [ ] Expected solution specified

**Comment by joshfree** [comment]
@danieljurek please feel free to close this, with a link to the issue(s), if this is already tracked elsewhere.

**Comment by danieljurek** [comment]
Closing. This work is tracked in https://github.com/azure/azure-sdk-for-c/issues/270 which will give us an idea of what automation we'll want to put in place for publishing to vcpkg.
