### ISSUE TITLE
Failing to generate SAS token on ESP32 direct MQTT connection

### ISSUE THREAD

**Issue by designncode7** [Azure/azure-sdk-for-c#2230]
**Query/Question**
I am following these instructions and using asymmetric keys: 
"[How to Setup and Run Azure SDK for Embedded C IoT Hub Client on Espressif ESP32](https://github.com/Azure/azure-sdk-for-c-arduino/tree/main/examples/Azure_IoT_Hub_ESP32#how-to-setup-and-run-azure-sdk-for-embedded-c-iot-hub-client-on-espressif-esp32)"
and getting the following error in Serial Monitor:
17:59:51.267 -> ..
17:59:51.788 -> 2022/6/14 15:59:51 [INFO] Time initialized!
17:59:51.788 -> 2022/6/14 15:59:51 [INFO] Try to initialize IoTHubClient
17:59:51.788 -> 2022/6/14 15:59:51 [INFO] Client ID: ESP32boardName
17:59:51.788 -> 2022/6/14 15:59:51 [INFO] Username: IoTHubName.azure-devices.net/ESP32DevBoard/?api-version=2020-09-30&DeviceClientType=c/1.3.1(ard;esp32)
17:59:51.788 -> 2022/6/14 15:59:51 [INFO] Try to initialize MQTT Client
17:59:51.788 -> 2022/6/14 15:59:51 [ERROR] mbedtls_base64_decode fail
17:59:51.788 -> 2022/6/14 15:59:51 [ERROR] Failed generating encoded signed signature
17:59:51.788 -> 2022/6/14 15:59:51 [ERROR] Failed generating SAS token signed signature
17:59:51.835 -> 2022/6/14 15:59:51 [ERROR] Failed generating SAS token
17:59:51.835 -> 2022/6/14 15:59:51 [ERROR] Failed generating SAS token
17:59:51.835 -> 2022/6/14 15:59:51 [INFO] SAS token expired; reconnecting with a new one.

>> Why can the SAS token not be generated?

***Why is this not a Bug or a feature Request?***
There is a difference between the api-version used in the sample code: **api-version=2020-09-30**
And the latest IoT [Hub MQTT documentation](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-support#example-in-c-using-mqtt-without-an-azure-iot-sdk): **api-version=2021-04-12**

1>> Is the difference in the api-version causing the SAS token generation error?
2>> If so: how can the api-version be changed in the sample code to be 2021-04-12?
3>> If not: what else could be causing this error?

**Setup:**
- OS: ESP32 board programmed from Arduino IDE
- IDE: latest Arduino IDE
- Version of the Library used: azure-sdk-for-c is 1.0.0.-beta4

Thanks!

**Comment by danewalton** [comment]
It seems like mbedtls is having a difficult timing decoding your key. Can you please give us details on where you are getting it? Note: it should not be the connection string, but just the key.

**Comment by designncode7** [comment]
Hi, thanks!  By using the Device Key (instead of the full connection string) it works.  The sample sketch can send telemetry to IoT Hub.

**Comment by danewalton** [comment]
Awesome glad to hear! I'll go ahead close this for now. Please let us know if you need any other help.
