### ISSUE TITLE
Azure IoT Hub ESP32 Example - Issue setting contentType and contentEncoding

### ISSUE THREAD

**Issue by markwest** [Azure/azure-sdk-for-c#2231]
Thanks for creating the Azure SDK for C (Arduino). It is very helpful.

I am working with the Azure IoT_Hub_ESP32 example. After updating the iot_configs.h file from the example, my ESP32 hardware successfully communicates with my device in Azure IoT Hub. However, the example code does not set the System Properties, contentType (i.e. application/json) and contentEncoding (i.e. utf-8). The typical payload I receive in Azure IoT Explorer is shown below. I removed the device-id and auth-generation-id for security purposes. Setting these properties is required to setup Azure IoT Hub Message Routing queries based on the content of the body in the payload. For example, $body.msgCount > 20.

I have spent a lot of time trying to rectify this issue. Unfortunately, I have not been successful. I am hoping your team can help me resolve this problem. Please let me know if you need additional information to troubleshoot. Thanks in advance for your support.

I presume there is a way to set the aforementioned properties. For this reason, I do not think this issue is a bug or feature request.

{
  "body": {
    "msgCount": 0
  },
  "enqueuedTime": "Tue Jun 14 2022 12:32:15 GMT-0400 (Eastern Daylight Time)",
  "systemProperties": {
    "iothub-connection-device-id": "****",
    "iothub-connection-auth-method": "{\"scope\":\"device\",\"type\":\"sas\",\"issuer\":\"iothub\",\"acceptingIpFilterRule\":null}",
    "iothub-connection-auth-generation-id": "****",
    "iothub-enqueuedtime": 1655224334960,
    "iothub-message-source": "Telemetry"
  }
}

Setup Information
- OS: Windows 10
- IDE: Arduino and PlatformIO (same issue with both)
- Framework: Arduino
- Azure SDK for C Arduino Release 1.0.0-beta.4
- Azure_IoT_Hub_ESP32 example project

Regards, Mark

**Comment by ericwol-msft** [comment]
THese are properties on the Telemetry message. See `AZ_IOT_MESSAGE_PROPERTIES_CONTENT_TYPE` and `AZ_IOT_MESSAGE_PROPERTIES_CONTENT_ENCODING` in az_iot_common.h

Here is an usage example: https://github.com/microsoft/edge-impulse-freezer-monitor/blob/6b9ce4854ccf7a1353624b88a272c2ccc4648c96/data_collection/iot_hub_data_collector/iot_hub_data_collector.ino#L94

**Comment by markwest** [comment]
Eric,

Your solution worked like a charm. I cannot thank you enough for your help. No longer have to beat my head against the wall. :) Also, thanks for the Freezer Monitor example, which I want to explore further.

Regards, Mark

**Comment by ericwol-msft** [comment]
here is the official Azure IoT hub MQTT documentation

https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-support
