### ISSUE TITLE
az_http_pipeline_policy_retry() has unreachable code

### ISSUE THREAD

**Issue by ericwol-msft** [Azure/azure-sdk-for-c#2232]
Our partner ST reported compilation warning for az_http_policy_retry.c that [line224](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-sdk-for-c%2Fblob%2F1.3.1%2Fsdk%2Fsrc%2Fazure%2Fcore%2Faz_http_policy_retry.c%23L224&data=05%7C01%7CEric.Wolz%40microsoft.com%7Ca3bf886949274f7da80108da4dc41ffb%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637907802067182750%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=1H53q1f9habJq89vAdeDQp1oSVqheJ%2FOE7nSgqh%2BhWY%3D&reserved=0) is unreachable code, could you take a look at it? thanks.

File azure-sdk-for-c\sdk\src\azure\core\az_http_policy_retry.c v 1.3.1
Line 224 is unreachable due to infinite while loop without breaking.

Warning highlighted by EWARM 9.20.4

Link to file: [https://github.com/Azure/azure-sdk-for-c/blob/1.3.1/sdk/src/azure/core/az_http_policy_retry.c](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-sdk-for-c%2Fblob%2F1.3.1%2Fsdk%2Fsrc%2Fazure%2Fcore%2Faz_http_policy_retry.c&data=05%7C01%7CEric.Wolz%40microsoft.com%7Ca3bf886949274f7da80108da4dc41ffb%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637907802067182750%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YlBl2mBUoJbPpLZlLdg%2FU%2BiTg9qZOrxQveUCcCIF3rQ%3D&reserved=0)

**Comment by JeffreyRichter** [comment]
Looks like we could just remove that line of code entirely.
