### ISSUE TITLE
api-version produced by azure-sdk-for-c is old

### ISSUE THREAD

**Issue by designncode7** [Azure/azure-sdk-for-c#2234]
**Query/Question**
There is a difference between the api-version produced by the sample code is: ?api-version=2020-09-30 and the one in the official MS MQTT documentation.  The latest IoT [Hub MQTT documentation](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-support#example-in-c-using-mqtt-without-an-azure-iot-sdk): ?api-version=2021-04-12

1. Why is the api-version produced by the azure-sdk-for-c 2020-09-30 and NOT 2021-04-12 (as per the documentation)?

2. What TLS version is used by the azure-sdk-for-c library?

***Why is this not a Bug or a feature Request?***
The upgrade to the latest api-version is probably planned.  If so, for when is it planned?

**Setup:**
- OS: ESP32 Dev Kit
- IDE: Arduino IDE
- Version of the Library used: Azure SDK for C 1.0.0.Beta-4

Thanks,
G. Hariz.

**Comment by danewalton** [comment]
The API version doesn't always go in lock step with the newest version from the service. If features are supported from the service side but not SDK side, we don't bump it. It's generally on an as needed basis.

As for the TLS, it should be 1.1 or 1.2 for the service. Note though that this SDK does no networking, so the used/supported version should be configured on your TLS stack of choice.

**Comment by danewalton** [comment]
I'm going to go ahead and close this for now. Please let us know if you would like it reopened.
