### ISSUE TITLE
MQTT Fail to connect to DPS by esp32 however connects using VS on PC

### ISSUE THREAD

**Issue by 3alimoh** [Azure/azure-sdk-for-c#2235]
**Describe the bug**
When connecting the ESP to DPS it only succeeds when using X509 for the first time and fails after that. When using Symmetric Keys fails (NOT AUTHORIZED MQTT). Everything is working from the IOT side, checked by SDK on PC.

***Exception or Stack Trace***
1970/1/1 00:00:04 [ERROR] MQTT client in ERROR state.
1970/1/1 00:00:04 [ERROR] esp_tls_stack_err=0; esp_tls_cert_verify_flags=0;esp_transport_sock_errno=0;error_type=2;connect_return_code=5
1970/1/1 00:00:04 [ERROR] connect_return_code=MQTT_CONNECTION_REFUSE_NOT_AUTHORIZED
E (5036) MQTT_CLIENT: MQTT connect failed
1970/1/1 00:00:04 [INFO] MQTT client disconnected.

**To Reproduce**

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**

- IDE: Arduino
- Version of the Library used

**Additional context**

**Information Checklist**
Please make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report

- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by danewalton** [comment]
Hi @3alimoh 
You're saying you've tried using the same credentials on the PC sample and it connects just fine?

**Comment by danewalton** [comment]
@3alimoh any updates?

**Comment by 3alimoh** [comment]
Yes, I got the reason of the problem.
The ESP32 fails to reconnect on the latest version of the C SDK, when I installed beta 2 instead of the latest version, everything works fine.
But it is trying to connect to time server too long sometimes and may fail to connect. If I tried to skip the time server, it will fail to connect to DPS.

**Comment by danewalton** [comment]
Interesting. If the time server is not giving the correct time, that would the connection to be refused. Are you sure that's correct? And by "latest" I assume you mean `1.0.0-beta.4`?

**Comment by danewalton** [comment]
Any updates here @3alimoh ?
