### ISSUE TITLE
Receiving transport_read() error: errno=128 when trying to retrieve the device twin

### ISSUE THREAD

**Issue by Tintin4000** [Azure/azure-sdk-for-c#2264]
Following the sample in the SDK to retrieve the Device Twin, I have adapted the code from the [Azure_IoT_Hub_ESP32](https://github.com/Azure/azure-sdk-for-c-arduino/tree/main/examples/Azure_IoT_Hub_ESP32) for the esp mqtt.
The sample Azure_IoT_Hub_ESP32 works fine, but the code the retrieve the Device Twin is returning transport_read() error: errno=128.

Using an MQTT client all seems to work as per the logic of the code.  So if you can help me understand what is not working, that would be great.  Or provide a workable example for ESP32 Arduino to get the device twin.

Calling the below function after both client initialized successfully:

```c
void subscribeToDeviceTwin()
{
    char twinDocBuffer[128];
    char twinData[128];

    if (esp_mqtt_client_subscribe(mqttClient, AZ_IOT_HUB_CLIENT_TWIN_RESPONSE_SUBSCRIBE_TOPIC, MQTT_QOS1) == MQTT_FAILURE)
    {
#ifdef DEBUG_SERIAL // Debug info
        Serial.printf("[AZURE] The subscription to the device twin topics failed.\n");
#endif
        exit(MQTT_FAILURE);
    }
    az_result rslt = az_iot_hub_client_twin_document_get_publish_topic(&azureClient, twin_document_topic_request_id, twinDocBuffer, sizeof(twinDocBuffer), NULL);
    if (az_result_failed(rslt))
    {
#ifdef DEBUG_SERIAL // Debug info
        Serial.printf("[AZURE] Failed to get the Twin Document topic: az_result return code 0x%08x.", rslt);
#endif
    }
#ifdef DEBUG_SERIAL // Debug info
    Serial.printf("[AZURE] Send an empty message to topic: %s\n", twinDocBuffer);
#endif
    if (esp_mqtt_client_publish(mqttClient, twinDocBuffer, twinData, sizeof(twinData), MQTT_QOS1, DO_NOT_RETAIN_MSG) == MQTT_FAILURE)
    {
#ifdef DEBUG_SERIAL // Debug info
        Serial.printf("[AZURE] The publish of the device twin topics failed.\n");
#endif
    }
}
```

The debug output:

```log
2022/7/11 09:15:48 [INFO] Client ID: ESP32GardenSensor1
2022/7/11 09:15:48 [INFO] Username: IoTHub4000.azure-devices.net/ESP32GardenSensor1/?api-version=2020-09-30&DeviceClientType=c/1.3.1(ard;esp32)
2022/7/11 09:15:202250/7/11 [INFO]  MQTT client started09
:15:50 [INFO] MQTT event MQTT_EVENT_BEFORE_CONNECT
2022/7/11 09:15:51 [INFO] MQTT event MQTT_EVENT_CONNECTED
2022/7/11 09:15:51 [INFO] Subscribed for cloud-to-device messages; message id:16042
2022/7/11 09:15:51 [INFO] MQTT event MQTT_EVENT_SUBSCRIBED
[AZURE] Send an empty message to topic: $iothub/twin/GET/?$rid=get_twin
2022/7/11 09:15:52 [INFO] MQTT event MQTT_EVENT_SUBSCRIBED
E (8685) MQTT_CLIENT: mqtt_message_receive: transport_read() error: errno=128
2022/7/11 09:15:52 [INFO] MQTT event MQTT_EVENT_ERROR
E (8686) MQTT_CLIENT: mqtt_process_receive: mqtt_message_receive() returned -1
2022/7/11 09:15:52 [INFO] MQTT event MQTT_EVENT_DISCONNECTED
```

**Comment by danewalton** [comment]
Hi @Tintin4000 [we published an update to the Arduino library which addresses this issue](https://github.com/Azure/azure-sdk-for-c-arduino/releases/tag/1.0.0-beta.5). Are you able to try it out and let us know if your issue goes away?

**Comment by danewalton** [comment]
Can you post the logs as you did before? I just want to double check.

**Comment by Tintin4000** [comment]
2022/7/12 04:22:21 [INFO] Client ID: ESP32GardenSensor1
2022/7/12 04:22:21 [INFO] Username: IoTHub4000.azure-devices.net/ESP32GardenSensor1/?api-version=2020-09-30&DeviceClientType=c/1.3.2(ard;esp32)
2022/7/12 04:202222/7:/1223 04 [INFO] :22:MQTT client started23
 [INFO] MQTT event MQTT_EVENT_BEFORE_CONNECT
2022/7/12 04:22:24 [INFO] MQTT event MQTT_EVENT_CONNECTED
2022/7/12 04:22:24 [INFO] Subscribed for cloud-to-device messages; message id:23806
2022/7/12 04:22:24 [INFO] MQTT event MQTT_EVENT_SUBSCRIBED
[AZURE] Send an empty message to topic: $iothub/twin/GET/?$rid=get_twin
2022/7/12 04:22:25 [INFO] MQTT event MQTT_EVENT_SUBSCRIBED
E (9691) MQTT_CLIENT: mqtt_message_receive: transport_read() error: errno=128
2022/7/12 04:22:25 [INFO] MQTT event MQTT_EVENT_ERROR
E (9692) MQTT_CLIENT: mqtt_process_receive: mqtt_message_receive() returned -1
2022/7/12 04:22:25 [INFO] MQTT event MQTT_EVENT_DISCONNECTED

**Comment by Tintin4000** [comment]
And on the Azure side:
authType:null
deviceId:ESP32GardenSensor1
errorMessage:Device disconnected, see cause and resolution at https://aka.ms/iothub404104
maskedIpAddress:80.209.90.XXX
protocol:Mqtt
statusCode:404

**Comment by danewalton** [comment]
Ahhh yup okay so the issue is from the second line of the log. It has `DeviceClientType=c/1.3.2`. That forward slash should be url encoded to a `%2F` which we did [here](https://github.com/Azure/azure-sdk-for-c-arduino/blob/a7d395be4c8592c315884dd35b32103c27724954/examples/Azure_IoT_Hub_ESP32/Azure_IoT_Hub_ESP32.ino#L45) in the samples for the newest release. You can either take the new sample or just change that line to match what's in the repo. Let me know how that works out for you.

**Comment by Tintin4000** [comment]
You are a star!  It worked.  Do you have an explanation so I learn the issue?  Log here under:
2022/7/12 14:24:09 [INFO] Client ID: ESP32GardenSensor1
2022/7/12 14:24:09 [INFO] Username: IoTHub4000.azure-devices.net/ESP32GardenSensor1/?api-version=2020-09-30&DeviceClientType=c%2F1.3.2(ard;esp32)
2022/7/12 14:24:202211/7/12 [INFO]  14MQTT client started:24:
11 [INFO] MQTT event MQTT_EVENT_BEFORE_CONNECT
2022/7/12 14:24:12 [INFO] MQTT event MQTT_EVENT_CONNECTED
2022/7/12 14:24:12 [INFO] Subscribed for cloud-to-device messages; message id:55025
2022/7/12 14:24:12 [INFO] MQTT event MQTT_EVENT_SUBSCRIBED
[AZURE] Send an empty message to topic: $iothub/twin/GET/?$rid=get_twin
2022/7/12 14:24:13 [INFO] MQTT event MQTT_EVENT_SUBSCRIBED
2022/7/12 14:24:13 [INFO] MQTT event MQTT_EVENT_PUBLISHED
2022/7/12 14:24:13 [INFO] MQTT event MQTT_EVENT_DATA
2022/7/12 14:24:13 [INFO] Topic: $iothub/twin/res/200/?$rid=get_twin
2022/7/12 14:24:13 [INFO] Data: {"desired":{"sensor":{"Sleep":5},"$version":2},"reported":{"$version":1}}

**Comment by danewalton** [comment]
The gist of it is that the user agent needs to be URL encoded and if it isn't, then the device can fail if the service fails to parse that. As long as that value is encoded you're good to go 👍🏼
