### ISSUE TITLE
ESP32 Over-the-Air "OTA" Firmware Update Code Sample Request

### ISSUE THREAD

**Issue by markwest** [Azure/azure-sdk-for-c#2279]
**Query/Question**
Is there an Azure SDK for Embedded C code sample available for performing Over-the-Air "OTA" firmware updates on the ESP32 MCU?

***Why is this not a Bug or a feature Request?***
My assumption is that this code/feature already exists

**Setup (please complete the following information if applicable):**
- OS: Windows 10
- IDE: PlatformIO (Arduino Framework)
- 1.0.0-beta.5

**Comment by danewalton** [comment]
Hi @markwest thanks for the question! Just in luck, we are working on this right now. We do not have it ready yet, but we should have something in the coming months.

**Comment by markwest** [comment]
@danewalton That is good news. In the interim, what is the recommended approach and resources for coding this functionality?

Regards, Mark

**Comment by danewalton** [comment]
Unfortunately I can't really give an alternative at this point since our first party solution is right around the corner. Hopefully we will have some preview code soon for you to use.

**Comment by markwest** [comment]
@danewalton Thanks for the feedback. I guess I can use the deprecated libraries for now and update to the new code once it is available.

**Comment by danewalton** [comment]
Hi @markwest 
Thanks for the patience. We now have a beta release on the ESP32 using the Arduino library manager here:

![image](https://user-images.githubusercontent.com/36710865/198413029-a944d3e6-0320-4ffd-83d2-a99dfe65bcae.png)

[The instructions can be found here.](https://github.com/Azure/azure-sdk-for-c-arduino/tree/main/examples/Azure_IoT_Adu_ESP32) Give it a try and let us know what you think!

**Comment by markwest** [comment]
@danewalton 

Sorry for the belated reply. I ended up rolling my own solution utilizing the Azure SDK for C along with the Microsoft AzIoTSasToken class and helper libraries for the WiFi connection, time initialization, MQTT client, etc. However, I would like to try your solution. I will try to implement soon and provide feedback. Thanks for the follow-up.

Regards, Mark

**Comment by danewalton** [comment]
Thanks @markwest sounds good. Since the feature is out for people to try, I will close this issue since it's original ask is now done. If you have further questions, feel free to open another GH issue. Thanks!
