### ISSUE TITLE
Inquiry: Registering Device Modules via DPS possible?

### ISSUE THREAD

**Issue by meta-space** [Azure/azure-sdk-for-c#2283]
I'm using the [Azure SDK for Arduino](https://github.com/Azure/azure-sdk-for-c-arduino) to connect an ESP32 to Azure IoT Hub.
I've setup a group enrollment on DPS and was able to dynamically register devices and push telemetry updates to the IoT Hub. Which is great.

I'd like to do the same thing with module twins, but so far I was only partially successful.
I managed to connect to the IoT hub and push telemetry updates of a module twin, but I had to manually create it on the IoT Hub before first use. Otherwise, I received NOT_AUTHORIZED response during initialization of the IoT client. Ideally, I'd like to create a module twins fully dynamically at runtime just like device twins.

Is this supported by the SDK? And if so, does documentation or sample code exist for this use case?

**Comment by danewalton** [comment]
Hi @meta-space 

At this time, we don't have support with module IDs and Device Provisioning. It can only be device ids and DPS.

**Comment by meta-space** [comment]
Oh well...  for now device IDs are sufficient for our use case. 

Thanks for confirming and keep up the great work!
