### ISSUE TITLE
Fatal Error: bits/c++config.h: No such file or directory

### ISSUE THREAD

**Issue by scotmos** [Azure/azure-sdk-for-c#2295]
Im using windows 10 and arduino IDE . Whenever I try to upload the Azure_Iot_Central_ESP32_AzureIOT sketch to the board i get the following error: fatal error: bits/c++config.h: No such file or directory [#include](https://www.youtube.com/hashtag/include) <bits/c++config.h>

**Comment by danewalton** [comment]
Hi @scotmos 
Did you make sure to add the esp32 board libraries? [Instructions on that can be found here](https://docs.espressif.com/projects/arduino-esp32/en/latest/installing.html).

**Comment by scotmos** [comment]
Hello.  I will choosing the wrong board in the Arduino IDE.  I followed the microsoft video and he said to use the ESP-32-WOVER.  My board is 6 months older. Once i update the board, then i was able to flash image the board.
