### ISSUE TITLE
Running out of memory connecting to IoT Hub on Arduino ESP8266

### ISSUE THREAD

**Issue by designncode7** [Azure/azure-sdk-for-c#2299]
**Query/Question**
Is there any way to make the C SDK library for Arduino shrink even more in size to fit on ESP8266 constrained device?  

The provided sample, [iothub_ll_telemetry_sample.c](https://github.com/Azure/azure-iot-sdk-c/blob/main/iothub_client/samples/iothub_ll_telemetry_sample/iothub_ll_telemetry_sample.c), does NOT work on ESP8266 but works on ESP32.  We have tried using MQTT and HTTP (via the Preprocessor Directives in the code), but still we cannot connect on ESP8266.  
Note: we need to add code for OTA updates later.  So more SRAM free space is needed.

This Microsoft site, [Develop for constrained devices using Azure IoT C SDK](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-develop-for-constrained-devices), shows that there are things that can be done to reduce the size of the library such as:

1. Turn OFF AMQP
2. Turn OFF logging
3. Turn OFF upload to blob capability

### Questions:
I know we are using the _LL_ low level libraries already.  However, we need to reduce the compiled code size even more.  So:

1. **Are there any other options (preprocessor directives) to turn off AMQP, turn off logging or turn off upload to blob capability to make the library even more nimble?**

2.  **Or do we need to Cross Compile our own library for Arduino (to remove the extra - not used - parts e.g AMQP)?** 
 
3. **If so, is there any documentation on how to Cross Compile (on Windows 10 with the Target platform being Arduino)?**

### 
***Why is this not a Bug or a feature Request?***
We can connect to IoT Hub - using the same C SDK libraries from ESP32 device - but not from ESP8266.  So this is not a bug in the libraries.  This is a question on how to make the libraries smaller to fit on a constrained device (ESP8266).

**Setup (please complete the following information if applicable):**
- OS: ESP8266 Arduino device 
- IDE: latest Arduino IDE
- Version of the Library used: latest C SDK for Arduino (azure-sdk-for-c-arduino).  We also tried the C Core SDK.

 **Information Checklist**
- [x] Query Added
- [x] Setup information Added

Thanks!
GH

**Comment by danewalton** [comment]
Hi @designncode7 
The repo you are looking for is located here: https://github.com/Azure/azure-iot-sdk-c

That being said, you came to the right place to connect constrained devices to Azure! We have an ESP8266 sample here using the Embedded C APIs:

https://github.com/Azure/azure-sdk-for-c-arduino/blob/main/examples/Azure_IoT_Hub_ESP8266/readme.md

**Comment by designncode7** [comment]
Hi @danewalton,

Thanks for the reply.

We are using an ESP8266 device and the **AzureIoTHub library for Arduino (1.6.1)** (header AzureIotHub.h).

In the new azure-sdk-for-c-arduino library - that you shared with us in the comment above - these headers are used instead:
// Azure IoT SDK for C includes
#include <az_core.h>
#include <az_iot.h>
#include <azure_ca.h>
This new library for Arduino is still in Beta release.

1. **>> Is this original library AzureIotHub (that uses this header AzureIoTHub.h), deprecated?**
2. **>> What is the last date that this library will be supported?**

**_Issue:_**
As you know there are TLS certificate changes coming up.  And Microsoft made a test IoT Hub endpoint available for testing (that uses the new G2 certificates): g2cert.azure-devices.net

We have NOT been able to connect to the NEW G2 cert endpoint (g2cert.azure-devices.net) using the original library (AzureIoTHub library for Arduino (1.6.1)).  
3. >> **Is this a known issue?  Should we be able to connect using the old library or do we need to upgrade to the Beta library to connect to the new G2 IoT Hub endpoint?**



Thanks,
GH
