### ISSUE TITLE
Azure Core: create retry policy

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-c#23]
Implement a policy to handle HTTP request retries.  The policy should be generic and useful for any REST endpoint.  It should also be configurable WRT exponential back-off or fixed delay, max cap between iterations, total iterations etc.

**Comment by antkmsft** [comment]
This will be in soon - https://github.com/Azure/azure-sdk-for-c/pull/320

**Comment by joshfree** [comment]
Moving to the March milestone, as part of closing out the past-due milestones

**Comment by antkmsft** [comment]
Done a bit while ago :)
