### ISSUE TITLE
Unable to connect to NEW G2 cert endpoint (g2cert.azure-devices.net) using existing Arduino library

### ISSUE THREAD

**Issue by designncode7** [Azure/azure-sdk-for-c#2313]
**Query/Question**
A TLS certificate update is happening soon on the IoT Hub service.  It seems that to connect to the new G2 cert IoT Hub endpoints we can only use the new Azure C library for Arduino.  However, this library is in BETA release. 

1.  Should we be able to connect to the new G2 cert IoT Hub endpoints from the original Arduino C library (ver. 1.6.1)?

**Background**:
We are using an ESP8266 device and the AzureIoTHub library for Arduino (1.6.1) (header AzureIotHub.h).

**Issue**:
As you know there are TLS certificate changes coming up. And Microsoft made a test IoT Hub endpoint available for testing (that uses the new G2 certificates): g2cert.azure-devices.net

We have NOT been able to connect to the NEW G2 cert endpoint (g2cert.azure-devices.net) using the original library (AzureIoTHub library for Arduino (ver 1.6.1)).

1. Is this a known issue? Should we be able to connect using the old library?  OR
2. Do we need to upgrade to the Beta library to connect to the new G2 IoT Hub endpoint?
3. Is the original library AzureIotHub (version 1.6.1 and that uses the header AzureIoTHub.h), deprecated?
4. What is the last date that this library will be supported?

In the new azure-sdk-for-c-arduino library (https://github.com/Azure/azure-sdk-for-c-arduino) these headers are used instead:
// Azure IoT SDK for C includes
#include az_core.h
#include az_iot.h
#include azure_ca.h
Note: **This new library for Arduino is still in Beta release**.

Thanks,
GH

***Why is this not a Bug or a feature Request?***
We can connect to the NEW G2 cert endpoint (g2cert.azure-devices.net) using the new Arduino BETA library

**Setup (please complete the following information if applicable):**

- OS: ESP8266 Arduino
- IDE: Arduino IDE
- Version of the Library used: 
a) original library AzureIotHub (version 1.6.1 
b) new Azure library for arduino 1.0.0-beta.5

 **Information Checklist**
 Please make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report

- [x] Query Added
- [x] Setup information Added

**Comment by danewalton** [comment]
Hi @designncode7 
1. The old library is deprecated and likely will not connect to the G2 endpoint.
2. Yes
3. Yes
4. If you're talking about the old one, it is deprecated and removed from the Arduino repository so we don't support it anymore. For this repo, this is our offering for embedded devices for the foreseeable future.

**Comment by designncode7** [comment]
Hello @danewalton,

Thanks for the reply.

In the OLD Arduino C library we can choose the protocol (MQTT or HTTP) via a Preprocessor Directive.

In the **new Arduino library**:
1. Is HTTP communications protocol supported?
2. Can we choose to connect via HTTPS via a preprocessor directive?
3. Is there a sample sketch (like iothub_ll_telemetry_sample.c) that uses the NEW library to connect via HTTPS to IoT Hub?

Thanks,
GH

**Comment by AKJ1979** [comment]
I need work ESP8266 with sensor Max30102, but how can connect this kind of sensor to send data to IoT hub by using same code in Arduino library  C SDK.

**Comment by danewalton** [comment]
> 1. In the new Arduino library: are there plans to support HTTPS protocol to send messages to IoT Hub?
> 2. If HTTPS protocol is already supported, is there a sample sketch that uses the NEW library to connect via HTTPS to IoT Hub?

1. No we do not intend to directly support HTTPS at this time. That library is intended to only be for MQTT. There are, however, libraries which would allow you to connect over HTTPS (websockets). [An example is here](https://www.arduino.cc/reference/en/libraries/websocketstreamclient/). That being said, we do not have a reference implementation and you would need to do that yourself. Know that the transport is up to the user with this library, so you may swap in any MQTT or MQTT/WS library that you'd like.
2. Answered via #1
