### ISSUE TITLE
Store Azure settings in ESP32 Preferences

### ISSUE THREAD

**Issue by PDE-Paul** [Azure/azure-sdk-for-c#2317]
**Query/Question**

I wish to store the following in the ESP32 Preferences, so I can dynamically change the settings remotely at run time.

IOT_CONFIG_IOTHUB_FQDN -> Works
IOT_CONFIG_DEVICE_ID -> Works
IOT_CONFIG_DEVICE_KEY -> Only works if this is hardcoded like this #define IOT_CONFIG_DEVICE_KEY "Device Key"

***Why is this not a Bug or a feature Request?***

The example provided works perfectly. I just want to use it in a dynamic way.

I am able to dynamically store and recall IOT_CONFIG_IOTHUB_FQDN and IOT_CONFIG_DEVICE_ID using the ESP32 Preferences functions, but when I try to recall IOT_CONFIG_DEVICE_KEY my ESP32 will not connect, it appears that the static function below has something to do with this issue I am having, It appears to not work with dynamic settings that are populated at run time, 

static AzIoTSasToken sasToken(
    &client,
    AZ_SPAN_FROM_STR(IOT_CONFIG_DEVICE_KEY),
    AZ_SPAN_FROM_BUFFER(sas_signature_buffer),
    AZ_SPAN_FROM_BUFFER(mqtt_password));

I am battling to understand why, any assistance or advise will be much appreciated

**Setup (please complete the following information if applicable):**

- ESP32 16MB
- IDE: Arduino
- 1.0.0

Thx in advance, Paul

**Comment by danewalton** [comment]
Hi @PDE-Paul,
Looking at that function and with your usage case, I'm guessing what might be happening is malformed data going into those span macros (`AZ_SPAN_FROM_STR()` and `AZ_SPAN_FROM_BUFFER()`). Just to note on what those are doing.

- `AZ_SPAN_FROM_STR()` will take in a pointer and run `strlen()` on it, and use that integer as the length of the data at the pointer. If the data is not `NULL` terminated, you may run into issues.
- `AZ_SPAN_FROM_BUFFER()` will take in an array and run `sizeof()` on it. It can't be a pointer to an array, as that will return the size of a pointer and not the size of the actual buffer.

If you want to create a span with an explicit pointer and size, you may use `az_span_create()` which takes in a pointer and a length. 

Let me know if any of this information helps. If it doesn't feel free to give more information on your scenario and I can try and help further.

**Comment by PDE-Paul** [comment]
Hi,

Many Thanks for the suggestion, much appreciated.

I am have changed this

static AzIoTSasToken sasToken(
&client,
AZ_SPAN_FROM_STR(IOT_CONFIG_DEVICE_KEY),
AZ_SPAN_FROM_BUFFER(sas_signature_buffer),
AZ_SPAN_FROM_BUFFER(mqtt_password));

to this..

static AzIoTSasToken sasToken(
&client, 
az_span_create((uint8_t*)iot_device_key,44),
AZ_SPAN_FROM_BUFFER(sas_signature_buffer),
AZ_SPAN_FROM_BUFFER(mqtt_password));

So far I have managed to get this to compile but still fails connection

Will let you know once I am successful

Regards
Paul

**Comment by PDE-Paul** [comment]
I can confirm I have a functional stable connection executing from setting residing in my ESP32 using Preferences settings. 

Thank you for the guidance and suggestion. Much Appreciated.

**Comment by danewalton** [comment]
Awesome glad to hear it @PDE-Paul!
Any hints on what the solution was for others which may be in a similar situation?

**Comment by PDE-Paul** [comment]
Yeah, here is what I did....and the order is critical so be careful where you place each of the lines below

static char iot_device_key[45]; ///(make sure this is the same size as the SharedAccessKey Azure generates)
String KeyStr;

In my setup routine I have...

KeyStr = preferences.getString("AzureSharedAccessKey", "");      ///....I read my SharedAccessKey out of Preferences

strcpy(iot_device_key,KeyStr.c_str());      //// then string copy KeyStr into iot_device_key

the follwing must be between setup() and loop() otherwise Azure connection will fail.

static AzIoTSasToken sasToken(&client, az_span_create((uint8_t*)iot_device_key,44), AZ_SPAN_FROM_BUFFER(sas_signature_buffer), AZ_SPAN_FROM_BUFFER(mqtt_password));

I worked out that the sasToken creates a sort of "place holder" for the SharedAccessKey

To populate AzureSharedAccessKey, I send a command from Azure, then reboot/power cycle/reset and the new settings will be used.

I use a preset Production SharedKey/host/deviceid, that is pushed into the Preferences if it is not setup, then once my product is completely functional and ready to be dispatched or even if it is initially installed, we can change the host the product must connect to remotely


I hope this makes sense, when I get a free moment I will create a simple example, that maybe can be added here for future users to find and use.

Kind Regards
Paul Brink

**Comment by danewalton** [comment]
Awesome thanks for the details Paul. I patched up you comment with some formatting...hope you don't mind. I'll go ahead and close this for now since it seems to be solved. But thank you for the question and hopefully this helps someone else in the future!
