### ISSUE TITLE
Device Twin support in ESP32

### ISSUE THREAD

**Issue by PDE-Paul** [Azure/azure-sdk-for-c#2320]
Hi,

Just a question is Device Twin support possible in the current Azure_SDK_for_C?

If it exists is there an example I can look at as the Arduino Library does not reflect Device Twin usage.

Kind Regards
Paul

**Comment by danewalton** [comment]
Hi @PDE-Paul 
Yes we do. You can find that sample here: https://github.com/Azure/azure-sdk-for-c/blob/main/sdk/samples/iot/paho_iot_hub_twin_sample.c

With the instructions on running that on Linux or Windows here: https://github.com/Azure/azure-sdk-for-c/tree/main/sdk/samples/iot#introduction

**Comment by PDE-Paul** [comment]
Hi,

I am looking for an Arduino ESP32 example. This is not urgent. So you can close this ticket and when I get round to Device Twin implementation I will reach out if I need support.

Much appreciated
Paul
