### ISSUE TITLE
Suppressing messages on Serial URT on ESP32

### ISSUE THREAD

**Issue by PDE-Paul** [Azure/azure-sdk-for-c#2328]
Hi,

My question : Is there a #define that I can comment out to remove all Error messages from being dumped to my ESP32 UART?

I need to use the UART to interface with a Nextion TFT panel and if any error messages from the Azure SDK get dumped to the UART, the Nextion locks up only a power cycle restores communications.

I am using the Arduino IDE

Thanks in advance

Paul

**Comment by danewalton** [comment]
Hi @PDE-Paul 
We don't currently have a macro which would give that behavior. That being said, you can probably try commenting out the sections of our logger which actually output the messages [HERE](https://github.com/Azure/azure-sdk-for-c-arduino/blob/a56c0b58961bba430a204abcd32805778d999d6a/examples/Azure_IoT_Hub_ESP32/SerialLogger.cpp#L51-L53) and [HERE](https://github.com/Azure/azure-sdk-for-c-arduino/blob/a56c0b58961bba430a204abcd32805778d999d6a/examples/Azure_IoT_Hub_ESP32/SerialLogger.cpp#L58-L60). That should turn the logging calls into no-op's.

**Comment by PDE-Paul** [comment]
Hi,

I don't have SerialLogger.h or SerialLogger.cpp included in my sketch. So I doubt it is the cause, The messages looking like this

![Screenshot 2022-09-06 165535](https://user-images.githubusercontent.com/62668857/188681377-5c403d9b-61f0-4d1b-9d3f-239b8aa1ca62.png)

If I cannot get rid of this, how do I disconnect or "turn off" a connected session from the ESP32 side.

Regards
Paul

**Comment by danewalton** [comment]
A lot of those log messages look like they're coming from other libraries which we don't control (ESP TLS and mqtt for example). In order to suppress those, you might have to look at the documentation for them specifically.

**Comment by PDE-Paul** [comment]
Hi,

I have done a quick search and these responses reside in the ESP-IDF API, so will close this question.

Thank you
Paul

**Comment by PDE-Paul** [comment]
Hi,

Found this and now I don't get any error messages

![image](https://user-images.githubusercontent.com/62668857/188867083-d6da04cf-f2d5-4ef3-a724-f203ca184fe2.png)

Just for future reference.

Regards
Paul
