### ISSUE TITLE
Arduino Sdk for Ethernet Shield

### ISSUE THREAD

**Issue by kc00018** [Azure/azure-sdk-for-c#2333]
**Query/Question**
Hi Team, would like to know how i can modify the coding for usage on arduino ethernet shield?

***Why is this not a Bug or a feature Request?***
feature request as arduino shield works almost the same with ESP8266

**Setup (please complete the following information if applicable):**

- IDE: [e.g. IntelliJ]
- Version of the Library used

 **Information Checklist**
 Please make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report

- [-] Query Added
- [ ] Setup information Added

**Comment by danewalton** [comment]
Hi @kc00018 

Here are a couple of examples of MQTT being used with Ethernet:

- https://github.com/256dpi/arduino-mqtt/blob/master/examples/ArduinoEthernetShield/ArduinoEthernetShield.ino
- https://doc.asksensors.com/docs/d/s3/connect-arduino-ethernet-over-mqtt/

You may use those for reference for getting basic MQTT functionality working. After that, you can use the parts from our Arduino sample for IoT Hub specific features. [Here is an example of telemetry.](https://github.com/Azure/azure-sdk-for-c-arduino/blob/a56c0b58961bba430a204abcd32805778d999d6a/examples/Azure_IoT_Hub_ESP32/Azure_IoT_Hub_ESP32.ino#L321-L354)

I hope that helps and I please let us know if you have any other questions.
