### ISSUE TITLE
Allow MQTT over websockets on port 443 for azure-sdk-for-c-arduino client library

### ISSUE THREAD

**Issue by ajanth97** [Azure/azure-sdk-for-c#2360]
Repository : https://github.com/Azure/azure-sdk-for-c-arduino

**Is your feature request related to a problem? Please describe.**
I am building an arduino IOT device using the `azure-sdk-for-c-arduino` client library.  I am currently using the MQTT over port 8883 but as you may know it is currently blocked in many coporate enviroments. 

**Describe the solution you'd like**
Since Azure IOT hub supports MQTT over WebSocket on port 443, it would be great if this library supports it. Since the [azure-sdk-for-c](https://github.com/Azure/azure-sdk-for-c) already supports MQTT over websockets on port 443. It'll be perfect if we could extend this to the arduino library.

**Describe alternatives you've considered**
I have tried using the following library : https://github.com/hideakitai/MQTTPubSubClient which supports MQTT over websockets but I didnt have any luck.

**Additional context**
I am willing to contribute and work on this issue together if someone will be willing to assist me.

**Information Checklist**
Please make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report

- [x] Description Added
- [x] Expected solution specified

**Comment by ajanth97** [comment]
Hi @danewalton Thank you for the response. 
I have two questions :

1. How do I bring this functionality to the [azure-sdk-for-c-arduino](https://github.com/Azure/azure-sdk-for-c-arduino) library ? Or where do I start ?
2. I am currently using the mqtt library https://github.com/knolleary/pubsubclient which was mentioned here : https://github.com/knolleary/pubsubclient . Is using MQTT over websockets a limitation of this library ?

Thank you

**Comment by danewalton** [comment]
1. [The arduino library has the same code here.](https://github.com/Azure/azure-sdk-for-c-arduino/blob/8f8f0353f5cb7e343486be55d650560644c26a02/src/az_iot_hub_client.h#L120-L132)
2. Our library specifically shouldn't be a limitation. [It does look like the PubSub client does not have websocket support.](https://github.com/knolleary/pubsubclient/issues/926) You will have to find another MQTT library which does support it and hook it in.

[Our sample does have a #define to use websockets here](https://github.com/Azure/azure-sdk-for-c/blob/a3c18d3a1d386d14a65ba543e39b5de8a5162f26/sdk/samples/iot/iot_sample_common.c#L62-L69) and feel free to use that as a guide or ask further questions here.
