### ISSUE TITLE
How to get Azure iot central twin properties data at startup of ESP32

### ISSUE THREAD

**Issue by electro89** [Azure/azure-sdk-for-c#2363]
I want to get data from twin at startup of esp32 device from azure IoT central to initialize data . But could not find any example related to this. In the example esp32 chip the variable telemetryFrequencySecs does not get updated from azure IoT central twin property at startup of the device. Is there function to retrieve data from twin property when the user manually wants it ?

**Comment by danewalton** [comment]
Hi @electro89 
This section here in our twin sample should be useful for that scenario:

https://github.com/Azure/azure-sdk-for-c/blob/b9ebeb34fb8395e4e19be21a5428eb5004c9ecff/sdk/samples/iot/paho_iot_hub_twin_sample.c#L252-L282

**Comment by electro89** [comment]
I tried to get twin data but I got an error 

```
[INFO] MQTT client subscribing to '$iothub/twin/PATCH/properties/desired/#'
[INFO] MQTT topic subscribed (message id=8786).
[INFO] MQTT client publishing to '$iothub/twin/GET/?$rid=0'
[INFO] MQTT message received.
[ERROR] azure_iot_mqtt_client_message_received failed (topic=$iothub/twin/res/200/?$rid=0).
```

**Comment by danewalton** [comment]
Hmm that topic that's received says `200` which is a success. Is the error from IoT api's or device/mqtt code?

**Comment by RLeclair** [comment]
Hi @electro89, wanted to check in on the above question.

**Comment by electro89** [comment]
@danewalton Even after using get_device_twin_document function it returned error, finally found out where the problem is, at 
https://github.com/Azure/azure-sdk-for-c-arduino/blob/main/examples/Azure_IoT_Central_ESP32_AzureIoTKit/AzureIoT.cpp#L773
It returns RESULT_ERROR

**Comment by PDE-Paul** [comment]
Hi,

Would it be possible to add a Device Twin example to the ESP32 sdk?

Regards
Paul Brink

**Comment by RLeclair** [comment]
Hi @PDE-Paul at the moment we are not adding a sample for Device Twin on ESP32 but you can take a look at our existing twin [sample](https://github.com/Azure/azure-sdk-for-c/blob/b9ebeb34fb8395e4e19be21a5428eb5004c9ecff/sdk/samples/iot/paho_iot_hub_twin_sample.c#L252-L282).
