### ISSUE TITLE
Binary Size Measurements

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-c#240]
Figure out size of binary as it comes out of the build. Can the binary be deployed in the available space on a given device? 

* Binary size tool 
* Tracking metrics produced by the tool

**Comment by ahsonkhan** [comment]
What's our plan for this Epic? Looks like we have a couple of related issues:
https://github.com/Azure/azure-sdk-for-c/issues/510
https://github.com/Azure/azure-sdk-for-c/issues/241

**Comment by ahsonkhan** [comment]
This would be great to have before we GA.

**Comment by RickWinter** [comment]
@ahsonkhan Can you add the addition items needed to complete pipeline.

**Comment by ahsonkhan** [comment]
> Tracking metrics produced by the tool

https://github.com/Azure/azure-sdk-for-c/issues/1096
