### ISSUE TITLE
ESP32 can not reconnect to Azure Central IoT  successfully  after wifi disconnect and wifi connect

### ISSUE THREAD

**Issue by electro89** [Azure/azure-sdk-for-c#2409]
Recently I have experienced this error with ESP32 Azure Central IoT which can not reconnect successfully  after wifi disconnect and wifi reconnect. This error is even in the official example [Azure_IoT_Central_ESP32 ](https://github.com/Azure/azure-sdk-for-c-arduino/tree/main/examples/Azure_IoT_Central_ESP32) .
In azure Central IoT Raw data shows many connected / disconnected. This happens only after wifi disconnection and reconnection. There are no issues if the wifi is connected always without any disconnection. Are there any backend issues at azure central IoT ?

`2022/11/9 09:22:04 [INFO] MQTT client connecting.
2022/11/9 09:22:07 [INFO] MQTT client connected (session_present=0).
2022/11/9 09:22:07 [INFO] MQTT client subscribing to '$iothub/methods/POST/#'
2022/11/9 09:22:07 [INFO] MQTT topic subscribed (message id=7861).
2022/11/9 09:22:07 [INFO] MQTT client subscribing to '$iothub/twin/res/#'
2022/11/9 09:22:07 [INFO] MQTT topic subscribed (message id=5938).
2022/11/9 09:22:07 [INFO] MQTT client subscribing to '$iothub/twin/PATCH/properties/desired/#'
2022/11/9 09:22:07 [INFO] MQTT topic subscribed (message id=32874).
2022/11/9 09:22:07 [INFO] MQTT client publishing to 'devices/1rj8zd54iz4/messages/events/'
2022/11/9 09:22:17 [INFO] MQTT client publishing to 'devices/1rj8zd54iz4/messages/events/'
2022/11/9 09:22:18 [INFO] MQTT client connecting.
E (63552) MQTT_CLIENT: mqtt_message_receive: transport_read() error: errno=128
2022/11/9 09:22:20 [ERROR] MQTT client in ERROR state.
2022/11/92022/11/9 09:22:20 [INFO]  09:22:20 [ERROR] esp_tls_stack_err=0; esp_tls_cert_verify_flags=0;esp_transport_sock_errno=0;error_type=1;connect_return_code=0
2022MQTT client connected (session_present=0).
2022/11/9 09:22:20 [ERROR] /Unexpected mqtt client connection (17).
2022/11/119/9  0099::22:21 [ERROR] azure_iot_mqtt_client_connected failed.
22:20 [ERROR] connect_return_code=MQTT_CONNECTION_ACCEPTED
E (63598) MQTT_CLIENT: mqtt_process_receive: mqtt_message_receive() returned -1
2022/11/9 09:22:21 [ERROR] Azure IoT client is in error state.
2022/11/9 09:22:21 [INFO] MQTT client disconnected.

2022/11/9 09:22:21 [INFO] MQTT client being disconnected.
2022/11/9 09:22:26 [INFO] Connecting to WIFI wifi_ssid IoT1
E (68619) TRANSPORT_BASE: poll_read select error 113, errno = Software caused connection abort, fd = 49
E (68621) MQTT_CLIENT: Poll read error: 119, aborting connection
2022/11/9 09:22:26 [INFO] MQTT client disconnected.
`

**Comment by electro89** [comment]
Any update on this?
@danewalton

**Comment by danewalton** [comment]
Hi @electro89 
Can you try this PR from @rmadurawe13 and see if it helps resolve your issue?
https://github.com/Azure/azure-sdk-for-c-arduino/pull/43

**Comment by electro89** [comment]
Yes it resolved the problem @danewalton  @rmadurawe13. Now I can turn on/off the wifi and can successfully reconnect to azure central.

**Comment by rmadurawe13** [comment]
Glad to hear it, @electro89 @danewalton! I am working on an ESP32 project myself where I am connecting to Azure Central, and if I run into any more bugs, I will continue to upload any and all fixes I do here.
