### ISSUE TITLE
Output map files from build

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-c#241]
Get map files from each build to begin investigating binary size

**Comment by danieljurek** [comment]
Also: https://interrupt.memfault.com/blog/code-size-deltas

**Comment by danieljurek** [comment]
From discussion last week 

* The size of the map file itself is not a strong indicator of the binary size
* Map files need an executable (e.g. a sample) to be produced because there needs to be enough information for linking to take place. In that case you'll see a map file per build. 
  * The IoT team is especially interested in binary size attributable to the SDK for samples that use the JSON parser
* Map file formats vary based on the build tools being used
* Some build tools like IAR output an easy to read summary at the end of the map file

**Comment by ahsonkhan** [comment]
Duplicate of https://github.com/Azure/azure-sdk-for-c/issues/240
