### ISSUE TITLE
[FEATURE REQ] Source cleanup

### ISSUE THREAD

**Issue by gilbertw** [Azure/azure-sdk-for-c#243]
Restructure the source into better directory structure

## Jeff List:
(moved to one note for easier edition)
https://microsoft.sharepoint.com/teams/AzureDeveloperExperience/_layouts/15/Doc.aspx?sourcedoc={6b458ae7-5852-4e5e-a0af-0cb93979ceef}&action=edit&wd=target%28Jeff%20refactoring%20list.one%7C%2FJeff%27s%20refactoring%20list%7C12b053b7-1ceb-41c6-a708-d69415096325%2F%29

**Comment by vhvb1989** [comment]
Rick, I think we can close this one.
@JeffreyRichter  have went all thru the code headers and we have merged all of his request by now.
