### ISSUE TITLE
Please include cellular support for the SDK. It works well with wifi and searches for the ntp server over cellular without any result. 

### ISSUE THREAD

**Issue by alfanumero** [Azure/azure-sdk-for-c#2433]
I have tried the fixes discussed here in vain.
 https://github.com/Azure/azure-iot-sdk-c/issues/1914

**Comment by CIPop** [comment]
@alfanumero please see https://github.com/Azure/embedded-wireless-framework :

> The Embedded Wireless Framework simplifies the development of internet and cloud connectivity for embedded device software by defining a set of APIs for network adapters, host interfaces, platforms, and software stacks. The goal is to provide a standard framework for writing applications and controlling wireless network adapters (cellular, Wi-Fi, LoRa...) while abstracting a driver interface for hardware vendors to plug in modules with self-developed drivers.

For example, IoT Hub Telemetry in conjunction with the EWF: https://github.com/Azure/embedded-wireless-framework/blob/main/src/examples/ewf_example_telemetry_basic.c
