### ISSUE TITLE
MQTT-Connection failed when the telemetry_payload size is too high

### ISSUE THREAD

**Issue by Omikron90** [Azure/azure-sdk-for-c#2445]
**Query/Question**
How can I send larger messages that have at least one telemetry_payload[4048] ?

***Why is this not a Bug or a feature Request?***
I have included the sample code "Azure_IoT_Hub_ESP8266" in my environment to send a bunch of second-by-second measurements in a message via IoT Hub every minute. 

However, I can only send readings of 5 seconds instead of the targeted 60 seconds in a message "az_span". When I set the telemetry_payload[2000], the code compiles but the MQTT connection fails.
"MQTT connecting ... failed, status code =-2. Trying again in 5 seconds."

There is no error message when compiling. Sufficient memory should also be available:
"The sketch uses 452625 bytes (47%) of program memory. The maximum is 958448 bytes.
Global variables use 42420 bytes (51%) of dynamic memory, leaving 39500 bytes for local variables."

If I set the value to telemetry_payload[1000], the code works. Also if I set the global variable for the definition of the measurement buffer too large, the same problems occur. 

Unfortunately, I don't know how to deal with this error, since I can't classify it.

**Setup (please complete the following information if applicable):**
- OS: ESPRESSIF ESP8266
- IDE: Arduino IDE v1.8.19
- Version of the Library used: v1.1.2

 **Information Checklist**
All information should be available.

- [x ] Query Added
- [ x] Setup information Added

**Comment by danewalton** [comment]
Hi @Omikron90 
You might be hitting throttling issues:
https://azure.microsoft.com/en-us/pricing/details/iot-hub/
https://learn.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-quotas-throttling#quotas-and-throttling

What size hub are you using?

**Comment by Omikron90** [comment]
Hi @danewalton 
Thank you for your quick reply. 
I took a look at the two sites, but I don't think there are trotteling problems. I have a S1 tier and about 10 active devices that are not getting to the limits of data/minute or other limitations. 

I have tried some more and think it is the dynmic memory that is failing, not understanding why. If I take the isolated example code for the ESP8266 and set the telemetry_payload to [10000], I have the same error pattern as in my code. However, in my case the limit is already reached at [2000]. 
The ESP8266 has the following memory specifications, that should be sufficient for the payload according to my estimations:
    32 KiB instruction RAM
    32 KiB instruction cache RAM
    80 KiB user-data RAM
    16 KiB ETS system-data RAM
Maybe you have an idea how I can work around this problem?

Thanks a lot

**Comment by danewalton** [comment]
I'm not quite sure why the connection itself would fail if the buffer for the telemetry is being modified. They're theoretically unrelated.

Does the initial connection fail to the IoT Hub? Or does the connection initially work but then disconnects once you send telemetry?

**Comment by Omikron90** [comment]
The initial connection to the IoT Hub fails. I have attached the message in the first post. 

I tried it with the ESP32, here the telemetry_payload can be set much higher without system crashing. I used the example for the ESP32 for this. 
So maybe it is a problem with the heap space, so the stack is crashing. But this is currently just a guess.

**Comment by Omikron90** [comment]
Hi @vaavva, thank you very much for the support. I have been sitting on my code for some time trying to reduce the heap. But unfortunately I could not get enough heap space free to make the application run continuously. Finally I switched to the ESP32 to avoid these problems also for later extensions of the code.
