### ISSUE TITLE
8622MOD cannot connect to azure central 

### ISSUE THREAD

**Issue by SH2015** [Azure/azure-sdk-for-c#2481]
**Describe the bug**
After successfully connecting we get a stack error , and we lose the connection 
***Exception or Stack Trace***
Add the exception log and stack trace if available
01:30:04.896 -> 3fffff00:  3fff10dc 00000000 00000020 3fffff20  
01:30:04.961 -> 3fffff10:  00000000 00000000 00000001 40100154  
01:30:05.024 -> 3fffff20:  00b944ea 3ffefb18 3ffefa7c 3ffefabc  
01:30:05.057 -> 3fffff30:  00000120 00000000 3ffef9c8 40204014  
01:30:05.121 -> 3fffff40:  3fffdad0 00000000 3ffef9c8 402019e1  
01:30:05.152 -> 3fffff50:  6554227b 7265706d 72757461 203a2265  
01:30:05.249 -> 3fffff60:  30302e30 30303030 7548222c 6964696d  
01:30:05.281 -> 3fffff70:  3a227974 33343131 35333536 37373931  
01:30:05.313 -> 3fffff80:  30333139 30343831 32363932 00003935  
01:30:05.376 -> 3fffff90:  3fffdad0 00000000 3ffefa7c 40100175  
01:30:05.441 -> 3fffffa0:  3fffdad0 00000000 3ffefa7c 40209df4  
01:30:05.472 -> 3fffffb0:  feefeffe feefeffe 3ffe84f8 40100c89  
01:30:05.537 -> <<<stack<<<
01:30:05.537 -> 
01:30:05.537 -> --------------- CUT HERE FOR EXCEPTION DECODER ---------------
01:30:05.645 -> �.��9��  - Connecting to WiFi..
01:30:06.239 ->   - - iotc.dps : getting auth...
01:30:07.203 ->   - - iotc.dps : getting operation id...
01:30:15.313 ->   - - iotc.dps : getting host name...
**To Reproduce**

***Code Snippet***
Add the code snippet that causes the issue.
```
// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full
// license information.

#include <ESP8266WiFi.h>
#include "src/iotc/common/string_buffer.h"
#include "src/iotc/iotc.h"
 #include "commonstruct.h"
 


#define WIFI_SSID "skynet"
#define WIFI_PASSWORD "19d19d19d1"

const char* SCOPE_ID = "xxxxxx";
const char* DEVICE_ID = "xxxxxx";
const char* DEVICE_KEY = "xxxxxxxx";
dhInfo getTemperature () ; 


void on_event(IOTContext ctx, IOTCallbackInfo* callbackInfo);
#include "src/connection.h"

void on_event(IOTContext ctx, IOTCallbackInfo* callbackInfo) {
  // ConnectionStatus
  if (strcmp(callbackInfo->eventName, "ConnectionStatus") == 0) {
    LOG_VERBOSE("Is connected ? %s (%d)",
                callbackInfo->statusCode == IOTC_CONNECTION_OK ? "YES" : "NO",
                callbackInfo->statusCode);
    isConnected = callbackInfo->statusCode == IOTC_CONNECTION_OK;
     yield();
delay (2000);
    return;
  }

  // payload buffer doesn't have a null ending.
  // add null ending in another buffer before print
  AzureIOT::StringBuffer buffer;
  if (callbackInfo->payloadLength > 0) {
    buffer.initialize(callbackInfo->payload, callbackInfo->payloadLength);
  }

  LOG_VERBOSE("- [%s] event was received. Payload => %s\n",
              callbackInfo->eventName, buffer.getLength() ? *buffer : "EMPTY");

  if (strcmp(callbackInfo->eventName, "Command") == 0) {
    LOG_VERBOSE("- Command name was => %s\r\n", callbackInfo->tag);
  }
   yield();
delay (2000);
}

void setup() {
  Serial.begin(9600);

  connect_wifi(WIFI_SSID, WIFI_PASSWORD);
  connect_client(SCOPE_ID, DEVICE_ID, DEVICE_KEY);

  if (context != NULL) {
    lastTick = 20000;  // set timer in the past to enable first telemetry a.s.a.p
  }
   
}

void loop() {
   yield();
float h = 5;
float t = 6 ;

  
  if (isConnected) {

    unsigned long ms = millis();
    if (ms - lastTick > 20000) {  // send telemetry every 10 seconds
      char msg[64] = {0};
      int pos = 0, errorCode = 0;

      lastTick = ms;
      if (loopId++ % 2 == 0) {  // send telemetry
            dhInfo info ; 
  //info =  getTemperature();
        pos = snprintf(msg, sizeof(msg) - 1, "{\"Temperature\": %f,\"Humidity\":%f}",
                      info.temperature, info.humidity);
        errorCode = iotc_send_telemetry(context, msg, pos);
        
        // pos = snprintf(msg, sizeof(msg) - 1, "{}",
        //                h);
        // errorCode = iotc_send_telemetry(context, msg, pos);
          
      } else {  // send property
        
      } 
  
      msg[pos] = 0;

      if (errorCode != 0) {
        LOG_ERROR("Sending message has failed with error code %d", errorCode);
      }
    }

    iotc_do_work(context);  // do background work for iotc
  } else {
    iotc_free_context(context);
    context = NULL;
    delay (2000);
    connect_client(SCOPE_ID, DEVICE_ID, DEVICE_KEY);
  }
   yield();
delay (2000);

}

```
**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**

- IDE: [e.g. IntelliJ]
- Version of the Library used

**Additional context**
using code snippets here : 
https://github.com/Azure/iot-central-firmware/blob/master/ESP8266/ESP8266.ino
**Information Checklist**
Please make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report

- [ X] Bug Description Added
- [ ] Repro Steps Added
- [X ] Setup information Added

**Comment by SH2015** [comment]
@danewalton  I am looking for code that connects ESP8266 to IoT Central, not to IoT hub, I am already able to connect to IoT hub , but there is no example code to connect to IOT central , if you can provide me any example that would be good.

**Comment by danewalton** [comment]
The link which you gave to the `Azure/iot-central-firmware` repo is not our repository and its last update was over two years ago. They were using code which isn't here in ours.

As for the Central example, we do have one for the ESP32 which you may use as a baseline for Central connection and interaction here: https://github.com/Azure/azure-sdk-for-c-arduino/tree/main/examples/Azure_IoT_Central_ESP32

**Comment by SH2015** [comment]
ESP32 example doesn't work with ESP8622. 
Anyway, I got a third-party code that could connect ESP8622 to IoT central, but it doesn't send proper payloads, I have to do aliases to get the data presented right.

**Comment by danewalton** [comment]
I understand that the sample itself won't run, but components from that can be used in the ESP8266 sample to create a central sample. Payloads which are generated, connection info created, etc. The underlying hardware and maybe networking could have to change, but the guts of the sample are there.
