### ISSUE TITLE
Since Wifi connected until messages be sent to Azure, too much error messages occurs on serial Debug

### ISSUE THREAD

**Issue by mayconmk81** [Azure/azure-sdk-for-c#2523]
I'm new on Azure SDK for C, after setting the Azure IoT Central correctly as well as  burning the flash code into the ESP32 WROOM Dev kit board accordind the microsoft Deep Dive video [(https://youtu.be/MLsnNXhzc2k).](https://youtu.be/MLsnNXhzc2k)

I see that it works correctly only after some minutes, but until there, on Serial Debug I can see a lot os ERRORs messages, but I coult not understand exactly what's going on during conection process to make these erros happen.

Can you help me to undestand and how to fix it?

Attached follow the erros messages that I got.

[20230310Log.txt](https://github.com/Azure/azure-sdk-for-c/files/10942645/20230310Log.txt)

**Comment by electro89** [comment]
@mayconmk81 check this out https://github.com/Azure/azure-sdk-for-c-arduino/pull/44 

This resolves wifi connection issue and continuous error output.

**Comment by mayconmk81** [comment]
Thank you @electro89 those comments were really valuable.

**Comment by mayconmk81** [comment]
Thank you @
