### ISSUE TITLE
Base64 encoding question

### ISSUE THREAD

**Issue by lafrank** [Azure/azure-sdk-for-c#2530]
This question is about MQQT event payload getting Base64 encoded somewhere by some code, and I am unable to figure out where..

I have posted a detailed question [here  ](https://learn.microsoft.com/en-us/answers/questions/1190723/how-to-get-rid-of-base64-encoding-on-event-body) about the issue I am experiencing, and already uncertain which component to search for the solution.
I's appreciate if someone could point ion the right direction.

- OS: N/A
- IDE: Arduino IDE 2.0
- Version of the Library used : c/1.5.0-beta.1(ard;esp8266)

**Comment by LeelaRajesh-Sayana** [comment]
Hello @lafrank Greetings! I have posted a response on the [Q&A thread](https://learn.microsoft.com/en-us/answers/questions/1190723/how-to-get-rid-of-base64-encoding-on-event-body) which addresses this issue. Can you review that and let me know if that helps?

Best Regards,
Leela.
