### ISSUE TITLE
Clang error: cast from 'const char *' to 'unsigned char *' drops const qualifier [-Werror,-Wcast-qual]

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-c#255]
```
/Users/runner/runners/2.160.1/work/1/s/sdk/core/core/inc/az_span.h:135:41: error: cast from 'const char *' to 'unsigned char *' drops const qualifier [-Werror,-Wcast-qual]
  return (az_span){ .begin = (uint8_t *)str, .size = strlen(str) };
```

Seen in: https://dev.azure.com/azure-sdk/public/_build/results?buildId=206799&view=logs&j=342c2766-5117-5186-106a-cc400cfb2aeb&t=9c076d15-12a2-545b-25fc-06b5663b034a

Docs: https://clang.llvm.org/docs/DiagnosticsReference.html#wcast-qual

**Comment by vhvb1989** [comment]
https://github.com/Azure/azure-sdk-for-c/pull/252

**Comment by danieljurek** [comment]
Closing, these errors don't appear in the current build log.
