### ISSUE TITLE
What MQTT library is being used in the paho iot hub twin device sample

### ISSUE THREAD

**Issue by OhmV-IR** [Azure/azure-sdk-for-c#2570]
I am trying to integrate twin device properties into my device code but I have found that this sample uses a different MQTT library and I couldn't find the file in the repo. I am using platformIO and vscode and was wondering where I could find the .h file to import into my project. 
(https://github.com/Azure/azure-sdk-for-c/blob/main/sdk/samples/iot/paho_iot_hub_twin_sample.c)

**Comment by RLeclair** [comment]
Hi @boura0013, this sample uses the [paho mqtt library](https://github.com/eclipse/paho.mqtt.c) which is obtained via `vcpkg`. You can take a look at our sample instructions to see how we do it: https://github.com/Azure/azure-sdk-for-c/tree/main/sdk/samples/iot.

**Comment by RLeclair** [comment]
Hi @OhmV-IR, closing this issue because it has been 3 weeks since the last response.
