### ISSUE TITLE
ESP32 DigiCert Global G2 migration

### ISSUE THREAD

**Issue by PDE-Paul** [Azure/azure-sdk-for-c#2579]
Hi All,

Does the current ESP32 SDK release 1.1.3 cover the DigiCert Global G2 migration?

I received notification from Microsoft this morning they will migrate all my Azure IoT Hub's to DigiCert Global G2 on the 13th of June, I am concerned about the Azure Clients I have already deployed in the field.

Please advice what I need to implement prior to this migration happening.

Regards
Paul Brink

**Comment by ericwol-msft** [comment]
On azure-sdk-for-c-arduino, there is a file in the azure-sdk-for-c Arduino library (not the samples, the product code), called azure_ca.h https://github.com/Azure/azure-sdk-for-c-arduino/blob/main/src/azure_ca.h

It contains the CA certs for Azure IoT. The vars defined in that header must be set in the tls stack of each sample (or the MQTT clients).

E.g., https://github.com/Azure/azure-sdk-for-c-arduino/blob/main/examples/Azure_IoT_Hub_ESP32/Azure_IoT_Hub_ESP32.ino#L272


For the freertos middleware ESP32 sample there is a function that must be called to set the root CA cert. 

https://github.com/Azure-Samples/iot-middleware-freertos-samples/blob/main/demos/projects/ESPRESSIF/esp32/components/sample-azure-iot/transport_tls_esp32.c#L303

iot-middleware-freertos-samples/transport_tls_esp32.c at main · Azure-Samples/iot-middleware-freertos-samples

This repo has samples for dev kits using the Azure IoT middleware for FreeRTOS - iot-middleware-freertos-samples/transport_tls_esp32.c at main · Azure-Samples/iot-middleware-freertos-samples

You can test the new CA on your hub by using the certificates tab of your hub in the Azure portal. This will allow you to switch between the two CA to test out your devices.

![image](https://github.com/Azure/azure-sdk-for-c/assets/37418465/fb5ec72e-49c8-4fde-8bee-0d477dd9b457)
