### ISSUE TITLE
Send json via ESP32

### ISSUE THREAD

**Issue by kmw0044** [Azure/azure-sdk-for-c#2582]
**Query/Question**
I would like to send a json with the Azure Hub ESP32 SDK, but I can't find the right solution to modifiying the getTelemetry method.

***Why is this not a Bug or a feature Request?***
No new feature and otherwise the sdk works

**Setup (please complete the following information if applicable):**

- OS: Windows
- IDE: Arduino 1.8
- Version of the Library used 1.1.4

 **Information Checklist**
 Please make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report

the data gets send to the hub but when I track it with the Device Explorer Twin i dont get a json but this:
![Screenshot 2023-06-02 181757](https://github.com/Azure/azure-sdk-for-c/assets/133108776/9716c524-b1b0-4d3e-9663-34a423730710)

My method looks like this:
![Screenshot 2023-06-02 182254](https://github.com/Azure/azure-sdk-for-c/assets/133108776/40975227-359a-44aa-961f-d70bd764c157)

temperature, moisture and uv are gloabl float variables

- [ ] Query Added
- [ ] Setup information Added

**Comment by ericwol-msft** [comment]
Telemetry data is not twin data. You can view telemetry data in the [IoT explorer](https://learn.microsoft.com/en-us/azure/iot/howto-use-iot-explorer) on the telemetry tab.

![image](https://github.com/Azure/azure-sdk-for-c/assets/37418465/7697f257-753a-49d3-b830-f6e6e11784d0)

**Comment by kmw0044** [comment]
Hi so I got it to send the json correctly, but now I have the issue that i want to send seperate messages, so for each sensor I need a seperate getTelemtryPayload. How can I integrate taht with sendTelemetry? And do I need seperate arrays for the telemtry payload?

**Comment by vaavva** [comment]
Hello @kmw0044! You could create multiple methods, like getTemperatureTelemetryPayload and getHumidityTelemetryPayload, and then have multiple get_publish_topics and publishes 
```
if (az_result_failed(az_iot_hub_client_telemetry_get_publish_topic(
          &client, NULL, telemetry_topic, sizeof(telemetry_topic), NULL)))
  {
    Serial.println("Failed az_iot_hub_client_telemetry_get_publish_topic");
    return;
  }
mqtt_client.publish(telemetry_topic, getTelemetryPayload(), false);
```
within sendTelemetry to send them as separate messages (or you could break that into multiple methods as well if you don't necessarily want them sending at the same time)

Let me know if this helps, or if you have further questions

**Comment by kmw0044** [comment]
Hi, already got it figured out, but thank you for your suggestions :)
