### ISSUE TITLE
Azure.Core: XML [de]serializer 

### ISSUE THREAD

**Issue by sergey-shandar** [Azure/azure-sdk-for-c#26]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Description Added
- [ ] Expected solution specified

**Comment by gilbertw** [comment]
The embedded C SDK has no current plans for adding XML helpers, #55.

See the C++ SDK for XML support https://github.com/Azure/azure-sdk-for-cpp
