### ISSUE TITLE
Direct Method Example to be added on arduino

### ISSUE THREAD

**Issue by ghostidentity** [Azure/azure-sdk-for-c#2601]
Can you add direct method example on arduino ? it seems missing. Trying to figure out how to properly call the method is inconvenient.
If the user navigate to esp-azure, to locate the existing sample, its missing header files so its no use.

![image](https://github.com/Azure/azure-sdk-for-c/assets/4637625/4f8a6016-484d-4147-aae8-2703292621b1)

**Comment by vaavva** [comment]
Hello @ghostidentity! The IoT Central examples in the Arduino repo have support for direct methods (commands)
[Information](https://github.com/Azure/azure-sdk-for-c-arduino/blob/aefe104380748c04387b041a6f94c59c44456cb8/examples/Azure_IoT_Central_ESP32/readme.md#send-a-command-on-the-device)
[Code reference](https://github.com/Azure/azure-sdk-for-c-arduino/blob/aefe104380748c04387b041a6f94c59c44456cb8/examples/Azure_IoT_Central_ESP32/Azure_IoT_Central_ESP32.ino#L331)

Let me know if this is enough information for you to get started!

**Comment by ghostidentity** [comment]
> Hello @ghostidentity! The IoT Central examples in the Arduino repo have support for direct methods (commands) [Information](https://github.com/Azure/azure-sdk-for-c-arduino/blob/aefe104380748c04387b041a6f94c59c44456cb8/examples/Azure_IoT_Central_ESP32/readme.md#send-a-command-on-the-device) [Code reference](https://github.com/Azure/azure-sdk-for-c-arduino/blob/aefe104380748c04387b041a6f94c59c44456cb8/examples/Azure_IoT_Central_ESP32/Azure_IoT_Central_ESP32.ino#L331)
> 
> Let me know if this is enough information for you to get started!

Hello, vaava thanks for responding. But I do believe that, since Azure Iot Hub supports capability to issue direct method call to IoT Device, then there's no need to use IoT central service ?  So seems like Azure IoT hub  example on arduino is incomplete ?  I'm expecting a keyword of: AZ_IOT_HUB_CLIENT_METHODS_SUBSCRIBE_TOPIC but it does not exist;

**Comment by vaavva** [comment]
@ghostidentity Yes - this can be used without IoT Central. It's not shown in the Hub Sample, but you can run the IoT Central Sample with DPS credentials that point to your hub, or use the direct method implementation from the IoT Central sample in the Hub sample:
https://github.com/Azure/azure-sdk-for-c-arduino/blob/main/examples/Azure_IoT_Central_ESP32/Azure_IoT_Central_ESP32.ino#L587
https://github.com/Azure/azure-sdk-for-c-arduino/blob/main/examples/Azure_IoT_Hub_ESP32/Azure_IoT_Hub_ESP32.ino#L179

We also have a generic example for direct methods in this repo that you can use as a baseline for arduino: https://github.com/Azure/azure-sdk-for-c/blob/main/sdk/samples/iot/paho_iot_hub_methods_sample.c

**Comment by ghostidentity** [comment]
Hello vaaka, I simply want an easy approach where I can download the zip file w/ all relevant dependency so I can test it on esp32 since it's not available on arduino example library yet.  I checked the generic link that you mentioned but it's missing library, I'm not sure where to find it.
![image](https://github.com/Azure/azure-sdk-for-c/assets/4637625/e6639912-0d3b-4aef-93f0-28da6e0719b9)

On azure IoT hub example, its using this dependency: <mqtt_client.h> but on the generic one it referencing to #include <MQTTClient.h>. 

Other dependency error also appear which Im not sure where to find 
![image](https://github.com/Azure/azure-sdk-for-c/assets/4637625/64e6ecd7-8cd3-4a19-a89b-28e6b06ebff7)

Can I ask what expected timeframe that other example like direct method call will be available on arduino ? 

Thanks

**Comment by vaavva** [comment]
Hello @ghostidentity ! A few out-of-the-box options: we do have this functionality in the Central Arduino sample. Despite the name, it's not locked into IoT Central only, and you can put credentials from DPS instead of from Central in this sample: https://github.com/Azure/azure-sdk-for-c-arduino/blob/main/examples/Azure_IoT_Central_ESP32/iot_configs.h#L56-L60

Some more details on this from the readme:
> What is the difference between IoT Hub and IoT Central samples?

> IoT Hub samples will get devices connected directly to [Azure IoT Hub](https://docs.microsoft.com/azure/iot-hub/iot-concepts-and-iot-hub)
IoT Central samples will leverage DPS ([Device Provisioning Service](https://docs.microsoft.com/azure/iot-dps/about-iot-dps)) to provision the device and then connect it to [Azure IoT Central](https://docs.microsoft.com/azure/iot-central/core/overview-iot-central).
> Please note that provisioning through DPS is mandatory for IoT Central scenarios, but DPS can also be used for IoT Hub devices as well.

Another option if you aren't tied to Arduino is to use our ESP32 sample for FreeRTOS that has support for direct methods: https://github.com/Azure-Samples/iot-middleware-freertos-samples/tree/main/demos/projects/ESPRESSIF/esp32
This readme also has more details on how to set up/get DPS values that are linked to your IoT Hub if you use the Arduino sample.

**Comment by vaavva** [comment]
To answer your other question about porting the paho direct method sample to arduino: The arduino samples use the esp_mqtt_client, whereas the paho one uses the paho MQTT client, so there will be some changes needed for the mqtt client functions. Here is a generic mqtt client agnostic description of how to use the embedded c sdk patterns: https://github.com/Azure/azure-sdk-for-c/blob/main/sdk/docs/iot/coding_patterns.md

**Comment by ghostidentity** [comment]
Thanks Vaava, I was expecting easy test but will look into existing documentations to figure it out.

**Comment by ghostidentity** [comment]
To provide some information to those who are facing similar issue, here's the screenshot of successful direct method call. 
![image](https://github.com/Azure/azure-sdk-for-c/assets/4637625/edd299d7-9323-4978-819d-93551b1fdf37)
