### ISSUE TITLE
Telemetry Payload question, azure-sdk-for-c-arduino, ESP32

### ISSUE THREAD

**Issue by MIKHANYA** [Azure/azure-sdk-for-c#2611]
**Query/Question** Difficulty with **Telemetry Payload Generation**
A clear explanation of why is this not a bug or a feature request?
I really can't figure out if it's a bug or me the standard example doesn't send the useful payload at all
**Setup :**
- OS: [Windows 10]
- IDE: [Arduino]
- LAST stable

Hi, I using this sample code https://github.com/Azure/azure-sdk-for-c-arduino/blob/main/examples/Azure_IoT_Hub_ESP32/readme.md. I'm having difficulty with **Telemetry Payload Generation**. Can you give me your thoughts on what I might be doing wrong? Or how to correctly put useful information in this code. I filled in all the required data in `iot_configs.h` but in my Telemetry storage file on Azure cloud, there is no Payload line, which is in the code, but system messages come. Here is a piece of code from an example `Azure_IoT_Hub_ESP32.cpp`, which in my opinion should be sent as telemetry to the server:

```
static void generateTelemetryPayload()
{
  // You can generate the JSON using any lib you want. Here we're showing how to do it manually, for simplicity.
  // This sample shows how to generate the payload using a syntax closer to regular delevelopment for Arduino, with
  // String type instead of az_span as it might be done in other samples. Using az_span has the advantage of reusing the 
  // same char buffer instead of dynamically allocating memory each time, as it is done by using the String type below.
  telemetry_payload = "{ \"msgCount\": " + String(telemetry_send_count++) + " }";
}
```
look forward to your reply

**Comment by vaavva** [comment]
Hello @MIKHANYA!
I ran a quick test of this sample, and I'm seeing the payload coming through in the portal when I run this command:
`az iot hub monitor-events --login <your Azure IoT Hub owner connection string in quotes> --device-id <your device id>`
```
Starting event monitor, filtering on device: esp-32, use ctrl-c to stop...
{
    "event": {
        "origin": "esp-32",
        "module": "",
        "interface": "",
        "component": "",
        "payload": "{ \"msgCount\": 50 }"
    }
}
```
Can you send what output you're getting instead? Both from the portal, and the device logs to make sure telemetry is being sent as well.

**Comment by MIKHANYA** [comment]
> 

Hello @vaavva 
First, I do not understand what should be in the quotes: `<your Azure IoT Hub owner connection string in quotes>` in
`az iot hub monitor-events --login <your Azure IoT Hub owner connection string in quotes> --device-id <your device id>`
![image](https://github.com/Azure/azure-sdk-for-c/assets/86317728/66d75fc1-0728-4008-9b6d-96502fcd8525)
As you can see, no data is coming to the console. Also, I used Azure IoT Explorer, but no data in telemetry console.
The only place i could see the telemetry is in the storage.
![image](https://github.com/Azure/azure-sdk-for-c/assets/86317728/8c8acfc2-7bef-467f-a7c8-abf800a23aa3)
one of the telemetry  storage lines:
`{"EnqueuedTimeUtc":"2023-07-25T11:49:13.2220000Z","Properties":{},"SystemProperties":{"connectionDeviceId":"dev1","connectionAuthMethod":"{\"scope\":\"device\",\"type\":\"sas\",\"issuer\":\"iothub\",\"acceptingIpFilterRule\":null}","connectionDeviceGenerationId":"63824********75987","enqueuedTime":"2023-07-25T11:49:13.2220000Z"},"Body":"eyAib*********************=="}`

I am also discussing this issue on: [stackoverflow](https://stackoverflow.com/questions/76687945/cant-see-telemetry-data-from-devices-in-azure-esp32-azure-sdk-for-c-arduino)

**Comment by vaavva** [comment]
@MIKHANYA You can get the iot hub owner connector string with these instructions: 
> Monitor the telemetry messages sent to the Azure IoT Hub using the connection string for the policy name iothubowner found under "Shared access policies" on your IoT Hub in the Azure portal.

**Comment by vaavva** [comment]
Also, is this the tutorial you followed to set up telemetry routing to storage?
https://learn.microsoft.com/en-us/azure/iot-hub/tutorial-routing?tabs=portal

**Comment by MIKHANYA** [comment]
> Also, is this the tutorial you followed to set up telemetry routing to storage? https://learn.microsoft.com/en-us/azure/iot-hub/tutorial-routing?tabs=portal

not exactly like in the guide in this paragraph
https://learn.microsoft.com/en-us/azure/iot-hub/tutorial-routing?tabs=portal#route-to-a-storage-account
![image](https://github.com/Azure/azure-sdk-for-c/assets/86317728/78588243-ec88-4b6c-9125-24a52410bed0)
and the rest, yes, according to the guide

**Comment by MIKHANYA** [comment]
@vaavva Thank You, you saved me. THANK YOU FOR DOING SO MUCH and solve my problem. 
and I have a question. Is it possible to write something in **Routing query** so that all messages come to the storage and to the console, but without modifying the code on the device, for testing, not for continuous monitoring ?

**Comment by vaavva** [comment]
@MIKHANYA Yes, you can add another route (with the same query, such as 'true') to the built-in endpoint to have the messages still show up in the console in addition to storage!
![image](https://github.com/Azure/azure-sdk-for-c/assets/54871851/72bcc9d4-e4e8-42b5-aa2c-9a7a7a150a6e)

Closing this issue for now as it sounds like your problem is resolved, but feel free to re-open it if you have additional questions.
