### ISSUE TITLE
ublox SARA R500S and ESP32

### ISSUE THREAD

**Issue by leonardojc** [Azure/azure-sdk-for-c#2640]
Is there any information or example on how to implement the AZURE-SDK on an ESP32 with a SARA-R500S module connected to it and use the LTE network to connect to an AZURE DPS?
thank you so much

**Comment by RLeclair** [comment]
Hi @leonardojc we have samples for provisioning with ESP32 here: https://github.com/Azure/azure-sdk-for-c-arduino/tree/main/examples/Azure_IoT_Central_ESP32

We don't have a specific sample for connecting via an LTE network, only Wi-Fi but you can modify our sample to connect using your LTE module.

**Comment by RLeclair** [comment]
Hi @leonardojc no response for the last 3 weeks so closing for now. Please feel free to re-open the issue if needed.
