### ISSUE TITLE
message properties

### ISSUE THREAD

**Issue by mZoda** [Azure/azure-sdk-for-c#2648]
**Query/Question**
How can i put a message properties to the message

***Why is this not a Bug or a feature Request?***
I can't find any information about this

**Setup (please complete the following information if applicable):**

- OS: Arduino
- IDE: Arduino
- Latest from git

 **Information Checklist**
 Please make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report

- [ ] Query Added
- [ ] Setup information Added

**Comment by RLeclair** [comment]
Hi @mZoda, could you please elaborate more? What message are you attempting to add properties to?

**Comment by mZoda** [comment]
Hi thx for respond :) , yea i realize it was not complete :(.

Well i'm trying to use a ESP8266 for sending data to Azure IoT hub, and installed the "Azure Embedded SDK for C" from git.
And in the example there is a static message created , sending to IoT hub, its working. :) And then i need to add a message property, to be used for routing in the IoT hub. And thats my first problem, how do i add it in the "C" environment (i'm in the C#  field, and there i know how to do it...). Second problem is the "LITERAL_STRING" thing, how can i get the 
"temp_span = az_span_copy(temp_span, AZ_SPAN_FROM_STR(" some text "));" to accept a String/charArray as parameter.

Mikael

**Comment by RLeclair** [comment]
Are you referring to this sample? https://github.com/Azure/azure-sdk-for-c-arduino/blob/main/examples/Azure_IoT_Hub_ESP8266/Azure_IoT_Hub_ESP8266.ino

In line 331, we publish to IoT Hub, is that where your first problem is? If you would like to add to the message, you can modify the size of `telemetry_payload` to account for enough space for your property. Then use `az_span_copy` to copy your property to the message.

`AZ_SPAN_FROM_STR` does not take in a C++ String Object but a constant char pointer (a C string). Of what type is your `Temperature` variable?

**Comment by mZoda** [comment]
HI, thx for responding :)
Yes i started with the SDK sample, ah.. C string....
Temperatrure is a float, and size of message is far less that 128 byte.
Sample of message :
{"v":13.81,"ts":"2023-09-26 08:35:45","id":"HB75-28-299","q":null}
Yea, during the "send" it usually fail after 64-69 messages, and reboots with Exception (29)

/Mikael

**Comment by RLeclair** [comment]
Apologies for the delay @mZoda, in that case, were you able to convert your temperature to a char pointer? If so, it seems that your exception is one from the ESP8266 (storeprohibitedcause). How are you preparing the message?
