### ISSUE TITLE
Shipping to Vcpkg; Investigate what's needed to ship to Vcpkg

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-c#270]
- Reach out to someone on Vcpkg to get an idea of the SLA
- Prototype a release in a fork of Vcpkg and validate that installation from the forked Vcpkg works properly 
- Open a Draft PR against Vcpkg repo and ensure that CI passes

**Comment by danieljurek** [comment]
Other questions: 
* What name do we want the package to have on Vcpkg?
* Versioning policy for C? 
* Copy for Description
* Documentation publishing?
* Do we want to support build systems other than cmake for this version? 


Considerations: 
* Building tests/docs/examples should not be enabled by default (Vcpkg docs)

**Comment by RickWinter** [comment]
Embedded C is not using vcpkg
