### ISSUE TITLE
[FEATURE REQ] Contract violations must call customer-overridable function that, by default returns an error. 

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-c#280]
Contract violations must call customer-overridable function that, by default returns an error. 
But, the customer can override the function to log and/or attach a debugger and/or terminate the application.

**Comment by gilbertw** [comment]
@vhvb1989 Please connect to the PreCondition PR and close

**Comment by vhvb1989** [comment]
fixed with https://github.com/Azure/azure-sdk-for-c/pull/421
