### ISSUE TITLE
GCC build errors 

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-c#286]
Many warnings as errors in the latest gcc build. Fixes are needed to merge #261 

Build log: https://dev.azure.com/azure-sdk/public/_build/results?buildId=222665&view=logs&j=d101aa69-0b62-5bec-4946-d14a2708bb8f&t=c55e0ad3-49ad-5de0-bec2-532cce2595cb

[gcc build errors.txt](https://github.com/Azure/azure-sdk-for-c/files/4016514/gcc.build.errors.txt)

**Comment by antkmsft** [comment]
I believe this is fixed now
