### ISSUE TITLE
Clang build errors

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-c#287]
Many types of Clang warnings as errors seen in latest build. Fixes are needed to merge #261 

Build log: https://dev.azure.com/azure-sdk/public/_build/results?buildId=222665&view=logs&j=342c2766-5117-5186-106a-cc400cfb2aeb&t=9c076d15-12a2-545b-25fc-06b5663b034a

[clang build errors.txt](https://github.com/Azure/azure-sdk-for-c/files/4016601/clang.build.errors.txt)

**Comment by antkmsft** [comment]
I believe this is fixed now
