### ISSUE TITLE
[FEATURE REQ] az_span_span feedback

### ISSUE THREAD

**Issue by danewalton** [Azure/azure-sdk-for-c#289]
**Is your feature request related to a problem? Please describe.**

> I think it might be useful to have the ability to statically create an `az_span_span` instead of the builder methodology that is currently implemented. So we can have a macro which constructs an `az_span_span` with an `az_span` array input and size of the array. Example here:
```c
typedef struct az_span_span_tag
{
    az_span** begin;
    size_t size;
} az_span_span;

#define AZ_SPAN_SPAN_CREATE(BEGIN, LEN) \
    { .begin = (az_span**)BEGIN, .size = LEN }

static az_span telemetry_topic_prefix = AZ_CONST_STR("devices/");
static az_span telemetry_topic_suffix = AZ_CONST_STR("/messages/events/");

static az_span* telemetry_topic_array[] =
{
    &telemetry_topic_prefix,
    NULL,                               //Device ID
    &telemetry_topic_suffix
};
static az_span_span telemetry_topic_span_concat =
    AZ_IOT_STR_CONCAT_CREATE(&telemetry_topic_array, 3);
```
> In IoT land this is useful for creating mqtt topics as statically as possible but then leaving space for the device_id span (as demo'd here). At runtime the device ID is slotted in the NULL position.

**Describe the solution you'd like**
> The macro would be nice so users don't have to spend time constructing `az_span_span`'s

**Describe alternatives you've considered**

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x ] Description Added
- [ x ] Expected solution specified

**Comment by gilbertw** [comment]
@vhvb1989 Can you address as part of your span cleanup work

**Comment by vhvb1989** [comment]
Hey @danewalton 
So, `az_span_span` has been removed a few days ago. 
We no longer require a builder.
And the idea of a `az_span_span` was changed for a `az_span *` witch is terminated with `az_span_null()`  (this is basically a NULL terminated array now).

An example of this is in Keyvault client for creating operations array
```c
key_options.operations = (az_span[]){ az_keyvault_key_operation_sign(), az_span_null() };
```

Please, let me know if this resolves this issue

**Comment by danewalton** [comment]
I think this does cover most issues but it doesn't seem to allow for the ability to have a span in the middle which is not initially populated. So in my example, you can have a "prefix", a value to be dropped in during run time, and then a suffix. The original problem this was attempting to solve might have a different solution now, so writing this just as a comment about the limitations.

**Comment by vhvb1989** [comment]
Yes, so, if you can provide more info about what we need this, it would be helpful. I would like to know why does it need to be an array of spans.

Something that comes to my mind is, that if we can have a pre-allocated buffer, or if we can use stack, we can have prefix, deviceId and suffix all together in one only span at runtime.

We have this macro `AZ_SPAN_FROM_BUFFER()` witch takes a uint8_t buffer as parameter and creates a new az_span with the buffer capacity and length = 0.  Then we can append the prefix span.  
Then we have another macro `AZ_SPAN_FROM_INITIALIZED_BUFFER()` that is similar to the one before but set the span length to the length of the buffer. This is what I would use for making az_span from deviceId.
```c
// some example.. (but, again, We need to know if this can be a method where we use stack, 
or what's the context)
// This can be static global variables
static az_span telemetry_topic_prefix = AZ_CONST_STR("devices/");
static az_span telemetry_topic_suffix = AZ_CONST_STR("/messages/events/");

//We can have a method to build the span
az_result az_build_telemetry_topic(az_span * out) {
  // copy prefix to out span from start (replace any other content in there)
  AZ_RETURN_IF_FAILED(az_span_copy(*out, telemetry_topic_prefix, out))
 
 // Get the device ID.  here we need to know how to get it..
 // Option 1.  If we have a ptr and size for device id
 az_span device_id_span = az_span_init((uint8_t *) device_id_ptr, size, size);
 // Option 2. We have the device id in some buffer
 az_span device_id_span = AZ_SPAN_FROM_INITIALIZED_BUFFER(device_id_buffer);

 // then we append it to out
 AZ_RETURN_IF_FAILED(az_span_append(*out, device_id_span, out);

 // and finally the suffix
 AZ_RETURN_IF_FAILED(az_span_append(*out, telemetry_topic_suffix , out);

 return AZ_OK;
}

// now we can have someplace to call this
int main () {
  uint8_t stack_buffer[1024 * 2]; // just adding some random size
  // make a span of if
  az_span buffer_span = AZ_SPAN_FROM_BUFFER(stack_buffer);

  // call out method
  az_result build_telemetry_device_id = az_build_telemetry_topic(&buffer_span);

  // We can now use this instead of the array of span or span_span

  return 0;
}
```

**Comment by danewalton** [comment]
Yea the use case currently can be mitigated. I think we might even have the device id as a pre-parsed `#define` which can then be dropped into a string a la:
```c
/* config.h */
#define DEV_ID "my_device"

/* some_c.c */
static const char* const tel_topic = "/device/" DEV_ID "/telemetry";
```
or something similar. For now I think we can probably table this.

**Comment by vhvb1989** [comment]
@danewalton  can we have this closed? 
Wondering if there is anything else to do for this one?

**Comment by danewalton** [comment]
Yup good to close.
