### ISSUE TITLE
[BUG] Duplicate information between readme and contributing guidelines

### ISSUE THREAD

**Issue by jspaith** [Azure/azure-sdk-for-c#292]
In the readme at root of repo there are instructions for how to build the sdk-for-c repo.  These instructions are more or less copy/pasted into the CONTRIBUTING.md document.

My 2 cents would be to have a separate document that both readme&contributing link against, but wherever the material lives I don't think we should be duplicating it.

**Comment by gilbertw** [comment]
This has been addressed.  All Readme files link to the central contributing.md now.
