### ISSUE TITLE
[BUG] IAR warnings

### ISSUE THREAD

**Issue by hihigupt** [Azure/azure-sdk-for-c#303]
**Describe the bug**
When I am trying to compile azure-sdk-for-c\sdk\core\core\ in IAR, I am getting following warnings:

Updating build tree...
az_assumptions.c
az_base64.c
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_result.h(78) : Warning[Pa089]: enumerated type mixed with another enumerated type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_result.h(80) : Warning[Pa089]: enumerated type mixed with another enumerated type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_span.h(102) : Warning[Pe188]: enumerated type mixed with another type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_span.h(102) : Warning[Pe188]: enumerated type mixed with another type
az_device_provision_client.c
az_iot_message.c
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_result.h(78) : Warning[Pa089]: enumerated type mixed with another enumerated type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_result.h(80) : Warning[Pa089]: enumerated type mixed with another enumerated type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_span.h(102) : Warning[Pe188]: enumerated type mixed with another type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_span.h(102) : Warning[Pe188]: enumerated type mixed with another type
az_json_builder.c
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_result.h(78) : Warning[Pa089]: enumerated type mixed with another enumerated type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_result.h(80) : Warning[Pa089]: enumerated type mixed with another enumerated type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_span.h(102) : Warning[Pe188]: enumerated type mixed with another type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_span.h(102) : Warning[Pe188]: enumerated type mixed with another type
az_json_get.c
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_result.h(78) : Warning[Pa089]: enumerated type mixed with another enumerated type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_result.h(80) : Warning[Pa089]: enumerated type mixed with another enumerated type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_span.h(102) : Warning[Pe188]: enumerated type mixed with another type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_span.h(102) : Warning[Pe188]: enumerated type mixed with another type
$build_root\azure-sdk-for-c\sdk\core\core\src\az_json_get.c(41) : Warning[Pe188]: enumerated type mixed with another type
az_json_parser.c
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_result.h(78) : Warning[Pa089]: enumerated type mixed with another enumerated type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_result.h(80) : Warning[Pa089]: enumerated type mixed with another enumerated type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_span.h(102) : Warning[Pe188]: enumerated type mixed with another type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_span.h(102) : Warning[Pe188]: enumerated type mixed with another type
$build_root\azure-sdk-for-c\sdk\core\core\src\az_json_parser.c(41) : Warning[Pe188]: enumerated type mixed with another type
$build_root\azure-sdk-for-c\sdk\core\core\src\az_json_parser.c(405) : Warning[Pe188]: enumerated type mixed with another type
az_json_pointer.c
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_result.h(78) : Warning[Pa089]: enumerated type mixed with another enumerated type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_result.h(80) : Warning[Pa089]: enumerated type mixed with another enumerated type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_span.h(102) : Warning[Pe188]: enumerated type mixed with another type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_span.h(102) : Warning[Pe188]: enumerated type mixed with another type
az_json_string.c
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_result.h(78) : Warning[Pa089]: enumerated type mixed with another enumerated type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_result.h(80) : Warning[Pa089]: enumerated type mixed with another enumerated type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_span.h(102) : Warning[Pe188]: enumerated type mixed with another type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_span.h(102) : Warning[Pe188]: enumerated type mixed with another type
$build_root\azure-sdk-for-c\sdk\core\core\src\az_json_string.c(96) : Warning[Pe188]: enumerated type mixed with another type
$build_root\azure-sdk-for-c\sdk\core\core\src\az_json_string.c(102) : Warning[Pe188]: enumerated type mixed with another type
$build_root\azure-sdk-for-c\sdk\core\core\src\az_json_string.c(108) : Warning[Pe188]: enumerated type mixed with another type
az_json_value.c
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_result.h(78) : Warning[Pa089]: enumerated type mixed with another enumerated type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_result.h(80) : Warning[Pa089]: enumerated type mixed with another enumerated type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_span.h(102) : Warning[Pe188]: enumerated type mixed with another type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_span.h(102) : Warning[Pe188]: enumerated type mixed with another type
az_mut_span.c
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_result.h(78) : Warning[Pa089]: enumerated type mixed with another enumerated type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_result.h(80) : Warning[Pa089]: enumerated type mixed with another enumerated type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_span.h(102) : Warning[Pe188]: enumerated type mixed with another type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_span.h(102) : Warning[Pe188]: enumerated type mixed with another type
az_pair.c
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_result.h(78) : Warning[Pa089]: enumerated type mixed with another enumerated type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_result.h(80) : Warning[Pa089]: enumerated type mixed with another enumerated type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_span.h(102) : Warning[Pe188]: enumerated type mixed with another type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_span.h(102) : Warning[Pe188]: enumerated type mixed with another type
az_span.c
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_result.h(78) : Warning[Pa089]: enumerated type mixed with another enumerated type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_result.h(80) : Warning[Pa089]: enumerated type mixed with another enumerated type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_span.h(102) : Warning[Pe188]: enumerated type mixed with another type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_span.h(102) : Warning[Pe188]: enumerated type mixed with another type
az_span_builder.c
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_result.h(78) : Warning[Pa089]: enumerated type mixed with another enumerated type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_result.h(80) : Warning[Pa089]: enumerated type mixed with another enumerated type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_span.h(102) : Warning[Pe188]: enumerated type mixed with another type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_span.h(102) : Warning[Pe188]: enumerated type mixed with another type
az_span_concat.c
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_result.h(78) : Warning[Pa089]: enumerated type mixed with another enumerated type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_result.h(80) : Warning[Pa089]: enumerated type mixed with another enumerated type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_span.h(102) : Warning[Pe188]: enumerated type mixed with another type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_span.h(102) : Warning[Pe188]: enumerated type mixed with another type
az_span_malloc.c
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_result.h(78) : Warning[Pa089]: enumerated type mixed with another enumerated type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_result.h(80) : Warning[Pa089]: enumerated type mixed with another enumerated type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_span.h(102) : Warning[Pe188]: enumerated type mixed with another type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_span.h(102) : Warning[Pe188]: enumerated type mixed with another type
az_span_reader.c
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_result.h(78) : Warning[Pa089]: enumerated type mixed with another enumerated type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_result.h(80) : Warning[Pa089]: enumerated type mixed with another enumerated type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_span.h(102) : Warning[Pe188]: enumerated type mixed with another type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_span.h(102) : Warning[Pe188]: enumerated type mixed with another type
az_span_writer.c
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_result.h(78) : Warning[Pa089]: enumerated type mixed with another enumerated type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_result.h(80) : Warning[Pa089]: enumerated type mixed with another enumerated type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_span.h(102) : Warning[Pe188]: enumerated type mixed with another type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_span.h(102) : Warning[Pe188]: enumerated type mixed with another type
az_str.c
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_result.h(78) : Warning[Pa089]: enumerated type mixed with another enumerated type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_result.h(80) : Warning[Pa089]: enumerated type mixed with another enumerated type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_span.h(102) : Warning[Pe188]: enumerated type mixed with another type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_span.h(102) : Warning[Pe188]: enumerated type mixed with another type
az_uri.c
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_result.h(78) : Warning[Pa089]: enumerated type mixed with another enumerated type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_result.h(80) : Warning[Pa089]: enumerated type mixed with another enumerated type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_span.h(102) : Warning[Pe188]: enumerated type mixed with another type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_span.h(102) : Warning[Pe188]: enumerated type mixed with another type
az_url.c
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_result.h(78) : Warning[Pa089]: enumerated type mixed with another enumerated type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_result.h(80) : Warning[Pa089]: enumerated type mixed with another enumerated type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_span.h(102) : Warning[Pe188]: enumerated type mixed with another type
$build_root\azure-sdk-for-c\sdk\core\core\inc\az_span.h(102) : Warning[Pe188]: enumerated type mixed with another type
$build_root\azure-sdk-for-c\sdk\core\core\src\az_url.c(24) : Warning[Pe188]: enumerated type mixed with another type
$build_root\azure-sdk-for-c\sdk\core\core\src\az_url.c(41) : Warning[Pe188]: enumerated type mixed with another type
$build_root\azure-sdk-for-c\sdk\core\core\src\az_url.c(53) : Warning[Pe188]: enumerated type mixed with another type
$build_root\azure-sdk-for-c\sdk\core\core\src\az_url.c(99) : Warning[Pe188]: enumerated type mixed with another type
$build_root\azure-sdk-for-c\sdk\core\core\src\az_url.c(114) : Warning[Pe188]: enumerated type mixed with another type
$build_root\azure-sdk-for-c\sdk\core\core\src\az_url.c(131) : Warning[Pe188]: enumerated type mixed with another type
$build_root\azure-sdk-for-c\sdk\core\core\src\az_url.c(145) : Warning[Pe188]: enumerated type mixed with another type
$build_root\azure-sdk-for-c\sdk\core\core\src\az_url.c(162) : Warning[Pe188]: enumerated type mixed with another type
$build_root\azure-sdk-for-c\sdk\core\core\src\az_url.c(176) : Warning[Pe188]: enumerated type mixed with another type
$build_root\azure-sdk-for-c\sdk\core\core\src\az_url.c(185) : Warning[Pe188]: enumerated type mixed with another type
$build_root\azure-sdk-for-c\sdk\core\core\src\az_url.c(209) : Warning[Pe188]: enumerated type mixed with another type
 
I would be great, if these warning can be fixed for IAR compiler too.

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by joshfree** [comment]
@antkmsft can you please take a look as part of your PAL refactoring?

**Comment by antkmsft** [comment]
I'll take a look, this should be fixable.

**Comment by antkmsft** [comment]
https://github.com/Azure/azure-sdk-for-c/pull/379

**Comment by antkmsft** [comment]
@hihigupt I made an attempt to fix warnings, and we followed up in Teams, and I think you told me that we are getting new ones now. Could you please either help me to get the IAR compiler, or to post the new batch of warnings here?

**Comment by antkmsft** [comment]
@hihigupt , I still don't have access to IAR compiler, but I recently completed a PR that enables a bunch of warnings for GCC and Clang, and fixes all the newly enabled warnings. Can you please retry it on IAR once again?

**Comment by hihigupt** [comment]
Closing as these warning is no more seen in our project with new changes

**Comment by ahsonkhan** [comment]
To close the loop and share root cause analysis:

This was causing the warning `az_result.h(78) : Warning[Pa089]: enumerated type mixed with another enumerated type`
https://github.com/Azure/azure-sdk-for-c/blob/6698dda769777575e14a4131da416fc33b33cba2/sdk/core/core/inc/az_result.h#L79

That was fixed by making sure to use the same type, using casts:
https://github.com/Azure/azure-sdk-for-c/blob/733574e5af651d4d972462f4cc8ed9c00980d781/sdk/inc/azure/core/az_result.h#L145-L148

Similar issue here and elsewhere `az_span.h(102) : Warning[Pe188]: enumerated type mixed with another type`:
https://github.com/Azure/azure-sdk-for-c/blob/6698dda769777575e14a4131da416fc33b33cba2/sdk/core/core/inc/az_span.h#L101-L103

This is about struct initialization where enum is the first field `az_json_get.c(41) : Warning[Pe188]: enumerated type mixed with another type`:
https://github.com/Azure/azure-sdk-for-c/blob/6698dda769777575e14a4131da416fc33b33cba2/sdk/core/core/src/az_json_get.c#L41

With the recent linter/clang-tidy fixes and struct field re-ordering, it will be less likely for such warnings to pop up again:
https://github.com/Azure/azure-sdk-for-c/pull/1265
https://github.com/Azure/azure-sdk-for-c/pull/1312
