### ISSUE TITLE
Errors from global warnings flags

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-c#304]
When enabling warning as error flags on all builds we have a few errors and those need to be fixed before merging to `master`

**Comment by danieljurek** [comment]
Errors from latest build: https://dev.azure.com/azure-sdk/public/_build/results?buildId=232356&view=logs&j=342c2766-5117-5186-106a-cc400cfb2aeb&t=9c076d15-12a2-545b-25fc-06b5663b034a

**Comment by danieljurek** [comment]
This now includes a merge conflict with `master`

**Comment by joshfree** [comment]
@danieljurek is this still actionable?

**Comment by danieljurek** [comment]
This has been taken care of. Thanks!
