### ISSUE TITLE
[FEATURE REQ] #endif comment for more clear #ifdefs

### ISSUE THREAD

**Issue by danewalton** [Azure/azure-sdk-for-c#305]
**Is your feature request related to a problem? Please describe.**
Currently `#ifndef`'s and other macro's do not have an indication on the ending `#endif` where they began.

**Describe the solution you'd like**
In a very basic example [here](https://github.com/Azure/azure-sdk-for-c/blob/6698dda769777575e14a4131da416fc33b33cba2/sdk/core/core/inc/az_http_header.h#L4), it would be nice if it was structured as so:
```c
#ifndef _az_HTTP_HEADER_H
#define _az_HTTP_HEADER_H
...
#endif /* _az_HTTP_HEADER_H */
```

In a more complex example for the `_az_cfg.h` [this](https://github.com/Azure/azure-sdk-for-c/blob/6698dda769777575e14a4131da416fc33b33cba2/sdk/core/core/inc/_az_cfg.h#L35) code snippet would turn into:
```c
#if defined(__clang__)

#pragma clang diagnostic ignored "-Wmissing-field-initializers"
#pragma clang diagnostic ignored "-Wmissing-braces"

#endif /* __clang__ */

#ifndef _az_CFG_H
#define _az_CFG_H

#ifdef _MSC_VER
#define AZ_INLINE static __forceinline
#elif defined(__GNUC__) || defined(__clang__)
#define AZ_INLINE __attribute__((always_inline)) static inline
#else
#define AZ_INLINE static inline
#endif /* _MSC_VER */

#if defined(__GNUC__) && __GNUC__ >= 7
#define AZ_FALLTHROUGH __attribute__((fallthrough))
#else
#define AZ_FALLTHROUGH \
  do { \
  } while (0)
#endif /* (__GNUC__) && __GNUC__ >= 7 */

#ifdef _MSC_VER
#define AZ_NODISCARD _Check_return_
#elif defined(__GNUC__) || defined(__clang__)
#define AZ_NODISCARD __attribute__((warn_unused_result))
#else
#define AZ_NODISCARD
#endif /* _MSC_VER */

#endif /* _az_CFG_H */
```

The C SDK for IoT currently does this and it makes it easier to follow opening and closing of these `#ifdef`'s

**Describe alternatives you've considered**
Feel free to format the comment after the closing `#endif` how you would like.

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Description Added
- [X] Expected solution specified

**Comment by antkmsft** [comment]
Can we use // style comments? /**/ are harder to comment out.

**Comment by danewalton** [comment]
> Can we use // style comments? /**/ are harder to comment out.

Totally cool with me. Seems reasonable

**Comment by antkmsft** [comment]
https://github.com/Azure/azure-sdk-for-c/pull/377

**Comment by danewalton** [comment]
Closed since was merged. Thanks @antkmsft
