### ISSUE TITLE
Curl implementation returns AZ_OK even when the host is unreachable

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-c#318]
Try to reach https://site.web via az_http_pipeline_process(), and you'll get AZ_OK with the empty response. I think that when host is not reachable, it is not AZ_OK,. but it is debatable. Let's discuss with the team. What are the other situtation when we might want non-AZ_OK? Is no internet an AZ_OK? Is 404 an AZ_OK? Is empty response a good indication of unsuccessful request?

**Comment by vhvb1989** [comment]
Fixed and tests added for validation on this with #354
