### ISSUE TITLE
[BUG] Doxygen Not Being Generated Due to Missing Label

### ISSUE THREAD

**Issue by danewalton** [Azure/azure-sdk-for-c#325]
If you run doyxgen over the sdk `inc` folders documentation doesn't get generated due to a missing label doyxgen requires at the top of files which need generated docs. Missing is the following at the top:
```c
/**
 * @file <insert header file name>
* /
```
Example [here](https://github.com/Azure/azure-ulib-c/blob/975efa4e287dc26db6b081ddc53bb45db0dae29c/inc/az_ulib_base.h#L5)

**Comment by vhvb1989** [comment]
@danewalton , can you share the Doxyfile you are using or the steps to reproduce this?

I have added the missing label but I want to see how your are invoking Doxygen

**Comment by vhvb1989** [comment]
https://github.com/Azure/azure-sdk-for-c/pull/355

**Comment by danewalton** [comment]
Yea [here is the Doxyfile used for ulib](https://github.com/Azure/azure-ulib-c/blob/master/docs/Doxyfile). Inside you can define the sources/directories for files to parse and any options you may want. From the computer you invoke 
```bash
doxygen Doxyfile
```
from the directory that houses the generated the docs.

**Comment by vhvb1989** [comment]
@danewalton  I have merged #355 
Can you see if this resolve this issue?  
I have added some more docs in headers for some structures.  I will be adding all missing docs in a new PR

**Comment by vhvb1989** [comment]
@danewalton did you try from latest master if it works as expected now?  Wonder if we can close this issue now?

**Comment by danewalton** [comment]
i didnt try but all the headers look like they have the `@file` so we should be good here. ill go ahead and close it.
