### ISSUE TITLE
Research retrieving test results from ctest and recording in Azure DevOps

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-c#328]
See: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=yaml

**Comment by vhvb1989** [comment]
https://github.com/Azure/azure-sdk-for-c/pull/343

**Comment by vhvb1989** [comment]
Using CMocka to generate xml files and CI updated to publish results

**Comment by vhvb1989** [comment]
Publishing one test result for each pipeline (win86, win64, lin64, mac64)
