### ISSUE TITLE
Update Json api to avoid passing az_span by *. Pass by value

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-c#348]
Ideally self would not be passed by *

_Originally posted by @JeffreyRichter in https://github.com/Azure/azure-sdk-for-c/pull/342_

**Comment by JeffreyRichter** [comment]
The point of this issue is to always pass az_span's by-value even within our non-public API surface. This is just a code hygiene thing. This can be done post-May but I think it should during the regular JSON code cleanup work.

**Comment by ahsonkhan** [comment]
Here's a link to the thread: https://github.com/Azure/azure-sdk-for-c/pull/342#discussion_r377434204
https://github.com/Azure/azure-sdk-for-c/blob/de74386a0dc9051ba16229b705ad574fc1069a26/sdk/core/core/src/az_json_string_private.h#L24

**Comment by RickWinter** [comment]
Affects private API and can be cleaned up in August

**Comment by ahsonkhan** [comment]
Fixed in https://github.com/Azure/azure-sdk-for-c/pull/871
