### ISSUE TITLE
[FEATURE REQ] Roadmap?

### ISSUE THREAD

**Issue by andre2007** [Azure/azure-sdk-for-c#357]
At first, I want to say **Thank you for working on a Azure C library**. I plan to write Azure applications in the D programming language and any C libraries can be directly used from D.

Could you may add an info, what is the current state of azure-sdk-for-c? Especially, what is working and what is not working. Maybe please also add a roadmap, what are the planned upcoming features.

**Comment by joshfree** [comment]
Thanks @andre2007; we're just getting started with this repo now.  We'll use this issue to track creating a roadmap.md / updating our root readme with more details soon.

**Comment by RickWinter** [comment]
We've significantly updated the content in our README for embedded C SDK.  In addition work has begun on the [C++ SDK](https://github.com/Azure/azure-sdk-for-cpp/) to support those working outside of the embedded C scenarios.  We look forward to your use and continued feedback on the SDKs.
