### ISSUE TITLE
[QUERY] How to compile as SO on linux?

### ISSUE THREAD

**Issue by andre2007** [Azure/azure-sdk-for-c#358]
**Query/Question**
How can I compile the library as `.so` instead of a static library `.a`?

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?

**Setup (please complete the following information if applicable):**
 - OS: Linux
 - IDE : none
 - Version of the Library used
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by vhvb1989** [comment]
We currently samples for using static lib only.
However, you can create the shared lib doing:
```bash
# from root folder
mkdir build-shared
cd build-shared
cmake -DBUILD_SHARED_LIBS=ON ..
make
```
This will produce .so instead of .o

**Comment by andre2007** [comment]
Thanks a lot. Maybe this is a candidate for the FAQ sections.
