### ISSUE TITLE
Allow customers to disable use of float/double

### ISSUE THREAD

**Issue by gilbertw** [Azure/azure-sdk-for-c#376]
Add ifdefs around the code to not compile float/double

**Comment by ahsonkhan** [comment]
Do we still have this requirement?

**Comment by ahsonkhan** [comment]
Iot PnP requires the use of float/double.

Please feel free to re-open if there is a need for this.
Currently, the SDK only uses double in a couple of APIs (double parsing/formatting and in reading/writing doubles as JSON). If the customer doesn't use those APIs, the rest of the SDK will continue to work.
