### ISSUE TITLE
Rename library folders to match name of library (e.g. `sdk/core/core` -> `sdk/core/az_core`) 

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-c#378]
This more closely follows the standards of naming the folder after the package names

**Comment by danieljurek** [comment]
After chatting w/ @gilbertw we should name this `azure-core` ... The C package name proposal currently uses `azure-core-c` but the ergonomics of the directory name are better.

**Comment by ahsonkhan** [comment]
@danieljurek - is this issue relevant anymore?

The directory structure looks like this now: `azure-sdk-for-c/sdk/inc/azure/core/`

Do we still want to rename `/core/` to `/az_core/`? Given `/core/` is a sub-directory under `/azure/`, it might be redundant to add `az_` to it.

**Comment by danieljurek** [comment]
This issue was opened before the discussions we had around restructuring the directories. It is superseded by that decision and we can close this.
