### ISSUE TITLE
[FEATURE REQ] Enable checks for secrets in commits

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-c#386]
**Is your feature request related to a problem? Please describe.**
Enabling tooling/checks that help prevent accidentally checking in secrets to the repo.

**Describe the solution you'd like**
Leverage existing tools to catch information disclosure and provides next steps along with preventative measures to reduce such cases.

**Comment by kurtzeborn** [comment]
Pretty sure this is unnecessary.  We have a global credscan watching all commits to our repos for accidental secret disclosure.
