### ISSUE TITLE
Update docs on how to run tests

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-c#415]
With the recent changes to use cmocka for testing (https://github.com/Azure/azure-sdk-for-c/pull/405), docs on how to run and debug tests are out-of-date. Specifically: https://github.com/Azure/azure-sdk-for-c/blob/master/CONTRIBUTING.md#building-and-testing

cc @vhvb1989

**Comment by vhvb1989** [comment]
https://github.com/Azure/azure-sdk-for-c/pull/423
