### ISSUE TITLE
Add support for component goverance into the pipeline

### ISSUE THREAD

**Issue by gilbertw** [Azure/azure-sdk-for-c#418]
Ensure we are properly scanning the source and dependencies.

**Comment by damirault** [comment]
Component Governance team is investigating adding support for VCPkg.

**Comment by danieljurek** [comment]
At the moment there is not an out-of-box pluggable solution for this. There are a couple of approaches which require custom work.

**Comment by kurtzeborn** [comment]
Component Governance runs everywhere now.
