### ISSUE TITLE
Conventional Commits

### ISSUE THREAD

**Issue by danewalton** [Azure/azure-sdk-for-c#420]
Many of the other IoT SDK's started using conventional commits. Just wanted to propose it to see if it's something this repo would want to do as well
[Link to Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)

**Comment by RickWinter** [comment]
There is a burden on each developer when following these patterns.  Unclear what we would use this for.  If there are specific tools/process that need this please add more details and reactivate.
