### ISSUE TITLE
[FEATURE REQ] CMake Required Version Reduction

### ISSUE THREAD

**Issue by danewalton** [Azure/azure-sdk-for-c#431]
Unless there is a feature added in `3.11` and `3.12` that is absolutely needed, what is the chance of getting it reduced to `3.10`? The newest version in Ubuntu 18.04 apt-get's is `3.10` and if someone is developing on that they would then have to build and install from source for CMake.

**Comment by danewalton** [comment]
linking #436

**Comment by ahsonkhan** [comment]
Has this been fixed?

**Comment by danewalton** [comment]
It has been merged. I will close.
