### ISSUE TITLE
C Engineering System for GA

### ISSUE THREAD

**Issue by kurtzeborn** [Azure/azure-sdk-for-c#453]
- [x] Pipelines
  - [x] Scheduled builds
  - [x] Release pipeline (source?)
- [ ] Guidance on where/how to integrate linters, code analysis, etc.

**Comment by gilbertw** [comment]
@kurtzeborn @danieljurek I updated the title to reflect that this work is about C.  The C++ work if any should be track in the C++ repo.
https://github.com/Azure/azure-sdk-for-cpp

**Comment by RickWinter** [comment]
@danieljurek @kurtzeborn Can we split this Epic into two epics.  One that tracks what is needed for GA and the other which tracks improvements we will do in the current semester.
