### ISSUE TITLE
[BUG] GCC compile warning after GCC diagnostic push

### ISSUE THREAD

**Issue by ericwol-msft** [Azure/azure-sdk-for-c#456]
**Describe the bug**
Compiling the SDK under GCC, I get warnings that there is no '#pragma GCC diagnostic [error|warning|ignored] "XXX"' after the "#pragma GCC diagnostic push"

`azure-c-sdk/sdk/core/core/inc/_az_cfg_prefix.h:18:9: warning: expected [error|warning|ignored] after '#pragma GCC diagnostic'`

**To Reproduce**
This is happening when I'm trying to port to microchip under the MPLAB IDE

**Expected behavior**
This is happening when I'm trying to port to microchip under the MPLAB IDE
https://gcc.gnu.org/onlinedocs/gcc/Diagnostic-Pragmas.html

**Setup (please complete the following information):**
 - OS: microchip
 - IDE : MPLAB IDE

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by ericwol-msft** [comment]
complier
xc16\v1.50\bin\xc16-gcc.exe

**Comment by antkmsft** [comment]
@ericwol-msft , can you please try to compile antk/gcc-warnings-push-pop branch?

**Comment by ericwol-msft** [comment]
verified, success
