### ISSUE TITLE
[BUG] Fail to compile span using GCC 

### ISSUE THREAD

**Issue by hihigupt** [Azure/azure-sdk-for-c#463]
**Describe the bug**
workspace/.build/azure-sdk-for-c/sdk/core/core/inc/az_span.h: In function ‘az_span_is_content_equal’:
workspace/.build/azure-sdk-for-c/sdk/core/core/inc/az_span.h:196:57: error: conversion to ‘size_t {aka unsigned int}’ from ‘int32_t {aka int}’ may change the sign of the result [-Werror=sign-conversion]
       && memcmp(az_span_ptr(span1), az_span_ptr(span2), az_span_length(span1)) == 0;
                                                         ^~~~~~~~~~~~~~
workspace/.build/azure-sdk-for-c/sdk/core/core/inc/az_span.h: In function ‘az_span_set’:
workspace/.build/azure-sdk-for-c/sdk/core/core/inc/az_span.h:383:42: error: conversion to ‘size_t {aka unsigned int}’ from ‘int32_t {aka int}’ may change the sign of the result [-Werror=sign-conversion]
   memset(az_span_ptr(destination), fill, az_span_capacity(destination));
                                          ^~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by vhvb1989** [comment]
https://github.com/Azure/azure-sdk-for-c/pull/465#event-3132175411

**Comment by antkmsft** [comment]
Done :)
