### ISSUE TITLE
[FEATURE REQ] CMake should enable all warnings in CI but disable them by default

### ISSUE THREAD

**Issue by sergey-shandar** [Azure/azure-sdk-for-c#49]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Description Added
- [ ] Expected solution specified

**Comment by gilbertw** [comment]
@barcharcraz, please add details for what should be done and why

**Comment by barcharcraz** [comment]
Can you explain what needs to be done here?

In general the warning level can be the same everywhere, it's /WX || -Werror that needs to be disabled by default.
