### ISSUE TITLE
Make code coverage and library code size numbers easily accessible/more visible in PRs

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-c#510]
Consider enabling a bot that comments on all GitHub PR/code changes with the overall code coverage numbers (from unit tests) and the size of the `az_core`, or any corresponding set of library that are built in the repo. This way, these metrics remain on top of mind and doesn't require reviewers to ask/verify every time.

Seeing the delta/change between what's in master and the PR would be great as well.

Some things to consider (especially if going with the GitHub comment approach):
- Should the comment show up for every commit (probably) OR just when the PR is first open?
- Should it only get triggered after CI is green and all legs/tests pass?
- Should we provide the break-down of SDK size by showing each built library/component individually?

cc @danieljurek

**Comment by kurtzeborn** [comment]
@ahsonkhan, would having the code coverage data in the DevOps UI for the pipeline be enought?  Writing the results back as a comment to the PR would require our public PR validation pipelines to have access to secrets that they currently don't have access to (and we don't want them to).

**Comment by ahsonkhan** [comment]
Interesting. Has no scenario ever come up before where having useful info shared from the DevOps pipeline back to PRs? There is something nice about having the dev work flow remain within the PR itself on GitHub and only deal with the CI legs/view if something failed. That said, I am fine with alternatives given the concern about secrets.

> would having the code coverage data in the DevOps UI for the pipeline be enough

Is that accessible to external contributors as well and easily visible? As long as there is a way for all contributors to see the important metrics that are generally common across PRs, it can remain top-of-mind and avoids reviewers having to keep asking for it. It becomes self-serve :)

What about other metrics that might be repo specific, like the code size of the built libraries in the case of the C SDK? Will we be able to see that as well in a reasonble fashion?

**Comment by danieljurek** [comment]
The data is available in our public ci pipelines for every PR and it's visible to all.

It's in the "Tests and Coverage" section and you can drill in on the details by clicking the coverage percentage or the "Code Coverage" tab. 

![image](https://user-images.githubusercontent.com/2158838/77588062-57823900-6ea6-11ea-9ee1-f237335ba7a0.png)

**Comment by ahsonkhan** [comment]
> The data is available in our public ci pipelines for every PR and it's visible to all.

Great.

FYI, I was playing around with the view in the CI pipelines, and unlike the `Tests` link, the `Code 
coverage` link doesn't take you to the right tab.

![image](https://user-images.githubusercontent.com/6527137/77592074-99af7880-6eae-11ea-904b-2d871c01b5f1.png)

For example:
https://github.com/Azure/azure-sdk-for-c/pull/518/checks?check_run_id=534813310

Clicking on `Tests` takes you to to the test tab: https://dev.azure.com/azure-sdk/public/_build/results?buildId=331602&view=ms.vss-test-web.build-test-results-tab

Clicking on `Code coverage` takes you to the summary tab: https://dev.azure.com/azure-sdk/public/_build/results?buildId=331602&_a=summary&tab=ms.vss-codecoverage-web.code-coverage-details&view=results

If we had a "Code size" section in the Details, that would be perfect.

**Comment by ahsonkhan** [comment]
Duplicate of https://github.com/Azure/azure-sdk-for-c/issues/240
