### ISSUE TITLE
Add support for retrieving the SDK version in code

### ISSUE THREAD

**Issue by gilbertw** [Azure/azure-sdk-for-c#527]
Need a general solution for returning the version of the SDK.

Probably want both spans and ints
Major
Minor
Patch

Also provide the GitHash of the commit
All values need to be read from the version.txt file

**Comment by vhvb1989** [comment]
adding proposal:
-  Adding version header with az_sdk_version_get() api
Customers would need to add this header if they want to print out the version that gets build for the lib.
Then we add a simple plain text file to SCM (repo) that cmake can read to define the version symbol
So then in the version header we do
```c
typedef struct {
  uint_8 major;
  uint_8 minor;
  uint_8 patch; 
} az_sdk_version;

static const SDK_VERSION = {
#ifdef SDK_MAJOR_VERSION
  .major = SDK_MAJOR_VERSION,
#else 
  .major = 0,
#endif

// same for minor and patch...  We define it on compilation time so it can't change
}

AZ_NODISCARD AZ_INLINE az_sdk_version az_sdk_version() {
  return SDK_VERSION;
}
```

**Comment by ericwol-msft** [comment]
We need to also bubble up platform info 

iOS 12.2.0
Linux; armv7l
Linux; armv5tejl
Debian 9.3; arm
Android; i686
Windows_NT 10.0.18362; ia32
Microsoft Windows 10.0.14393; X64
