### ISSUE TITLE
Add Environment helpers

### ISSUE THREAD

**Issue by gilbertw** [Azure/azure-sdk-for-c#545]
Add helpers for using spans with environment variables

**Comment by ahsonkhan** [comment]
There isn't a simple portable way to get environment variables. That makes it difficult to provide support for this within the SDK.

Within samples, folks can call `getenv` and copy it into their own buffer to avoid concerns with overriding data. Here's an example of that:
https://github.com/Azure/azure-sdk-for-c/blob/6a966901e467747d66e5705a3e25848b9ef45be8/sdk/samples/iot/hub/src/paho_iot_hub_telemetry_example.c#L191-L210
