### ISSUE TITLE
XML payload builder/parser

### ISSUE THREAD

**Issue by gilbertw** [Azure/azure-sdk-for-c#55]
Storage uses XML request and response semantics.  The SDKs in general provide strong value add by handling the XML formation for the client.  

The XML parser needs to support building requests and parsing response

- [ ] Request Builder/Parser
- [ ] Response Builder/Parser

**Comment by sergey-shandar** [comment]
```c
az_xml_parser_read_attribute(az_xml_parser *, az_span * name, az_span * value);
```

**Comment by gilbertw** [comment]
The embedded C SDK has no current plans for adding XML helpers.
