### ISSUE TITLE
Build gate configuration with preconditions turned off

### ISSUE THREAD

**Issue by danewalton** [Azure/azure-sdk-for-c#553]
I think it would be worthwhile to build the SDK with the preconditions turned off to make sure we don't get errors. Mainly, @CIPop pointed out we could have some issues with unused parameters on some functions that get "masked" with the preconditions.

**Comment by gilbertw** [comment]
As discussed lets add an option and entries into the matrix
```
option(BUILD_PRE_CONDITIONS "Build with PreCondition checks" ON)

#enable mock functions with link option -ld
if NOT (BUILD_PRE_CONDITIONS)
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DNO_PRECONDITION_CHECKING")
endif()
```
