### ISSUE TITLE
Remove use of _azcfg.h from tests and samples

### ISSUE THREAD

**Issue by CIPop** [Azure/azure-sdk-for-c#564]
This is tracking fixing the MSVC compiler warnings related to span initialization with auto-variables.
Using `AZ_SPAN_FROM_BUFFER` causes MSVC to issue a warning (treated as error) in our build system.

~~The work should be completed after `az_span` is changed to take only buffer and size (no capacity).~~

**Comment by gilbertw** [comment]
@CIPop this should be fixed now.  Can you remove the header and confirm its no longer necessary for samples/customers to use

**Comment by CIPop** [comment]
@gilbertw I'm afraid the initial assumption that this will be fixed was wrong.
/cc @ahsonkhan 

Removing the header from any of our samples using `AZ_SPAN_FROM_BUFFER` causes:

```
   S:\c\sdk\iot\provisioning\samples\src\paho_iot_provisioning_example.c(103,1): warning C4204: nonstandard extension used: non-constant aggregate initializer [s:\c\build\sdk\iot\provisioning\samples\paho_iot_provisioning_
       example.vcxproj]
         S:\c\sdk\iot\provisioning\samples\src\paho_iot_provisioning_example.c(112,1): warning C4204: nonstandard extension used: non-constant aggregate initializer [s:\c\build\sdk\iot\provisioning\samples\paho_iot_provisioning_
       example.vcxproj]
         S:\c\sdk\iot\provisioning\samples\src\paho_iot_provisioning_example.c(116,1): warning C4204: nonstandard extension used: non-constant aggregate initializer [s:\c\build\sdk\iot\provisioning\samples\paho_iot_provisioning_
       example.vcxproj]
         S:\c\sdk\iot\provisioning\samples\src\paho_iot_provisioning_example.c(125,1): warning C4204: nonstandard extension used: non-constant aggregate initializer [s:\c\build\sdk\iot\provisioning\samples\paho_iot_provisioning_
       example.vcxproj]
         S:\c\sdk\iot\provisioning\samples\src\paho_iot_provisioning_example.c(129,1): warning C4204: nonstandard extension used: non-constant aggregate initializer [s:\c\build\sdk\iot\provisioning\samples\paho_iot_provisioning_
       example.vcxproj]
```

The fix would be to:

1. Not use the macros in user applications (making the macros internal)
2. Create a common environment reader using char*/size/len instead of `az_span`. (#545)
