### ISSUE TITLE
[BUG] Storage sample is not resetting http response to be reused

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-c#580]
In the sample, after sending the first operation to put a blob, and before sending the next operation to download the blob, we need to re-init the http response structure if we want to re-use the same structure previously used.

If we don't re-init the response, the next response from server is going to be appended at the end of current response, witch is not OK.

We might want to consider calling the response_init in the pipeline?  in case the size of the response is greater than 0?   So then we can re-use a response without customer needing to re-init it ? @JeffreyRichter @gilbertw

**Comment by gilbertw** [comment]
I was expecting the pipeline to treat the response object as an object it would overwrite.  My mental model is this is an outparam and its contents should be disregarded.
We should clear the response at the start of the pipeline
