### ISSUE TITLE
[Design] AZ_RESULT and simple output values.

### ISSUE THREAD

**Issue by sergey-shandar** [Azure/azure-sdk-for-c#59]
# Options

## 1. `az_result` and `az_result_VALUE_TYPE`

`az_result` can't have non-error (non-negative) values except `AZ_OK`.

`az_result_VALUE_TYPE` can have non-error values from `VALUE_TYPE`.

Similar to [HRESULT](https://en.wikipedia.org/wiki/HRESULT#How_HRESULTs_work) implementation. For example:

### az_result.h
```c
// it's an error or a byte.
typedef az_result az_result_byte;

enum {
  // for compatibility with standard C EOF.
  AZ_ERROR_EOF = AZ_MAKE_ERROR(AZ_C_FACILITY, 0xFFFF);
};

AZ_STATIC_ASSERT(AZ_ERROR_EOF == EOF);
```

### az_span.h

```c
az_result_byte az_span_get(az_span span, size_t i) {
  if (span.size <= i) {
    return AZ_ERROR_EOF;
  }
  return span.begin[i];
}
```

### az_iter.h

```c
/**
 * Possible results:
 * - an error, for example `AZ_ERROR_TIME_OUT` or `AZ_ERROR_EOF`.
 * - a value is a byte (0..255).
 */
az_result_byte az_iter_current(az_iter const * iter);
```

## 2. `az_result` and optional types (eg. `az_option_byte`)

`az_result` can't have non-error (non-negative) values except `AZ_OK`.

For example

### az_option_byte.h

https://en.wikipedia.org/wiki/Option_type

```c
// `az_option_byte` can't be implicitly cast to `uint8_t` without compiler error/warning.
// It's relatively safe to compare `az_option_byte` and `uint8_t`.  
typedef int16_t az_option_byte;

enum {
  AZ_OPTION_NONE = EOF
};
```

### az_span.h

```c
//  this function is useful for streams and iterators.
az_option_byte az_span_try_get(az_span span, size_t i) {
  if (span.size <= i) {
    return AZ_OPTION_NONE;
  }
  return span.begin[i];
}

az_result az_span_get(az_span span, size_t i, uint8_t * out) {
  AZ_CONTRACT_ARG_NOT_NULL(out);
  AZ_CONTRACT_ARG_INDEX_OF_SPAN(i, span);

  *out = span.begin[i];
  return AZ_OK;
}
```

### az_iter.h

```c
/**
 * Possible results:
 * - `AZ_OK`, then `*out` is either AZ_OPTION_NONE (EOF, -1) or a byte (0..255).
 * - an error, for example `AZ_ERROR_TIME_OUT`
 */
az_result az_iter_current(az_iter const * p_iter, az_option_byte * out);
```

## 3. `az_result` and non-error/non-value types

`az_result` CAN have non-error values which can be used to report a state but not a value.

For example

### az_result.h
```c
enum {
  // It's incompatible with C EOF.
  AZ_NO_MORE_ITEMS = AZ_MAKE_RESULT(AZ_CORE_FACILITY, 42);
};
```

### az_span.h

```c
az_result az_span_get(az_span span, size_t i, uint8_t * out) {
  AZ_CONTRACT_ARG_NOT_NULL(out);
  AZ_CONTRACT_ARG_INDEX_OF_SPAN(i, span);

  *out = span.begin[i];
  return AZ_OK;
}
```

### az_iter.h

```c
/**
 * Possible results:
 * - `AZ_OK`, then `*out` is a byte (0..255).
 * - `AZ_NO_MORE_ITEMS`
 * - an error, for example `AZ_ERROR_TIME_OUT`
 */
az_result az_iter_current(az_iter const * p_iter, uint8_t * out);
```

**Comment by sergey-shandar** [comment]
@gilbertw, @antkmsft, @vhvb1989 which one do you prefer for simple functions?

**Comment by antkmsft** [comment]
I vote for option 2.

**Comment by vhvb1989** [comment]
option 2 looks simpler to maintain.  
I would probably get rid of `AZ_CONTRACT_ARG_NOT_NULL` for now.

**Comment by sergey-shandar** [comment]
@vhvb1989 yeah, we don't have `AZ_CONTRACT_ARG_NOT_NULL` in Azure.Core yet. I will have a PR for that. It's a macro that may return with `az_result`.

**Comment by sergey-shandar** [comment]
@JeffreyRichter, @barcharcraz ?

**Comment by barcharcraz** [comment]
I still think you need to write it with the out parameters, if we want a fancy functional interface we should deliver that as a wrapper in a functional language.

Also, this lacks a third option which is "az_result can have non-error values but is never used as a channel for the return value"

**Comment by sergey-shandar** [comment]
@barcharcraz I think, we already discussed that we may have functions that never ever return errors and in this case we would like to return a value instead of `az_result`. Really, they are very usefull and simplify logic and remove useless checks (like non-null output parameters). Without them, our C development life will be even harder :-)

about the third option, we may say it's the first option but with slightly adjusted meaning of what do we call error or not-error. We can still reserve the space for "non-error" but I personally would like to avoid API that uses such "non-error" things.

**Comment by JeffreyRichter** [comment]
This is the best version:
az_result az_span_get(az_span span, size_t i, uint8_t * out) {
  AZ_CONTRACT_ARG_NOT_NULL(out);

  if (span.size <= i) {
    return AZ_ERROR_OUT_OF_RANGE;
  }
  *out = span.begin[i];
  return AZ_OK;
}

If we do contract checking, then we should check that i is >=0 && i < span.size and return an az_result for failing this contract. i being out of range is also a contract violation - not an error.

These code samples are a good step but really, when we compare approaches we need to see what the calling/customer code would look like; not what our code would look like.

**Comment by sergey-shandar** [comment]
@barcharcraz I've added option 3. On of the problems with this, that it's more error prone because it's not obvious from a function signature that there is a special non-error case `AZ_NO_MORE_ITEMS` that requires special attention.

**Comment by sergey-shandar** [comment]
@JeffreyRichter I agree, usage examples would be good.

**Comment by sergey-shandar** [comment]
@antkmsft, @vhvb1989, @gilbertw I've added an option #3. When az_result may have non-error/non-value status.

I still vote for #2.

**Comment by sergey-shandar** [comment]
By the way: `AZ_CONTRACT_ARG_...` requires that the function returns `az_result`. Example of `AZ_CONTRACT_ARG_NOT_NULL`:

```c
#define AZ_CONTRACT_ARG_NOT_NULL(arg) \
  do { \
    if ((arg) == NULL) { \
      return AZ_ERROR_ARG; \
    } \
  } while (0)
```

**Comment by sergey-shandar** [comment]
@katmsft, @rafilho, @mamokarz

**Comment by gilbertw** [comment]
We've settled on the az_result return with out parameters.

az_result az_span_get(az_span span, size_t i, uint8_t * out) {
  AZ_CONTRACT_ARG_NOT_NULL(out);
  // we can't use `span.size - 1` because it may overflow in case of `span.size == 0` because `size_t` is unsigned integer.
  AZ_CONTRACT_ARG_IN_RANGE(i, 0, span.size);
  // or AZ_CONTRACT_ARG_ARRAY_INDEX(i, span.size);

  *out = span.begin[i];
  return AZ_OK;
}
