### ISSUE TITLE
az_span_ato64 should support negative numbers since az_span_i64toa support it

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-c#598]
negative int to a is currently supported, 
but a to negative int is not.

```c
uint8_t buffer[100];
  az_span b_span = AZ_SPAN_FROM_BUFFER(buffer);
  az_span remainder;
  int32_t size_before_write = az_span_size(b_span);
  int64_t number = -123;
  az_span number_str = AZ_SPAN_FROM_STR("-123");

  assert_return_code(az_span_i64toa(b_span, number, &remainder), AZ_OK);
  assert_int_equal(size_before_write, az_span_size(b_span));
  // remainder should be size minus number of digits (4)
  assert_int_equal(az_span_size(remainder), size_before_write - 4);

  // create az_span for written data
  b_span = az_span_init(az_span_ptr(b_span), az_span_size(b_span) - az_span_size(remainder));

  assert_true(az_span_is_content_equal(b_span, number_str));

  // convert back TODO: az_span_ato64 should support negative numbers since az_span_i64toa support
  // it. 
  /* uint64_t reverse = 0;
  assert_return_code(az_span_atou64(b_span, &reverse), AZ_OK);
  assert_int_equal(reverse, number);
  */
```

**Comment by JeffreyRichter** [comment]
Yes, we should have atou64 (assumes unsigned) and atoi64 (assumed signed and works with negative numbers).

**Comment by ahsonkhan** [comment]
Here's what we have atm in master:
- az_span_i64toa
- az_span_i32toa
- az_span_dtoa
- az_span_u32toa <-> az_span_atou32
- az_span_u64toa <-> az_span_atou64

If we want full round-tripping support of int32, uint32, int64, uint64, and double, we need to add these 3 overloads to complete the set (so we have 10 in total):
- az_span_atoi64
- az_span_atoi32
- az_span_atod

https://github.com/Azure/azure-sdk-for-c/blob/d935811ddb7f9be184f2859165bc5e7aa8efebae/sdk/core/core/inc/az_span.h#L282-L385

**Comment by vhvb1989** [comment]
@JeffreyRichter , based on the comments from https://github.com/Azure/azure-sdk-for-c/pull/627/files
Can we close this issue as we will not add/support functions:
-  az_span_i64toa
-  az_span_i32toa
-  az_span_dtoa
??  
@gilbertw  This is marked as for may release. And it is becoming on risk of not enough time to be implemented based on las comments from initial PR for adding az_span_dtoa,  FYI

**Comment by JeffreyRichter** [comment]
Sure, don't implement for now. For JSON support, I'd expect us to need double read/write support. I can also imagine logging needing some integer to ascii support.

**Comment by JeffreyRichter** [comment]
Here's code for all atoX and Xtoa scenarios. Someone can just drop this into Azure Core. Some tests are at the bottom (in main):

void _az_span_atox(char const *span, char * format_template, void *v) {
    int len = strlen(span) - 3; // len = span size; the -3 is just for testing without spans
    // Precondition: size must be >=0 && < 100
    format_template[1] = (len / 10) + '0';
    format_template[2] = (len % 10) + '0';
    int n = sscanf(span, format_template, v);    // if n!=1, error
    //return (n == 1)? AZ_OK : AZ_ERROR_PARSE;
}

double az_span_atof(char const *span) {
    char format_template[] = "%00lf";   // Stack based string to allow thread-safe mutation by _az_span_atox
    double v = 0;
    _az_span_atox(span, format_template, &v);
    return v;
}

int32_t az_span_atoi32(char const *span) {
    char format_template[] = "%00d";   // Stack based string to allow thread-safe mutation by _az_span_atox
    int32_t v = 0;
    _az_span_atox(span, format_template, &v);
    return v;
}

uint32_t az_span_atou32(char const *span) {
    char format_template[] = "%00u";   // Stack based string to allow thread-safe mutation by _az_span_atox
    uint32_t v = 0;
    _az_span_atox(span, format_template, &v);
    return v;
}

int64_t az_span_atoi64(char const *span) {
    char format_template[] = "%00ld";   // Stack based string to allow thread-safe mutation by _az_span_atox
    int64_t v = 0;
    _az_span_atox(span, format_template, &v);
    return v;
}

uint64_t az_span_atou64(char const *span) {
    char format_template[] = "%00lu";   // Stack based string to allow thread-safe mutation by _az_span_atox
    uint64_t v = 0;
    _az_span_atox(span, format_template, &v);
    return v;
}


  
int32_t _magnitude(int32_t value) {
    int32_t magnitude = 10;
    for (; value / magnitude > 0; magnitude *= 10) ;
    //printf("For %d, the magnitude is %d\n", value, magnitude/10);
    return magnitude / 10;
}

int32_t _convert_itoa(int32_t value, char *span, int32_t size, int32_t max_digits) {
    bool ok_to_truncate = max_digits != -1;
    int32_t digits = 0;
    for (int32_t magnitude = _magnitude(value); magnitude > 0; magnitude /= 10) { 
        //if (ok_to_truncate) printf("max_digits=%d, didigts=%d, mag=%d\n", max_digits, digits, magnitude);

        if (digits == size) {   // Buffer not big enough
            // If not OK to truncate (max_digits==-1), return failure; else return # digits appended
            return (max_digits == -1) ? -1 : digits;   
        }

        if (ok_to_truncate && (digits == max_digits)) {
            // We hit the max number of desired digits; truncate remainder
            return digits;
        }

        int32_t tens_value = value / magnitude;
        //printf("value=%d, mag=%d, 10s=%d\n", value, magnitude, tens_value);
        span[digits++] = tens_value + '0';
        value %= magnitude; 
    } 
    return digits;
}

// Converts a floating-point/double number to a string. 
int32_t az_span_ftoa(float f, char* span, int32_t size, int32_t fraction_digits) { 
    if ((f < 0) || (f > 0) || (f == 0)) /* valid float */;
    else { // float is not a number (nan)
        memcpy(span, "nan", 4);
        return 3;
    }

    int32_t digits = 0;
    if (f < 0) {    // If negative
        span[digits++] = '-';   // Start with a minus sign
        f = -f; // Make f positive
    }

    // Convert mantissa to a string:
    int32_t mantissa = (int32_t)f;  // Extract integer part of float
    int32_t added = _convert_itoa(mantissa, &span[digits], size - digits, -1);
    if (added == -1) return -1; // Buffer not big enough
    digits += added;
    if (digits == size) return -1;   // Buffer not big enough; return failure
      
    if (fraction_digits != 0) { // If appending fraction digits, append a decimal point
        span[digits++] = '.'; // add decimal point
        if (digits == size) return digits;   // Buffer not big enough; truncate
  
        // Convert float to a string:    
        float fraction = f - (float)mantissa;  // Extract floating part 
        
        // Convert fractional part to integer with required # of digits
        for (int32_t d = 0; d < fraction_digits; d++) fraction *= 10;   
        digits += _convert_itoa(fraction, &span[digits], size - digits, fraction_digits);
    } 
    return digits;
} 

void atof_test(float f) {
    char num[40];
    int32_t size = az_span_ftoa(f, num, 5, 3);
    printf("size=%d\n", size);
    num[size] = 0;
    printf("%d: %f == %s\n", size, f, num);
}  

int main() {
    atof_test(0.0 / 0.0);
    atof_test(0);
    atof_test(-0);
    atof_test(1);
    atof_test(-1);
    atof_test(12);
    atof_test(-12);
    atof_test(123);
    atof_test(-123);
    atof_test(.34567);
    atof_test(-.34567);
    atof_test(9876.54321);
    atof_test(-9876.54321);
    atof_test(987654.321);
    atof_test(-987654.321);

/*
    printf("%f\n", az_span_atof("   "));    // empty or invalid returns 0
    printf("%f\n", az_span_atof("ABC   "));    // empty or invalid returns 0

    printf("%f\n", az_span_atof("-123.456789   "));
    printf("%d\n", az_span_atoi32("-9999999999   "));   // Too big overflows
    printf("%d\n", az_span_atoi32("-1234567890   "));
    printf("%u\n", az_span_atou32("12345   "));
    printf("%ld\n", az_span_atoi64("-1234567890123456   "));
    printf("%lu\n", az_span_atou64("1234567890123456   "));*/
    return 0;
}

**Comment by JeffreyRichter** [comment]
Sorry, here's a better version:

void _az_span_atox(char const *span, char * format_template, void *v, bool *success) {
    int size = strlen(span) - 3; // size = span size; the -3 is just for testing without spans
    // Precondition: size must be >=0 && < 100
    format_template[1] = (size / 10) + '0';
    format_template[2] = (size % 10) + '0';
    int chars_consumed = 0;
    int n = sscanf(span, format_template, v, &chars_consumed);    // if n!=1, error
    //printf("val=%*s, size=%d, cc=%d\n", size, span, size, chars_consumed);
    if (success != NULL) {
        *success = (size > 0) && (size == chars_consumed);  // true if all of the span's value was consumed by sscanf
    }
}

double az_span_atof(char const *span, bool *success) {
    char format_template[] = "%00lf%n";   // Stack based string to allow thread-safe mutation by _az_span_atox
    double v = 0;
    _az_span_atox(span, format_template, &v, success);
    return v;
}

int32_t az_span_atoi32(char const *span, bool *success) {
    char format_template[] = "%00d%n";   // Stack based string to allow thread-safe mutation by _az_span_atox
    int32_t v = 0;
    _az_span_atox(span, format_template, &v, success);
    return v;
}

uint32_t az_span_atou32(char const *span, bool *success) {
    char format_template[] = "%00u%n";   // Stack based string to allow thread-safe mutation by _az_span_atox
    uint32_t v = 0;
    _az_span_atox(span, format_template, &v, success);
    return v;
}

int64_t az_span_atoi64(char const *span, bool *success) {
    char format_template[] = "%00ld%n";   // Stack based string to allow thread-safe mutation by _az_span_atox
    int64_t v = 0;
    _az_span_atox(span, format_template, &v, success);
    return v;
}

uint64_t az_span_atou64(char const *span, bool *success) {
    char format_template[] = "%00lu%n";   // Stack based string to allow thread-safe mutation by _az_span_atox
    uint64_t v = 0;
    _az_span_atox(span, format_template, &v, success);
    return v;
}

int32_t _magnitude(int32_t value) {
    int32_t magnitude = 10;
    for (; value / magnitude > 0; magnitude *= 10) ;
    //printf("For %d, the magnitude is %d\n", value, magnitude/10);
    return magnitude / 10;
}

int32_t _convert_itoa(int32_t value, char *span, int32_t size, int32_t max_digits) {
    bool ok_to_truncate = max_digits != -1;
    int32_t digits = 0;
    for (int32_t magnitude = _magnitude(value); magnitude > 0; magnitude /= 10) { 
        //if (ok_to_truncate) printf("max_digits=%d, didigts=%d, mag=%d\n", max_digits, digits, magnitude);

        if (digits == size) {   // Buffer not big enough
            // If not OK to truncate (max_digits==-1), return failure; else return # digits appended
            return (max_digits == -1) ? -1 : digits;   
        }

        if (ok_to_truncate && (digits == max_digits)) {
            // We hit the max number of desired digits; truncate remainder
            return digits;
        }

        int32_t tens_value = value / magnitude;
        //printf("value=%d, mag=%d, 10s=%d\n", value, magnitude, tens_value);
        span[digits++] = tens_value + '0';
        value %= magnitude; 
    } 
    return digits;
}

// Converts a floating-point/double number to a string. 
int32_t az_span_ftoa(float f, char* span, int32_t size, int32_t fraction_digits) { 
    if (isinf(f)) { // float is infinity (inf)
        memcpy(span, "inf", 4);
        return 3;
    } else if (isnan(f)) { // float is not a number (nan)
        memcpy(span, "nan", 4);
        return 3;
    }

    int32_t digits = 0;
    if (f < 0) {    // If negative
        span[digits++] = '-';   // Start with a minus sign
        f = -f; // Make f positive
    }

    // Convert mantissa to a string:
    int32_t mantissa = (int32_t)f;  // Extract integer part of float
    int32_t added = _convert_itoa(mantissa, &span[digits], size - digits, -1);
    if (added == -1) return -1; // Buffer not big enough
    digits += added;
    if (digits == size) return -1;   // Buffer not big enough; return failure
      
    if (fraction_digits != 0) { // If appending fraction digits, append a decimal point
        if (digits == size) return digits;   // Buffer not big enough; truncate
        span[digits++] = '.'; // add decimal point
        if (digits == size) return digits;   // Buffer not big enough; truncate
  
        // Convert float to a string:    
        float fraction = f - (float)mantissa;  // Extract floating part 
        
        // Convert fractional part to integer with required # of digits
        for (int32_t d = 0; d < fraction_digits; d++) fraction *= 10;   
        digits += _convert_itoa(fraction, &span[digits], size - digits, fraction_digits);
    } 
    return digits;
} 

void atof_test(float f) {
    char num[40];
    int32_t size = az_span_ftoa(f, num, 5, 3);
    //printf("size=%d\n", size);
    num[size] = 0;
    printf("%d: %f == %s == ", size, f, num);

    num[size + 0] = ' ';
    num[size + 1] = ' ';
    num[size + 2] = ' ';
    num[size + 3] = 0;
    printf("%f\n", az_span_atof(num, NULL));
}  

int main() {
    atof_test(0.0 / 0.0);
    atof_test(1.0 / 0.0);
    atof_test(0);
    atof_test(-0);
    atof_test(1);
    atof_test(-1);
    atof_test(12);
    atof_test(-12);
    atof_test(123);
    atof_test(-123);
    atof_test(.34567);
    atof_test(-.34567);
    atof_test(9876.54321);
    atof_test(-9876.54321);
    atof_test(987654.321);
    atof_test(-987654.321);

    bool success;
    printf("%f (%d)\n", az_span_atof("   ", &success), success);    // empty or invalid returns 0
    printf("%f (%d)\n", az_span_atof("ABC   ", &success), success);    // empty or invalid returns 0
    printf("%f (%d)\n", az_span_atof("1.23E3   ", &success), success);
    printf("%f (%d)\n", az_span_atof("-123.456789   ", &success), success);
    printf("%d (%d)\n", az_span_atoi32("-9999999999   ", &success), success);   // Too big overflows
    printf("%d (%d)\n", az_span_atoi32("-1234567890   ", &success), success);
    printf("%u (%d)\n", az_span_atou32("12345   ", &success), success);
    printf("%ld (%d)\n", az_span_atoi64("-1234567890123456   ", &success), success);
    printf("%lu (%d)\n", az_span_atou64("1234567890123456   ", &success), success);
    return 0;
}

**Comment by ahsonkhan** [comment]
Thanks @JeffreyRichter - I will use these to test the JSON parser and try to get them in to master. If I need help to fit this into the June milestone, I will ping you @vhvb1989. I hope that's ok.
