### ISSUE TITLE
Consolidate common const values in IoT to common file

### ISSUE THREAD

**Issue by danewalton** [Azure/azure-sdk-for-c#605]
Tracking improvement to consolidate various constant values used for IoT features into one file to save space.

**Comment by ahsonkhan** [comment]
There is no milestone on this issue. @danewalton - do we need this for GA?

**Comment by danewalton** [comment]
ooof umm let me see with the team what to do here. It wouldn't be a public API change so doesn't necessarily have to.

**Comment by danewalton** [comment]
closing since not very crucial right now
