### ISSUE TITLE
Provide ability to do JSON string comparison that is resilient to escaped characters

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-c#608]
See https://github.com/Azure/azure-sdk-for-c/pull/590#discussion_r412524964

When it comes to JSON, "e" and "\u0065" are considered equal strings. We should provide some mechanism for the user to either:
- get the unescaped string so they can do direct byte-by-byte comparison with a known literal they are looking for (and/or)
- provide a helper API that does the comparison for them.

We don't want components that process/parse JSON and search for a particular property to behave differently between strings that have escaped characters vs. those that don't.

cc @JeffreyRichter, @gilbertw

**Comment by JeffreyRichter** [comment]
Better to provide an equals function that does the correct comparison because this would be non-allocating

**Comment by CIPop** [comment]
Using this feature should be optional. Azure service protocols come with some guarantees around what text is acceptable.
No issue having it enabled by default.

**Comment by ahsonkhan** [comment]
Fixed in https://github.com/Azure/azure-sdk-for-c/pull/871
