### ISSUE TITLE
[QUERY] Stack trace logging

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-c#609]
**Query/Question**

As per the [logging](https://github.com/Azure/azure-sdk/blob/master/docs/general/implementation.md#logging) design guideline, logging of stack trace should be done only for  specific log levels, verbose as per general guideline but languages may have different name for this level.

Opening this issue as a question to confirm that we're not logging sensitive stack trace unless user requested it by setting appropriate level.

**Comment by RickWinter** [comment]
C sdk does minimal logging by default.  Users can elect to log more locally via their callback mechanism
