### ISSUE TITLE
Investigate Logging infrastructure for Azure.Core

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-c#61]
Tracking issue to investigate adding a C99 logging package to our core components.  Java Azure SDKs use Log4J.

Log4C seems like a reasonable starting point for C99.

http://log4c.sourceforge.net/

**Comment by antkmsft** [comment]
Can we close this now? - https://github.com/Azure/azure-sdk-for-c/pull/302

**Comment by gilbertw** [comment]
Support for logging added in https://github.com/Azure/azure-sdk-for-c/pull/302
