### ISSUE TITLE
[FEATURE REQ] Investigate XML stack for Azure.Core

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-c#62]
Tracking issue for investigating and adding a 3rd party C99 XML stack for Azure.Core usage.

Expat, a stream-orientated XML parser library written in C seems like a good place to start the investigation.  "Expat excels with files too large to fit RAM, and where performance and flexibility are crucial."

https://libexpat.github.io/

**Comment by ahsonkhan** [comment]
There is no need for an XML stack, currently in the embedded SDK.
