### ISSUE TITLE
Enable generating release docs locally with instructions

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-c#634]
As part of the inner dev loop, it would be great if we can easily generate the docs locally to test/verify local changes. We have a mechanism today, but that doesn't produce the exact docs in the format that our release pipeline generates. For example, it doesn't filter out internal APIs/docs.

This should include an update to the docs so contributors know how to generate the release docs, similar to what we have atm, which currently doesn't produce the exact docs that we publish:
https://github.com/Azure/azure-sdk-for-c/blob/master/CONTRIBUTING.md#build-docs

cc @danieljurek, @gilbertw

**Comment by danieljurek** [comment]
The monolithic release now uses `doxygen Doxyfile` to generate docs for the entire project (which has been updated in CONTRIBUTING.md). Closing.
