### ISSUE TITLE
Support national cloud authentication urls.

### ISSUE THREAD

**Issue by gilbertw** [Azure/azure-sdk-for-c#636]
This needs to be a configuration setting.  It can change based on which cloud the application is running.  By default we would use the above.
https://docs.microsoft.com/en-us/azure/active-directory/develop/authentication-national-cloud

_Originally posted by @gilbertw in https://github.com/Azure/azure-sdk-for-c/pull/633/review_comment/create_

**Comment by antkmsft** [comment]
Thank you Rick. Yes, I think it must not only be a config setting, but the client secret credential should be configurable for that, i.e. you should be able to create credentials that use different auth URLs.

**Comment by gilbertw** [comment]
Needs to be addressed before GA

**Comment by antkmsft** [comment]
Based on offline conversations, we can move this one for the next sprint.
