### ISSUE TITLE
Extend the contract feature beyond preconditions and add debug asserts

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-c#638]
We should consider extending the contracts features to include the following in addition to preconditions:
- [ ] P1: asserts (and/or invariants)
- [ ] P2: post conditions

This will either require renaming the compiler flags to disable the contracts (to be more general rather than `NO_PRECONDITION_CHECKING`), or adding more flags to turn individual contracts off.

For reference: https://en.wikipedia.org/wiki/Design_by_contract

See the discussion here, which highlights why some asserts can help developers convey intent and catch dev-time bugs:
https://github.com/Azure/azure-sdk-for-c/pull/590#discussion_r412522054

cc @JeffreyRichter, @vhvb1989

**Comment by gilbertw** [comment]
PRE_CONDITIONS used to be CONTRACTS, which were asserts.  The switch to PRECONDITIONS with a callback method was a specific design change request.
Is this looking to add contracts back in addition to preconditions?  If so, what does the Contract provide that the precondition doesn't also provide?
Note, we could have the pre-condition be an assert in the callback.  That wasn't done b/c IoT wanted the sleep forever behavior.

**Comment by JeffreyRichter** [comment]
Let me cleanup some terminology. Contracts is a concept and there are 3 kinds of contracts: precondition, invariant, and post-condition. One way of implementing the concept of a contract is by using an assert.

So now, we could have a general purpose assert mechanism that, when it fails invokes the callback which, by default, enters an infinite loop. I'm OK with doing this. So az_precondition_failed_fn becomes az_assert_failed_fn and az_precondition_failed_get_callback() becomes az_assert_failed_get_callback() and the AZ_PRECONDITION macro becomes AZ_ASSERT

Then we keep ALL of our other precondition macros which internally leverage the renamed AZ_ASSERT macro. I think it's good to keep these macros named as they are as they make a statement about the contract and any developer modifying a function MUST consider the preconditions so as not to accidentally break the contract.

Then in the middle of functions, code can call AZ_ASSERT for an invariant/postcondition check. If we want to add specific AZ_POSTCONDITION macros or AZ_INVARIANT macros we can but it's probably unnecessary.
