### ISSUE TITLE
Consider adding simple "debug" and "release" flavors of compiling the SDK

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-c#639]
We currently have debug and debug with testing. As the number of granular flags and options grows, it becomes difficult to remember what users should do during dev time (debug) vs production (release).

https://github.com/Azure/azure-sdk-for-c/blob/93cbc98b3c725e055246a75cb7de78d0e7a4fa8c/CMakeSettings.json#L16

https://github.com/Azure/azure-sdk-for-c/blob/b365d28aacbe56ebbc46dd469bd4e2ed954ca4f0/CMakeLists.txt#L16-L18

We should document and create simple debug vs release flavors for someone building/contributing to/testing the SDK.

I would imagine Release to have things like:
- preconditions turned off
- recommended compiler optimizations flags depending on the compiler being used
  - This is necessary because it is possible that certain compiler optimizations could reorder instructions or eliminate code which could change the behavior of the API (hence we need to run tests here as well).

Consider the contributor scenario: They should be able to build the SDK by passing in a single debug/release option (default to debug if no option is passed).

For contributors (and CI), I think building unit tests is orthogonal, and we should consider building (and running) them for both flavors. If the end user who consumes the SDK doesn't need tests, we can disable the tests there, but I am not sure if that is necessary.

cc @danieljurek, @vhvb1989

**Comment by ahsonkhan** [comment]
cc @gilbertw - in case you have some thoughts on this (ore regarding triaging)

**Comment by gilbertw** [comment]
Note that CMakeSettings.json is VS specific and not all customers will use VS.  Although we can add the varieties to that file for VS users, the settings and configurations need to be all in CMake.

Here are my suggested varieties, matrix optimizations may be in order as this will explode our pipeline requirements
- [ ] Release (Preconditions Off, optimizations ON)
- [ ] Debug (Preconditions ON, optimizations ON) 
- [ ] Full Debug (Preconditions ON, optimizations OFF)

**Comment by kurtzeborn** [comment]
@ahsonkhan, you might consider what we do in .NET as a guide in how you add support for release and debug here.  In .NET all PR validation builds and validates using the 'debug' flag.  After merge, the CI pipelines and the nightly runs build and run tests using the 'release' flag.  You can observe this here: https://github.com/Azure/azure-sdk-for-net/blob/master/eng/pipelines/templates/variables/globals.yml#L8
