### ISSUE TITLE
IAR compile time warning

### ISSUE THREAD

**Issue by hihigupt** [Azure/azure-sdk-for-c#640]
Hi,

I am trying to compile az_json_parser.c in IAR (8.5) from latest master of azure-sdk-for-c and getting following warnings: 

$WS\azure-sdk-for-c\sdk\core\core\src\az_json_parser.c(70) : Warning[Pe188]: enumerated type mixed with another type
$WS\azure-sdk-for-c\sdk\core\core\src\az_json_parser.c(585) : Warning[Pe188]: enumerated type mixed with another type

Can you please fix these warnings.

Thanks
Himanshu

**Comment by ahsonkhan** [comment]
> I am trying to compile az_json_parser.c in IAR (8.5) from latest master of azure-sdk-for-c and getting following warnings

@hihigupt, do you know what compiler is being used here and whether it is feasible for us to add a CI leg with that compiler? That way, once we fix the existing warnings, we can always remain green, as CI would catch such warnings up front.

cc @danieljurek

**Comment by antkmsft** [comment]
https://github.com/Azure/azure-sdk-for-c/issues/303

**Comment by hihigupt** [comment]
IAR compiler getting used her (IAR WORKSPACE 8.50.1.24811), I our project we are using following pipeline in devops: 
https://expresslogic.visualstudio.com/X-Ware/_build/results?buildId=14961&view=logs&j=84d3beb9-ba6d-5951-beee-b2a2468262b8&t=bad6f326-b907-572a-dcfa-71f5585c9e23&l=1210

These warnings looks to be newer warnings, as in earlier github issue I verified warnings coming from sdk-core and it was clean compilation. It would be great to add CI steps, if we support IAR compiler.

**Comment by ahsonkhan** [comment]
Can you please retry with the latest bits from master and see if the issue is still reproducible in IAR and let me know if you still see the warnings?

The parser code that was initially giving you this warning has changed significantly in master since 
https://github.com/Azure/azure-sdk-for-c/pull/871

**Comment by RickWinter** [comment]
@hihigupt can you confirm this is still an issue on the latest bits in master

**Comment by hihigupt** [comment]
I am not seeing any warning on latest master
