### ISSUE TITLE
CMake system prevents composition into other projects

### ISSUE THREAD

**Issue by PProvost** [Azure/azure-sdk-for-c#646]
**Describe the bug**
The current cmake-based build system assumes it is building a static library to be installed into your build environment (e.g. build .a files and copy to /usr/local/lib). As part of this, it sets up a number of build options (CFLAGS, etc.) that should be provided by the app including the SDK. This is particularly important for embedded builds, where every single aspect of the compile and link sequence has to be controlled by the developer.

**To Reproduce**
The way this manifests itself is as follows...

1. I want to use the SDK in my existing project, so I add it as a submodule to my git project:
    `git submodule add https://github.com/Azure/azure-sdk-for-c.git`
2. I include it into my existing cmake build system similarly:
    `add_subdirectory(libs/azure-sdk-for-c)`
3. Build as I normally would, expecting my compiler and linker settings to be used when building the SDK

***Code Snippet***
I've created a repository that shows how I "wrapped" the SDK's existing CMake system to have it build as part of the parent's cmake build. The trick here is to use what cmake calls "interface libraries".

https://github.com/PProvost/cmake-azuresdk-wrapper

**Expected behavior**
I should be able to add a submodule and then add_subdirectory and it should work without me having to create my own cmake wrapper.

**Comment by PProvost** [comment]
Additionally, it should be much easier to figure out which files are required and which are not. Since the IoT components take a dependency on core/core, there is an implied dependency on core/core/src/az_http_*.c and core/core/src/az_aad.c -- both of which require me to include one of the network stacks hidden under ~/platform.

**Comment by danewalton** [comment]
Just to give some context to this...the example repo is [here](https://github.com/PProvost/cmake-azuresdk-wrapper) with the code snippet demo of the "interface" dynamic [here](https://github.com/PProvost/cmake-azuresdk-wrapper/blob/master/lib/cmake-azure-sdk-for-c/libs/core/core.cmake).

**Comment by danewalton** [comment]
#652 for some progress

**Comment by danewalton** [comment]
#653 for more progress

**Comment by gilbertw** [comment]
Fix is available, https://github.com/Azure/azure-sdk-for-c/releases/tag/1.0.0-preview.2

**Comment by gilbertw** [comment]
Reopening as this is tracking some additional work

**Comment by gilbertw** [comment]
@PProvost @danewalton did the support for including us as a submodule address this issue?  Is there any additional work needed?

**Comment by danewalton** [comment]
> @PProvost @danewalton did the support for including us as a submodule address this issue?  Is there any additional work needed?

The issue of composition is fixed but the follow up comment of “what the dependencies are for a library” is still true. I think this can be rectified by explicitly linking to the libs which are depended upon (`target_link_libraries`) since we’re ditching the idea of versioning

**Comment by PProvost** [comment]
I'm happy with how it works now. Feel free to close this issue.

**Comment by danewalton** [comment]
Closing thanks @PProvost
