### ISSUE TITLE
Simplify build matrix

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-c#669]
The current build matrix spends a lot of time on vcpkg. Is it possible to reuse vcpkg to save overall agent time? 

For example, boostrap vcpkg, install a union of all dependency sets on the agent, then run each build scenario with something like `git clean -xdf` between each scenario... or sequence the installation of dependencies so that we don't pollute the VM (if that matters)

**Comment by vhvb1989** [comment]
We would only need to run `rm -rf *` inside /build folder before the next configuration..

So, we would reduce or Pipeline to Win86, Win64, Linux64 and Mac64.
Then, on each one, system is setup with dependencies, then we run configurations sequentially.

We just need to make sure to let the Code Cov configuration to be run at the end right?  (only if publishing to Azure makes a copy, then we don't care about the ordering).

**Comment by danieljurek** [comment]
Binary caching handles this.

**Comment by kurtzeborn** [comment]
Not a priority at this point.
