### ISSUE TITLE
Investigate and reconcile differences in how different langauges encode URLs and the C SDK

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-c#686]
Currently, we only URL encode (using percent encoding) the following characters, which follows RFC 3986 and only leaving unreserved characters un-encoded https://tools.ietf.org/html/rfc3986#section-2.3:
https://github.com/Azure/azure-sdk-for-c/blob/2b649d3d657e13cc8f9afbc8911afc4a93f65cd0/sdk/core/core/src/az_span.c#L695-L707

Other languages behave differently and we should make sure that either we have specific reasons for the discrepancy, OR we try to mimic what other languages do after figuring out what precedent to follow (since there isn't clear consensus).

**Things to consider:**
- What about following the IRI spec, i.e. RFC 3987 - https://tools.ietf.org/html/rfc3987#section-2.2
- ~Do we want to escape white space (' ') as '%20' or as '+'?~ No

C#: https://dotnetfiddle.net/TH7z7h
```C#
using System;
using System.Text.Encodings.Web;
					
public class Program
{
	public static void Main()
	{
		string query = "Hellö Wörld@Some lang$!*()+;";
		string encodedQuery = UrlEncoder.Default.Encode(query);
		// Hell%C3%B6%20W%C3%B6rld@Some%20lang$!*()%2B;
		Console.WriteLine(encodedQuery);
		
		// Hell%C3%B6%20W%C3%B6rld%40Some%20lang%24%21%2A%28%29%2B%3B
		Console.WriteLine(Uri.EscapeDataString(query));
	}
}
```

https://source.dot.net/#System.Text.Encodings.Web/System/Text/Encodings/Web/UrlEncoder.cs,123
https://docs.microsoft.com/en-us/dotnet/api/system.uri.escapedatastring?view=netcore-3.1
https://docs.microsoft.com/en-us/dotnet/api/system.net.webutility.urlencode?view=netcore-3.1#remarks
https://github.com/Azure/azure-sdk-for-net/pull/11657

Golang: https://play.golang.org/p/BMrXEtoFR_K
```go
package main

import (
	"fmt"
	"net/url"
)

func main() {
	query := "Hellö Wörld@Some lang$!*()+;"
	// Hell%C3%B6+W%C3%B6rld%40Some+lang%24%21%2A%28%29%2B%3B
	fmt.Println(url.QueryEscape(query))
}
```

Java: https://repl.it/repls/VapidMealyKeygens
```java
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.io.UnsupportedEncodingException;

class Main {

  // Method to encode a string value using `UTF-8` encoding scheme
    private static String encodeValue(String value) {
        try {
            return URLEncoder.encode(value, StandardCharsets.UTF_8.toString());
        } catch (UnsupportedEncodingException ex) {
            throw new RuntimeException(ex.getCause());
        }
    }
    
  public static void main(String[] args) {
    String query = "Hellö Wörld@Some lang$!*()+;";
    String encodedQuery = encodeValue(query);
    // Hell%C3%B6+W%C3%B6rld%40Some+lang%24%21*%28%29%2B%3B
    System.out.println(encodedQuery);
  }
}
```
https://docs.oracle.com/javase/7/docs/api/java/net/URLEncoder.html
https://github.com/Azure/azure-sdk-for-java/pull/10273

cc @antkmsft, @JeffreyRichter, @gilbertw, @alzimmermsft

**Comment by JeffreyRichter** [comment]
We are not building a generic HTTP stack; we are building an HTTP stack that only needs to talk to Azure services. For the blob service, see https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata

If we need to encode characters in addition to the reserved ones, that's fine and we should do it. 
I can tell you for sure that we should NOT encode spaces as a '+'. Java does this and it has caused us enormous problems with the Storage service; we ended up having to write our own URL encoder for Java and not use the Java-built-in encoder.

**Comment by ahsonkhan** [comment]
> I can tell you for sure that we should NOT encode spaces as a '+'. 

Sounds good and that makes sense. Looks like the "path" component of the URL should never encode space as '+' but the query string part can. However, it is simpler to avoid that all together.

So, as it stands, we are currently over-encoding as some of the characters we encode aren't strictly necessary. This will result in slightly larger payload sizes, but for simplicity, it is fine to do so.

If we want to revisit this, the action item would be to follow RFC 3987 for IRI (https://tools.ietf.org/html/rfc3987#section-2.2) and let some of the characters (such as from the set `@$!*();`) through without encoding.

**For now, this issue is not actionable. We can close this unless reducing size is important.**

> We are not building a generic HTTP stack; we are building an HTTP stack that only needs to talk to Azure services. For the blob service, see https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata

From that link:
> However, there are certain characters that are not valid in URL paths even when encoded. These characters cannot appear in blob or container names. Code points like \uE000, while valid in NTFS filenames, are not valid Unicode characters, so they cannot be used. In addition, some ASCII or Unicode characters, like control characters (0x00 to 0x1F, \u0081, etc.), are also not allowed. 

@JeffreyRichter, do we validate that the container name doesn't contain such characters? I am not sure, but I don't think it the responsibility of the url encoder to reject these, but we should try to adhere to these restrictions somewhere in the stack.

**Comment by JeffreyRichter** [comment]
The Azure SDK team's policy (for all languages) is that clients do NOT validate values that are sent to a service; the service does the validation. The reason is that characters the service considers invalid today might be valid in the future and we don't want the SDK to block the service request. So, we should encode as required by RFCs but do not validate as required by services.

**Comment by ahsonkhan** [comment]
Thanks, closing.

**Comment by ahsonkhan** [comment]
FYI @CIPop
