### ISSUE TITLE
Add Security Code Analysis to build

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-c#713]
Add to CI and nightly builds. 

Onboarding docs: https://docs.microsoft.com/en-us/azure/security/develop/security-code-analysis-onboard
YAML: https://docs.microsoft.com/en-us/azure/security/develop/yaml-configuration

**Comment by kurtzeborn** [comment]
No longer valid.  We do CredScan, CodeQL, SBOM, and everything else we're required to do everywhere we're required to do it.
