### ISSUE TITLE
Fix up storage documentation

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-c#722]
Header file is missing doxygen commands and the `az_storage_blobs.h` file does not show any doc content: 

![image](https://user-images.githubusercontent.com/2158838/81624542-44222300-93ab-11ea-9238-558b05202a6c.png)

**Comment by ahsonkhan** [comment]
Fixed by https://github.com/Azure/azure-sdk-for-c/pull/734

**Comment by ahsonkhan** [comment]
The storage blob client type defs are missing documentation. Re-opening the issue.

https://github.com/Azure/azure-sdk-for-c/blob/39d9e43c16fd8cea9fafd9c1add053ac21c1d431/sdk/storage/blobs/inc/az_storage_blobs.h#L35-L57
 
https://djurekdocs.z5.web.core.windows.net/mono/annotated.html
![image](https://user-images.githubusercontent.com/6527137/81768225-4cec2500-948f-11ea-8220-986260a40a98.png)
