### ISSUE TITLE
Regenerate Doxygen asset files

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-c#745]
Doxygen assets were generated using 1.8.17 and we're targeting using Doxygen in 1.8.18

Steps: 

* Generate new doxygen assets
* Apply current asset changes over the generated ones and merge appropriate changes

**Comment by ahsonkhan** [comment]
If there was a way to script/automate the generation changes so that a doxygen version update triggers the files to be re-generated as well, that would be great.
