### ISSUE TITLE
Images in markdown don't render as expected in doxygen

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-c#747]
They look great in markdown. Let's see if we can figure out a way to fix this in doxygen.

https://github.com/Azure/azure-sdk-for-c/blob/master/sdk/iot/README.md#key-features

![image](https://user-images.githubusercontent.com/6527137/81756278-2c60a280-9470-11ea-972f-d82c794134de.png)

cc @danewalton, @danieljurek

**Comment by danieljurek** [comment]
This looks like it might be related: https://github.com/doxygen/doxygen/issues/6517

**Comment by danieljurek** [comment]
Discussed in standup... we should use img tags 

```markdown
![check mark](https://github.githubassets.com/images/icons/emoji/unicode/2714.png?v8)
```

Use images defined here: https://api.github.com/emojis

**Comment by danewalton** [comment]
If we do it that way the images don't seem to scale well.

What about [this](https://www.doxygen.nl/manual/emojisup.html)?

**Comment by danieljurek** [comment]
To further excite matters, doxygen commands in the .md files will render correctly using Doxygen... It's as if we should be replacing `:<something>:` with `\emoji <something>` 

```
 Retry Policies | \emoji heavy_check_mark * | 
```
![image](https://user-images.githubusercontent.com/2158838/86155785-bfee4100-bab9-11ea-939f-ae4ee525ad73.png)

**Comment by weshaggard** [comment]
Another option is to directly use the unicode chars from http://unicode.org/emoji/charts/full-emoji-list.html. Github supports doing something like &#x1F600; which is the same as :smile: so assuming Doxygen also supports the unicode char set it should work.
