### ISSUE TITLE
All public typedef structs are not visible within the doxygen generated docs

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-c#749]
Go to Files > Globals > Typedefs within the docs
We should expect to see all public types such as `az_span`, `az_context`, etc.

See https://github.com/Azure/azure-sdk-for-c/pull/735#issuecomment-627109346

**Comment by RickWinter** [comment]
@vhvb1989 please take a look

**Comment by vhvb1989** [comment]
@ahsonkhan 
`az_span`, `az_context`, etc are structures.
Doxygen has an specific section for Data Structures.  

So, it is not expected to see the data structs in the Files/ section.
Files/ section covers:
 
![image](https://user-images.githubusercontent.com/24213737/90280112-369f8d80-de1f-11ea-8442-451de5992f8b.png)

While Data Structures are display in section:
![image](https://user-images.githubusercontent.com/24213737/90280151-49b25d80-de1f-11ea-99a6-cf60967bbf9d.png)

**Comment by ahsonkhan** [comment]
That does't make sense to me. The list of typedefs includes the other IoT structures like `az_iot_hub_client`.
https://azuresdkdocs.blob.core.windows.net/$web/c/docs/1.0.0-preview.4/globals_type.html

Why would some be included but not others? My hunch is that since we specify the name after in some structs, doxygen isn't picking those up as named typdefs:
```typdef struct {} name;```
vs.
```typdef struct name {};```
OR
```typdef struct name {} name;```

See this, compared to:
https://github.com/Azure/azure-sdk-for-c/blob/6a966901e467747d66e5705a3e25848b9ef45be8/sdk/inc/azure/iot/az_iot_hub_client.h#L57-L65

Compared to az_span:
https://github.com/Azure/azure-sdk-for-c/blob/8a65ecd08d60aae12a9ed4e5fd957d6c3225dd68/sdk/inc/azure/core/az_span.h#L32-L39

**Here are some options:**
1) Remove the duplicate names in the IoT struct definitions, so they don't show up in this list either
2) Add the duplicate names to all Core structs, so they do show up.
3) Fix up doxygen to show the structs, regardless of whether the name is stated in the beginning or in the end, or both.

As an example, look at LLVM docs, it lists structs (by providing the name twice): http://llvm.org/doxygen/globals_type.html

**Comment by danewalton** [comment]
I'd recommend setting this Doxyfile setting to on:
https://github.com/Azure/azure-sdk-for-c/blob/94d5fbf4abd3399dcb705c29e6ac6e52aa8302c0/Doxyfile#L428-L437
It should fix it.

**Comment by vhvb1989** [comment]
There is no difference after enabling the setting:
![image](https://user-images.githubusercontent.com/24213737/90428192-757c5000-e078-11ea-8f10-43aa37e5794c.png)

**Comment by RickWinter** [comment]
@vhvb1989 My understanding of that switch is it prevents the typedef from duplicating the entry.  The screen shot you showed doesn't show duplicates which implies its working

**Comment by vhvb1989** [comment]
even making setting `TYPEDEF_HIDES_STRUCT   = YES`
structs are not display in typedef section.

@ahsonkhan , should we just close this?  Even if we find a way to display structus in typedef section, do we want to duplicate the info in both sections?

**Comment by vhvb1989** [comment]
> 
> 
> @vhvb1989 My understanding of that switch is it prevents the typedef from duplicating the entry. The screen shot you showed doesn't show duplicates which implies its working

That's how it was working even before (we can take a look to a previous CI build)
I initially closed this issue mentioning that structs are mentioned in the data structures section.

The issue was reopened with the question of "should we update the way we define structures so they can be displayed in both sections like the iot structs"

Then iot updated their structs.

So, I don't think we need to set this option to YES at all

**Comment by vhvb1989** [comment]
Image from CI build before setting the value (the one where iot re-defined structs)
![image](https://user-images.githubusercontent.com/24213737/90428918-93968000-e079-11ea-8c36-a105915fd847.png)

**Comment by vhvb1989** [comment]
Image from CI build before IOT change to strcuts:
https://dev.azure.com/azure-sdk/public/_build/results?buildId=497534&view=artifacts&type=publishedArtifacts

![image](https://user-images.githubusercontent.com/24213737/90429154-fe47bb80-e079-11ea-8d64-469eff6c2e12.png)

**Comment by vhvb1989** [comment]
Actually, reading again the setting description, it mentions that it is for when the code is like:
  `typedef struct TypeS {} TypeT`
And our code is not doing this anywhere, we do:
  `typedef struct {} TypeT`

So, enabling the setting is useless.  

I wonder if we want to add this way of defining an struct to code guidelines? @RickWinter

**Comment by ahsonkhan** [comment]
In order to understand what exactly are the semantics of a `typedef struct`, I have been reading a bunch of discussion and thoughts on how to use and define structs in C, including not using them, separating typedefs and tag names from the opaque struct definition, etc., **which are out of the scope of this particular issue, but something that might be of interest, nonetheless.**

https://www.kernel.org/doc/html/latest/process/coding-style.html#typedefs
https://stackoverflow.com/a/32405369/12509023
https://stackoverflow.com/a/252810/12509023
https://stackoverflow.com/a/254250/12509023

**Comment by vhvb1989** [comment]
No need to do anything else for this issue.
Created issue for guidance update:
https://github.com/Azure/azure-sdk/issues/1696
