### ISSUE TITLE
APIs and types in the platform directory are missing doc comments in source

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-c#750]
The types and APIs within sdk/platform should have documentation.
For example: `az_platform_mtx`

These come from the following header:
https://github.com/Azure/azure-sdk-for-c/blob/a20134e42d3f866a4d4ccd75932093d7e4b019e5/sdk/core/core/internal/az_platform_internal.h#L14-L23

https://github.com/Azure/azure-sdk-for-c/blob/661ab65f33be27c2648e4be93604b484d239a91d/sdk/platform/http_client/nohttp/src/az_nohttp.c#L7-L14
https://github.com/Azure/azure-sdk-for-c/blob/661ab65f33be27c2648e4be93604b484d239a91d/sdk/platform/noplatform/inc/az_platform_impl.h#L9-L17

cc @vhvb1989, @antkmsft

**Comment by RickWinter** [comment]
az_platform_mtx is no more.  The rest are documented in az_platform.h
