### ISSUE TITLE
Documentation shows az_http_client_send_request twice, one from the transport header and one from the impl

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-c#751]
![image](https://user-images.githubusercontent.com/6527137/81757087-7ba7d280-9472-11ea-8f58-1f0695438f75.png)

https://github.com/Azure/azure-sdk-for-c/blob/019ff27d03c871960b761c4ab820d97448219407/sdk/core/core/inc/az_http_transport.h#L151-L169

https://github.com/Azure/azure-sdk-for-c/blob/661ab65f33be27c2648e4be93604b484d239a91d/sdk/platform/http_client/curl/src/az_curl.c#L597-L605

cc @vhvb1989

**Comment by RickWinter** [comment]
@vhvb1989 Confirm if this is still an issue

**Comment by ahsonkhan** [comment]
This issue has been fixed by https://github.com/Azure/azure-sdk-for-c/pull/969

See https://azuresdkdocs.blob.core.windows.net/$web/c/docs/1.0.0-preview.4/az__http__transport_8h.html#adf5f4aa9dfa854471090c33559ab86a5
