### ISSUE TITLE
Broken client-credential implementation for http request

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-c#799]
After removing Mutex (https://github.com/Azure/azure-sdk-for-c/pull/771) we got a regression on keyvault sample where making a request with secret credential is not working anymore.

The issue is that the Authorization header value is getting corrupted in memory because it is set to a function scooped variable (see below code from https://github.com/Azure/azure-sdk-for-c/blob/master/sdk/core/az_core/src/az_credential_client_secret.c#L55)
```c
  _az_token token = { 0 };
  AZ_RETURN_IF_FAILED(
      _az_credential_token_get_token(&credential->_internal.token_credential, &token));

  if (_az_token_expired(&token))
  {
    AZ_RETURN_IF_FAILED(_az_credential_client_secret_request_token(
        credential, ref_request->_internal.context, &token));

    AZ_RETURN_IF_FAILED(
        _az_credential_token_set_token(&credential->_internal.token_credential, &token));
  }

  int16_t const token_length = token._internal.token_length;

// ---> Here we add the auth header that points to a function scope variable.
//         MemAddress for variable will be reused as soon as we leave the function, corruption the header.
  AZ_RETURN_IF_FAILED(az_http_request_append_header(
      ref_request, _az_auth_header_name, az_span_init(token._internal.token, token_length)));

  return AZ_OK;
```

We need to think how we want to solve this.

-  Adding an extra buffer to request to keep the token (this would break refresh token and thread safe)
-  Pass the token_credential to transport http adapter (like libcurl) and let it call get_token to set header. This is basically moving the time for when we write the header, Request will not have this header.

Any other ideas? @gilbertw @ahsonkhan @JeffreyRichter

**Comment by gilbertw** [comment]
We should be using the token_credential from:
&credential->_internal.token_credential
when adding the token to the header in this line:
  AZ_RETURN_IF_FAILED(az_http_request_append_header(
      ref_request, _az_auth_header_name, az_span_init(token._internal.token, token_length)));
