### ISSUE TITLE
Azure pipline link is broken

### ISSUE THREAD

**Issue by ericwol-msft** [Azure/azure-sdk-for-c#805]
if you click on the azure pipeline link on the top of the read me, give you a 404 error

**Comment by danieljurek** [comment]
Strange... The badge code hasn't changed recently and there have been no changes to the `c - client - ci` pipeline that would cause this. This appears to be a new development and other pipeline status badges (even in our internal project) are failing to show the correct page. This could be a configuration switch that was flipped on the DevOps side or possibly a service bug.

**Comment by kurtzeborn** [comment]
This was a regression in devops.  Just checked this morning and it's still broken.

**Comment by danieljurek** [comment]
This issue no longer reproduces. Looks like it's been fixed.
