### ISSUE TITLE
Add documentation and test for consuming repo without CMake

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-for-c#832]
Based on our recent directory restructuring we should add some documentation for how to consume our repo without CMake. We should also add some test coverage to ensure we keep that scenario functioning.

cc @danewalton

**Comment by danewalton** [comment]
Agreed I think this is a great idea :+1:

**Comment by danewalton** [comment]
#841 for part of it.

**Comment by RickWinter** [comment]
CMake **is a requirement** for building our repo.  Although users can recreate our build system without CMake, it is **NOT** currently an officially supported scenario

**Comment by weshaggard** [comment]
@RickWinter perhaps I missed something but I thought the who reason we structured the repo as we did was to enable this scenario for people to be able to consume the repo easily without CMake. How do we help ensure that continues to work without tests?

**Comment by RickWinter** [comment]
@danewalton What is left on this issue?  Can it be closed?

**Comment by danewalton** [comment]
Closing since largely done. Can do additional work if we get issues around this.
