### ISSUE TITLE
[FEATURE REQ] Setup proper test framework

### ISSUE THREAD

**Issue by gilbertw** [Azure/azure-sdk-for-c#84]
We need to settle on a test framework.

Possible options could be:
- Cleanup and use what we have
- Leverage the IOT test framework
- Use the community favorite framework

**Comment by danieljurek** [comment]
DevOps supports getting results from CTest, which should make test failure information available in the pipeline for free: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=yaml

**Comment by vhvb1989** [comment]
https://github.com/Azure/azure-sdk-for-c/pull/343
