### ISSUE TITLE
az_json_builder_append_double_number needed in az_json.h

### ISSUE THREAD

**Issue by momuno** [Azure/azure-sdk-for-c#843]
**Describe the bug**
When building a JSON, the only option to append a number is an int32_t.  There also needs to be a double option.  

See file `sdk/inc/azure/core/az_json.h`

Explanation:
An `az_json_token` of kind "number" is defined as a double.  The `AZ_NODISCARD az_result
az_json_parser_parse_token(az_json_parser* json_parser, az_json_token* out_token)` extracts a token, from which `AZ_NODISCARD az_result az_json_token_get_number(az_json_token const* token, double* out_value)` correctly extracts a double.  The **`AZ_NODISCARD az_result
az_json_builder_append_int32_number(az_json_builder* json_builder, int32_t value)`** is the only function to append a number to a json.  An additional append function for a type double should be added.

**Comment by ahsonkhan** [comment]
This has been addressed by https://github.com/Azure/azure-sdk-for-c/pull/896

Please re-open if it hasn't.
