### ISSUE TITLE
[Azure IoT] System properties key name not defined

### ISSUE THREAD

**Issue by hihigupt** [Azure/azure-sdk-for-c#847]
System properties key names missing in IoT Embedded sdk lib :
message-id : $.mid
correlation-id : $.cid
content-type: $.ct
content-encoding: $.ce

List:
https://github.com/Azure/azure-iot-sdk-c/blob/0d423dac74f6cd3cff4911440ca12bbcbed08b07/iothub_client/src/iothubtransport_mqtt_common.c#L83

**Comment by RickWinter** [comment]
@hihigupt @ericwol-msft @danewalton Can you triage this to the appropriate owner

**Comment by ericwol-msft** [comment]
Dane owns this.
