### ISSUE TITLE
[FEATURE REQ] CI should build and test on Free BSD.

### ISSUE THREAD

**Issue by sergey-shandar** [Azure/azure-sdk-for-c#86]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Description Added
- [ ] Expected solution specified

**Comment by danieljurek** [comment]
An initial discussion suggested that it was possible to do this with FreeBSD 12 but the steps needed to do this would take engineering time: 

1. Get .NET CLI running (.NET CLI is not officially supported in FreeBSD, we'd have to build it) 
1. Build the Azure DevOps Agent (to ensure it works we'd need to sync code from the latest agent and merge changes in from another branch that added FreeBSD support) 

It is possible to short circuit some of these steps with the DevOps agent but we aren't confident that the agent will function properly if we do so.

**Comment by kurtzeborn** [comment]
Nope
