### ISSUE TITLE
Investigate sscanf difference between compilers when parsing doubles that are too large.

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-c#893]
`1.8e309` is too large to be represented by a double. So, this is considered equal to `inf`. The parsing APIs rely on `sscanf` to do the heavy lifting for double parsing. However, for strings that are out-of-range, we have a difference in behavior of `sscanf` based on the compiler, where in some cases `errno` is set, while in others, it isn't.

Here's a sample program that illustrates the problem:
```C
#include  <stdio.h>
#include  <stdint.h>
#include  <errno.h>

int main(void)
{
    double num = 0;
    int32_t n = 0;
    errno = 0;
    int ret = sscanf("1.8e309", "%20lf%n", &num, &n);
    printf("num=%lf, %d, %d, %d\n", num, n, ret, errno);
   
   // On MSVC:
   // num=inf, 7, 1, 0

  // On GCC, Clang:
  //  num=inf, 7, 1, 34
}
```
MSVC: https://rextester.com/SCYSI40711
Clang: https://rextester.com/UMMQ44933

Because of this, the following test fails on GCC/Clang (see https://github.com/Azure/azure-sdk-for-c/pull/885 for more info):
```C
// fails, instead returns AZ_ERROR_PARSER_UNEXPECTED_CHAR
assert_int_equal(az_span_atod(AZ_SPAN_FROM_STR("1.8e309"), &value), AZ_OK);
assert_true(value == INFINITY);
```

cc @barcharcraz, @BillyONeal

**Comment by BillyONeal** [comment]
The only functions documented as touching `errno` in the input/output section of the C standard are:
* `fgetpos`
* `fsetpos`
* `ftell`
* `perror` (except accepts an `errno` value as input)

Notably `fscanf` and `scanf` are not documented as affecting the value of `errno`, so you can't really assume anything about its value after such a call. `fscanf`/`scanf` *might* call `strtod` under the covers (but are not required to), which says C11 7.22.1.3 "The strtod, strtof, and strtold functions"/10: (emphasis mine)

> The functions return the converted value, if any. If no conversion could be performed,
zero is returned. **If the correct value overflows and default rounding is in effect (7.12.1),
plus or minus `HUGE_VAL`, `HUGE_VALF`, or `HUGE_VALL` is returned (according to the
return type and sign of the value), and the value of the macro `ERANGE` is stored in
`errno`.** If the result underflows (7.12.1), the functions return a value whose magnitude is
no greater than the smallest normalized positive number in the return type; whether
`errno` acquires the value `ERANGE` is implementation-defined.

Note also that POSIX *prohibits* `scanf`/`fscanf` from detecting this condition and setting `ERANGE`. See "ERRORS" in https://pubs.opengroup.org/onlinepubs/9699919799/functions/fscanf.html

Note also C11 7.22.1 "Numeric conversion functions"/1: (emphasis mine)

> The functions `atof`, `atoi`, `atol`, and `atoll` need not affect the value of the integer
expression `errno` on an error. **If the value of the result cannot be represented, the
behavior is undefined.**

which suggests that if you want to provide reasonable overflow behavior here `az_span_atod` should be called `az_span_strtod`.

**Comment by ahsonkhan** [comment]
The following link seems to suggest checking for `errno != 0` after calling sscanf, which does end up capturing some of the underflow, overflow cases while parsing.

https://linux.die.net/man/3/sscanf

> Note also that POSIX *prohibits* `scanf`/`fscanf` from detecting this condition and setting `ERANGE`. 

Where is that stated? I am having trouble finding it.

> The only functions documented as touching `errno` in the input/output section of the C standard are

The "RETURN VALUE" section from the link you shared seems to state otherwise. Do you have somewhere I can read up on why I can't rely on `errno` when calling `sscanf`?
> Upon successful completion, these functions shall return the number of successfully matched and assigned input items; this number can be zero in the event of an early matching failure. If the input ends before the first conversion (if any) has completed, and without a matching failure having occurred, EOF shall be returned. If an error occurs before the first conversion (if any) has completed, and without a matching failure having occurred, EOF shall be returned [CX] [Option Start]  **and errno shall be set to indicate the error**.

Regardless, if I can't rely on `errno` to be set when using `sscanf` for parsing doubles that return in `inf` for too large numbers, or `0` for too small numbers (such as `1e-400`), do you have a recommendation on how I can detect those cases and deterministically fail, regardless of what compiler is being used?

Here's the current check for successful parsing (inspired by @JeffreyRichter's suggestion to use `sscanf` https://github.com/Azure/azure-sdk-for-c/issues/598#issuecomment-633277659):
https://github.com/Azure/azure-sdk-for-c/blob/c9396dc3ab682a3c55c5a31c9e1070a1d28a3bd1/sdk/src/azure/core/az_span.c#L156-L161

We can't use strtod because of the zero-termination requirement (which results in data copies). We had tried that approach and decided against it:
https://github.com/Azure/azure-sdk-for-c/pull/627

> which suggests that if you want to provide reasonable overflow behavior here `az_span_atod` should be called `az_span_strtod`.

If we were providing an API that is trying to follow suite with the C runtime, I can see why we'd name it `az_span_strtod`, but overloading that could cause confusion with spans and strings (null termination vs not). Naming aside, the pressing matter is finding a way to provide reasonable overflow behavior in the first place :)

**Comment by BillyONeal** [comment]
>The following link seems to suggest checking for errno != 0 after calling sscanf, which does end up capturing some of the underflow, overflow cases while parsing.

That's not what the link says:

>The value EOF is returned if the end of input is reached before either the first successful conversion or a matching failure occurs. **EOF is also returned if a read error occurs, in which case the error indicator for the stream (see ferror(3)) is set, and errno is set indicate the error.**

That is, I/O errors only, not `ERANGE`.

>Where is that stated? I am having trouble finding it.

`ERANGE` is not one of the enumerated valid error values. All of the enumerated error values are I/O errors.

>The "RETURN VALUE" section from the link you shared seems to state otherwise. Do you have somewhere I can read up on why I can't rely on errno when calling sscanf?

It isn't that you can't rely on `errno` when calling `sscanf`, it's that `sscanf` does not consider this condition an error. For special values like `inf`, even `strtod` does not consider parsing that an error.

>Regardless, if I can't rely on errno to be set when using sscanf for parsing doubles that return in inf for too large numbers, or 0 for too small numbers (such as 1e-400), do you have a recommendation on how I can detect those cases and deterministically fail, regardless of what compiler is being used?

I believe `strtod` (and friends) are the only portable option.

**Comment by ahsonkhan** [comment]
>  For special values like `inf`, even `strtod` does not consider parsing that an error.

There is a difference between values that are semantically double inf, and actually/precisely `inf`. strtod does set errno for semantically infinity values.

Should we just reject any input that results in a non-finite double value when parsing? For example, fail when `isfinite(result) == false`?

// Same output on all 3 compilers: clang, msvc, gcc
```C
#include <stdio.h>      /* printf, NULL */
#include <stdlib.h>     /* strtod */
#include <errno.h>

int main(void)
{
  errno = 0;
  char semantic_inf[] = "1e400";
  double d1 = strtod (semantic_inf, NULL);
  printf ("vaule: %lf, errno:%d\n", d1, errno); // vaule: inf, errno:34
   
  errno = 0;
  char actual_inf[] = "inf";
  double d2 = strtod (actual_inf, NULL);
  printf ("vaule: %lf, errno:%d\n", d2, errno); // vaule: inf, errno:0
  
  return 0;
}
```
