### ISSUE TITLE
Rename AZ_ERROR_EOF az_result to something more descriptive such as AZ_ERROR_UNEXPECTED_END 

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-c#894]
See https://github.com/Azure/azure-sdk-for-c/pull/871#discussion_r448689576

cc @antkmsft, @JeffreyRichter

**Comment by vhvb1989** [comment]
IMHO, `EOF` is more common than unexpected_end.

**Comment by ahsonkhan** [comment]
It doesn't cleanly fit in the context where it is used. There is no file, the data ended abruptly.

Parsing `1234.1e` and seeing EOF seems odd, so being more verbose/clear makes sense to me. We discussed this when we reviewed the `az_result` values and @antkmsft likes it. Anton, thoughts?
