### ISSUE TITLE
Add JSON parser and builder sample usage code snippets to an .md file as part of docs.

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-c#903]
Start from the samples provided in the PR descriptions (barring any renames or API changes):
https://github.com/Azure/azure-sdk-for-c/pull/871
https://github.com/Azure/azure-sdk-for-c/pull/902
https://github.com/Azure/azure-sdk-for-c/pull/1023

This seems like a good location for them:
https://github.com/Azure/azure-sdk-for-c/tree/master/sdk/docs/core#azure-sdk-core-library-for-embedded-c

cc @RickWinter, @JeffreyRichter

**Comment by ahsonkhan** [comment]
Thanks for the suggestion, @ericwol-msft

**Comment by ahsonkhan** [comment]
From https://github.com/Azure/azure-sdk-for-c/issues/842 by @momuno 

> **Is your feature request related to a problem? Please describe.**
> The az_json_parser does not have quality documentation for the end-user. The only current examples are in the test files or the provisioning service files (core/az_core/test/test_az_json.c), (iot/provisioning/src/az_iot_provisioning_client.c)
> 
> **Describe the solution you'd like**
> json parser needs documented examples for end users to learn from that are easy to find/access,

**Comment by RickWinter** [comment]
Moving to part of the doc improvement story before GA

**Comment by sadranyi** [comment]
Any updates on this ?
