### ISSUE TITLE
Set vcpkg ref

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-c#928]
Hard requirement: The ref appears in only one location in the repo. 

Today it's in a single location but links to this point to a particular line in a yml file. That line number may change over time. So instead we can put it in a txt file (like version.txt of old) and have docs point to that file. We can also read the ref into a variable and use the variable in the build.

**Comment by danieljurek** [comment]
Chatted w/ @weshaggard about this he suggests that we write a script (possibly PowerShell) which does a fresh clone of the vcpkg repo, and checks out the appropriate ref. Devs who use the repo can follow the steps in the script or just run the script themselves to get set up properly and we ensure that the ref is only written in one place. 

This would also greatly simplify our `vcpkg.yml` file which is currently hand written to deal with the various quirks of the vcpkg instances that are already on the hosted agent images.

**Comment by weshaggard** [comment]
> (possibly PowerShell) 

While it would be great to be platform agnostic I suspect we might want to consider at least platform specific boot wrappers (i.e. sh and cmd). However that would be more of a question for the folks that might use these.
