### ISSUE TITLE
Remove use of AZ_CONTINUE az_result an update its current usages (which are internal only)

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-c#931]
The following success az_result is never exposed to the user and is currently only used for state management between internal method calls:
https://github.com/Azure/azure-sdk-for-c/blob/099446822c992b911f83443d28e92f092bb16011/sdk/inc/azure/core/az_result.h#L74

We should remove this enum value, and use a different mechanism for managing the state between those methods, or refactor that logic.

Current usages:
https://github.com/Azure/azure-sdk-for-c/blob/c9c15de5b73f961cabe6c74f57449cfb8039f37d/sdk/src/azure/core/az_span.c#L756-L770

https://github.com/Azure/azure-sdk-for-c/blob/c9c15de5b73f961cabe6c74f57449cfb8039f37d/sdk/src/azure/core/az_http_response.c#L17-L20

https://github.com/Azure/azure-sdk-for-c/blob/43e4de8dcac97b144c24e0693028c88a17b98b91/sdk/src/azure/core/az_http_request.c#L18-L21

cc @vhvb1989

**Comment by RickWinter** [comment]
As discussed switch the methods to use bool return
