### ISSUE TITLE
Reevlaute the need for a platform facility and update the az_result to use HTTP adapter

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-c#932]
The platform facility might not be needed, and we should rename the az_result values that use it to HTTP adapter, which is the replaceable transport layer component (like curl), while we keep the current HTTP facility for the rest of the HTTP stack, which is implemented within the SDK.

https://github.com/Azure/azure-sdk-for-c/blob/099446822c992b911f83443d28e92f092bb16011/sdk/inc/azure/core/az_result.h#L102-L109

https://github.com/Azure/azure-sdk-for-c/blob/43e4de8dcac97b144c24e0693028c88a17b98b91/sdk/inc/azure/core/az_http_transport.h#L202-L207

https://github.com/Azure/azure-sdk-for-c/blob/43e4de8dcac97b144c24e0693028c88a17b98b91/sdk/src/azure/platform/az_curl.c#L27-L38

When we think of platform, we mean the abstraction layer between the SDK and the underlying hardware, which provides the method implementations for things like clock and sleep. For example, see this:
https://github.com/Azure/azure-sdk-for-c/blob/43e4de8dcac97b144c24e0693028c88a17b98b91/sdk/inc/azure/core/az_platform.h#L21
https://github.com/Azure/azure-sdk-for-c/tree/master/sdk/docs/core#porting-the-azure-sdk-to-another-platform

For other usages within the SDK, like these, we may need a general purpose az_result within core for this (since base64 APIs are coming from the underlying platform, outside of the SDK):
https://github.com/Azure/azure-sdk-for-c/blob/099446822c992b911f83443d28e92f092bb16011/sdk/samples/iot/src/sample_sas_utility.c#L28-L32

**Comment by vhvb1989** [comment]
@ahsonkhan I have created a PR for this.
However, I believe we should keep PLATFORM facility.  Look in the PR how IoT is using the `AZ_ERROR_OUT_OF_MEMORY` error on samples.
We might need to use a different ERROR on those samples, or keep the PLATFORM facility to be use for those cases.

**Comment by ahsonkhan** [comment]
@vhvb1989 , I addressed that in the issue description above:

> For other usages within the SDK, like these, we may need a general purpose az_result within core for this (since base64 APIs are coming from the underlying platform, outside of the SDK):
