### ISSUE TITLE
Add json api to add generic, prebuilt JSON span to a document

### ISSUE THREAD

**Issue by danewalton** [Azure/azure-sdk-for-c#934]
@ahsonkhan for eyes.

Imagine we have a span which already contains valid JSON that we want to add to a document. We currently can only add per element. It would be nice to have an api to append something already built up. Especially useful in IoT where we might have some "envelope" for a JSON payload and we just want to let the user build up their "value" and append it in our JSON envelope.

Something like the following where the "value" could be any of the three:
```json
{
  "component": {
    "name": "my_component",
    "value": 45
  }
}
```
```json
{
  "component": {
    "name": "my_component",
    "value": "my_value"
  }
}
```
```json
{
  "component": {
    "name": "my_component",
    "value": {
       "foo": 45,
        "bar": "example",
    }
  }
}
```

The API for us would be simplified with the following:
```c
az_result pnp_helper_create_reported_property(
    az_span component_name,
    az_span property_name,
    az_span property_json_value);
```
instead of needing a separate API for each type (double, int, string, object, etc).

**Comment by hihigupt** [comment]
We are also hitting issue when we are trying to write complex object using the json writer.
