### ISSUE TITLE
DPS SAS sample not correctly using auto-generated primary key

### ISSUE THREAD

**Issue by momuno** [Azure/azure-sdk-for-c#945]
**Describe the bug**
When the primary key is auto-generated upon enrolling a device with the DPS (using SAS), the sample breaks.  Receives "Unauthorized" message.
A shorter primary key (40 characters) works.  Speculation this may be an API issue with openSSL and us not understanding certain requirements for primary keys.

**To Reproduce**
Enroll a new device with the DPS using SAS and select auto-generate primary key.  Use this primary key when running the sample.

**Expected behavior**
The client should connect to the service and register.

**Screenshots**
![image](https://user-images.githubusercontent.com/64985898/88099441-03374f00-cb50-11ea-84b9-de86a10c6752.png)
![image](https://user-images.githubusercontent.com/64985898/88099719-6aed9a00-cb50-11ea-86a1-13e1bdeb0d39.png)

**Setup (please complete the following information):**
 - OS: Ubuntu 20.04 and Windows 10
 - IDE : Vim and Visual Studio 2019
 - OpenSSL on Ubuntu: 1.1.1f-1ubuntu2
 - OpenSSL on Windows: OpenSSL 1.1.1d

**Comment by kartben** [comment]
I think it's simply that the `sas_b64_decoded_key_buffer` is not long enough? An auto-generated **DPS key is 64 bytes, but the buffer only holds 32 bytes**.
BTW I don't know what are the max lengths for both DPS/Hub auto-generated keys but maybe that's what the buffer size should be set to in all the samples?

https://github.com/Azure/azure-sdk-for-c/blob/master/sdk/samples/iot/paho_iot_provisioning_sas_sample.c#L101

**Comment by momuno** [comment]
That was it.  The autogenerated key for the Hub I count at 44 characters, and for DPS is 88 characters.  Where were you able to determine the autogenerated key for the DPS is 64 bytes?  The b64 decoded SAS key needs the 32 bytes for the Hub, and 64 bytes for the DPS.  SAS is new to me so I appreciate your help in understanding this space.  Thanks.

**Comment by kartben** [comment]
@momuno Yes the the DPS auto-gen'd key is 88 characters *when b64-encoded* indeed -- I was taking a shortcut when saying it is 64 bytes (once decoded into `sas_b64_decoded_key_buffer`), sorry.

BTW can you please re-open the issue until the fix has actually been pushed? Or I'm also happy to provide a PR but it looks like you tested the fix on your side already!

**Comment by momuno** [comment]
Thanks @kartben.  I will reopen, and already have a fix for it ready to go.  Will close once committed. Thanks!

**Comment by momuno** [comment]
fix comitted.
