### ISSUE TITLE
Show build status in GitHub, don't show in docs

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-c#947]
The status here: 
![image](https://user-images.githubusercontent.com/2158838/88109127-d0e11e00-cb5e-11ea-892e-0323d86df4cb.png)

Is a URL that points to the latest build status. It's confusing when it's in docs and (on occasion) shows red. The image itself doesn't offer any sense of whether builds are passing for the specific version of the code that the documentation covers.

**Comment by kurtzeborn** [comment]
All of the other language repos have already gotten rid of their README badges.
