### ISSUE TITLE
Investigating onboarding IAR to CI

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-c#952]
Ideally we'll be able to install this on the host agent VM.

**Comment by danieljurek** [comment]
IAR findings from initial discussion: 

* IoT uses lab machines to build on IAR
  * Uses IAR network license and network license server
  * Has physical IoT device plugged into the machine
  * Lab machines are registered to a pool and used in DevOps 
* IAR has two licensing models (neither is a smooth story for using hosted agents in DevOps): 
  * Network license - machines on a small network can be instructed to communicate with a server on that network to obtain a license
  * Node license - individual machines have the license installed on them

**Comment by RickWinter** [comment]
This is dependent on the new IAR lab.

**Comment by kurtzeborn** [comment]
We decided not to do this years ago.
