### ISSUE TITLE
Table of Contents (and other anchor links within Doxygen do not work)

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-c#964]
In the case of links to anchors in the same document (e.g. the index page) Doxygen is using a different translation for the anchors: 

![image](https://user-images.githubusercontent.com/2158838/88847795-6bafad00-d19c-11ea-930b-e75278a4ce37.png)

![image](https://user-images.githubusercontent.com/2158838/88847921-9994f180-d19c-11ea-8107-e4b79b40bd3c.png)

**Comment by RickWinter** [comment]
Possible solution is docfx generates conceptual docs which will link out to api/functional docs which are generated by doxygen

**Comment by kurtzeborn** [comment]
The EngSys team is not going to get to this any time soon.  If this is a priority for the C language team, please go ahead.
