### ISSUE TITLE
Guidelines: az_X_create() naming

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-c#999]
We need to update guidelines to put wording explicitly allowing names for "constructor" functions to have names lika `az_X_create`, `az_X_create_with_Y`, `az_X_create_from_Y` (instead of `az_X_create_X`, `az_X_create_X_with_Y`, and `az_X_create_X_from_Y`).

Create functions (unlike `init`s) return values (usually structs) by value copy, instead of az_result.

**Comment by antkmsft** [comment]
Specific comments thread, for more context: https://github.com/Azure/azure-sdk-for-c/pull/988#discussion_r465482570

**Comment by RickWinter** [comment]
@antkmsft please move this issue the sdk repo, https://github.com/Azure/azure-sdk

**Comment by RickWinter** [comment]
@antkmsft please move this issue the sdk repo, https://github.com/Azure/azure-sdk
